### ISSUE TITLE
Submit notebook with no runtimes configured can lockup lab - forcing page reload

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1000]
If a user attempts to submit a notebook when no runtimes are configured (just temporarily rename your runtimes directory if you have one), they are presented with this message:
<img src="https://user-images.githubusercontent.com/22599560/97203502-24709280-1772-11eb-9d81-1295abcc395f.png" width="400" height="200">

Selecting 'OK' then presents this dialog:
<img src="https://user-images.githubusercontent.com/22599560/97203579-40743400-1772-11eb-8b45-6eabfa782485.png" width="400" height="200">

If 'OK' (the default) is selected, the dialog cannot be dismissed and there's nothing the user can do other than use the browser button to reload the page.

Selecting 'Cancel' will exhibit expected behavior although it seems like the second dialog should not be displayed at all in this case.

**Comment by karlaspuldaro** [comment]
Resolved by #1404
