### ISSUE TITLE
Add support for pipeline runtime specific components

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1004]
Enable the notion of a registry that can parse and expose the necessary information required to expose runtime specific components on the Elyra pipeline editor. 

![image](https://user-images.githubusercontent.com/382917/97216670-6950f500-1783-11eb-8d5f-271b8a819564.png)

Examples of KFP Components:
 - https://github.com/kubeflow/pipelines/tree/master/components
Example of Airflow Components:
 - https://github.com/apache/airflow/tree/1.10.15/airflow/operators
 - https://github.com/apache/airflow/tree/1.10.15/airflow/contrib/operators

Things to consider:
- Abstraction of classes to enable the concept of "federated registry" that reads from different sources/locations/types
- Caching on multiple layers: Frontend, Service, Filesystem contents

**Comment by Jeffwan** [comment]
I think it would be great to have some abstraction to import verified components to a box (could be a elyra concept) on cavas.

**Comment by lresende** [comment]
> I think it would be great to have some abstraction to import verified components to a box (could be a elyra concept) on cavas.

@Jeffwan we are finally working on the implementation of the registry functionality to register and serve additional components to the pipeline editor. Do you want to create a new issue for "importing verified components" and we would add it to the umbrella issue we have for Pipeline Editor 2.0. Please describe your requirements on the issue, I was thinking initially maybe a CLI and subsequently maybe some sort of admin UI similar to what we have for runtimes, etc?
