### ISSUE TITLE
[Lab 3.0] Run and Export buttons are disabled on pipelines

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1010]
When opening an existing pipeline on lab 3.0, both Run and Export buttons are disabled despite runtimes being present:
![image](https://user-images.githubusercontent.com/22599560/97362280-04b69880-185e-11eb-9aab-ab7ae659672f.png)

However, these buttons become enabled when selected the Runtimes icon in the toolbar:
![image](https://user-images.githubusercontent.com/22599560/97362510-5bbc6d80-185e-11eb-801e-d06500c3ae4b.png)

Yet they still fail to bring up any kind of dialog when selected:
![image](https://user-images.githubusercontent.com/22599560/97362434-3f203580-185e-11eb-827d-9f948bffde6f.png)

**Comment by lresende** [comment]
Fixed in `jupyterlab3` branch with upstream updates to JupyterLab 3.0
