### ISSUE TITLE
[Lab 3.0] Notebook and Python script files cannot be dragged onto canvas

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1012]
Using a build based on lab 3.0, Notebook and Python script files cannot be dragged onto the canvas:

![BrokenCanvas](https://user-images.githubusercontent.com/22599560/97363703-36c8fa00-1860-11eb-9ed2-b34cc6df48cd.gif)

**Comment by kevin-bates** [comment]
Discovered that _new_ nodes can be created using `Copy`/`Paste` via the right-clicked properties menu on the node to be copied.

**Comment by karlaspuldaro** [comment]
I think this is related, when right-click a file, then click `Add File to Pipeline`, also doesn't work in 3.0

**Comment by lresende** [comment]
Fixed in `jupyterlab3` branch with upstream updates to JupyterLab 3.0
