### ISSUE TITLE
Create conda recipes for individually installable extensions

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1014]
Follow up to https://github.com/elyra-ai/elyra/pull/1009.

Users should be able to install the following Elyra extensions separately, like it can already be done using `pip`:
- https://pypi.org/project/elyra-pipeline-editor-extension/
- https://pypi.org/project/elyra-code-snippet-extension/
- https://pypi.org/project/elyra-python-editor-extension/

**Comment by akchinSTC** [comment]
@lresende - can we get source packages pushed to pypi for these server extensions as well?

**Comment by ptitzler** [comment]
https://github.com/elyra-ai/elyra/pull/1009 provides the documentation updates.

**Comment by akchinSTC** [comment]
waiting on 1.4.0 release of Elyra

**Comment by akchinSTC** [comment]
PR - https://github.com/conda-forge/staged-recipes/pull/13201

**Comment by akchinSTC** [comment]
merged
