### ISSUE TITLE
[Lab 3.0] Notebook and Python files cannot be opened by double-clicking node

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1015]
When opening an existing pipeline using the Lab 3.0 version of Elyra, the node's notebook or python scripts cannot be opened by double-clicking the node or by selecting `Open File` via a right-click on the node.

**Comment by lresende** [comment]
Fixed in `jupyterlab3` branch with upstream updates to JupyterLab 3.0
