### ISSUE TITLE
pipeline export to Python DSL produces invalid script

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1025]
Elyra 1.3+

- git clone `https://github.com/elyra-ai/examples.git` into your JL workspace
- navigate to `examples/pipelines/dax_noaa_weather_data`
- open `analyze_NOAA_weather_data.pipeline` in the pipeline editor
- create a KFP runtime configuration
- export the pipeline to Python DSL
- run the exported Python script
  ```
  $ python analyze_NOAA_weather_data.py 
   File "analyze_NOAA_weather_data.py", line 18
    pipeline_outputs='['data/noaa-weather-data-jfk-airport/jfk_weather.csv']',
                           ^
  SyntaxError: invalid syntax
  ```

The problematic generated code is attached: 
[generated_py.tar.gz](https://github.com/elyra-ai/elyra/files/5467993/generated_py.tar.gz)

**Comment by ptitzler** [comment]
Some of the issues:

- string arrays are not properly escaped
```
pipeline_inputs='['data/noaa-weather-data-jfk-airport/jfk_weather.csv', 'data/noaa-weather-data-jfk-airport/jfk_weather_cleaned.csv']',
```

- file names are used as is as variable names
```
notebook_op_examples_pipelines_dax_noaa_weather_data_Part 2 - Data Analysis.name = 'Part 2 - Data Analysis 800007f9b87046ed'
```

This used to work in earlier releases.

**Comment by akchinSTC** [comment]
Im going to try updating the kfp jinja template to fix
