### ISSUE TITLE
Support exposure of pipeline run performance metrics in KFP UI

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1032]
In Kubeflow Pipelines one can export and visualize pipeline metrics , as described here: https://www.kubeflow.org/docs/pipelines/sdk/pipelines-metrics/. 

![image](https://user-images.githubusercontent.com/13068832/97921440-cf072900-1d0f-11eb-9ed1-f4803c4a0de6.png)

The Elyra/KFP [NotebookOp](https://github.com/elyra-ai/kfp-notebook/blob/master/kfp_notebook/pipeline/_notebook_op.py#L178) does accept the required `file_outputs` parameter as input. However, the parameter is not defined  when a pipeline is executed from the VPE or included in the exported  Python DSL code and therefore no metrics will ever be rendered if a Python script or notebook is executed.

**Comment by ptitzler** [comment]
For reference, this is what an invocation would have to look like to make it work, assuming that a notebook/python script generates `/tmp/mlpipeline-metrics.json` (arbitrary name), which contains the KFP compatible metrics dump: 

```
NotebookOp(name='produce',
                          notebook='produce.ipynb',
                         cos_endpoint='http://...',
                         cos_bucket='pipeline-artifacts',
                         cos_directory='...',
                        cos_dependencies_archive='....tar.gz',
                        pipeline_inputs=[],
                        pipeline_outputs=[],
                        image='...',
                       file_outputs={'mlpipeline-metrics': '/tmp/mlpipeline-metrics.json'})
```

**Comment by ptitzler** [comment]
@MLnick @romeokienzler. wdyt would having access to some(?) metrics in the KFP UI be of value? Without this ability you'd always have to download the notebook/script output to see the results, e.g. after. a training run. So in a way this can be seen as a sneak preview of some sort.

**Comment by MLnick** [comment]
@ptitzler broadly speaking yes, ability to see the metrics from a run would be useful without always having to dig around in object storage buckets to find the corresponding output notebook HTML etc.

Also, support for https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/ would be useful (I think adding support for metrics would essentially enable support for output viewers too since it also uses `file_outputs` as far as I can see.
