### ISSUE TITLE
KFP UI: associate pipeline run with  input + output artifacts

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1033]
The KFP UI provides  [output viewers](https://www.kubeflow.org/docs/pipelines/sdk/output-viewer/#markdown), which support markdown. We could use this capability to associate each node in the graph with (1) a link to the input archive on COS/minio and/or (2) a link to the bucket where the  input and output artifacts are located.

![image](https://user-images.githubusercontent.com/13068832/97932311-827a1880-1d24-11eb-8c31-8ae568a8a38c.png)

Currently a user has to manually parse the container log file to obtain this information.

**Comment by ptitzler** [comment]
I believe https://github.com/elyra-ai/kfp-notebook/blob/master/kfp_notebook/pipeline/_notebook_op.py#L42 already contains the required information needed to make the implementation completely self-contained and transparent to the user / notebooks  /python scripts.

**Comment by MLnick** [comment]
Per my comment in #1032 user-defined output viewers can then also be supported.
