### ISSUE TITLE
Use images from other registries

### ISSUE THREAD

**Issue by pacospace** [elyra-ai/elyra#1035]
Hi everybody, 

I noticed that custom runtime images can be used, but only if uploaded on Docker container registry https://hub.docker.com. https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html#prerequisites.

Is there any plan to generalize it to other registries?

**Comment by ptitzler** [comment]
Hi @pacospace,

this actually already works today for _public_ image registries. I just ran a quick test by creating a dummy [Tensorflow image on quay.io](https://quay.io/repository/ptitzler/tensorflow?tab=tags) and specifying the following in the runtime image configuration:

![image](https://user-images.githubusercontent.com/13068832/98281383-89d23980-1f51-11eb-9a6f-325dae068b84.png)

The pipeline did work as expected but we do need to update the documentation to reflect that "any" public registry can be used.

**Comment by pacospace** [comment]
> Hi @pacospace,
> 
> this actually already works today for _public_ image registries. I just ran a quick test by creating a dummy [Tensorflow image on quay.io](https://quay.io/repository/ptitzler/tensorflow?tab=tags) and specifying the following in the runtime image configuration:
> 
> ![image](https://user-images.githubusercontent.com/13068832/98281383-89d23980-1f51-11eb-9a6f-325dae068b84.png)
> 
> The pipeline did work as expected but we do need to update the documentation to reflect that "any" public registry can be used.

Thanks @ptitzler! Very nice to hear that :100:

**Comment by ptitzler** [comment]
Go for it!
