### ISSUE TITLE
Elyra images as notebook-server for kubeflow?

### ISSUE THREAD

**Issue by kd303** [elyra-ai/elyra#1036]
This is more of a query: Are there any images provided for running Elyra as a notebook server on existing kubeflow cluster? Something I can use and customize as well ?

Also if not available do you forsee any issues creating a custom image for Elyra? I see this is a very useful plugin and something that can really be helpful in creating the kubeflow pipeline projects.

Thanks for your help, I went through the documentation and could not find any reference.

**Comment by kd303** [comment]
@kevin-bates thanks for the acknowledgement, I did some reading and looked into code, I am not fully aware of Elyra docker image creation and details of it, I did realize Kubeflow expects a [different startup script](https://www.kubeflow.org/docs/notebooks/custom-notebook/), I am exploring that option to see if we can get Elyra as a custom image on  kubeflow, I think it would be a great addition for our DS team.

**Comment by kevin-bates** [comment]
This sounds interesting, thank you for looking into things here.  

The elyra project build and tests are driven via a Makefile.  As such, the command [`make docker-image`](https://github.com/elyra-ai/elyra/blob/master/Makefile#L150-L154) should build the elyra image.  Once we figure out the startup requirements, we could either plumb appropriate parameters into [`start-elyra.sh`](https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/start-elyra.sh) or create an alternate CMD that could be used/overridden in these kinds of scenarios. 

cc @akchinSTC for any possible corrections or comments.

**Comment by lresende** [comment]
I believe @kd303 is trying to use our Elyra image to launch a "notebook instance" when they click "notebooks" on the left panel, rather then talking about "Elyra runtime-images" which is used during component execution. 

@kd303 We have extensively tested the image with JupyterHub and Jupyter related components, but I am aware Kubeflow departed from that and we might indeed have some divergency there, having said that, I believe our colleague @tomlyn has done this in the past and can help us here, otherwise, I can take a quick look during the week to see what we might need to update here.

**Comment by tomlyn** [comment]
Hi  @lresende I think you may have incorrectly tagged m your response above since I have no knowledge about this issue.

**Comment by lresende** [comment]
Sorry, @tomlyn.

@Tomcli should be the right one tagged on this issue.

**Comment by kd303** [comment]
@lresende @tomcli Thanks for your comments, would you have any blog reference or anything that I might refer to do further digging?

**Comment by lresende** [comment]
Sorry for the delay here, this is next on my priority list and I should get some updates in the next few days.

**Comment by frankmanbb** [comment]
any update on this? want to use that in kubeflow as well.

**Comment by kd303** [comment]
@lresende in my simple mind (I am just dabbling with lot of things and nowhere near expert category), I am able to run my jupyter hub notebook on kubeflow, so if I install Elyra plugin as mentioned in github pages should it not work? (`pip install --upgrade "elyra<2.0.0" && jupyter lab build`)

The difference is the way Elyra's `start-elyra.sh` [https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/start-elyra.sh] and the way Kubeflow expects it. I tried doing this on my local machine but `jupyter lab build` fails complaining npm is not installled.
