### ISSUE TITLE
[KFP pipelines] Improve usability of exported Python DSL

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1037]
A pipeline can be exported to Python DSL, which enables users to deploy and run a pipeline outside of JupyterLab. I've been using the currently generated code extensively and have identified a couple of improvements that should improve usability.

**Comment by akchinSTC** [comment]
@ptitzler, can you add some bullets to this issue details what improvements should be made or add links to issues if this is intended to be an umbrella issue. Thanks!

**Comment by ptitzler** [comment]
Yep, I'll add them once I've wrapped up the KFP metadata/metrics work

**Comment by ptitzler** [comment]
Referring to https://github.com/elyra-ai/elyra/blob/master/elyra/templates/kfp_template.jinja2#L32-L42, we should 
 - explicitly upload the pipeline and then run it instead of just running it. as is, the pipeline does not show up in the KFP UI under `> pipelines`, only under `>experiments`
 - add error checking
 - add "logging" and documentation to make it easier to understand what is happening

e.g.

```
Connecting to http://devises1.fyre.ibm.com:32235/pipeline ...
Uploading pipeline "do_nothing2" ...
Creating experiment "do_nothing2 experiment" if it doesn't exist yet ...
Submitting pipeline run in experiment "do_nothing2 experiment" ...
Pipeline run URL: http://devises1.fyre.ibm.com:32235/pipeline/#/runs/details/9647ad92-d793-4f8d-a028-701a0fc7ecbb
```

**Comment by ptitzler** [comment]
Re discussion, this is the relevant code:
```
client.create_experiment(...)
...
client.run_pipeline(...)
```

**Comment by ptitzler** [comment]
I believe the generated Python code should replicate the sequence of KFP client API calls that we are using when a pipeline is run from the editor:
- compile (`kfp*.compiler.....compile`)
- upload pipeline (`client.upload_pipeline`)
- create experiment (`client.create_experiment`)
- run pipeline in experiment (`client.run_pipeline`)

This way the outcome is consistent with an ad-hoc run from the pipeline editor.

**Comment by a-ag** [comment]
Investigated this issue and this is not reproducible. The pipeline shows up under both `>pipelines` and `>experiments` on KFP UI.

**Comment by lresende** [comment]
Thanks for the investigation @a-ag
