### ISSUE TITLE
Python editor: current working directory behavior is unexpected

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1046]
Create the following setup:
 - the file browser lists no files
 - create a python script `script1.py` that produces a file `./file1.txt`
 - run `script1.py` in the editor. `./file1.txt` is created in the same directory
 - create a subdirectory `dir2`
 - in `dir2` create a python script `script2.py` that produces a file `./file2.txt`
- run `script2.py` in the editor. `./file2.txt` is created in the parent directory

I do realize that when one runs `python dir2/script2.py` in a terminal window, `cwd` is `.`.  However, in JL I expected `cwd` to be the directory where the Python script is located, since a drill down in the file browser should be semantically equivalent to a `cd dir2`. The script name in the editor also lists `script2.py` not `dir2/script2.py`, which seems to imply that `cwd` is the location of the script, not the base directory in the file browser.

Related issue: https://github.com/elyra-ai/elyra/issues/1045

**Comment by kevin-bates** [comment]
I suspect this could have something to do with how the editor is starting the kernel that will run the script.  

@karlaspuldaro - I believe [kernel launch from the editor](https://github.com/elyra-ai/elyra/blob/ade62e2233a49d2f18e9d0386a914edef8380580/packages/python-editor/src/PythonRunner.ts#L69) can specify things like a `path` in addition to the kernel name.  Do you know if that's true and/or what parameters are allowed in the start request body?  

When `path` is set, the server will, I believe, equate that to what will become the kernel process's working directory.

**Comment by karlaspuldaro** [comment]
@kevin-bates Yes I think that's correct, according to[ ISessionOptions](https://jupyterlab.github.io/jupyterlab/modules/_services_src_index_._services_src_session_session_.html#isessionoptions) a `path` can be also passed in as in [this example](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/packages/services/examples/browser/src/session.ts#L19).

**Comment by kevin-bates** [comment]
Thanks @karlaspuldaro.  For this issue, we might want to explore setting `path` to the directory (relative to the root) in which the python script is located.  This path will then get used as the [`cwd` for the kernel](https://github.com/jupyter/notebook/blob/cd7a06ce88387b70c3dbe1bca6ab5ae222e28c60/notebook/services/kernels/kernelmanager.py#L174-L175).   The example shows it reflecting the notebook filename, but where it gets converted to the `kernel_path`[in session creation](https://github.com/jupyter/notebook/blob/cd7a06ce88387b70c3dbe1bca6ab5ae222e28c60/notebook/services/sessions/sessionmanager.py#L95-L102), a [pure directory is tolerated](https://github.com/jupyter/notebook/blob/cd7a06ce88387b70c3dbe1bca6ab5ae222e28c60/notebook/services/contents/filemanager.py#L595-L598).

**Comment by karlaspuldaro** [comment]
@kevin-bates Makes sense, I can take a look at that.

**Comment by lresende** [comment]
Reassigning to try to get this to the 1.4 release
