### ISSUE TITLE
lint-server error message

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1051]
When running `make install` from master we are getting this lint error:
```
elyra/pipeline/tests/util.py:35:1: H238: old style class declaration, use new style (inherit from `object`)
elyra/pipeline/tests/resources/node_util/node_util.py:23:1: H238: old style class declaration, use new style (inherit from `object`)
make: *** [lint-server] Error 1
```

**Comment by kevin-bates** [comment]
These changes were introduced in #991.  That PR and subsequent PRs did not encounter the lint issue which is run as part of the CI.  I agree these should be flagged, but given this didn't come up until now implies a hole in our build process.
