### ISSUE TITLE
Import/export functionality for runtime configurations

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1066]
In runtime configurations, it would be helpful to import/export runtime configurations.
In addition, importing / exporting a list or selection of configurations would be a nice additional feature

![image](https://user-images.githubusercontent.com/5694071/98913978-5ef36280-24c8-11eb-8eae-ce8beae52165.png)

**Comment by ptitzler** [comment]
We should probably support this for all types of metadata (code snippets, runtime images, ...), not just runtime configurations.

**Comment by kevin-bates** [comment]
We should also discuss:
- if this is to be performed from UI or CLI or both?
- what is the output format - which becomes the input format?  A combined JSON or tar file, etc.? (JSON is more user friendly)
- how are desired export sets expressed?  List of specific names?  Everything for a given schema?  namespace?
- how to deal with differing schema versions on import?

**Comment by lresende** [comment]
Also, it's good to remember that these are pretty much json files on a local folder, so in the mean time, they can be manually copied. 

```
$ elyra-metadata list runtimes
Available metadata instances for runtimes (includes invalid):

Schema   Instance    Resource                                                           
------   --------    --------                                                           
kfp      kfp-shared  /Users/lresende/Library/Jupyter/metadata/runtimes/kfp-shared.json  
```

**Comment by ptitzler** [comment]
Metadata import using CLI will be delivered by the PR for https://github.com/elyra-ai/elyra/issues/2500. 

A related feature (duplicate metadata) was added to the GUI to make it easier to create similar metadata instances quickly. ([Documentation](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#duplicating-a-runtime-configuration), [Demo](https://github.com/elyra-ai/elyra/releases/tag/v3.6.0))

Import/export from/to a remote location (browser on machine A, JupyterLab running on machine B) is not supported.
