### ISSUE TITLE
Publish Elyra images on more than one public registry

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1069]
Related to https://github.com/elyra-ai/elyra/issues/1068. We should consider publishing the [Elyra images](https://hub.docker.com/r/elyra/elyra/tags) also on another public registry, such as quay.io.

**Comment by akchinSTC** [comment]
A copy of all runtime images provided has been pushed to quay.io under the elyra org

**Comment by ptitzler** [comment]
I see Elyra `1.4.1`, but there's no `latest` tag unlike on Docker Hub. Is that intentional?

**Comment by akchinSTC** [comment]
If i remember correctly the latest tag in dockerhub doesn't mean the latest version of that particular image per se. In order to avoid confusing users who don't understand the nuance, I opted not to push latest tags. (although maintenance of the image the tag is attached to ultimately falls on us)  If there is a use case for us needing to use the latest tag, we can create them then.

**Comment by ptitzler** [comment]
Right, I was just thinking about consistency and our documentation assets. We should either maintain a `latest` image tag in "both/all" public registries or none of them. Either option is fine with me. The current state I'd rather avoid since there's no reasonable explanation we can give why the difference is warranted.

**Comment by akchinSTC** [comment]
lets stay consistent with docker.io then. Will start adding latest tags to our images.

**Comment by ptitzler** [comment]
Doc update: https://github.com/elyra-ai/elyra/pull/1124

**Comment by ptitzler** [comment]
Do note that the current `Dockerfile` [references an image](https://github.com/elyra-ai/elyra/blob/master/etc/docker/elyra/Dockerfile#L19) `jupyterhub/k8s-singleuser-sample:0.9.0`, which is not on quay.io.

**Comment by akchinSTC** [comment]
All runtime images have been pushed to quay.io as well as docker.io. 
Images that only have a single version tag (e.g. images that dont contain specific library versions) have been updated with latest tags.

**Comment by ptitzler** [comment]
Perhaps it would be good to add a description in each repository indicating whether the images are mirrors and what their source is?

**Comment by akchinSTC** [comment]
^^ added descriptions to the images
