### ISSUE TITLE
 Add support to pull runtime images as an authenticated user

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1070]
Adding support to be able to pull container images as an authenticated user on dockerhub will allow us to avoid the rate limit imposed by dockerhub.

**Comment by ptitzler** [comment]
I believe this requirement was fulfilled when support for image pull secrets was added. The relevant documentation can be found here:
https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html#image-pull-secret-pull-secret

Please re-open issue if this does not meet the original goal of this issue.
