### ISSUE TITLE
Ability to have a default Runtime Image for nodes

### ISSUE THREAD

**Issue by gherka** [elyra-ai/elyra#1073]
When creating a pipeline purely for local use, the Runtime Image option doesn't seem to affect anything, but is still required before the pipeline can be run. For more than a few nodes this gets tedious pretty quickly. 

It'd be nice to be able to bypass this setting for local workflows or better still specify a Jupyter kernel for notebooks or virtual environment for code nodes.

Is this something that you think of as "in-scope" or the development focus is primarily on cloud containers / workflows?

**Comment by gherka** [comment]
answered at PyData Global

**Comment by nchelaru** [comment]
Do you mind sharing what the answer was? 👍 

You are right, setting the runtime for every notebook when run locally get very tedious. It would be great if a default runtime can be set.

**Comment by ptitzler** [comment]
> Do you mind sharing what the answer was?

As of today ...

> It'd be nice to be able to bypass this setting for local workflows

We have a more general enhancement request open (https://github.com/elyra-ai/elyra/issues/1129) that introduces the concept of global pipeline properties. Some of these global properties will apply to all pipeline nodes unless they are overridden. If implemented, one such global property could be the runtime environment setting, which would then remove the need to select a runtime for every node.

> specify a Jupyter kernel for notebooks or virtual environment for code nodes.

This is how it already works today for notebooks. The kernel that's specified in the notebook properties is used.

**Comment by nchelaru** [comment]
Thank you for the quick reply!
