### ISSUE TITLE
Drag and drop still highlights in Safari

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#1074]
When drag and dropping nodes into a pipeline or code snippets into a notebook the page is highlighted while doing the drag and drop. This should not happen.

![Untitled](https://user-images.githubusercontent.com/13952758/99126068-48c5cf00-25ba-11eb-99f5-6c45106c9dd7.gif)
![Screen Recording 2020-11-13 at 2 00 35 PM](https://user-images.githubusercontent.com/13952758/99126072-49f6fc00-25ba-11eb-87a6-99b6556db9ff.gif)

**Comment by karlaspuldaro** [comment]
No random highlights in Safari Version 14.1 and Elyra v2.3.0-dev
![Jun-15-2021 14-30-50](https://user-images.githubusercontent.com/25207344/122105527-e39fb980-cde6-11eb-86e5-e51e5d32c879.gif)
