### ISSUE TITLE
Update Extensions to use federated build

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#1077]
Jupyterlab 3.0 has introduced a new way to build extensions (currently refereed to as federated builds) that leverage pip to make the extensions build dynamically. More information can be found in the docs https://jupyterlab.readthedocs.io/en/latest/user/extensions.html#extensions

We should update Elyra's extensions to use the new build system. Since this upgrade is non-trivial it was decided to not make the update part of Elyra's initial support of Jupyterlab 3.0

Some initial notes from when I had a working branch using federated builds:

- The new build setup require many new build files, many of which contain redundant metadata, we may want to find a way to generate the build files rather than have static files that need to be kept in sync.
- With the new build system, many of the build steps in our current Makefile may be redundant, in my previous "working" branch our Makefile seemed to rebuilding the code 3-4 times when leveraging the new build system.

**Comment by ajbozarth** [comment]
Putting some observations down here for reference:

Lab offers a tool for migrating single extensions to the new build system that works great for single extensions, this can also work with local libraries as well.

An issue with the above tool and suites like Elyra is that Elyra currently builds into a top level build dir using learn, but the migration assumes a build dir per package. this starts causing issues when leveraging libraries that depend on each other (eg the metadata extension package depends on metadata-common library package which depends on ui-components library package). Normally there are no version conflict issues because learn creates a shared build dir, but by having individual build dirs per package those conflicts arise. 

A potential solution I thought of immediately prior to the holiday (thus I have not had an opportunity to attempt) would be to "trick" the new build system to build all the packages at root (as it does now) which would remove the issue.

Another solution I though of over vacation that I'm unsure of would be to "have two build systems." This solution seems bad at first glance but actually would take advantage of how the new build system works for developers.

In the pre-built extensions build system, each extension has a python build file, just like backend extensions do. This allows users to install an extension in one step. But for devs the build steps are actually increased and essentially still leverage the source extension builds, but called indirectly through the python build.

So IIUC we could potentially add these new build files, but only leverage them for our releases and not local dev builds. Again I have not had time to test this theory yet though.

**Comment by ajbozarth** [comment]
Note that https://github.com/mamba-org/gator and https://github.com/jupyter-lsp/jupyterlab-lsp both have done this migration (as was directed to me a couple days before the holidays). From reading their code I am unsure which of my two method above they use (or if it's some amalgamation of both)

**Comment by ajbozarth** [comment]
migration tool documentation for reference https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#jupyterlab-2-x-to-3-x

**Comment by ajbozarth** [comment]
also @bourdakos1 old open draft PR for reference. This attempt was a partially successful try at having the build dirs in each package

**Comment by bourdakos1** [comment]
Howdy 👋
