### ISSUE TITLE
Metadata editor should not persist empty values for optional fields unless explicitly set

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1087]
Feel free to rename issue ^^

When retrieving values from the `runtime_configuration.metadata` dictionary for use in the processor, empty fields in the UI should not produce empty values for keys in the dictionary. Ideally the key would not be present in the dictionary at all. 

See #1053 and PR #1081

**Comment by kevin-bates** [comment]
Thanks Alan.  Yeah, I think the issue is more about what is persisted.  Once that is resolved, the retrieval portion will just work.  

The CLI tool works correctly by only persisting specified fields (or those not specified who's metadata specify a default value).

**Comment by akchinSTC** [comment]
![image](https://user-images.githubusercontent.com/13340013/99697485-a176eb00-2a44-11eb-82ff-cba9bf800f91.png)
Once the user_namespace field is set and saved, any attempts to remove it via the UI results in a regex match failure.
