### ISSUE TITLE
"Making server request..." dialog content should be customizable

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1091]
Various tasks in the Elyra UI display a generic message dialog 

![image](https://user-images.githubusercontent.com/13068832/99827972-2dede000-2b0f-11eb-947e-101561f6ddc2.png)

It would be nice if both, the heading and the text would be optionally customizable to provide the user with relevant information. 

For example, a pipeline export could take a while and it's not necessarily obvious to the user why. Context information might provide insights why:

```
Processing pipeline ...

Packaging and uploading pipeline artifacts to cloud storage. This may take some time.

[OK]
```

**Comment by ptitzler** [comment]
As far as I can tell the following features should benefit from this:
 - local pipeline execution
 - remote pipeline execution
 - export pipeline

**Comment by ajbozarth** [comment]
I have this partial implemented and will be continuing work on it today
