### ISSUE TITLE
Simplify https://github.com/elyra-ai/elyra repository README

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1102]
The readme currently contains a lot of low level information that we can probably remove or replace by linking to the appropriate official documentation, which we've improved a lot during the past couple of months. Doing so would remove duplication (and thus simplify maintenance) and make the readme cleaner.

Opportunities for Growth include:
- Add new getting started section with links to the most important resources, such as tutorials. This would replace the current features list and add links to the in-depth topics in the documentation.
- Remove section https://github.com/elyra-ai/elyra#configuring-runtimes-for-pipeline-execution
- Remove docker content https://github.com/elyra-ai/elyra#using-docker and link to https://elyra.readthedocs.io/en/latest/getting_started/installation.html#docker instead

**Comment by akchinSTC** [comment]
Fixed with #1122. Closing
