### ISSUE TITLE
When using elyra dev tag error is main.js: SyntaxError: expected expression, got '?'

### ISSUE THREAD

**Issue by dummys** [elyra-ai/elyra#1112]
Hi, using kubernetes and the elyra image I get the following error:

`SyntaxError: expected expression, got '?'main.e41ae1cf1107c2b063a2.js:46:31`

It seems to be this line: `_CONFIG_DATA = configData ?? Object.create(null);` that fail.

when launching with helm  my chart for jupyterhub I get this warning:

`coalesce.go:196: warning: cannot overwrite table with non table for extraConfig (map[])`

My config: 

```
hub:
  db:
    type: sqlite-memory

  extraConfig: |-
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
        def get_env(self):
            env = super().get_env()

            env['KG_HTTP_USER'] =  self.user.name
            env['KERNEL_USERNAME'] =  self.user.name

            return env
    c.JupyterHub.spawner_class = CustomKubeSpawner
    config = '/etc/jupyter/jupyter_notebook_config.py'
    c.Spawner.start_timeout = 500
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - ""
singleuser:
  # force using new UI from jupyterlab
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    tag: dev
    # disable this in a production environment
    pullPolicy: "Always"
  storage:
    dynamic:
      storageClass: nfs-dynamic
  extraEnv:
    JUPYTER_GATEWAY_URL: http://myurl/gateway
    KG_REQUEST_TIMEOUT: "120"
```

**Comment by lresende** [comment]
This is good timing, as I am just about updating my jupyterhub scripts/environment. 

By taking a quick look at your config, I noticed it has a couple of differences:
https://github.com/lresende/ansible-kubernetes-cluster/blob/master/roles/jupyterhub/templates/jupyterhub-config.yaml.j2

Let me make progress on my side and I will let you know. 

BTW, what version of Hub or Z2JH are you using?

**Comment by dummys** [comment]
Hello,

first I tried the 1.2.1 but then I get warning because I'm not using 1.1.0, then I downgraded to 1.1.0

**Comment by lresende** [comment]
A couple of updates here:

> coalesce.go:196: warning: cannot overwrite table with non table for extraConfig (map[])

I got this warning, but AFAIK it is not affecting the configuration at all, and I moved this to a lower priority

> But if I understand correctly, normally when I go to /gateway, traefik should redirect the query to / on the gateway right ? Not /gateway

Yes, you will need to configure stripPrefix, and with the new traefik, it should look like [this](https://github.com/lresende/ansible-kubernetes-cluster/blob/master/roles/jupyter-enterprise-gateway/templates/enterprise-gateway-ingress-route.yaml.j2) or the [old way](https://github.com/lresende/ansible-kubernetes-cluster/blob/f50ae934e4602299cbdcbc50927bb115fcff917d/roles/jupyter-enterprise-gateway/templates/enterprise-gateway-ingress.yaml.j2).


**Current status:**
I am now tweaking the Elyra image to properly work with the volume mounts, as the current one is configuring things on the jovyan user home directory that gets overridden by the nfs storage configured [here](https://github.com/lresende/ansible-kubernetes-cluster/blob/f89607dfacdcda459904e134ffc8336830ed37f8/roles/jupyterhub/templates/jupyterhub-config.yaml.j2#L50).

**Comment by dummys** [comment]
ok to be honest I'm fed up debugging this traefik things, so much time I'm on it and it didn't work. I always get a "404 ERROR for /gateway" It's like the PathPrefixStrip is not working nor used by this F**** traefik....

**Comment by lresende** [comment]
Yes, these are some of the issues I have fixed either on the `ansible-scripts` and/or the new image `quay.io/elyra/elyra:dev`. Once you pass these, the one extra remaining thing is that in order to have this working with lab3, we need to set `JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"` on the hub config. 

With these changes, I seem to have all working now, let me push these changes to the respective repositories and as you to do a final test. 

BTW, Thank you for the patience, I know how it is, as I was also very frustrated with ingress and some of the K8s configuration stuff. But I am glad we made good progress.

**Comment by lresende** [comment]
I have pushed the latest [JupyterHub config](https://github.com/lresende/ansible-kubernetes-cluster/blob/master/roles/jupyterhub/templates/jupyterhub-config.yaml.j2) and you could use the command below to update your hub deployment:
```
helm upgrade hub jupyterhub/jupyterhub --namespace hub --version 0.10.6 --values /tmp/ansible-install/jupyterhub-config.yaml
```

Note that the config is now using the elyra image from quay.io, which I have been updating with the fixes to some of the permission issues you described above. 

@dummys Please let me know if that works for you.

**Comment by lresende** [comment]
> And last but not least, is it possible to make it work with ubuntu ? It would be nice to deploy everything from scratch.

In ubuntu you could use `microk8s` which will give you a working k8s environment with storage and ingress,  and you just need to cherry-pick the commands to deploy gateway and hub from the ansible scripts.

**Comment by lresende** [comment]
The changes to Elyra docker image have been released as part of Elyra 1.4.2, and configuration updates have been updated to the ansible scripts. Note that, Elyra 1.4.2 is still based on JupyterLab 2.x while master (and the Eyra image dev tag) is based on JupyterLab 3.0 release candidates.

**Comment by dummys** [comment]
ok but then changing the version of the hub means changing the version of the gateway ? I have made a small fix to fix the permissions issue:

```


```

**Comment by lresende** [comment]
The hub and gateway versions are independent.

**Comment by dummys** [comment]
ok I see. For now its not working

` https://github.com/jupyter/enterprise_gateway/releases/download/v2.3.0/jupyter_enterprise_gateway_helm-2.3.0.tgz`
I use this gateway

**Comment by lresende** [comment]
Find me or others on the Elyra team at: https://gitter.im/elyra-ai/community
We also have dev meetings every Thursday, see project readme for details (at the bottom of the readme)

**Comment by dummys** [comment]
ok but I didn't received any response on the gitter.

**Comment by lresende** [comment]
@dummys please reopen if we still need to discuss this issue.
