### ISSUE TITLE
Data Asset Browser/Navigator/Explorer

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1119]
Enable Elyra to allow for browsing through data sets from:

- [ ] IBM DAX 
- [ ] openml.org
- [ ] https://huggingface.co/datasets

Once selected, python code for accessing it is generated and pasted to the notebook, and/or a component can be dragged and dropped to the pipeline editor

**Comment by akchinSTC** [comment]
Closed
See https://github.com/elyra-ai/elyra/issues/2560
