### ISSUE TITLE
Cannot set breakpoints on debugger mode

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1121]
Steps to reproduce:
- Run `make clean install` on Elyra's master branch
- Run jupyterlab
- Open a python notebook
- Select the xpython kernel
- Enable debugger on the toggle button in the notebook toolbar
- Try to set a breakpoint by clicking next a number line in your notebook code cell

Issue: Can't add breakpoints
Browser console error: `Cannot read 'sourcePath' of undefined`, pointing to [this debugger code line in lab](https://github.com/jupyterlab/jupyterlab/blob/22fe80330ed3a9eba3eac123306cab255d787dc2/packages/debugger/src/service.ts#L399)

**Comment by karlaspuldaro** [comment]
Trying out a few package combinations I noticed that, for both elyra and lab3 only environments, the requirements are:
For python 3.7, xeus-python >=0.8.0,<0.9.0
For python 3.8, xeus-python=0.9.0

We need to fix Elyra's clean-jupyterlab script to install the appropriate xpython version.
This can issue also be raised in lab.

**Comment by lresende** [comment]
Please raise this with labs, as they are closing the release.

**Comment by karlaspuldaro** [comment]
Lab issue https://github.com/jupyterlab/jupyterlab/issues/9414
