### ISSUE TITLE
Cannot build current master branch using `make clean install`

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1128]
Running `make clean install` in my existing dev environment (where an older dev build based on JupyterLab 2.2.9 was already installed) the following error is raised:

```
cd packages/theme && jupyter labextension install --no-build .
An error occured.
ValueError: 
"@elyra/theme-extension@2.0.0-dev" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension         Package
>=2.2.6 <2.3.0          >=3.0.0-rc.10 <4.0.0@jupyterlab/application
>=2.2.6 <2.3.0          >=3.0.0-rc.10 <4.0.0@jupyterlab/apputils
>=2.2.6 <2.3.0          >=3.0.0-rc.10 <4.0.0@jupyterlab/launcher
>=16.9.0 <16.10.0       >=17.0.1 <18.0.0  react
See the log file for details:  /var/folders/h8/l3qh8v192rv_vvggc6wyphzc0000gn/T/jupyterlab-debug-vfn6sx26.log
make: *** [install-ui] Error 1
```

Output from `pip freeze | grep -i jupyter` after the failed installation attempt

```
jupyter-client==6.1.7
jupyter-core==4.7.0
jupyter-server==1.0.7
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
pytest-jupyter==0.0.1

```

**Comment by ptitzler** [comment]
The same build in a new conda environment,  where no legacy version of JupyterLab is installed, completes as expected. It appears that `clean` doesn't properly handle the scenario where an older version of JupyterLab (2.2.9) is already installed.

**Comment by ptitzler** [comment]
Running `make install-server` the log contains the following entries:

```
Collecting jupyterlab>==3.0.0rc10
  Using cached jupyterlab-3.0.0rc10-py3-none-any.whl (8.2 MB)
...
Requirement already satisfied, skipping upgrade: jupyterlab>==3.0.0rc10 in /Users/patti/anaconda3/envs/elyra_dev/lib/python3.7/site-packages (from elyra==2.0.0.dev0) (2.2.9)
```

Based on the output and checking the referenced location

```
drwxr-xr-x   25 patti  staff     800 Dec  1 12:55 jupyterlab
drwxr-xr-x    9 patti  staff     288 Dec  1 12:55 jupyterlab-2.2.9.dist-info
```

 it appears that `pip install --upgrade --upgrade-strategy only-if-needed dist/elyra-*-py3-none-any.whl` doesn't upgrade as expected, maybe because `3.0.0.rc10` is not a stable release and `--pre` not specified?

**Comment by ptitzler** [comment]
To avoid the issue, `clean` could uninstall `jupyterlab` to  avoid the conflict.

**Comment by ajbozarth** [comment]
@ptitzler the Elyra Makefile is designed to only touch Elyra files. In order to help with development we have the `etc/scripts/clean-jupyterlab.sh` script that cleans the jupyter environment. The clean script will update your jupyterlan version to the expected version for the branch you're currently on. So for devs you would want to run that script prior to make clean install when switching between elyra major versions

**Comment by ptitzler** [comment]
Ah yes. Thank you. I didn't know about the script and didn't find a reference to it in the documentation. Is there a specific reason why this is a stand-alone script instead of a task in the `Makefile`?
