### ISSUE TITLE
Add pipeline templates

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1130]
With #1129 we are thinking about introducing pipeline global properties, and these could be generic environment configurations common to multiple pipelines. This would enable users to create empty pipelines or a preconfigured one based on a previously created template.

**Comment by akchinSTC** [comment]
Small Update, based on our weekly dev meeting today 2/4, this feature was +1 by Theodore during the meeting to provide pipeline scoped env variables for each node.
