### ISSUE TITLE
Discontinue use of `latest` tag for Elyra container images?

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1139]
We currently build and publish Elyra images on Docker Hub and quay.io, but
- don't automatically tag an image as `latest`
- don't define a publish task in the main `Makefile` (not specific to `latest`)
- don't document how container images are published in the two public registries

Before we can try to close these gaps, we should decide whether or not we want to continue using `latest` as a valid tag, and if we do, what its semantics are, as there could be a need for multiple `latest` tags, e.g. one for each release.

**Comment by ptitzler** [comment]
I would be in favor of discontinuing use of the `latest` tag and removing it from Docker Hub and quay.io  because there won't be anymore any ambiguity what published code level a tagged release refers to.

Removal of the tag would require updates of the main repo readme, several places in the documentation and some of the published articles/blog posts.

**Comment by akchinSTC** [comment]
@lresende 
Use of the latest tag presents the following issues:
- We will need to create separate images, as in image names for each of the elyra branches (1.x, 2.x) and label them as such order to support the latest tag
- Same goes for each of the pipeline runtime images we host, this part will get very messy considering we host 4 different tensorflow images. 

With that said, we should discontinue use of the latest tag in all repositories and stick with pulling explicit tags from any and all image registries. 

Thoughts?

**Comment by ptitzler** [comment]
We've discussed this and decided to continue publishing Elyra container images with the `latest` tag. `latest` does not refer to the most current published release. It always refers to the **stable release with the highest version identifier**, which is always built from the main branch.

Hypothetical example, assuming there are two releases `1.x` and `2.x` being maintained:

- `1.5.0`
- `2.0` ->  `latest`

If a version `1.5.1` is published after `2.0` was published, it would not be tagged `latest` because it is associated with a downlevel release.

- `1.5.1`
- `2.0` ->  `latest`

**Comment by lresende** [comment]
Can we close this?
