### ISSUE TITLE
About "Output Files" of pipeline node property

### ISSUE THREAD

**Issue by vlavorini** [elyra-ai/elyra#1149]
Hello,

is the "Output Files" field in a pipeline node really used?

I fellow the [hello world](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world) tutorial, and I see that if I change the "Output Files" field in the  `load_data.ipynb` node, the pipeline is executed anyway without a blink. This means that neither the actual node nor the following one really need this field, and their link is "manually hardcoded" within the notebooks via the write and read of the CSV files.

So my question: why is it this field needed?
Is there a way of accessing this property inside the notebooks?

Thank you for the clarification

**Comment by ptitzler** [comment]
Hi @vlavorini,

You are right that local pipeline execution does not require output files to be declared. However, if you run a pipeline on Kubeflow Pipelines (or in the future in other supported remote environments, where each notebook or Python script is executed in an isolated container), you have to.  Please take a look at the extended tutorial (https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world_kubeflow_pipelines) for a more in-depth explanation.
