### ISSUE TITLE
Does pipeline editor support Kubeflow pipeline components directly? 

### ISSUE THREAD

**Issue by Jeffwan** [elyra-ai/elyra#1152]
I am trying elyra recently and notice pipeline editor interface ask "start your new pipeline by dragging files from the file browser pane"

Seems it will use python files or notebooks as a step in Kubeflow Pipeline. It's a little bit hard for existing kubeflow pipeline who are familiar with Ops. 

Does pipeline editor supports https://github.com/kubeflow/pipelines/tree/master/components directly? I think it would be great to drag those components in the editor and the experiences will be very close to how we use `kfp` sdk to build the pipeline.

**Comment by akchinSTC** [comment]
Hi Jeffwan !
Thanks for visiting! You are correct in that we only support python scripts or notebooks as a step in the pipeline editor for now. We are currently working the second iteration of Elyra pipelines with this enhancement in mind. We plan on supporting components specific to each runtime. As always we welcome any discussion/feedback or contributions =) around these issues.

#1002 Elyra Pipeline Editor 2.0 (umbrella issue), and more specifically 
#1004 - Add support for pipeline runtime specific components. 

There is a work in progress PR at the moment #969.

**Comment by Jeffwan** [comment]
@akchinSTC Thanks a lot. This is very helpful and I will take a look and see if anything I can help with.
