### ISSUE TITLE
Investigate cypress failures on CI runs

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1154]
As a follow up to #533 implemented in #1044 , the tests for `inserting code snippets into various widgets` are failing CI runs and need further investigation.

Steps where tests fail remotely only:
- After inserting a snippet, the code mirror check fails because the content is not yet rendered
- After checking code mirror, the new tabs are closed (for notebook, python editor and markdown files). A save dialog is expected to be displayed, although the screenshot on CI indicates that the dialog has already been dismissed somehow

This isn't a blocker issue. Insert tests can be uncommented for local dev runs.

**Comment by lresende** [comment]
Not an issue anyore
