### ISSUE TITLE
Delete confirmation dialog message does not reveal metadata type

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1160]
![image](https://user-images.githubusercontent.com/13068832/102247647-0c390c00-3eb5-11eb-84e0-4a6099ed34cd.png)

Not totally sure but I believe in earlier releases the message was more user friendly and said something like "`Delete [runtime configuration | runtime image | snippet | ...] : <id>`".

![image](https://user-images.githubusercontent.com/13068832/102247978-84073680-3eb5-11eb-9f7d-260bedff88fb.png)

**Comment by akchinSTC** [comment]
Marking this as seen in v1.5.3
![image](https://user-images.githubusercontent.com/13340013/106817078-34c6c200-662b-11eb-9f9f-19520e49aa6a.png)

**Comment by ptitzler** [comment]
Maybe I'm misremembering and @marthacryan only added custom code for code snippets?

**Comment by karlaspuldaro** [comment]
@ptitzler correct, the only dialog message describing the metadata type is for code snippets
![image](https://user-images.githubusercontent.com/25207344/116463833-2f979e80-a839-11eb-8040-f0c36b3a74bc.png)
