### ISSUE TITLE
creating Dockerfile with buildah from kernel-image-puller lead to a permission issue on quay.io

### ISSUE THREAD

**Issue by dummys** [elyra-ai/elyra#1165]
I'm trying to use buildah on my k8s cluster migrated to containerd to pre-pull image and I'm always getting error using the registry:

```
buildah pull docker.io/elyra/kernel-imager-puller
Error initializing source docker://elyra/kernel-imager-puller:latest: Error reading manifest latest in docker.io/elyra/kernel-imager-puller: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

ERRO exit status 125
```

Pulling on another registry is working like:

```
buildah pull docker.io/byrnedo/alpine-curl
Getting image source signatures
Copying blob c975b7455e06 done
Copying blob 89d9c30c1d48 done
Copying config 621496cef4 done
Writing manifest to image destination
Storing signatures
621496cef4f8cdf5a9b44cd538d4a23c7546b9b86bbb041f50032c5dd3c9c444
```

**Comment by dummys** [comment]
and with skopeo inspect it lead to error:
```
sudo skopeo inspect docker://elyra/kernel-image-puller
FATA[0001] Error parsing image name "docker://elyra/kernel-image-puller": Error reading manifest latest in docker.io/elyra/kernel-image-puller: manifest unknown: manifest unknown
```

**Comment by dummys** [comment]
didn't see that they were a typo `image`

**Comment by kevin-bates** [comment]
Also, please note that kernel-image-puller is an Enterprise Gateway application and only pulls _kernel_ images based on a server's set of kernelspecs.  It has nothing to do with Elyra and the _runtime_ images it uses.

Ref: https://github.com/jupyter/enterprise_gateway/issues/916

_((Historical note: The initial "project name" for Enterprise Gateway was `elyra` and some remnants of that have remained (like the docker hub org).  Then we needed a "project name" for the pipeline stuff and decided to use `elyra` there.  As a result, we have this confusing overlap relative to project-specific images in Enterprise Gateway and Elyra.))_
