### ISSUE TITLE
Integrate jupyterlab-lsp to Elyra 2.0

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1173]
Elyra users would benefit from a full integration with the [jupyterlab-lsp extension](https://github.com/krassowski/jupyterlab-lsp). The Language Server Protocol provides a high level support for multiple programming languages, the integration with jupyterlab brings editor features such as autocompletion, code navigation, hover suggestions, linters and rename.

Currently, the extension supports JupyterLab >=2.2.0, <3.0.0, therefore it requires Elyra 1.0

Installation steps:
- install jupyterlab and jupyterlab-lsp server extension
`pip install 'jupyterlab>=2.2,<3.0.0a0' jupyter-lsp`

- install front end lsp
`jupyter labextension install @krassowski/jupyterlab-lsp`

- install lsp server for languages of your choice (eg. python)
`pip install python-language-server[all]`

- install elyra
`pip install elyra && jupyter lab build`

Support for JupyterLab 3.0 is already in progress. After a new release, it will be ready for Elyra 2.0 integration

**Comment by lresende** [comment]
Just to make sure, for 2.0 release, we want to make sure these are integrated as with git and it's transparent to the user

**Comment by ptitzler** [comment]
Must have.
