### ISSUE TITLE
Allow for creation of a notebook from URL

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1187]
As a user, I commonly explore notebooks that are stored in a public location, for example on GitHub or S3. Currently there does not appear to be an (obvious) way to create a notebook in JupyterLab from an external source without downloading it first.

Example:
A user would like to try the JupyterLab debugger example notebook, which is located here: https://github.com/jupyterlab/debugger/blob/master/examples/index.ipynb
To use the notebook, the user currently either has to clone the entire Git repository and then locate the notebook file, or download the source to the local machine.

**Comment by kevin-bates** [comment]
I agree this would be a nice feature, but it doesn't seem applicable to Elyra.  Are you asking that there be some kind of Elyra-based extension that can address this?

**Comment by ptitzler** [comment]
Yes, it's more of a general requirement. Would a JupyterLab enhancement request be more appropriate?

**Comment by lresende** [comment]
Please create a feature request for JupyterLab.
