### ISSUE TITLE
Unable to install versions>2.0

### ISSUE THREAD

**Issue by vlavorini** [elyra-ai/elyra#1189]
Hi,

In fact, the latest available version seems to be the 1.5.3:

     pip install  --use-deprecated=legacy-resolver elyra==

    # output:
    ERROR: Could not find a version that satisfies the requirement elyra== (from versions: 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 
    0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0rc0, 0.11.0rc1, 0.11.0rc2, 1.0.0b0, 1.0.0b1, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 
    1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3)

**Comment by ptitzler** [comment]
@vlavorini Version 2.0 has not been released yet. Only the master branch is currently at 2.0 / JupyterLab 3.0.

**Comment by vlavorini** [comment]
I see, thank you.
So maybe it's good to update the README, since it's not clear.

Cheers!

**Comment by ptitzler** [comment]
Ah yes. You are right. We need to do something about that.
