### ISSUE TITLE
Make opening properties flyout simpler

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#1220]
Currently, the only way to open the properties editor for pipeline nodes is to right-click a node and select "Properties" from the context menu. Once the properties editor is open, single-clicking another node will switch to the properties editor for that node.
A few ideas to make opening the properties editor faster / more straightforward:
* One idea is to open the properties editor on double-click. However, the pipeline editor currently opens the file that a node represents when that node is double-clicked, so it might be confusing to change that behavior for users. 
* Another idea is to open the properties editor on single-click (regardless of whether the properties editor is already open). This could cause issues if someone doesn't want the properties editor to be open (because of screen real estate) and they aren't able to easily keep it closed. 
* **My suggestion:** It could be good to have a toggle in the toolbar to open or close the properties editor. Then, if someone wants to quickly open the editor, it's as simple as clicking the toggle and single-clicking the node they want to edit.

**Comment by karlaspuldaro** [comment]
@marthacryan I believe this issue is already resolved with the new toolbar button that opens properties?
