### ISSUE TITLE
elyra/util/http.py, line 64 IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1228]
**Describe the issue**
Refer to https://github.com/elyra-ai/elyra/issues/1198#issuecomment-765541378 for background information.

```
File "/Users/anaconda3/envs/smartix/lib/python3.8/site-packages/elyra/util/http.py", line 64, in write_error
        reply['message'] = exception.args[0]
    IndexError: tuple index out of range
```

**To Reproduce**
See https://github.com/elyra-ai/elyra/issues/1198

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
No exception should be raised.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 1.5.3
 - Operating system: [e.g. macos, linux]
 - Installation source: custom container image
 - Deployment type: Kubeflow 1.0 [notebook server]

The issue is not OS, deployment or source specific.

**Comment by lresende** [comment]
Fixed by #1229
