### ISSUE TITLE
Metadata editor support for optional dropdown/enum is broken

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1240]
**Describe the issue**
Update a schema 9e.g. runtime) to add a new optional field, either a:

- a dropdown
```
        "engine": {
          "title": "Kubeflow Pipelines engine",
          "description": "The Kubeflow Pipelines engine in use (Argo or Tekton)",
          "type": "string",
          "uihints": {
            "field_type": "dropdown",
            "default_choices": ["Argo", "Tekton"]
          }
        },
```

- enum
```
        "engine": {
          "title": "Kubeflow Pipelines engine",
          "description": "The Kubeflow Pipelines engine in use (Argo or Tekton)",
          "type": "string",
          "enum": ["Argo", "Tekton"],
          "default": "Argo",
          "uihints": {
            "field_type": "dropdown",
            "default_choices": ["Argo", "Tekton"]
          }
        },
```

Now try to open an existing metadata document where this field was not populated (e.g. old doc with a new schema with the optional field)

Exception:
```
MetadataEditor.tsx:347 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at MetadataEditor.tsx:347
    at find (index.es6.js:2266)
    at MetadataEditor.getDefaultChoices (MetadataEditor.tsx:344)
    at MetadataEditor.renderField (MetadataEditor.tsx:460)
    at MetadataEditor.render (MetadataEditor.tsx:522)
    at vdom.js:53
    at new Promise (<anonymous>)
    at MetadataEditor.renderDOM (vdom.js:52)
    at MetadataEditor.onUpdateRequest (vdom.js:30)
    at MetadataEditor.onUpdateRequest (MetadataEditor.tsx:302)
```

Also, in the case of enums, getDefaultChoices should not look into the values of existing metadata documents as it does not support other values except the enum ones.

**Comment by lresende** [comment]
Also, what are my options for `enums`, do I need to set `"default_choices": ["Argo", "Tekton"]` on ui-hints?

**Comment by marthacryan** [comment]
The issue is coming from the dropdown field dynamically creating the default choices. It starts with the `default_choices` from `ui-hints`. The issue is arising when it appends the value of that field in all other metadata instances for that schema (and assumes that all other metadata have a value for that field, which isn't true in this case). 

I can put up a quick PR to fix this (or I could just push straight to this PR?), but @lresende or @kevin-bates how should make `enum` and `default_choices` work? If both are present, should it merge them? Or go with `enum` by default? Let me know and I can get this up this afternoon.

**Comment by lresende** [comment]
> The issue is coming from the dropdown field dynamically creating the default choices. It starts with the `default_choices` from `ui-hints`. The issue is arising when it appends the value of that field (here it's `engine`) from all other metadata instances for that schema (and assumes that all other metadata have a value for that field, which isn't true in this case).
> 

I thought that as well, but then why I have a similar issue if I manually edit the runtime and add the `engine` field? If you add it manually is the issue gone?

> I can put up a quick PR to fix this, but @lresende or @kevin-bates how should make `enum` and `default_choices` work? If both are present, should it merge them? Or go with `enum` by default? Let me know and I can get this up this afternoon.

So, from @kevin-bates point this morning, when the field is an enum, it should not consider anything else other than the values from the enum (e.g. users cannot enter their own new values)
