### ISSUE TITLE
Observations related to node properties

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1253]
**Describe the issue**

1. Currently we visually separate the runtime image property from the cpu/gpu/mem properties, as shown below:
![image](https://user-images.githubusercontent.com/13068832/106044285-60c6ce00-6094-11eb-895c-f0056a4514b7.png)

  Since the  cpu/gpu/mem properties only apply to runtime images and not to local execution we should probably not display the divider line marked in the screen capture.

2. There appears to be a value range check in place for the GPU property. 

![image](https://user-images.githubusercontent.com/13068832/106044679-e5b1e780-6094-11eb-9758-11e3cbaa16c6.png)

  If a value of 99 is entered, an error message is displayed.
  - It's not clear why 99 was selected as the threshold
  - The "invalid" value is stored if one closes the properties view and saves the pipeline. It therefore appears as if whatever constraint violation is visualized in the UI is not actually enforced or reported elsewhere. For example, changing the value to 200, saving the pipeline, and re-opening the pipeline no validation errors are raised.

**To Reproduce**
1. Create an empty pipeline
2. Add a node of any type
3. Open the node's properties

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.0.0

**Comment by marthacryan** [comment]
@akchinSTC Do you have any input on the maximum value for cpu/gpu/ram?

**Comment by akchinSTC** [comment]
It really depends on the user and environment.. I want to say a fair range for each of them would be 0-99. I personally have never seen anyone allocate 99 of any, but that not to say it couldn't happen. I imagine the kubernetes administrator would have set a global resource limit well under this number though.

**Comment by lresende** [comment]
The observation regarding the divider/separator line has been already taken care:

![image](https://user-images.githubusercontent.com/382917/111018797-e0bca500-836f-11eb-8a30-542e4e6045c2.png)


Regarding the upper limit, we have opted to not set one for now. Note that these values are suggestions and the runtime (e.g. Kubernetes) will most like just not satisfy something not available. Validation of lower boundaries have been introduced based on #1412
