### ISSUE TITLE
Feature request: possibility to use private docker repositories

### ISSUE THREAD

**Issue by ConverJens** [elyra-ai/elyra#1256]
On-prem installations are usually closed off from internet access due to security reasons and restricting to only public repositories means Elyra can't be used for on-prem installations. 

Adding the option to specify a repository as an argument or as part of the image name would solve this. Any authorization would be for the user to handle and not part of Elyra.

**Comment by ptitzler** [comment]
Related issue: https://github.com/elyra-ai/elyra/issues/1164 (TL;DR during node processing files are downloaded from public GitHub)

**Comment by ptitzler** [comment]
@ConverJens You already can specify a container registry as part of the container image name. For example, `quay.io/elyra/elyra:1.4.1` is perfectly valid. In theory you should therefore be able to specify a private container registry that is only accessible in an intranet environment, as long as no credentials are required and the container registry server is accessible from the Kubernetes cluster where Kubeflow Pipelines is running.

That said, the issue I referenced above would still need to be resolved.

**Comment by ptitzler** [comment]
I also wanted to clarify that the documentation in https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html#image-name-image-name was meant to convey that "public" refers to registries that are accessible without the need for credentials. I do realize now the ambiguity between "public = accessible on on the internet" and "public = accessible without credentials".

**Comment by ConverJens** [comment]
@ptitzler I see, thank you for the clarification! It was the fact that I got an error while trying this and that the  documentation said (from the Prerequisites): "The image must be stored in a public container registry (no authentication required) (e.g. https://hub.docker.com)." 
that lead me to believe that this was the issue. Thank you for clarifying!

**Comment by ptitzler** [comment]
I'll create a PR to update the documentation.
