### ISSUE TITLE
Allow for specifying resource constraints per pipeline step

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1257]
**Describe the issue**
When submitting a pipeline to kubeflow I get a resource error

**To Reproduce**
clone the project and run the pipeline
https://github.com/romeokienzler/elyra-classification/blob/main/train-trusted-ai.pipeline

**Screenshots or log output**
This step is in Failed state with this message: The node was low on resource: memory. Container wait was using 15980Ki, which exceeds its request of 0. Container main was using 2519384Ki, which exceeds its request of 0. 

![image](https://user-images.githubusercontent.com/5694071/106151351-8f1fd880-617c-11eb-8ff0-c20ac7a91481.png)

**Pipeline runtime environment**
KFP 1.12 on IKS

**Comment by ptitzler** [comment]
Which version of Elyra did you use? Version 2.0.x does allow for the optional definition of minimum container resource constraints. However, since this error seems to indicate that your Kubernetes system is out of resources, I doubt this will help.

**Comment by romeokienzler** [comment]
thanks @ptitzler was on an 1.x version - sorry for that - now it works like a charm!
