### ISSUE TITLE
Add Elyra support for R editor

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1263]
New feature

Make `Python Editor` a `Script Editor` and add support for R scripts

- Rename `Python Editor` to `Script Editor`
- Refactor editor code to separate UI from controller (ScriptEditorController, REditor, PythonEditor)
- Kernel dropdown displays R kernels
- Add R language server installation (make sure LSP extension features  work on R files)
- Add command to create new R file from Launcher and Main menu
- Update `SubmitScriptButtonExtension` for any python specific references (R support for pipelines reference: #1418)
- Update documentation
- Update integration tests

![image](https://user-images.githubusercontent.com/382917/110995652-9287b180-832f-11eb-9228-3e08e529b779.png)

**Comment by lresende** [comment]
Additional discussion points
- Ability to decouple installable pieces (python vs R)
