### ISSUE TITLE
Improve pipeline properties dark theme

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1268]
**Describe the issue**
This is a follow up issue based a suggestion proposed in [this PR comment](https://github.com/elyra-ai/elyra/pull/1262#issuecomment-772897698)
- Runtime image dropdown down arrow icon to have more contrast
- Also the arrows in CPU/GPU/RAM dropdowns could be dark gray instead of black

**To Reproduce**
To turn on dark mode
1. On Jupyterlab top menu, click on Settings
2. Select JupyterLab theme
3. Select JupyterLab dark

To open pipeline node properties
1. Open a pipeline with at least one node, or create a new pipeline and add a notebook from your file browser
2. Right click on a node and select Properties
3. You should see the properties side pane
![image](https://user-images.githubusercontent.com/25207344/106919103-d4418e80-66d7-11eb-80ba-792b4dab6a5f.png)

**Environment information**
 - Elyra version: v2.1.0-dev
 - Operating system: macOS
 - Browser: Chrome

**Comment by benbeetle** [comment]
@karlaspuldaro I'm thinking about taking a stab at this.  Is anyone else working on this that you know of?

**Comment by karlaspuldaro** [comment]
@benbeetle great! The issue is still open, I can assign you to it :)

**Comment by benbeetle** [comment]
@karlaspuldaro Many thanks for getting me pointed in the right direction!  

How does this look?  

![image](https://user-images.githubusercontent.com/5120460/108571050-466fc100-72dd-11eb-8f64-14cb1dca7e88.png)

![image](https://user-images.githubusercontent.com/5120460/108571053-4b347500-72dd-11eb-9b01-22010ad6c24d.png)

**Comment by karlaspuldaro** [comment]
@benbeetle Looks great! When you open a PR you can add screenshots there as well.
