### ISSUE TITLE
Changing the Editor Theme doesn't change the Python Editor theme

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#127]
When using the Setting's menu to change the theme for the Text Editor it does not apply to the Python Editor.

**Comment by kinow** [comment]
The python editor seems to be working fine for me when I switched to dark mode.

![image](https://user-images.githubusercontent.com/304786/76393145-d15ef080-63d7-11ea-82fe-2c1488b4af93.png)

And also switching to the default theme and increasing font size.

![image](https://user-images.githubusercontent.com/304786/76393193-e9cf0b00-63d7-11ea-8e8c-e077f9165c0b.png)

**Comment by ajbozarth** [comment]
Thanks for checking into this, it seems some of our recent work has made some of the `codeditor` features like dark theme start working without realizing it.

**Comment by ajbozarth** [comment]
Though python editor seems to work ok, other parts of elyra don't support dark mode. I'm going to use this issue to track addressing elyra dark mode over all. I plan to work on this myself, but if a new dev would like to take it if before I get to it that's ok as well. I'll make sure to post here when I actually start work on this. Afaik the side bar icons and side bar widgets all need to be updated for dark mode support, as well as pipeline editor.
