### ISSUE TITLE
Metadata widget should support metadata collection based on multiple schemas (e.g. airflow/kfp runtimes)

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1278]
**Describe the issue**
By enabling the support for multiple runtimes, each metadata might be based on a different schema and the editor should enable editing these files. Currently, it takes one schema and tries to apply it to the whole metadata collection. 

**To Reproduce**
1. Go to airflow pr
2. Create airflow runtime and kfp runtime
3. Try to edit a valid kfp one, and the editor does not allow to save as it expects other fields from the other schema

![image](https://user-images.githubusercontent.com/382917/107257499-969e7780-69ef-11eb-8a99-a1d77ede8416.png)

**Comment by karlaspuldaro** [comment]
Just to make sure all cases are covered, the issue happens not only on editing, but also on creating new runtime through the UI.
Also, when creating a new runtime, hovering over the `+` button shows an airflow specific msg
![image](https://user-images.githubusercontent.com/25207344/107441961-351bfd00-6b04-11eb-8f81-67a967ba4ed0.png)

**Comment by ajbozarth** [comment]
@karlaspuldaro I just pushed a fix for that

@lresende I also pushed a fix that makes sure the correct editor is opened for pre-existing runtimes if you could test it.

I'm still working on updating the UI to support multiple schemas when adding a new runtime and also plan on doing some general clean up for the UI, there's a lot of inconsistent text between the two schemas as well as some remaining hard-coded kip text to update.
