### ISSUE TITLE
Parsing of environment variables from notebook pipeline component fails

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1285]
**Describe the issue**
Parsing of environment variables from notebook pipeline component fails

**To Reproduce**
1. Insert a cell to a notebook
2. Paste the following content
from os import environ as e
source_folder = e.get('source_folder','images')
target_column = e.get('target_column','finding')
image_column = e.get('image_column','filename')
output_folder = e.get('output_folder','data')
target_replace = e.get('output_folder_replace','')
target_replace_with = e.get('output_folder_replace_with','')

3. drag to pipeline canvas
4. Observe that the env variables are not rendered

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/5694071/107649643-f447f380-6c7d-11eb-8e7d-c2bc8b29b4ce.png)

**Expected behavior**
Env. variables should be rendered

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [2.0.1]

**Comment by romeokienzler** [comment]
The following format is supported

import os
source_folder = os.environ.get('source_folder','images')
target_column = os.environ.get('target_column','finding')
image_column = os.environ.get('image_column','filename')
output_folder = os.environ.get('output_folder','data')
target_replace = os.environ.get('output_folder_replace','')
target_replace_with = os.environ.get('output_folder_replace_with','')

**Comment by ptitzler** [comment]
Can you clarify what you mean by "not rendered"? There is currently no automation in place that parses notebooks | Python scripts, extracts environment variables, and pre-populates the `Environment Variables` node properties.

**Comment by kevin-bates** [comment]
Actually, there is some parsing that happens.  I believe it handles `os.environ.get('xxx')` and `os.getenv('xxx')` forms of access.  This issue is asking for much richer parsing, which, frankly, I think we should push back on via documentation and say something to the affect of: "If you'd like your environment variables automatically populated, use one of these two forms in your script."

I don't know if this parsing occurs on python scripts or only for notebooks.

cc: @ajbozarth

**Comment by ptitzler** [comment]
Good to know! Is this a documented feature?

> This issue is asking for much richer parsing, [...] we should push back

I agree since static code analysis wouldn't be able to identify variable names in 100% of the cases anyway.

**Comment by kevin-bates** [comment]
> Is this a documented feature?

I think it will be soon. :smile:

**Comment by ajbozarth** [comment]
What @kevin-bates described is correct, but there also the limiting factor that the parsing only occurs on initial creation of a node and only works if the notebook is already open in jupyterlab when adding the node.

**Comment by ptitzler** [comment]
Given the listed constraints when parsing is performed, wouldn't it be better to make this an explicit task, for example by adding a "scan file for environment variables" button? Handling this implicitly (like it is done now) just introduces too many potential problems.

**Comment by lresende** [comment]
For now, let's document what is currently supported.
