### ISSUE TITLE
Submit notebook as pipeline fails

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1300]
**Describe the issue**
See error message

**To Reproduce**
1. Create a simple notebook
2. Configure a KFP runtime environment
3. Submit notebook for execution in that env
4. See error. Note the reference to Airflow even though KFP was selected as runtime

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
[I 2021-02-17 15:26:56.219 ServerApp] airflow 'Untitled-0217152656' - Submitting pipeline 
[I 2021-02-17 15:26:56.220 ServerApp] Creating pipeline definition as a .py file
[I 2021-02-17 15:26:56.232 ServerApp] airflow 'Untitled-0217152656' - processing pipeline dependencies to: http://cloning1.fyre.ibm.com:31671 bucket: pipeline-artifacts folder: Untitled-0217152656 
[I 2021-02-17 15:26:56.251 ServerApp] airflow 'Untitled-0217152656':'Untitled' - processing operation dependencies for id: 46d4d67f-3241-4ae6-87a3-1636f02cfe9b 
[I 2021-02-17 15:26:56.254 ServerApp] airflow 'Untitled-0217152656':'Untitled' - generated dependency archive: /var/folders/h8/l3qh8v192rv_vvggc6wyphzc0000gn/T/elyra/Untitled-46d4d67f-3241-4ae6-87a3-1636f02cfe9b.tar.gz (0.003 secs)
[I 2021-02-17 15:26:56.913 ServerApp] airflow 'Untitled-0217152656':'Untitled' - uploaded dependency archive to: Untitled-0217152656/Untitled-46d4d67f-3241-4ae6-87a3-1636f02cfe9b.tar.gz (0.173 secs)
[I 2021-02-17 15:26:56.913 ServerApp] airflow 'Untitled-0217152656' - pipeline dependencies processed (0.681 secs)
[E 2021-02-17 15:26:56.965 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1613604416188 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/elyra/pipeline/schedule?1613604416188', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 75, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 79, in process
        repo = github_client.get_repo(github_repo)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/github/MainClass.py", line 338, in get_repo
        assert isinstance(full_name_or_id, (str, int)), full_name_or_id
    AssertionError: None
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.0.x
 - Operating system: macos
 - Installation source:  from source
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines (provide version number, whether multi-user auth enabled)
 - Apache Airflow (provide version number)
 
**Runtime configuration settings**
Not relevant in this scenario

**Comment by akchinSTC** [comment]
This issue is related to the use of "the button" in the notebook. https://github.com/elyra-ai/elyra/blob/dd58862f908ab9e228cf2c77c29c76980a109c03/packages/pipeline-editor/src/utils.ts#L62 is setting the pipeline payload explicitly to `airflow` instead of deferring to a selection of runtimes.
