### ISSUE TITLE
Jupyterlab-requirements extension button is overriding the submit-notebook button in the UI

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1301]
**Describe the issue**
The submit-notebook button is missing after installing the jupyterlab-requirements extension. 

**To Reproduce**
1. install elyra ...e.g.` make clean install` on master
2. run `pip install jupyterlab-requirements` 
3. start elyra 

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/13340013/108288353-4aff7280-7141-11eb-80ec-8ca1af072bad.png)
![image](https://user-images.githubusercontent.com/13340013/108288390-5eaad900-7141-11eb-9927-bc8003bd5b12.png)
Paste the log output here.
</pre>
</details>

**Expected behavior**
Both buttons visible and functional

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0 dev
 - Operating system: macos
 - Installation source: source and pypi
 - Deployment type: local

**Comment by akchinSTC** [comment]
@pacospace - FYI

**Comment by pacospace** [comment]
Hi @akchinSTC thanks for reaching out, I opened this issue some time go, related to this case https://github.com/thoth-station/jupyterlab-requirements/issues/47. Is there a better way to make extension cannot be overwritten in terms of position in jupyterlab notebook button number? Assigning numbers can clash with any extension I assume. I can see that you have position 10 as well in place: https://github.com/elyra-ai/elyra/blob/dd58862f908ab9e228cf2c77c29c76980a109c03/packages/pipeline-editor/src/SubmitNotebookButtonExtension.tsx#L114 which is the same as we currently have. I can change that for next release `v0.4.0` to be `11` sounds good? You can track it here: https://github.com/thoth-station/jupyterlab-requirements/milestone/3

**Comment by karlaspuldaro** [comment]
I just tried to recreate this issue by adding another notebook button extension in the same position on the toolbar, this is the behaviour:
Before installing `jupyterlab-requirements`, both buttons are visible when being added in the same position (10)
![image](https://user-images.githubusercontent.com/25207344/108413186-b0626a80-71f8-11eb-9b8a-5e49a98d638d.png)

But only `Submit Notebook` button is gone after installing the `requirements` extension, independent of `submit notebook` button position in the toolbar (I tried them all at position 10, then moved submit notebook button to other positions without luck)
![image](https://user-images.githubusercontent.com/25207344/108413244-c4a66780-71f8-11eb-88c2-455cdeafe220.png)

I'm not sure the position only is the problem, I can help investigate it in lab.

**Comment by pacospace** [comment]
FYI https://pypi.org/project/jupyterlab-requirements/0.4.2/

**Comment by karlaspuldaro** [comment]
The fix in the new release of `jupyterlab-requirement` solved the issue. 
We can open a followup lab issue to avoid similar problems with other plugins.

**Comment by akchinSTC** [comment]
@pacospace - thx for the new release. seems to resolve the issue and thx @karlaspuldaro for testing. Ill open up a follow up issue in the jupyterlab repo to see if anyone there thinks this is an upstream bug. RE: #1001 - We're also going with a more formal approach by writing up a new EIP proposal to introduce the concept of a `project` or file structure in general in Elyra to support requirements files. Related issues that come up: competing projects/gitops templates like thoth ex. repo2docker etc.

**Comment by pacospace** [comment]
> EIP proposal

Thanks @akchinSTC very nice!! Please keep us in the loop :) 

Have a look at what example we created here: https://github.com/thoth-station/elyra-aidevsecops-tutorial :) let us know what you think!!
