### ISSUE TITLE
Invalid operation: circular references in pipeline.

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1303]
**Describe the issue**
Pipeline Editor shows: Invalid operation: circular references in pipeline.

**To Reproduce**
Create a pipeline as described below in the screenshot

**Screenshots or log output**

**Expected behavior**
condition-blessing=>deploy-watson should be connectable
![image](https://user-images.githubusercontent.com/5694071/108376043-dbea5280-7202-11eb-9bef-b7072b61a317.png)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.0.1
 - Operating system: RHEL/Docker
 - Installation source: dockerhub
 - Deployment type: local installation
 - 
**Pipeline runtime environment**

 - Kubeflow Pipelines

**Comment by marthacryan** [comment]
Could you post the contents of the pipeline file (JSON)?

**Comment by romeokienzler** [comment]
@marthacryan please checkout developer_article branch on https://github.com/cloud-annotations/elyra-classification-training/tree/developer_article and then please open covid19-trustedai.pipeline and try to connect "condition-blessing" to "deploy-kfserving"

**Comment by bourdakos1** [comment]
@marthacryan @romeokienzler I don't see anything out of the ordinary with the pipeline json. I'll try to put together a failing test case for the cycle check

**Comment by bourdakos1** [comment]
I've put together a minimum reproducible test case:
```
  //            ╭───╮
  //            │ e │
  //            ╰───╯
  //              ▲
  //             l3
  //              │
  // ╭───╮      ╭───╮      ╭───╮
  // │ a │──l0─►│ b │──l2─►│ d │
  // ╰───╯      ╰───╯      ╰───╯
  //              │          │
  //             l1          l4
  //              ▼          ▼
  //            ╭───╮      ╭───╮      ╭───╮
  //            │ c │──l5─►│ f │──l6─►│ g │
  //            ╰───╯      ╰───╯      ╰───╯
  {
    it: "issue #1303",
    given: [
      { id: "l0", srcNodeId: "a", trgNodeId: "b", type: "nodeLink" },
      { id: "l1", srcNodeId: "b", trgNodeId: "c", type: "nodeLink" },
      { id: "l2", srcNodeId: "b", trgNodeId: "d", type: "nodeLink" },
      { id: "l3", srcNodeId: "b", trgNodeId: "e", type: "nodeLink" },
      { id: "l4", srcNodeId: "d", trgNodeId: "f", type: "nodeLink" },
      { id: "l5", srcNodeId: "c", trgNodeId: "f", type: "nodeLink" },
      { id: "l6", srcNodeId: "f", trgNodeId: "g", type: "nodeLink" },
    ],
    expected: [],
  },
```

**Comment by ptitzler** [comment]
Yeah, if one cuts any of the marked dependencies then  no circular dependency is detected ...

![image](https://user-images.githubusercontent.com/13068832/108524562-04fef780-7284-11eb-8599-e2b0c19f5973.png)

**Comment by ptitzler** [comment]
A fix should definitely add logging that dumps the dependency list in the console to aid with troubleshooting in the future.

**Comment by bourdakos1** [comment]
@ptitzler what do you mean by the dependency list?

**Comment by bourdakos1** [comment]
I found the issue, luckily it's not an issue with the logic. It's just an `undefined` bug. basically, I'm popping from an array and if the array is empty it returns `undefined` and I'm slicing another array from 0 to the popped value, when it's undefined the sliced array should return an empty array, but this returns the entire array haha... quick fix, I'll make a PR

**Comment by ptitzler** [comment]
> @ptitzler what do you mean by the dependency list?

If a bug is caused by a logic error, wouldn't it be helpful if the console log would include something like a graph representation (a -> b -> a) of the identified loop that visualizes the dependencies?

**Comment by bourdakos1** [comment]
Isn't that what the UI does?

**Comment by ptitzler** [comment]
Not if there is a bug in the logic that evaluates the graph ...
That said, if you don't think that doing this would speed up analysis, then let's move on.

**Comment by bourdakos1** [comment]
oh I see what you mean, as long as we have the actual pipeline file it's not hard to derive a test case from it.

**Comment by ptitzler** [comment]
Okay! Five stars for adding a test case for the problem

**Comment by ptitzler** [comment]
@romeokienzler The fix is now available in the master branch and in the automatically built dev container image: `docker pull elyra/elyra:dev`
