### ISSUE TITLE
"latest" tag on docker hub is outdated

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1318]
**Describe the issue**
https://hub.docker.com/repository/docker/elyra/elyra "latest" is 3 month old, build process should ensure that "latest" always points to the latest stable release

**Comment by ptitzler** [comment]
Confirmed that this is an issue. As of today, `latest` should be equivalent to https://hub.docker.com/layers/elyra/elyra/2.0.1/images/sha256-583c9e70d1f1c9079b1a5aae52e0d8f82a61b59d0dc01bfa922e8f2fb3810508?context=explore

**Comment by ptitzler** [comment]
@kevin-bates @akchinSTC @lresende hold authority to push container images. One of them will have to address this.

**Comment by ptitzler** [comment]
The `latest` tag was updated.

![image](https://user-images.githubusercontent.com/13068832/108760507-99768d80-7502-11eb-82c0-31906661e438.png)
