### ISSUE TITLE
Drag and dropped node appeares far left on the canvas

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1319]
**Describe the issue**
Drag and dropped node appeares far left on the canvas

**To Reproduce**
Create a large horizontal pipeline, then drag a node to the canvas, it appears far left

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/5694071/108686239-6b3e8100-74f5-11eb-9af1-9e588ad7f55e.png)

**Expected behavior**
Node should appear exactly where it has been dropped to

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [dev as of commit 26163183a19504f987e26935c8fe7ca62fe64b9e]
 - Operating system: [rhel 7.9]
 - Installation source: [dev docker image]
 - Deployment type: [e.g. local docker installation]
 - Browser: FF 85.0.2

**Comment by lresende** [comment]
I cannot reproduce the problem, nodes are appearing around the location where they are dragged. 

![drag-and-drop](https://user-images.githubusercontent.com/382917/109689920-a6b2fe00-7b3a-11eb-87c5-f83342957b61.gif)

Please reopen with more details or additional information

**Comment by romeokienzler** [comment]
Thanks for having a look, please see below:

https://user-images.githubusercontent.com/5694071/111216671-fa125b00-85d4-11eb-8176-e0bc007a2940.mp4

**Comment by marthacryan** [comment]
I believe this isn't an issue with the new pipeline editor package. @romeokienzler Can you still reproduce this on a more updated version of Elyra?

**Comment by romeokienzler** [comment]
@marthacryan no - it is fixed now, thanks a lot!
