### ISSUE TITLE
Properties item not rendered anymore

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1320]
**Describe the issue**
The properties item of the component's context menu is not rendered anymore since [commit](https://github.com/elyra-ai/elyra/commit/26163183a19504f987e26935c8fe7ca62fe64b9e)

**To Reproduce**
1. git checkout  26163183a19504f987e26935c8fe7ca62fe64b9e
2. make container-image
3. docker run -it ....
4. drag a notebook to the canvas
5. try to edit it's properties, it's not working

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/5694071/108716012-e024b180-751b-11eb-890a-76daf1074106.png)

**Expected behavior**
An item called "properties" should appera

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: commit  26163183a19504f987e26935c8fe7ca62fe64b9e
 - Operating system: rhel 7.9
 - Installation source: self-built container image on commit 26163183a19504f987e26935c8fe7ca62fe64b9e
 - Deployment type: docker
 - FF version: 85.0.2

**Comment by ptitzler** [comment]
I just pulled the latest code from the `master` branch but was unable to recreate the problem.

**Comment by romeokienzler** [comment]
@ptitzler @marthacryan sorry for the hassle @bourdakos1 thanks a lot for the hint - de-selecting the nodes and selecting only one is your friend
