### ISSUE TITLE
Elyra container image that was built from master fails with `webbrowser.Error: could not locate runnable browser`

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1321]
**Describe the issue**
See error message

**To Reproduce**
1. `git clone https://github.com/elyra-ai/elyra.git` 
2. `cd elyra`
3. `make container-image` 
4. `docker run -it -p 8888:8888 elyra/elyra:dev jupyter lab`

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
**Note: Removing dead /tmp/elyra/packages/python-editor "@elyra/theme-extension"
**Note: Removing dead /tmp/elyra/packages/python-editor "@elyra/code-snippet-extension"
**Note: Removing dead /tmp/elyra/packages/python-editor "@elyra/metadata-extension"
**Note: Removing dead /tmp/elyra/packages/python-editor "@elyra/pipeline-editor-extension"
**Note: Removing dead /tmp/elyra/packages/python-editor "@elyra/python-editor-extension"
**Note: Removing dead /tmp/elyra/packages/metadata-common "@elyra/services"
**Note: Removing dead /tmp/elyra/packages/metadata-common "@elyra/ui-components"
**Note: Removing dead /tmp/elyra/packages/metadata-common "@elyra/metadata-common"
Removing orphaned linked package @elyra/services
Removing orphaned linked package @elyra/metadata-common
Removing orphaned linked package @elyra/ui-components
Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jovyan/.cache/black/20.8b1/Grammar3.8.6.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jovyan/.cache/black/20.8b1/tmprft725mx'
Generating grammar tables from /opt/conda/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jovyan/.cache/black/20.8b1/PatternGrammar3.8.6.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jovyan/.cache/black/20.8b1/tmpj2jpmoq0'
[I 2021-02-22 16:37:21.296 ServerApp] elyra | extension was successfully linked.
[I 2021-02-22 16:37:21.296 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2021-02-22 16:37:21.296 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2021-02-22 16:37:21.314 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-02-22 16:37:21.314 ServerApp] jupyterlab_git | extension was successfully linked.
[W 2021-02-22 16:37:21.321 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 16:37:21.321 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 16:37:21.322 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-02-22 16:37:21.330 ServerApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2021-02-22 16:37:21.776 ServerApp] nbgitpuller | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-22 16:37:21.776 ServerApp] nbgitpuller | extension was successfully linked.
[I 2021-02-22 16:37:21.776 ServerApp] nbclassic | extension was successfully linked.
[I 2021-02-22 16:37:21.776 ServerApp] nbdime | extension was successfully linked.
[I 2021-02-22 16:37:21.879 ServerApp] Registering processor "EntryPoint('airflow', 'elyra.pipeline.processor_airflow', 'AirflowPipelineProcessor', Distribution('elyra', '2.1.0.dev0'))" with type -> airflow
[I 2021-02-22 16:37:21.880 ServerApp] Registering processor "EntryPoint('kfp', 'elyra.pipeline.processor_kfp', 'KfpPipelineProcessor', Distribution('elyra', '2.1.0.dev0'))" with type -> kfp
[I 2021-02-22 16:37:21.880 ServerApp] Registering processor "EntryPoint('local', 'elyra.pipeline.processor_local', 'LocalPipelineProcessor', Distribution('elyra', '2.1.0.dev0'))" with type -> local
[I 2021-02-22 16:37:21.881 ServerApp] elyra | extension was successfully loaded.
[I 2021-02-22 16:37:22.015 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2021-02-22 16:37:22.016 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2021-02-22 16:37:22.018 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
[I 2021-02-22 16:37:22.018 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2021-02-22 16:37:22.022 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-22 16:37:22.025 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2021-02-22 16:37:22.031 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-22 16:37:22.148 ServerApp] nbdime | extension was successfully loaded.
[I 2021-02-22 16:37:22.150 ServerApp] nbgitpuller | extension was successfully loaded.
[I 2021-02-22 16:37:22.150 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2021-02-22 16:37:22.150 ServerApp] Jupyter Server 1.4.0 is running at:
[I 2021-02-22 16:37:22.150 ServerApp] http://1e2862c63702:8888/lab?token=fb52cde7485ba71eb37faa862296b58e7a0d0dc17ff56020
[I 2021-02-22 16:37:22.151 ServerApp]  or http://127.0.0.1:8888/lab?token=fb52cde7485ba71eb37faa862296b58e7a0d0dc17ff56020
[I 2021-02-22 16:37:22.151 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2018, in launch_browser
    browser = webbrowser.get(self.browser or None)
  File "/opt/conda/lib/python3.8/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 520, in launch_instance
    serverapp.start()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2100, in start
    self.start_app()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2059, in start_app
    self.launch_browser()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2020, in launch_browser
    self.log.warning(_('No web browser found: %s.') % e)
UnboundLocalError: local variable '_' referenced before assignment
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1 (master branch)
 - Operating system: macos
 - Installation source: custom container image built from `master`
 - Deployment type: Docker, Kubernetes

**Comment by ptitzler** [comment]
Note the `Removing dead ...` messages, which I have never seen before. I don't think they are the root cause of this issue but need to be looked at.

**Comment by kevin-bates** [comment]
This is due to a [recent issue in Jupyter Server](https://github.com/jupyter-server/jupyter_server/issues/423).  A patch release is being cut today.

**Comment by ptitzler** [comment]
Workaround: run the container image as follows:

```
docker run -it -p 8888:8888 elyra/elyra:dev jupyter lab --no-browser
```

**Comment by kevin-bates** [comment]
After building the image with Jupyter Serve 1.4.1, the following is produced:
```
[I 2021-02-22 19:49:58.260 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2021-02-22 19:49:58.260 ServerApp] http://22ae9e4be9e9:8888/lab?token=b5c5ff906eb461472d98ed26986572bbcbd9a403027cda29
[I 2021-02-22 19:49:58.260 ServerApp]  or http://127.0.0.1:8888/lab?token=b5c5ff906eb461472d98ed26986572bbcbd9a403027cda29
[I 2021-02-22 19:49:58.260 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2021-02-22 19:49:58.267 ServerApp] No web browser found: could not locate runnable browser.
[C 2021-02-22 19:49:58.268 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-8-open.html
    Or copy and paste one of these URLs:
        http://22ae9e4be9e9:8888/lab?token=b5c5ff906eb461472d98ed26986572bbcbd9a403027cda29
     or http://127.0.0.1:8888/lab?token=b5c5ff906eb461472d98ed26986572bbcbd9a403027cda29
```

No browser starts up, but no exception occurs either.  If I copy the posted URL to a browser, JLab and Elyra appear and are usable.  

I do see what looks like something related to the git extension producing the following after posting the URL...
<details><summary>possible git extension issue?</summary>
<pre>
[E 2021-02-22 20:02:26.057 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Content-Length": "19",
      "Sec-Ch-Ua": "\"Chromium\";v=\"88\", \"Google Chrome\";v=\"88\", \";Not A Brand\";v=\"99\"",
      "Authorization": "token cfe59f7ffd36fb9631296906a36ab954214e416abcd36090",
      "X-Xsrftoken": "2|dbd7acf4|36f371db221f5d8e10a5499e0e9001a2|1614024050",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Origin": "http://127.0.0.1:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://127.0.0.1:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|dbd7acf4|36f371db221f5d8e10a5499e0e9001a2|1614024050; username-127-0-0-1-8888=\"2|1:0|10:1614024146|23:username-127-0-0-1-8888|44:NWQ4OTE4NGE5YTgyNDE0MDg2NmViMDQyYWMzYzEyNDQ=|eb13baae7544330e782de80be87096868328dbd9f44496e17d8a4981f3d989c3\"",
      "Sec-Gpc": "1"
    }
[E 2021-02-22 20:02:26.057 ServerApp] 500 POST /git/show_top_level?1614024146045 (172.17.0.1) 12.22ms referer=http://127.0.0.1:8888/lab
</pre>
</details>

but I haven't used Elyra recently enough to know if this is specific to new behavior in Jupyter Server or not.

@ptitzler - could you please advise?

**Comment by ptitzler** [comment]
I am running with Jupyter server 1.2.2 and git 0.30.0b1 and am observing the same error message., which appears to be a known problem: https://github.com/jupyterlab/jupyterlab-git/issues/842.

I think we can go ahead and close this issue. Thanks for verifying Kevin!
