### ISSUE TITLE
Cannot run pipeline multiple times due to experiment creation error

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1329]
**Describe the issue**
See next section

**To Reproduce**
1. Create or import a pipeline.
2. Run the pipeline from the pipeline editor. This should succeed.
3. Run the pipeline again from the pipeline editor. 

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
ApiException: (409) Reason: Conflict HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'content-type': 'application/json', 'trailer': 'Grpc-Trailer-Content-Type', 'date': 'Tue, 23 Feb 2021 17:32:48 GMT', 'x-envoy-upstream-service-time': '15', 'server': 'istio-envoy', 'transfer-encoding': 'chunked'}) HTTP response body: {"error":"Create experiment failed.: Already exist error: Failed to create a new experiment. The name untitled already exists. Please specify a new name.","message":"Create experiment failed.: Already exist error: Failed to create a new experiment. The name untitled already exists. Please specify a new name.","code":6,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Failed to create a new experiment. The name untitled already exists. Please specify a new name.","error_details":"Create experiment failed.: Already exist error: Failed to create a new experiment. The name untitled already exists. Please specify a new name."}]}
</pre>
</details>

**Expected behavior**
The pipeline should execute without any issues and not require deletion of any KFP artifacts.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1/master
 - Installation source: from source
 - Deployment type: local installation

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines 1.3

**Comment by ptitzler** [comment]
Interesting enough this problem only occurs in the test environment only if the experiment name is `untitled`. 

Recreate:

```
import kfp
client = kfp.Client(host='http://.../pipeline')
experiment_name = 'untitled'
# create experiment fails with above error message
experiment = client.create_experiment(experiment_name, namespace='anonymous')

# get experiment fails because the experiment doesn't exist
 ex = client.get_experiment(experiment_name=experiment_name, namespace='anonymous')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/kfp/_client.py", line 454, in get_experiment
    raise ValueError('No experiment is found with name {}.'.format(experiment_name))
ValueError: No experiment is found with name untitled.
```

Replace `experiment_name` with a different value and things seem to work 🤷 . Need to dig into this some more but I'm suspecting that this is a scoping issue.

**Comment by ptitzler** [comment]
Mystery solved. On the target system there was already an experiment named `Untitled` defined. Note the difference in case - `untitled` vs `Untitled`. Somehow `create_experiment` doesn't take case into account (`u` = `U`) yet `get_experiment` does.

**Comment by ptitzler** [comment]
Updated recreate:

```
import kfp
client = kfp.Client(host='http://.../pipeline')
# create experiment succeeds if no experiment named `u|Untitled` exists
experiment = client.create_experiment('Untitled', namespace='anonymous')
# create experiment fails with above error message
experiment = client.create_experiment('untitled', namespace='anonymous')
```

**Comment by kevin-bates** [comment]
> On the target system there was already an experiment named Untitled defined.

By "target system" I assume you mean KFP (in this case).  If so, won't this still happen if the pipeline name is unique relative to the Elyra instance?

How does scoping work?  Just wondering if we need to make the experiment name unique as well (perhaps with some random letters - no a timestamp) - with that value used in subsequent runs (and suffixed with a timestamp).
