### ISSUE TITLE
Expose github exceptions in a more user-friendly way

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1332]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/13068832/109045065-00717f00-7688-11eb-9a62-2fa1c5f14576.png)

**Describe the solution you'd like**

GitHub exceptions often contain information in a structured format, like shown in the screen capture above. We should create and use a utility function that 
- determines whether the raw exception text is JSON
- if JSON: parse properties, locate relevant information and expose it

For the example, given the example above a more user-friendly message would be 
```
Error uploading DAG .... : Branch main-cookie not found. (404)
```

**Additional context**
Follow-up to https://github.com/elyra-ai/elyra/pull/1316

**Comment by lresende** [comment]
@ptitzler I just want to clarify here, are you asking to properly propagate the error (or just the cause) of it and still treat this use case as a generic `error` communicating with the git repo? Or you want to try to have special handling of specific issues?

**Comment by ptitzler** [comment]
> special handling of specific issues

... well-known error scenarios that are a result of a runtime configuration problem:
 - Invalid GitHub server API endpoint
 - Invalid access token (*)
 - Invalid repository name (*)
 - Invalid branch name (*)

The GitHub client returns a JSON data structure (see example in screen shot above) for most problems, which contains the relevant status code and status message.  The error message (the  paragraph below "Error making request") should
 - identify the operation that failed (e.g. connect or upload)
 - the problem
 - if applicable, a blurb asking the user to validate the runtime configuration, to make the dialog "actionable".
