### ISSUE TITLE
Metadata Editor / Apache Airflow configuration: display custom property

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1335]
**Is your feature request related to a problem? Please describe.**
Currently the runtime configuration metadata editor displays two links, based on the property values of the metadata instance:
 - a link to the runtime's GUI (`api_endpoint` property value)
 - a link to cloud object storage (`cos_endpoint` property value)

![image](https://user-images.githubusercontent.com/13068832/109081644-75a87880-76b7-11eb-9ce7-a5e16022bc45.png)

**Describe the solution you'd like**
For Apache Airflow runtimes there is a third GUI that we need to expose: a link to the Github location where the DAGs for the runtime instance are stored. The URL is not directly stored but can be assembled from property values as follows:
`modified_github_api_endpoint` + `/` + `github_repo` +  `/tree/` + `github_branch`  

Note that  `modified_github_api_endpoint` is the value of `github_api_endpoint` with the host name removed, e.g. `https://api.github.com` => `https://github.com`

Example: `https://github.com/ptitzler/airflow-dags/tree/main`

**Comment by ptitzler** [comment]
@ajbozarth

**Comment by ajbozarth** [comment]
@ptitzler @lresende 

Question: currently we use the url as the link text, do we want to continue to do this? I was thinking we may just as well make the title text itself linkable. Most users don't care what the url is, and if they want to see it they can always open the editor. Opinions?

**Comment by ajbozarth** [comment]
tl:dr answer to above question via a webex: don't change it
