### ISSUE TITLE
Tag input doesn't appear for new runtime configuration editors

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#1343]
**Describe the issue**
When editing an existing runtime configuration, a list of tags appears as one of the fields. However, when creating a new runtime configuration, the tags list doesn't appear as one of the fields. 

**To Reproduce**
1. Open runtime configurations list in left side bar
2. Click "Create new runtime configuration"
3. There is no field for "tags"

**Screenshots or log output**
No errors in log. 
![image](https://user-images.githubusercontent.com/6673460/109222855-74db1980-777f-11eb-8c4c-620ce8ab9e15.png)

**Expected behavior**
 The tag list should appear as so:
![image](https://user-images.githubusercontent.com/6673460/109223151-db603780-777f-11eb-95cb-e318f1be113c.png)

**Comment by lresende** [comment]
This was fixed as part of #1293
