### ISSUE TITLE
Update links in extension tracker documentation

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#1346]
The links in the [extension tracker documentation](https://elyra.readthedocs.io/en/latest/developer_guide/trackers.html) are broken and should be updated to point to the current pages in the [JupyterLab documentation](https://jupyterlab.readthedocs.io/en/stable/index.html).

**Comment by ptitzler** [comment]
Please take a stab at it! The documentation for documentation development is at https://elyra.readthedocs.io/en/latest/developer_guide/documentation.html
