### ISSUE TITLE
Add READMEs to directories in elyra/etc

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1351]
**Describe the issue**
The `etc` directory is being used as a catch all location for any misc tools and helper scripts/configs for elyra. These sub-directories have little to no documentation on what they are for or how to relate to the project as a whole.  

**To Reproduce**

**Screenshots or log output**

**Expected behavior**
Document each subdirectory with a README to describe what it does/used for.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Operating system: [e.g. macos, linux]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]

**Comment by ptitzler** [comment]
+ add links to the appropriate GH directory to the documentation
+ add link to the appropriate documentation topic to the README
+ avoid "content" duplication as much as possible
