### ISSUE TITLE
Pass through pipeline comments that are associated with nodes

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1358]
**Is your feature request related to a problem? Please describe.**

As a user, I can attach comments to nodes that describe its purpose.

![image](https://user-images.githubusercontent.com/13068832/109674910-284f5f80-7b2c-11eb-8c23-77221c479e8a.png)

Elyra currently does not pass through this information to the target environment (Kubeflow Pipelines and Apache Airflow), even though it might be useful to the user. Apache Airflow, for example, explicitly supports documentation for DAGs and tasks: https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html#adding-dag-and-tasks-documentation

**Describe the solution you'd like**
If a user associated a comment with a node, the comment text is passed through to pipeline processors that support node-level documentation.

**Comment by yuhuishi-convect** [comment]
Hello. I am interested in contributing to this feature.

I did a quick look up into the KFP doc and didn't find ways to add documentation/description to individual ops within a pipeline. However, by using a pod **annotation**, I think the comment can be passed to the compiled pipeline definition.

Please let me know if **annotation** sounds a good solution. 

---

Some research into the code base, here's my initial plan on how to add the feature:

1. Add one more field `doc` to the [`Operation` class](https://github.com/elyra-ai/elyra/blob/dad93b2d7ce0e35f084abdac3fd800f9c95fc23c/elyra/pipeline/pipeline.py#L49)
2. Modify the [`parser` ](https://github.com/elyra-ai/elyra/blob/dad93b2d7ce0e35f084abdac3fd800f9c95fc23c/elyra/pipeline/parser.py#L34) logic to add user comments to operations
3. Add operation `doc` field as annotations when creating the KFP ops - https://github.com/elyra-ai/elyra/blob/20c5e97934ba27bfd8f22c75d5cfa642f16290f7/elyra/kfp/operator.py#L298

Please suggest if that's the right way to do that.

**Comment by akchinSTC** [comment]
@yuhuishi-convect - yeah that seems like a good place to start, shouldnt be too difficult to add the comments on the airflow side as well see : https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#dag-task-documentation

**Comment by yuhuishi-convect** [comment]
> @yuhuishi-convect - yeah that seems like a good place to start, shouldnt be too difficult to add the comments on the airflow side as well see : https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#dag-task-documentation

Thanks for the pointer. Will start to work on that.

**Comment by yuhuishi-convect** [comment]
@akchinSTC I have a working PR.  #2396 . May I have you as the reviewer?
