### ISSUE TITLE
Metadata - select box uses hard-wired placeholder

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1368]
**Describe the issue**

The select box in the KFP runtime configuration appears to be using a hard-wired placeholder text `Create or select  ...` https://github.com/elyra-ai/elyra/blob/master/packages/ui-components/src/DropDown.tsx#L88

![image](https://user-images.githubusercontent.com/13068832/109889826-f547c180-7c3a-11eb-83df-a670fe8fcc77.png)

**To Reproduce**
1. Create a Kubeflow Pipelines runtime configuration
2. Inspect the `Kubeflow Pipelines engine` select box

**Expected behavior**
Scenario 1: The select box input area displays the `default` value (if one is defined) if the user can only choose from a set of predefined options but cannot add an option ("read-only" drop down) https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/kfp.json#L76

Scenario 2: The select box input area displays the `uihints.placeholder` value, if one is defined:
https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/kfp.json#L71 (none is defined yet in this case) and it's an "editable drop down")

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1/master
 - Installation source: from source

**Comment by marthacryan** [comment]
Are you thinking that the `default` value specified in the schema should be a placeholder or the actual value of the field?

**Comment by ptitzler** [comment]
> Are you thinking that the `default` value specified in the schema should be a placeholder or the actual value of the field?

The actual/selected value.
