### ISSUE TITLE
Pipeline submission takes forever when running jupyterlab from a large dir

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#137]
The pipeline submission process zips up the cwd, but this is not the same as the current directory in jupyterlab, but the dir which it was started in. This issue is similar to the issue that jupyterlab has when opening terminal/consoles https://github.com/jupyterlab/jupyterlab/issues/1366

I ran into this issue when using the following command to run jupyter lab:
` jupyter lab --notebook-dir=/Users/ajbozart/workspace/jupyter/labtestenv`
`notebook-dir` sets the working dir for the jupyterlab file browser, but "server-side" code such as the terminal/console or our extension's back end services are still run from the cwd we ran the command from.

**Comment by ptitzler** [comment]
- Is this still an issue or can this be closed?
- The issue title seems to describe a different problem than the description
