### ISSUE TITLE
The backend should do a more thorough validation of pipelines

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1370]
The backend shouldn't assume that the pipeline file submitted is valid. Currently, the frontend blocks the user from submitting a pipeline if it has issues, but in the future this won't always be true.

We should make the following checks at a minimum:
- [x] the file has content
- [x] the file is valid json
- [x] the pipeline version matches the current version of Elyra (this is dependent on:)
  - the pipeline contains a `primary_pipeline` field that is a string
  - the pipeline contains a `pipelines` field that is an array
  - the `primary_pipeline` is findable in the `pipelines` array
  - the found `primary_pipeline` has an `app_data` field that is an object containing a `version` field that is a number
  - the found `primary_pipeline` has an `nodes` field that is an array
- [x] check for circular references (does not need to be exhaustive, can bail on first found cycle)
- [x] validate node properties (initially we can just test for missing required properties, but we might also want to check the types)

Notes:
- We shouldn't make assumptions on what the node properties are (i.e. don't assume the node will have a `filename` field)
- This doesn't include checks for `runtime` / `runtime_config`, because they aren't included in a raw pipeline file
- In preparation for #500 we need to be prepared for more dynamic validation, where properties are validated based on components required properties.

Edit:
I think we cover most of the basic json validation, but we still don't do any deeper checks like circular references and validating node properties. This will probably require some deeper discussion with the pipeline 2.0 changes. We might want to see how possible it would be to use the language server to do this validation?

**Comment by akchinSTC** [comment]
Closing since https://github.com/elyra-ai/elyra/pull/1664 seems to satisfy all the requirements here
