### ISSUE TITLE
New runtime configuration selection is displayed incorrectly

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1374]
**Describe the issue**

Running in Chrome:

![image](https://user-images.githubusercontent.com/13068832/110036260-9bee9980-7cf1-11eb-8206-ca7e24ad3591.png)

**To Reproduce**
1. Open the runtime configuration panel
2. Click +
3. Inspect the dialog

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1 RC1
 - Installation source: PyPI

**Comment by ptitzler** [comment]
Also note 
![image](https://user-images.githubusercontent.com/13068832/110045462-8aac8980-7cff-11eb-8393-a63ca0794266.png)

**Comment by ajbozarth** [comment]
I've checked for this on both latest master and installing rc1 in a new env and I don't see this. My best guess is that your env ended up in a weird state where some of the Material-UI CSS was missing.

**Comment by ptitzler** [comment]
I've tried this again today using RC1 in a new environment and I am no longer seeing the issue.
