### ISSUE TITLE
Submitting kfp pipeline with user namespace in pipeline runtime returned invalid link to experiment

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1384]
**Describe the issue**
Submitting kfp pipeline with user namespace in pipeline runtime returned invalid link to experiment

**To Reproduce**
1. Create a new pipeline runtime with the `user namespace` populated
2. Open or create any pipeline
3. select the new pipeline runtime you just created and submit
4. success message, click to see your runtime job
5. Get error message in kfp pipeline UI saying cannot find experiment.

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.

**Expected behavior**
success dialog box to provide valid link to experiment in kfp ui

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc1 
 - Operating system:  linux ubuntu 18
 - Installation source: pypi
 - Deployment type: local

**Pipeline runtime environment**
 - Kubeflow Pipelines - v1.3.0 

 
**Runtime configuration settings**
If the issue is related to pipeline execution, document the runtime configuration settings from the Elyra UI, omitting confidential information.

**Comment by ptitzler** [comment]
This is a known issue. As a workaround one needs to open the Kubeflow Pipelines GUI and select a namespace. Then the link does work. I couldn't find a way to make the namespace part of the URL payload - just appending `namespace=...` didn't do the trick.

**Comment by akchinSTC** [comment]
@ptitzler - im going to take a stab at fixing this, wont spend that long on it though if i hit a wall.

**Comment by akchinSTC** [comment]
Issue no longer exists to my knowledge. Elyra supports several authentication methods now with kubeflow and assuming the user is authenticated via the KFP dex portal, should be directed to their respective namespace in kubeflow and be able to view their runs/experiements via the provided link.
