### ISSUE TITLE
False missing notebook indicator in pipeline editor

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1389]
**Describe the issue**
When hovering over a notebook node in the pipeline editor, it displays an error indicator indicating that the notebook file is missing, yet the notebook is present and the pipeline can be run.

**To Reproduce**
1. Open an existing pipeline.
2. Hover over a node.
3. Note the error indicator.

If I drag a notebook onto the pipeline, this does not occur.  Yet when I open the pipeline file in a text editor, there is no difference in the two notebook node file entries - they both reference local notebook files.

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/22599560/110398454-c8275480-8028-11eb-9519-ebd867303338.png)

Here's the pipeline file.  
[untitled.pipeline.tar.gz](https://github.com/elyra-ai/elyra/files/6104882/untitled.pipeline.tar.gz)

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc2
 - Operating system: macos
 - Installation source: PyPI
 - Deployment type: local installation

**Comment by kevin-bates** [comment]
Here's my complete pipeline directory since I think this might be difficult to reproduce.

[my_pipeline.gz](https://github.com/elyra-ai/elyra/files/6104983/my_pipeline.gz)

**Comment by ajbozarth** [comment]
@kevin-bates the file you included seems to be corrupt, I can't even open it in lab (in the text editor or pipeline editor) and when I open it in vim it's full of random chars mixed in the json

**Comment by lresende** [comment]
Looks like the reported issue has been resolved, but some other node properties are not following the same pattern. An example is playing with the resource values while testing #1394

**Comment by lresende** [comment]
Never mind, too many merges at the same time, after `clean install` this seems to have resolved the issue mentioned above as well.
