### ISSUE TITLE
Resource values (cpu, memory, gpu) should be validated

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1390]
**Describe the issue**
When editing a node's properties, I am able to enter negative values for CPU and GPU. Note that I can enter a negative value for memory, but it is caught _on the server_.  Also, I can enter invalid values (32 GPU) when there aren't any, and the pipeline's execution will succeed w/o error.

**To Reproduce**
1. Open a pipeline's node properties and enter -8 for the CPU.  Although there is a warning, the value is permitted.  Also enter a value of some large number of GPUs (e.g., 37)
2. Execute the pipeline successfully.

I tried this on KFP and local.  Did not try on Airflow, but I suspect the same issue.

**Expected behavior**
At a minimum, invalid values like negative numbers should be caught on the client.  I understand it might be harder (or impossible) to validate actual numbers of CPUs and GPUs since a runtime may be involved.

**Comment by bourdakos1** [comment]
I think we need to have a discussion about how to handle node properties. I think we are having more and more properties that are specific to a runtime. At the moment we have 3 runtimes `local` / `kfp` / `airflow`, where `local` is kinda a special case.

For the 2 node types we currently have (notebook/python execution nodes) there seems to be 2-3ish groups of properties:
- properties that always matter for that node (if we  don't consider `local` a special case)
- properties that always matter for that node (if we do consider `local` a special case)
- properties that can vary from runtime to runtime

For example, take notebook execution nodes:

properties that always matter (`local` not special)
- filename
- env_vars

properties that always matter (`local` is special)
- runtime_image
- dependencies
- include_subdirectories
- outputs

properties that can vary:
- cpu
- gpu
- memory

At the moment, you can always run a pipeline locally, but I have a feeling with pipeline 2.0 stuff coming, this won't hold true. I think as time goes on `local` will become less of a special case. 

-I'm not sure where I'm going with this. I'll keep updating this with my thoughts-

**Comment by lresende** [comment]
Now, if this is a blocker for 2.1, I would say no. But because this has been introduced recently, I would say it's a strong nice to have.

**Comment by bourdakos1** [comment]
yea, I think adding a requirement for no negative numbers is an easy fix for now, since everything is hard-coded. I was more talking about what we should think about for the future

**Comment by kevin-bates** [comment]
@bourdakos1 - thank you for bringing this up.   I agree this current discussion is more about the future.

How to handle "local" is tough because it will (almost) always co-exist with a runtime, whereas a given site will typically only have one of the runtimes (kfp or airflow at the moment).

We should also consider introducing a configurable-defaults inheritance mechanism where default values can be specified globally and automatically seed the node to be optionally overridden.  I could see many installations having a common set of dependencies where a given node might add to that set - the same goes for runtime-image.

Since much of this discussion would then tie a pipeline to a runtime, perhaps "local" becomes a "test-mode" of sorts?  Or we promote "local" to a runtime and provide an easy means to "swap-out" node properties based on the (pre)selected runtime?

Of course, we'll also have other node-types besides notebook and python but, assuming they "do work", many of the properties would likely apply although we should design things in a way where properties are ultimately a function of runtime **and** node-type.

**Comment by kevin-bates** [comment]
FWIW - TIL that I was misled on how KFP handles invalid resource values due to another bug that kept sending me to a successful status page.  It turns out that, prior to our checks for negative values, KFP will catch the negative value and fail the node:
![image](https://user-images.githubusercontent.com/22599560/110684656-3dfaff80-8192-11eb-8165-cb87ac348afd.png)

With respect to positive values in which the resource is not available (e.g.., 32 GPUs), KFP will mark the node as pending and, essentially wait for the resources to become available:
![image](https://user-images.githubusercontent.com/22599560/110684415-fd9b8180-8191-11eb-8186-3060fc884e04.png)
