### ISSUE TITLE
Runtime should not appear as an option if there are no instances

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1391]
**Describe the issue**
When choosing to run a pipeline, the user is greeted with a drop-down to select which runtime to run against.  If there are no instances of a given runtime, especially since there's no way to create a runtime instance from that dialog, then I wonder if the runtime should even be selectable.

**To Reproduce**
1. With no instances of Airflow or KFP runtimes present, open a pipeline and run it.
2. Click on a runtime that has no instances.  

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/22599560/110399967-9cf23480-802b-11eb-93c7-e540fa6ff330.png)

**Expected behavior**
The runtime (Apache Airflow in this case) should not be present or greyed out.

**Comment by karlaspuldaro** [comment]
This is related to #1339 and #1340

**Comment by akchinSTC** [comment]
Test case:
kfp runtime exists, aa runtime does not exist
result : only KFP shows up as an option in the first drop down
