### ISSUE TITLE
Long tags in code snippet search overflows the button element

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1395]
**Describe the issue**
Long tags in code snippet search overflows the button element when the side pane is narrower than the text

![image](https://user-images.githubusercontent.com/25207344/110495000-189ec080-80c2-11eb-80e7-d692799296f6.png)

**To Reproduce**
1. Open the code snippet widget (click code snippets button on the side bar)
2. Either edit an existing snippet or create a new one
3. Add a tag with a long name and press enter to enable it
4. Save and close
5. Go back to the code snippet widget (side panel)
6. Click on the tag button to filter for tags
7. Check the long tag added 
8. Play with the side pane width (the problem happens on narrow states)

**Expected behavior**
The tag name should be contained in the button element, independent of the widget width.
If the full text can't fit, we could trim the end such as
`thisisanexampleofaverylongtag` --> `thisisanexample...`

**Environment information**
- Elyra version: 2.1.0rc2
- Operating system: MacOS
- Browser: Chrome

**Comment by jdcai** [comment]
Hi, you can assign this to me.
