### ISSUE TITLE
Resource values that require values > 0 treat null as 0 and produce error

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1412]
**Describe the issue**
When _removing_ a value for CPU or Memory, the node border will show it in an error state even though no value should be considered valid (and was valid when the node was originally added).

**To Reproduce**
1. Bring up a node's properties and set a valid value for CPU or Memory (e.g., 4) and close the properties
2. The node border is blue and no errors
3. Bring up the node's properties and _delete_ the previously entered value, leaving nothing in that portion of the dialog, and close the properties.
4. Note the error state of the node and, when hovering, the message indicating the value must be greater than 0.
5. Since GPU allows >= 0 as valid, this is not an issue there.

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/22599560/110716132-664b2400-81bb-11eb-8bf6-5d8d3db4cd81.png)

**Expected behavior**
Null or empty values should be treated as _no_ value and not as zero (which is invalid).

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc3
 - Operating system: macos
 - Installation source: PyPI
 - Deployment type: local installation

**Comment by bourdakos1** [comment]
fun fact, in javascript:
`null == 0` is `false`
`null < 0` is `false`
`null > 0` is `false`
but:
`null <= 0` is `true`
`null >= 0` is `true`
