### ISSUE TITLE
Pipeline export: allow for custom export file name

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1417]
**Is your feature request related to a problem? Please describe.**

Currently export produces a file with the pipeline name, e.g. `my-pipeline.py` or `my-pipeline.yaml` for Kubeflow Pipelines environments. With the newly added support for Apache Airflow as a runtime environment in version 2.1, export also produces a `my-pipeline.py` file when AA is selected as target environment. (The content of `my-pipeline.py` (KFP) and `my-pipeline.py` (AA) is very different.)

**Describe the solution you'd like**
To make it easier for users to determine what the purpose of a generated file is, Elyra should
- generate a default file name that identifies the export target, e.g. `my-pipeline-kfp-dsl.py`
- allow the user to choose a custom name prior to processing the export request

## Update 
Since each runtime type now only has a single export format -- `.py` for Airflow and `.yaml` for KFP) -- it's probably sufficient to allow the user to customize the export file name and have the default file name pre-populated as the pipeline file name. This behavior is similar to that which already exists for pipeline run/submission.

**Comment by sanika93** [comment]
@karlaspuldaro I am interested in working on this issue!

**Comment by salonee13** [comment]
I am interested in working on this issue!
