### ISSUE TITLE
Handle environment variables when submitting Python files

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1419]
The current `Submit Script` feature does not handle parsing environment variables from the editor,  as noted in [this comment](https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/src/SubmitScriptButtonExtension.tsx#L65) in `SubmitScriptButtonExtension.tsx`.

This is related to #710

**Comment by lresende** [comment]
Fixed with #1654
