### ISSUE TITLE
Support for global properties / env variables in pipeline editor

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1421]
**Is your feature request related to a problem? Please describe.**
Some properties are confidential (eg. hostnames, usernames, passwords) - when a pipeline is shared, those have to be removed manually by opening each pipeline step's properties

**Describe the solution you'd like**
A section for global properties attachable to the pipeline which are valid / accessible for all pipeline steps which can easily be removed/copy pasted

**Describe alternatives you've considered**
Writing a parser and removing env variables of the json file of the pipeline

**Comment by ptitzler** [comment]
Can you please clarify what you mean by "when a pipeline is shared". The `.pipeline` file (as stored in the JupyterLab working directory) does not contain any of the properties you mentioned. Are you referring to artifacts that are produced during a pipeline run (e.g. the DAG in AA) or export?
