### ISSUE TITLE
Material UI style specificity issues

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1428]
Since we have multiple instances of `material-ui` each one of them injects styles into the head without awareness of what the others are injecting.

Each instance only injects the styles that are needed at that moment, so you can get into weird states like this:
One instance  of `material-ui` renders a `MenuItem` which uses both `Button` and `MenuItem` styles, so it injects `Button` styles first and `MenuItem` second so that the `MenuItem` styles override `Button`. 
but then the other instance of `material-ui` is only rendering a `Button` so it injects styles for `Button` and if that happens after `MenuItem` then you end up with  `Button` > `MenuItem` > `Button` with `Button` incorrectly overriding `MenuItem` styles.

There’s a few possible fixes:
- Wrap all of JupyterLab inside of a `StylesProvider` component (the best solution, if possible)
- have a classname generator with `disableGlobal` set to `true` (This will make all the Mui style names non-deterministic, so we won’t be able to override styles via css, but I believe we can override them via a theme)
- create our own classname generator that allows us to create deterministic Mui classes, but with each mui instance prefixed with something custom

**Comment by bourdakos1** [comment]
relevant documentation on generating class names: https://material-ui.com/styles/api/#creategenerateclassname-options-class-name-generator

**Comment by kevin-bates** [comment]
@bourdakos1 - having sat in the initial debug session for this, this analysis is really fantastic!  Thank for you the clear description (especially for noobs like me!).

> Wrap all of JupyterLab inside of a StylesProvider component (the best solution, if possible)

Would the _wrapping_ be something we (elyra) do - as specific consumers of the Lab front-end or is there something that can (and should) be done for Lab extensions in general (and perhaps provided externally)?  Just trying to understand if this would help the Lab community.  (Note: I may not understand your response. :smile: )

**Comment by bourdakos1** [comment]
After reflecting a bit more on this, I don't think _wrapping_ would be a good solution. First, I don't think it's possible because I assume the react widgets in jupyter are all their own react roots so a provider wouldn't be able to pass context to them. Also, wrapping everything in a provider could cause issues for other react widget extensions that are attempting to use material-ui. 

However, I believe we can get the intended effect of wrapping without actually wrapping. If I understand correctly, as long as there is only a single instance of a classname generator across all of our extensions, things should work as expected. 

I think it's best if we create our own classname generator that is prefixed with something specific to elyra, so if other extensions are using material-ui it won't interfere with us (this includes jupyter starting to use material-ui instead of blueprint).

We will just need a way to share a singleton of our classname generator across all of our extensions

**Comment by bourdakos1** [comment]
I was able to make the original issue we were seeing reproducible. The issue is the git extension, it uses `material-ui` for tabs, but the tabs only render if you are in a git initialized folder. If you run jupyter lab in a folder with git the dropdown will be broken. If you run jupyter lab in a normal non-git project folder the dropdown will render correctly

**Comment by kevin-bates** [comment]
> If you run jupyter lab in a folder with git the dropdown will be broken. If you run jupyter lab in a normal non-git project folder the dropdown will render correctly

To clarify this, it's really a function of where your `notebook-dir` is pointing relative to a git configuration.  Since I **always** run lab with `--notebook-dir=~/notebooks` and git is not configured in `~/notebooks`, I did not see this problem when when invoking `jupyter lab` from my elyra dev tree.  However, based on this information, if I perform that same invocation, but do not add `--notebook-dir=~/notebooks`, the issue reproduces.  Nice find @bourdakos1!
