### ISSUE TITLE
Add runtime metadata button does not match theme or is not centered correctly

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1433]
**Describe the issue**
The +(plus) button to add a metadata runtime does not match the default light theme (when selected). When dark theme is selected, the icon is off center. 
After switching back to the light theme, the icon appears correctly and matches the light theme.

**To Reproduce**
1. Click on the runtime metadata icon on the left side menu
2. See error

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/13340013/111193926-ef75a880-8577-11eb-8313-0a686e7ae201.png)
![image](https://user-images.githubusercontent.com/13340013/111194200-2cda3600-8578-11eb-8256-1536b8f4a2f4.png)

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1 rc5
 - Operating system: linux
 - Installation source: pypi
 - Deployment type: local

**Comment by karlaspuldaro** [comment]
@akchinSTC is this still an issue? I couldn't reproduce it. Which browser do you use?

**Comment by akchinSTC** [comment]
This issue seems to be resolved, although I am unsure when. Closing
