### ISSUE TITLE
Node labels are not used within the server

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1440]
**Describe the issue**
When a node has been renamed such that the node (label) is different than the node filename, the server still uses the basename of the node filename as the operation name (which should be the label's value).

**To Reproduce**
1. Create a pipeline
2. Update the node name of a given node to something different than its corresponding file.
3. When executing the pipeline locally (or via a platform), anywhere the node (operation) name should be used, the basename of the node's filename is used instead.

**Screenshots or log output**
In this pipeline, the nodes have been renamed to be different from their respective filenames.  In this case, the node name `Prepare` has been updated for the node file `node1.ipynb`.
![image](https://user-images.githubusercontent.com/22599560/111230661-34fc9a80-85a5-11eb-8d97-bce19c26cfdd.png)
Yet corresponding error messages or log entries that use `operation.name` reference `node1` rather than `Prepare`.
![image](https://user-images.githubusercontent.com/22599560/111230900-9290e700-85a5-11eb-9770-9b9e34508e58.png)

**Expected behavior**
The name of the operation should appear as `Prepare`, not `node1`.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0rc5
 - Operating system: macos
 - Installation source: pypi
 - Deployment type: local installation

**Comment by ptitzler** [comment]
Is this a duplicate of https://github.com/elyra-ai/elyra/issues/971?

**Comment by kevin-bates** [comment]
Yes, I believe it is.  I just updated #971 with an additional comment and am closing this issue as a duplicate.
