### ISSUE TITLE
Questions about two errors.

### ISSUE THREAD

**Issue by KevinRyu** [elyra-ai/elyra#1464]
Hi,

I wanted code-snippets extention in jupyter lab for windows. (windows10 pro)

Error1:
I tried to install from extention manger UI in Lab. 

I got an error: Message box opend.
  "Error contacting server
   Endpoint elyra/metadata/code-snippets not found" 

Error2:
I tried to install by using pip installation.
My jupyter lab version is 2.2.9. So, I entered pip command from instruction in this github page. 
After installing libraries and checking dependency, I got an errors like the following when building is proceeding, 

============================================================================
[LabBuildApp] JupyterLab 2.2.9
[LabBuildApp] Building in E:\Users\Anaconda3\envs\tf2.2\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
\Exception in thread Thread-7:
Traceback (most recent call last):
  File "E:\Users\Anaconda3\envs\tf2.2\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\Users\Anaconda3\envs\tf2.2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Users\Anaconda3\envs\tf2.2\lib\subprocess.py", line 1267, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 263: illegal multibyte sequence

Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
IndexError: list index out of range

========================================================
What should I do to solve problems?

**Comment by lresende** [comment]
> Error1:
> I tried to install from extention manger UI in Lab.

The extension manager on Lab 2.x can only be used for dependencies that do not have a requirement on server extensions. Based on this, extensions such as git and elyra ones, that leverage server extensions are not installable via extension manager and need to be installed via pip or conda. 



>Error2:
>I tried to install by using pip installation.
>My jupyter lab version is 2.2.9. So, I entered pip command from instruction in this github page.
>After installing libraries and checking dependency, I got an errors like the following when building is proceeding,

Here I am not sure what pip command you used, but for JupyterLab 2.x you should use:
```
pip install --upgrade "elyra<2.0.0" && jupyter lab build
```
or
```
pip install --upgrade elyra-code-snippet-extension<2.0.0 && jupyter lab build
```
Some more installation details are available in the [project readme](https://github.com/elyra-ai/elyra#installation)
And more details about code-snippet extension on this [article](https://blog.jupyter.org/reusable-code-snippets-in-jupyterlab-8d75a0f9d207).

Please let us know if this helps you make progress on your issues.

**Comment by akchinSTC** [comment]
@KevinRyu - Hi Kevin, just checking in to see if you had made any progress on this issue or if it's been resolved?

**Comment by KevinRyu** [comment]
Hi. Thanks very much for help. I resolved errors. I am sorry for late to
reply.

2021년 3월 27일 (토) 오전 7:44, Alan Chin ***@***.***>님이 작성:
