### ISSUE TITLE
Progress bar/indicator for local execution of pipelines

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1475]
**Is your feature request related to a problem? Please describe.**

I've created a pipelines making use of the local execution mode - it runs for 2-3h on a 16 core server. I'm running this on the IBM Kubernetes Service, so it is very hard to poll der log for progress (without using a shell and kubectl) - I only see what you can see on the screenshot below

![image](https://user-images.githubusercontent.com/5694071/112322274-0cfded00-8cb1-11eb-9f06-a2fadc5f48c6.png)

**Describe the solution you'd like**
I'd like to have a progress bar telling me in which notebook (and maybe in which cell) the processing is currently done

**Describe alternatives you've considered**
So far I'm using a shell and kubectl to poll the log

**Additional context**
With this functionality in place people could start with pipelines without the need for airflow or kubeflow and then, once needed seamlessly move to it. At the current state the function looses a lot of it's practicality by not having progress feedback somehow and somewhere in the UI

**Comment by romeokienzler** [comment]
@kevin-bates would like to hear your thoughts about this

**Comment by ptitzler** [comment]
Duplicate of #1265

**Comment by romeokienzler** [comment]
closing as duplicate, thanks @ptitzler
