### ISSUE TITLE
Credentials for cloud object storage bucket are exposed in KFP UI (Argo UI or Tekton UI as well)

### ISSUE THREAD

**Issue by pacospace** [elyra-ai/elyra#1479]
**Describe the issue**
As Elyra user,

when I need to submit a pipeline I set object storage credentials to create runtime. When running a pipeline, if other users have access to KFP UI, they can see the credentials.
This issue can be found also if users have access to the Argo/Tekton UI.

**To Reproduce**
1. Submit a pipeline from Elyra.

**Screenshots or log output**
See: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/190

**Expected behavior**
Credentials are not exposed but encrypted. Maybe a Kubernetes secret is used and referenced for the environment variables.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.0.1
 - Operating system: linux
 - Installation source: [1]
 - Deployment type: Open Data Hub

References
[1] https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags

**Comment by ptitzler** [comment]
This is currently a know (design) restriction and applies to pipelines run on Kubeflow Pipelines and Apache Airflow.

**Comment by pacospace** [comment]
> This is currently a know (design) restriction and applies to pipelines run on Kubeflow Pipelines and Apache Airflow.

Thanks @ptitzler!

I believe this should be an important feature to consider as it affects security.
Do you have some timeline for this?

**Comment by akchinSTC** [comment]
@pacospace - we added this issue to our next release (2.3) so we're hoping to have a solution/plan-for-a-solution for you in the next 2-3 weeks.

**Comment by pacospace** [comment]
> @pacospace - we added this issue to our next release (2.3) so we're hoping to have a solution/plan-for-a-solution for you in the next 2-3 weeks.

Thanks @akchinSTC!!
