### ISSUE TITLE
Create CLI overview documentation topic in the user guide

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1491]
**Is your feature request related to a problem? Please describe.**
Currently there is CLI content sprinkled throughout various topics, e.g. https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#id1 and https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html, but there's no formal entry point, that introduces the CLI and common concepts.

**Comment by lresende** [comment]
I thought about that. Today the CLI has been documented when describing the "main topic" as one way to interface with the content (e.g. metadata) and I thought that was ok. With this, would we remove the CLI content from the topic and promote to its own section/set of documents?

**Comment by ptitzler** [comment]
> With your proposal, would we remove the CLI content from the topic and promote it to its own section/set of documents?

See PR. TL;DR: no
