### ISSUE TITLE
Submit script submits the wrong file when multiple file editors are open

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1497]
**Describe the issue**
Submit script submits the wrong file when multiple file editor open

**To Reproduce**
1. Open a Python file in the Python Editor
2. Open a R file in the R editor
3. Go back to Python editor and submit the file
4. The R file is submitted

**Screenshots or log output**

![image](https://user-images.githubusercontent.com/382917/112939794-f1e01280-90e0-11eb-9e07-27ef93029656.png)

**Comment by ajbozarth** [comment]
I've looked into this and this seems to be a general issue with our submit button, for both scripts and notebooks. Specifically the submit button will always submit whichever script or notebook was opened last for the type of submit button (r and python share the same script button). So this is non-blocking for #1435, and seems to be a long existing bug (still really bad though)
