### ISSUE TITLE
Update Elyra image in ODH to 2.1.0 or latest

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1500]
**Is your feature request related to a problem? Please describe.**
Current image in use is out of date

**Describe the solution you'd like**
Update the Elyra image used by OpenDataHub to 2.1.0 or latest
Parent issue: https://github.com/opendatahub-io/s2i-lab-elyra/issues/23

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/opendatahub-io/s2i-lab-elyra
https://quay.io/repository/thoth-station/s2i-lab-elyra

**Comment by ptitzler** [comment]
Status:
- [ ] [Container image published](https://github.com/opendatahub-io/s2i-lab-elyra/pull/26)
- [ ] [Manifest updated/published](https://github.com/opendatahub-io/odh-manifests/pull/380)

**Comment by ptitzler** [comment]
The 2.2.1 container image is now available in the v1.0.9 manifest version `https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.9`.
