### ISSUE TITLE
Script Editor console does not properly highlight error messages

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1513]
**Describe the issue**
When a code execution from the script editor hits an error, the message displayed in the console output is supposed to be highlighted in red. This does not happen whenever the first output line is an error message.
It does behave as expected only when the error is detected on subsequent lines, as shown below:

![image](https://user-images.githubusercontent.com/25207344/113337404-bb2f1580-92f5-11eb-90f6-2f1e07b6851a.png)

The error class is added to the element in the [handleKernelMsg function
](https://github.com/elyra-ai/elyra/blob/66e4009ed405f45326b2ba8588c2eca9accd0f16/packages/script-editor/src/ScriptEditor.tsx#L222)
It looks like the class is either being removed somehow on the first display iteration, or the CSS properties are not being applied.

**To Reproduce**
1. Open a new Python Editor
2. Paste the broken code below in the editor
```
for i in range(10):
    print('i:' + i)
```
3. Click Run
4. See the error message in the console in a white background
5. Edit the code by adding a print statement to line 1 of the editor (eg. `print('test')`)
6. Rerun the code and notice now the console output is highlighted in red

**Expected behavior**
The Script Editor should highlight error messages independent of the order they are received by the kernel.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.1
 - Operating system: macOS
 - Installation source: PyPI (using conda environment)
 - Browser: Chrome

**Comment by VNA818-RPI** [comment]
I would like to work on this issue
