### ISSUE TITLE
Submit notebook/script dialog validation can be improved

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1516]
**Describe the issue**
The submit feature for notebooks and scripts does not validate its dialog input fields.
![image](https://user-images.githubusercontent.com/25207344/113350903-1cf87b00-9308-11eb-8187-0b25cb406b26.png)

Compared to the Pipeline Editor validation:
<img src="https://user-images.githubusercontent.com/25207344/113351032-487b6580-9308-11eb-91da-3795833a0e2b.png" width="550"><img src="https://user-images.githubusercontent.com/25207344/113351397-d22b3300-9308-11eb-984d-f4db099bd2f1.png" width="250">

**To Reproduce**
1. Open a notebook or script editor
2. click the submit button
3. Add a negative value to the CPU field
4. The `Ok` button is still enabled

**Expected behavior**
The `Ok` button should be disabled should the user type an invalid input to any field

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.1
 - Operating system: MacOS
 - Installation source: PyPI (in a conda environment)
- Browser: Chrome

**Comment by akchinSTC** [comment]
As a backup, the validation service does check for negative values in the resources when submitting a standalone pipeline
