### ISSUE TITLE
[RFC] Runtime specific node properties for pipelines 2.0

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1520]
## Requirements
- a runtime should be able to declare properties that are available for all node types
- a runtime should be able to pull from a shared set of properties i.e. `cpu`/`gpu`/`memory`/`runtime-image`
- a runtime should be able to override properties of nodes that the runtime doesn't own

## Proposal
Elyra should define a set of properties that can be used across runtimes, following the proposed properties schema (RFC #1519). A runtime can provide a list of global properties that will be applied across all node types and overrides for specific nodes that it doesn't own. The list of properties can be composed of full property definitions or a pointer to the Elyra defined "shared" properties.

Example "shared" properties:
```js
[
  {
    id: "runtime-image",
    title: "Runtime Image",
    type: "string",
    enum: ["one", "two", "three"],
    required: true
  },
  {
    id: "cpu",
    title: "CPU",
    type: "number",
    minimum: 0
  },
  ...
]
```

Example runtime schema:
```js
{
  id: "kfp"
  global: [
    { id: "shared.cpu" },
    { id: "shared.gpu", maximum: 2 }, // possibility to override some constraints
    { id: "shared.memory" },
    {
      id: "some-kfp-custom-global",
      title: "KFP Global Property",
      type: "string"
    }
  ],
  overrides: {
    "execute-notebook-node": [{ id: "shared.runtime-image" }],
    "execute-python-node": [{ id: "shared.runtime-image" }] 
  }
}
```

**Comment by lresende** [comment]
I think we should rename this issue to "Common node properties", and we should also consider https://github.com/elyra-ai/elyra/issues/1421 with the notion of "global pipeline properties" during the implementation.

**Comment by lresende** [comment]
Adding @kevin-bates as I know he would suggest using metadata and/or JSON schemas.
