### ISSUE TITLE
kf-notebook:2.2.1 container image has version 2.1.0 installed

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1522]
**Describe the issue**

Follow the instructions in https://elyra.readthedocs.io/en/latest/recipes/using-elyra-with-kubeflow-notebook-server.html and specify `elyra/kf-notebook:2.2.1` as custom container image.

![image](https://user-images.githubusercontent.com/13068832/113438833-364c0680-939e-11eb-86c9-b76c36f8b414.png)

Connect to the server, open a terminal window, and type in `pip list | grep elyra`:

![image](https://user-images.githubusercontent.com/13068832/113438914-68f5ff00-939e-11eb-9fd9-ac171dd34ca5.png)

**Comment by ptitzler** [comment]
Confirmed that this is not some kind of caching issue by running `docker run -p 8888:8888 elyra/kf-notebook:2.2.1` locally.

**Comment by lresende** [comment]
I can have a quick PR to make the necessary updates for this, but we really should have a way to have master building and installing Elyra from the master, and only during the release, we should install the release being produced.

**Comment by ptitzler** [comment]
> should have a way to have master building and installing Elyra from the master, and only during the release, we should install the release being produced.

Yes, I agree. Regular users should only create the container image only from published packages. ER for publication support ^^  https://github.com/elyra-ai/elyra/issues/1525
