### ISSUE TITLE
Support GitLab/GitLab Enterprise when adding an Apache Airflow runtime

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1524]
**Is your feature request related to a problem? Please describe.**
Currently, when submitting a pipeline to an Apache airflow runtime, users can only add Github based endpoints as a destination for their DAGs 

**Describe the solution you'd like**
Allow users to select gitlab as a git repository when submitting adding an apache airflow runtime.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by nanaones** [comment]
I'm also eagerly awaiting this feature.

**Comment by marquisthunder** [comment]
+1
