### ISSUE TITLE
Support settings for Elyra extensions in JupyterLab

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1530]
**Is your feature request related to a problem? Please describe.**
As a user I might want to always use certain defaults that are different from the hard-wired values stored in the published version. For example, running Elyra on OpenShift, a user would likely want to specify Tekton as Kubeflow engine instead of the current default of Argo.

Exposing settings would probably also enable us to expose "experimental" features that might not be ready for production use but fair game for exploration.

**Describe the solution you'd like**

Expose Elyra extension settings in  `Settings` > `Advanced Settings Editor`.

**Comment by lresende** [comment]
Note: Advanced Settings Editor is just a json blog and AFAIK is not accessible via an API from the backend.

**Comment by kevin-bates** [comment]
This particular use case strikes me as another thing asking for a _default instance_.  If we had such a notion, couldn't the user configure their specific "tekton-based instance", mark it as _the_ default, and party on that?

Currently, some of the defaults you're referring to are baked into the system schema and there may be several "tweaks" within a given object (instance) that could be captured by a _default instance_ - independent of the schema.

**Comment by ptitzler** [comment]
Starting with Elyra 3.7 VPE settings can be customized. https://github.com/elyra-ai/elyra/pull/2517 introduces the first configurable setting, which governs what happens when a user double clicks on a node.
