### ISSUE TITLE
Remove dev dependencies from install requirements in setup.py in all Elyra repositories

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1546]
**Is your feature request related to a problem? Please describe.**
It appears that in some of the repositories packages are required that are only needed during development. For example `flake8` is included in  [`setup.py` in elyra-ai/kfp-notebook](https://github.com/elyra-ai/kfp-notebook/blob/master/setup.py#L30) and [`setup.py` in elyra-ai/airflow-notebook](https://github.com/elyra-ai/airflow-notebook/blob/master/setup.py#L30)) . Those dev dependencies should be declared as such to avoid installation in non-development environments since they serve no purpose there.

**Comment by lresende** [comment]
Please make sure we replicate this in all repos

**Comment by akchinSTC** [comment]
Closing this issue since both repos in question (kfp-notebook and airflow-notebook are deprecated and archived)
and flake 8 has been moved out of the setup.py in elyra root repo and into a separate makefile target. Test dependencies have been moved into the extras of the setup.py.
