### ISSUE TITLE
Fira code ligatures don't work after installing Elyra extension

### ISSUE THREAD

**Issue by miwojc** [elyra-ai/elyra#1549]
**Describe the issue**
On a fresh install of lab v3 i changed settings to use fira code wich supports ligatures. It worked fine. After i installed Elyra extension the fira code ligatures don't work anymore.

**To Reproduce**
On Windows 10 in Windows Terminal with conda:
1. Install Fira Code font with these instructions: `https://github.com/tonsky/FiraCode/wiki/Installing#windows`
1. Install jupyter lab in new conda environment: `conda install -c conda-forge jupyterlab` (v3.0.13)
2. Set font to Fira Code in Jupyter Lab advanced settings -> Notebook settings: { "codeCellConfig": { "fontFamily": "Fira Code"}} - font and ligatures work fine
3. Install Elyra extension as per instruction: 
`conda install -c conda-forge nodejs`
`pip install --upgrade elyra && jupyter lab build`
https://elyra.readthedocs.io/en/stable/getting_started/installation.html
4. after installation fira code ligatures don't work anymore

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/32404415/114272386-42773a00-9a16-11eb-875f-d1a6a20d934e.png)

**Expected behavior**
Fira code ligatures should work after installing Elyra

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 
       @elyra/code-snippet-extension v2.2.1 enabled ok
        @elyra/metadata-extension v2.2.1 enabled ok
        @elyra/pipeline-editor-extension v2.2.1 enabled ok
        @elyra/python-editor-extension v2.2.1 enabled ok
        @elyra/r-editor-extension v2.2.1 enabled ok
        @elyra/theme-extension v2.2.1 enabled ok
 - Operating system: Windows 10
 - Installation source: pip and conda as above
 - Deployment type: local in conda env

**Comment by lresende** [comment]
Just a note that I was able to reproduce the issue on Windows environment, but still have to investigate. I will also try to check this on a non-Windows environment as this shouldn't be a platform-specific issue.

**Comment by lresende** [comment]
This is also reproducible in a non-windows machine (e.g. mac os), but I still need to investigate what might be causing this.

**Comment by karlaspuldaro** [comment]
Still investigating this.
Other custom fonts installed work normally on elyra (fira code text font renders as expected, only ligatures are affected).
After isolating elyra extensions, ligatures only break when pipeline editor extension is installed.

**Comment by bourdakos1** [comment]
The issue seems to be coming from `carbon-components` css. Setting `letter-spacing` breaks the ligatures
