### ISSUE TITLE
Fail to launch elyra container image mapping work dir

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1550]
**Describe the issue**
Fail to launch elyra container image mapping work dir

**To Reproduce**
Using the following command to launch the elyra-image:
```
docker run -it -p 8888:8888 \
-v "${HOME}/opensource/jupyter-notebooks/:/home/jovyan/local-notebooks" \
-v "${HOME}/Library/Jupyter:/home/jovyan/.local/share/jupyter" \
-w "/home/jovyan/local-notebooks" elyra/elyra:dev
```

1. Go to jupyterlab UI and launch terminal
2. Go to parent directory: `cd ..`
3. List folders: `ls -la`
4. Notice that there are two folders named 'local-notebooks' and this happens with whatever folder name you use (e.g. work)
5. You will also note that one of the folders, the one with the correct contents, have an extra character on the name (e.g. `cd local-notebooks?`
6. This seems to be happening with old container images from previous releases

**Expected behavior**
There should be only one work directory with the correct linked contents

**Comment by ptitzler** [comment]
This works just fine in my environment.

**Comment by akchinSTC** [comment]
can't duplicate bug, unable to locate the extra directory with the latest dev image

**Comment by lresende** [comment]
User error.
