### ISSUE TITLE
[Still not working] Elyra installation on Jupyterhub: "Error contacting server - Endpoint elyra/namespace not found"

### ISSUE THREAD

**Issue by marcelbo2021** [elyra-ai/elyra#1554]
**Describe the issue**
The issue described in #1474 still exists in my opinion, although it was closed. I performed a clean installation on an Azure Kubernetes Cluster, as described in the issue, after having deleted the namespaces _jhub_ and _enterprise-gateway_. Nevertheless, the reported error remains.
**To Reproduce**
see #1474

**Comment by lresende** [comment]
Could you please provide the following info from hub/lab terminal:
 - pip list | grep elyra
 - jupyter --version

Also, if you change from dev to latest elyra version on the single user image tag, does it make any difference?

Otherwise I will try to figure out how I could try this on Azure.

**Comment by lresende** [comment]
I will close this, and reopen the original one that has all the details on how to reproduce it.
