### ISSUE TITLE
Hide/remove https://www.npmjs.com/package/@elyra/code-snippet-extension-experimental 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1558]
**Is your feature request related to a problem? Please describe.**
This outdated package is listed in the extension manager even though it is no longer maintained or supposed to be used.

**Describe the solution you'd like**
Remove or hide the package so users don't accidentally install it.

**Comment by lresende** [comment]
I would prefer not to remove this as it would break some releases that should still be in use by  users that have not yet upgraded to the latest JupyterLab 3.x
