### ISSUE TITLE
independent installation of elyra-python-editor-extension is failing with Module not found

### ISSUE THREAD

**Issue by harshad16** [elyra-ai/elyra#1564]
**Describe the issue**
While trying to install **elyra-python-editor-extension** independently, by following the documentation for installing the extension independently of elyra https://elyra.readthedocs.io/en/latest/getting_started/installation.html#pip, the process errored out with Module not found error during the `jupyter lab build` step. 

` ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/lab' in '/opt/app-root/share/jupyter/lab/staging/node_modules/@elyra/ui-components/lib'`
is the @material-ui/lab package missing ?
what should i do to resolve this issue? i couldn't find any similar issue.

**To Reproduce**
1. Open the container: `podman run -it quay.io/thoth-station/s2i-minimal-py38-notebook:latest bash`
2. Install: `pip install elyra-python-editor-extension`
3. Execute: `jupyter lab build`
4. See error log present in /tmp dir

**Screenshots or log output**
Small snippet of the lab build log:
```
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/lab' in '/opt/app-root/share/jupyter/lab/staging/node_modules/@elyra/ui-components/lib'
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1672:28
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:712:13
    at eval (eval at create (/opt/app-root/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/opt/app-root/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:628:24
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:782:8
    at /opt/app-root/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:902:5
resolve '@material-ui/lab' in '/opt/app-root/share/jupyter/lab/staging/node_modules/@elyra/ui-components/lib'
  Parsed request is a module
```
full error: 
[lab.log](https://github.com/elyra-ai/elyra/files/6308310/lab.log)

**Deployment information**
Describe what you've deployed and how:
 - **elyra-python-editor-extension** version: 2.2.1
 - Operating system: linux , ubi8 image
 - Installation source: PyPI
 - Deployment type: Docker image
 
```
(app-root) python --version
Python 3.8.3
(app-root) node --version
v14.16.1
(app-root) npm --version
6.14.12
 (app-root) jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 5.6.1
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

Additional Context:
Related-to: https://github.com/thoth-station/s2i-generic-data-science-notebook/pull/20

**Comment by ptitzler** [comment]
Side note (this is not an attempt to explain the issue):
I'm not sure the editors have been tested (in general) with the classic notebook interface or are even exposed. (`quay.io/thoth-station/s2i-minimal-py38-notebook:xxx` seems to be using the classic interface, not the lab IDE). I ran a quick sanity check using a local Elyra installation:
- Install all Elyra extensions `pip install  elyra && jupyter lab build`
- Run `jupyter notebook`
- Try to create a Python script or R script (no option given for either editor)
   ![image](https://user-images.githubusercontent.com/13068832/114746158-44861500-9d04-11eb-9dc4-b6b740d68df6.png)

So even if a stand-alone install worked, it doesn't seem like the editor would be usable.

**Comment by akchinSTC** [comment]
Looks like a required dependency "@material-ui/lab" was not listed as part of the ui-components package.json resulting in the error. Thanks @ajbozarth 

Will need to probably either cut a new release or push new extension packages (if possible)

**Comment by harshad16** [comment]
> Side note (this is not an attempt to explain the issue):
> 
> * Install all Elyra extensions `pip install  elyra && jupyter lab build`
> * Run `jupyter notebook`
> * Try to create a Python script or R script (no option given for either editor)
>   ![image](https://user-images.githubusercontent.com/13068832/114746158-44861500-9d04-11eb-9dc4-b6b740d68df6.png)
> 
> So even if a stand-alone install worked, it doesn't seem like the editor would be usable.

actually it has juyter lab support included as well, so instead of **Run `jupyter notebook`** if we do **Run `jupyter lab`**, we would get the lab interface.

**Comment by harshad16** [comment]
> Looks like a required dependency "@material-ui/lab" was not listed as part of the ui-components package.json resulting in the error
> Will need to probably either cut a new release or push new extension packages (if possible)

oh ok, thank you for looking into this :)

**Comment by ptitzler** [comment]
> actually it has juyter lab support included as well, so instead of Run jupyter notebook if we do Run jupyter lab, we would get the lab interface.

Got it. Just wanted to find out if you had a requirement for this to work in the classic interface. If you are switching to the lab UI then you might as well include all Elyra extensions. (:

**Comment by harshad16** [comment]
> Got it. Just wanted to find out if you had a requirement for this to work in the classic interface. If you are switching to the lab UI then you might as well include all Elyra extensions. (:

absolutely, we have s2i-lab-elyra image for that :) . this is just a side use case where there is just the python-editor.

**Comment by akchinSTC** [comment]
current workaround is to run 
`cd /opt/app-root/share/jupyter/lab/staging/node_modules/@elyra/ui-components && npm install @material-ui/lab`
between steps 2 and 3.

**Comment by harshad16** [comment]
> current workaround is to run
> `cd /opt/app-root/share/jupyter/lab/staging/node_modules/@elyra/ui-components && npm install @material-ui/lab`
> between steps 2 and 3.

the directory `/opt/app-root/share/jupyter/lab/staging/` is created after `jupyter lab build`.
and, it contains the node_modules.

this workaround couldn't use, is this something that worked for you?

**Comment by ptitzler** [comment]
@harshad16 we are going to deliver a fix in patch 2.2.2

**Comment by akchinSTC** [comment]
> the directory `/opt/app-root/share/jupyter/lab/staging/` is created after `jupyter lab build`.
> and, it contains the node_modules.

@harshad16 - My fault, you are correct, youll need to run that between step 3 and 4, then rerun `jupyter lab build`

**Comment by harshad16** [comment]
>My fault, you are correct, youll need to run that between step 3 and 4, then rerun `jupyter lab build`

@akchinSTC thank you, this workaround works.
i would use this, if we need it before and couldn't wait for the 2.2.2 release
