### ISSUE TITLE
Define Open API entry for contents/properties endpoint

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#1572]
**Describe the issue**
#1460 introduced a new endpoint (`elyra/contents/properties`) that should be documented in the Open API spec: https://github.com/elyra-ai/elyra/blob/master/elyra/api/elyra.yaml

~Also absent in that PR were unit tests to test the handler (endpoint) interactions that should be included as well.~ (Edit: as pointed out below, this was already written up in #1542)

**Comment by kiersten-stokes** [comment]
Are the handler tests the same as described in #1542?

**Comment by kevin-bates** [comment]
Geez - I'm sorry.  Description and title updated.
