### ISSUE TITLE
Refactor elyra backend tests for code reuse support

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1578]
**Describe the issue**
Today, Elyra's python codebase implements its tests in a sub-directory of the module which makes it a little hard to share code between the different tests on different modules. 

See the current structure below:

```
.
└── elyra/
    ├── cli/
    │   └── tests
    ├── contents/
    │   └── tests
    ├── metadata/
    │   └── tests
    ├── pipeline/
    │   └── tests
    ├── templates
    └── util/
        └── tests
```

Thinking about reusability and removal of code-duplication (as it came up in the #1551 discussions: https://github.com/elyra-ai/elyra/pull/1551#discussion_r614253113)

Some references below for used patterns:
- [PyTest common directory structure](https://docs.pytest.org/en/reorganize-docs/new-docs/user/directory_structure.html)
- [Jupyter Server directory structure](https://github.com/jupyter-server/jupyter_server/tree/master/jupyter_server)

```
.
└── project/
    ├── module1
    ├── module2
    ├── module3
    └── tests/
        ├── module1
        ├── module2
        ├── module3
        ├── shared.py
        ├── conftest.py
        └── etc
```

Note that we should consider that our `cypress` integration tests are already located at the `root/tests` folder, so if we consider that, we might need to refactor that to a child directory (e.g. integration). 

Thoughts?

**Comment by lresende** [comment]
I would like to propose we move more towards following the same structure as [Jupyter Server](https://github.com/jupyter-server/jupyter_server/tree/master/jupyter_server)

```
.
└── project/
    ├── module1
    ├── module2
    ├── module3
    └── tests/
        ├── module1
        ├── module2
        ├── module3
        ├── shared.py
        ├── conftest.py
        └── etc
```

**Comment by bourdakos1** [comment]
@lresende I think the cypress tests would be okay, because they are in the root folder, not `elyra`:
```
.
├── cypress
└── elyra/
    ├── cli
    ├── contents
    ├── metadata
    ├── pipeline
    ├── templates
    ├── util
    └── tests/
        ├── cli
        ├── contents
        ├── metadata
        ├── pipeline
        ├── util
        ├── shared.py
        ├── conftest.py
        └── etc
```

**Comment by lresende** [comment]
If we follow the [jupyter-server](https://github.com/jupyter-server/jupyter_server/tree/master/jupyter_server) model,  It's actually going to be something like:

```
.
├── cypress
└── elyra/
    ├── cli
    ├── contents
    ├── metadata
    ├── pipeline
    ├── templates
    ├── util
└── tests/
    ├── cli
    ├── contents
    ├── metadata
    ├── pipeline
    ├── util
    ├── shared.py
    ├── conftest.py
    └── etc
```

**Comment by kevin-bates** [comment]
@lresende - the _PyTest common directory structure_ link in the description looks incorrect.  Was this the intended link: https://docs.pytest.org/en/6.2.x/goodpractices.html#choosing-a-test-layout-import-rules

If so, it looks like we're leaning toward this form: https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code, is that correct?
