### ISSUE TITLE
New label for the "Submit Notebook ..." button on the tool bar

### ISSUE THREAD

**Issue by sputnik62** [elyra-ai/elyra#1590]
IBM Skills Network uses JupyterLab with Elyra to teach data science. Learners are given assignments to complete in Jupyter Notebooks. When a learner completes their notebook assignment and sees the button labeled "Submit Notebook" they instinctively think "I need to submit my assignment notebook for grading to get a mark" and they click on that button. This has led to mass confusion as we have hundreds of thousands of learners.

We would like to see the title of the button changed to something like "Submit Pipeline" or "Execute Pipeline" or "Run Pipeline" or "Submit Pipeline Run" or an equally meaningful label.

**Comment by lresende** [comment]
A couple of suggestions:
- [ ] Submit as pipeline
- [ ] Execute notebook as pipeline
- [ ] Execute as pipeline
- [ ] Run notebook as pipeline

**Comment by sputnik62** [comment]
I like "Execute as pipeline"

**Comment by ptitzler** [comment]
Perhaps `Run as pipeline` to shorten the label text?

**Comment by sputnik62** [comment]
> ?

I like `Run as pipeline` a lot.
