### ISSUE TITLE
Refactor pipeline validation into a shared service

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1592]
**Describe the issue**
We are starting to see a lot of new requirements related to validation, and these need to be shared between multiple clients as well as with the backend that can't assume a submitted pipeline is valid. 

Requirements:

- Refactor this as a REST API that takes a pipeline JSON and 
- The lifecycle should not require any user involvement (e.g. install, start, stop should be automated and handled by

Options to be considered:

- How to implement this in a way that could be easily sharable between Lab and other IDEs?
   - REST API as a server handle (requires Lab/Elyra to be deployed together with other IDEs)
   - Use a language server interface that is then supported in other IDEs
      - Elyra handler could proxy the request to a language server to hide the implementation details from Elyra on top of JupyterLab

Payload types:
Call to the service that include a remote runtime config (at pipeline submission)
Call to the service that local runtime config (at pipeline submission)
Call to the service without a runtime config (on trigger from changes in the pipeline editor UI)

Related Issues:
https://github.com/elyra-ai/elyra/issues/1370 https://github.com/elyra-ai/elyra/issues/938 https://github.com/elyra-ai/elyra/issues/870

Pull Requests: https://github.com/elyra-ai/elyra/pull/1595

**Comment by akchinSTC** [comment]
Validates basic JSON structure
- [ ]   contains valid json
- [ ] - Contains `primary pipeline’ and is a string
- [ ] - Contains at least one `pipeline element` in the json and that is a list
- [ ] - Checks pipeline schema version matches or works with the current version being run
- [ ] - the primary_pipeline is findable in the pipelines array
- [ ] - the found primary_pipeline has an app_data field that is an object containing a version field that is a number
- [ ] - the found primary_pipeline has a nodes field that is an array

Validate compatibility 
- [ ] - Based on the version of Elyra, determines what operations are supported (a bit moot unless we are planning on retrofitting earlier versions of elyra) for instance python script support was introduced in 1.0.0 and r-script in 2.2.0
- [ ] - Construct a support matrix based on runtimes, will be expanded to include runtime-specific components at runtime 
- [ ] - Rename null to generic? for the runtime agnostic pipeline under `pipeline_json['pipelines']['app_data']['ui_data']['runtime']['name']`
- [ ] - provide option to update old pipelines to current format?

Validate node properties
- [ ] - Check filename for validity and existence 
- [ ] - Check image name registry coordinate syntax
- [ ] - Check resource values
- [ ] - Check dependencies for validity and existence 
- [ ] - Check env vars
- [ ] - Check inputs and outputs
- [ ] - Check ui data label validity against acceptable runtime naming standards
- [ ] - Expand to check runtime specific components properties in pipeline json compared to current component registry

Validate the graph
- [ ] - Check for graph cycles
- [ ] - Check for singleton nodes to give warning?? Ones without any children

Response will include
- [ ] List unsupported node IDs for the runtime
- [ ] List of invalid link IDs (leads to a cycle)
- [ ] List of nodes with invalid properties e.g (node id, [list of invalid properties for said node])

**Comment by ptitzler** [comment]
Is `invalidPipeline` meant to be a superset of the others or supposed to encapsulate pipeline issues that don't fall into the other problem areas?

**Comment by bourdakos1** [comment]
@ptitzler `invalidPipeline` are for parsing errors past a successful parsing of the actual JSON, for example if the pipeline was missing the "nodes" list field. These errors should only ever occur if the user tries to manually edit the pipeline json

**Comment by bourdakos1** [comment]
current invalid pipeline errors:
```
    messages.push("Could not determine the primary pipeline.");

    messages.push("Field 'primary_pipeline' should be a string.");

    messages.push("Pipeline definition not found.");

    messages.push("Field 'pipelines' should be a list.");

    messages.push(`Primary pipeline '${primaryID}' not found.`);

    messages.push(`Primary pipeline is missing 'app_data' field.`);

    messages.push(`Could not determine the pipeline version.`);

    messages.push("Field 'version' should be a number.");

    messages.push("Field 'nodes' should be a list.");
```
