### ISSUE TITLE
Info symbol for 'Include Subdirectories in Dependencies' in block's properties shouldn't be clickable

### ISSUE THREAD

**Issue by fatkaratekid** [elyra-ai/elyra#1600]
**Describe the issue**
Hovering over info symbol:
![image](https://user-images.githubusercontent.com/2835130/115586878-513ed600-a2cd-11eb-9b03-421ab6f996a4.png)
changes cursor from arrow to a 'finger', which implies that it should be clicked. Which is not the case. If you click, the checkbox is selected, which is not what the user would expect.

**To Reproduce**
1. Hover over the info symbol in the 'Include Subdirectories in Dependencies' section of the block's properties.
![image](https://user-images.githubusercontent.com/2835130/115586569-04f39600-a2cd-11eb-8f1a-86c36fb9e517.png)
2. The cursor will change, so the expected action is the 'i' symbol should be clicked.
3. The lag until the hover produces a message is long enough that the user would just click before it is shown.
4. The checkbox is now checked and no info message is shown.
![image](https://user-images.githubusercontent.com/2835130/115586622-13da4880-a2cd-11eb-9ba8-aaa2c32baf38.png)

**Expected behavior**
The click action on the info symbol of the 'Include Subdirectories in Dependencies' in the block's properties should not select the checkbox.
All the other 'i' symbols behave as expected.

**Comment by akchinSTC** [comment]
With the release of elyra 3.0, the new properties editor displays the "info" wholeheartedly ![image](https://user-images.githubusercontent.com/13340013/128918771-b99e8f72-1a7c-46e1-b809-133121e2e85f.png)

so the info hover button will likely not be returning and we currently have no plans for a 2.x patch release for this. Will close in a few days unless any comments are made. Thanks
