### ISSUE TITLE
Default runtime is always 'Local Runtime'

### ISSUE THREAD

**Issue by fatkaratekid** [elyra-ai/elyra#1602]
Every time you run a pipeline you have to select the runtime. By default it will always be local. So practically every time you have a couple of extra steps.

![default_runtime](https://user-images.githubusercontent.com/2835130/115719083-0cbe4380-a37c-11eb-8613-846ed8b6290b.png)

I would prefer to either have 'remember this setting' checkbox, that it remembers my last choice or that you can select it in the runtimes section as the default.

**Comment by akchinSTC** [comment]
@fatkaratekid - This feature is coming with our new pipeline refactor in the next release. See #1004

**Comment by fatkaratekid** [comment]
Great news!
Thanks
