### ISSUE TITLE
Elyra documentation contains a non-functional search page

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1606]
**Describe the issue**
A clear and concise description of what the issue is.
see below

**To Reproduce**
1. Open https://elyra.readthedocs.io/en/latest/search.html
2. There's nothing a user can do on this page
3. The ["edit on github" link](https://github.com/elyra-ai/elyra/blob/master/docs/source/search.md) yields a 404

**Comment by tlzhu19** [comment]
@karlaspuldaro I can look into this

**Comment by lresende** [comment]
@ptitzler What are you looking for? The ability to search? Have you seen the search field on the top left?

![image](https://user-images.githubusercontent.com/382917/117253521-250e7380-adfc-11eb-9249-2b40d21c3f9a.png)

**Comment by ptitzler** [comment]
I am looking for a way to remove that page.
