### ISSUE TITLE
Documentation: problematic links

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1608]
**Describe the issue**

https://elyra.readthedocs.io/en/latest/recipes/deploying-kubeflow-locally-for-dev.html:
- link to https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/  404

https://elyra.readthedocs.io/en/latest/genindex.html
- Nothing to do or see here
- Link to github yields 404

**To Reproduce**
1. Open https://validator.w3.org/
2. Specify `https://elyra.readthedocs.io/en/latest/` as URL

**Comment by tlzhu19** [comment]
@karlaspuldaro please assign to me

**Comment by lresende** [comment]
Fixed by #1644
