### ISSUE TITLE
Env variables in properties view not updating

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1614]
**Describe the issue**
Env variables in properties view not updating

**To Reproduce**
1. Create a pipeline
1. Create two notebooks
1. Add first notebook to pipeline
1. Add second notebook to pipeline 
1. Edit first notebook properties:
   - add a runtime image (any will do)
   - add environment variable (any will do)
1. Edit first notebook properties:
   - add a runtime image (any will do)
   - add a different environment variable (any will do, just not the same)
1. select different nodes and inspect the environment variable properties - the same values are displayed for all nodes

**Expected behavior**
env. section not updating
![image](https://user-images.githubusercontent.com/5694071/115916850-a87faa80-a475-11eb-838d-054fb90c7154.png)
Here model.zip always stays there even if you click on different pipeline components

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: elyra/elyra@sha256:6c4c2178bde39eb2c22ae5ef7b043cf514e67c637e07918ea054b54318adbef8
 - Operating system: RHEL 7.9
 - Installation source: dockerhub
 - Deployment type: kubernetes (kind)

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - all
 - 
**Runtime configuration settings**
Kubeflow Pipelines API Endpoint
http://10.96.70.234/

Cloud Object Storage Endpoint
http://10.96.60.153:9000/

On Argo

**Comment by ptitzler** [comment]
Reproducible in 2.2.4

**Comment by ptitzler** [comment]
Not reproducible in 2.3/master. Any chance the fix can be retrofitted to 2.2.x so Romeo's conference lab doesn't have to use version 2.3, which is not mature enough?

**Comment by kevin-bates** [comment]
@ptitzler, @romeokienzler - Seems like this issue was being kept open for the possibility of retrofitting a change in 2.2.x and I'm now asking if that is necessary (and whether this issue can be closed).
