### ISSUE TITLE
Handle Kubeflow authentication/authorization errors

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1636]
**Describe the issue**
See below.

**To Reproduce**
1. Provision a _secured_ KFP deployment 
1. Create a runtime configuration in Elyra that meets one of the following criteria
    - no user name + password specified
    - invalid user name specified
    - invalid password specified
2. Create a notebook
3. Create a pipeline
4. Add notebook to pipeline
4. Using the "invalid" runtime configuration run pipeline OR export pipeline DSL and run DSL
5. Observe failure 
   ```
   f"pipeline submitted: {api_endpoint}/#/runs/details/{run.id}",
    AttributeError: 'NoneType' object has no attribute 'id'
   ```
During a preliminary investigation I've noticed that there are several silent errors that are never detected. For example, experiment creation fails without raising an error. It appears that the `kfp` client (tested with `0.7.0`) doesn't seem to detect/handle/expose authentication/authorization issues caused by missing/invalid credentials.

**Expected behavior**
Elyra analyzes the KFP response for signs that an API call might have failed even though no exception is raised or error returned.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.3/master (likely also in earlier versions)
 - Kubeflow 1.3 with security enabled (e.g. via DEX) - didn't test earlier versions

**Comment by ptitzler** [comment]
Basic recreate to illustrate the issue:
- Download [recreate.py.gz](https://github.com/elyra-ai/elyra/files/6407910/recreate.py.gz)
- Add a valid Kubeflow host name in line 26
- In lines 27/28 make sure the id/password combination is _not valid_ for the specified  KF host
- In lines 30/31 this can be any bogus information
- Run the script
- Inspect the outputs, e.g.
  ```
  Creating experiment heythere ...
   {'created_at': None,
    'description': None,
    'id': None,
    'name': None,
    'resource_references': None,
    'storage_state': None}
  ```

**Comment by ptitzler** [comment]
Same behavior with kfp 1.3.0 and kfp-tekton 0.6.0

**Comment by ptitzler** [comment]
I believe we should treat this as a bug in Elyra because the call in https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_kfp.py#L86-L88 returns `None` as session cookie when invalid credentials were specified. Unfortunately https://github.com/elyra-ai/elyra/blob/e82a3ec8b189ac94ade9d87e4482e0b760d5596b/elyra/pipeline/processor_kfp.py#L488 does not return a 403 HTTP status code if invalid credentials were provided. Therefore we might have to interpret the absence of  a cookie as a failure condition and raise an authentication error.

**Comment by kevin-bates** [comment]
Seems like we should also log the URL returned from the initial `requests.get()` call.  Are we always guaranteed that `auth` will be present in _that_ URL?  I suspect there are all sorts of ways to configure things in that aspect and wonder if just using the URL straight up might be better.  

We should also log if there's no auth cookie found.

**Comment by ptitzler** [comment]
No guarantee because we are only testing with one Dex configuration. But since things are already failing should a host ever return an auth URL that our pattern match doesn't catch, we are at least not regressing when we add the additional code(c:
