### ISSUE TITLE
Using softlinks for pointers to libraries

### ISSUE THREAD

**Issue by simon-streamotion** [elyra-ai/elyra#1648]
Created from discussion topic https://github.com/elyra-ai/elyra/discussions/1646 at request of @lresende 

I'd like to have a directory setup something similar to the following:
```
root
  -- common_libs
  -- pipe_1
     -- pipe1_files
     -- softlink_to_../common_libs
  -- pipe_2 
     -- pipe2_files
     -- softlink_to_../common_libs
```
The idea is that there is just one common_libs directory containing all my common libraries, and each pipeline dir contains a soflink to that directory. That way, I can easily import the common libs into the stages of my pipeline.

The problem arises when I try to run the pipeline on kubeflow - the stages fail when trying to import anything from common_libs because it cannot find the file.

It appears the tar command used to create the archive for the pipeline stages includes the softlink to common_libs rather than the files themselves. This is the default behaviour of tar but I believe it can be changed by using the --dereference flag - which includes a copy of the file in the archive rather than the link.

Any chance of changing the tar command for building the stage archives to include the dereference flag ?

**Comment by ptitzler** [comment]
Can you clarify where the `.pipeline` file would be located in the file system in your layout?

```
"root-dir" /
    common_libs/
    pipe1.pipeline <<< Here (1)?
    pipe1-dir/
    pipe1-dir/pipe1.pipeline    <<< Here (2) ?
    pipe1-dir/softlink-to-../common_libs
```

**Comment by simon-streamotion** [comment]
Hi Patrick,
 My current setup and original thought is (2) above. (1) would be ok though, I just think (2) is neater overall.

 We both are using the same definition of 'root-dir' - apologies for the confusion :-)

Cheers -- Simon

**Comment by ptitzler** [comment]
All good, just wanted to make sure we are not heading down a slippery slope! 

It appears that a one line change is required, adding `dereference=True` right here https://github.com/elyra-ai/elyra/blob/master/elyra/util/archive.py#L118. A new test case might be required as well.

**Comment by simon-streamotion** [comment]
Let me check with my org re. contributions to open source code :-)
