### ISSUE TITLE
Front end CI tests are failing in master branch 

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1651]
**Describe the issue**
Front end tests are failing on master branch 

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.

Screenshots are non-inclusive, example of one of the test failures.
![image](https://user-images.githubusercontent.com/13340013/117693499-f3d2d200-b172-11eb-9968-0c87f44f5c92.png)

**Expected behavior**
Tests to complete and pass

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: master

**Comment by lresende** [comment]
Fixed by #1660
