### ISSUE TITLE
Pipeline file label displays 'default' in tab right click menu 

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1652]
**Describe the issue**
When right clicking a pipeline tab, the action labels referring to the pipeline show as `default`
![image](https://user-images.githubusercontent.com/25207344/117703873-30fd8b00-b198-11eb-93ec-da5e1f0d4718.png)

As compared to a Python File or Notebook, the context menu displays the correct file type
![image](https://user-images.githubusercontent.com/25207344/117704007-568a9480-b198-11eb-98cb-2abffa8cf997.png)

**To Reproduce**
1. Create a new pipeline or open an existing one from the file browser
2. Right click the tab on the main menu and compare the context menu options with the screenshot above

**Expected behavior**
Options label should read either:
1. `<action> Pipeline`
2. `<action> <Pipeline type> Pipeline Editor` (to match the options in `File --> New ...` menu)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: v2.3.0-dev
 - Operating system: macOS
 - Installation source: conda

**Comment by bourdakos1** [comment]
@karlaspuldaro I think that might be the `displayName` for `addFileType`, here's from python-editor:
```js
app.docRegistry.addFileType({
      name: PYTHON,
      displayName: 'Python File',
      extensions: ['.py'],
      pattern: '.*\\.py$',
      mimeTypes: ['text/x-python'],
      icon: pyIcon
    });
```

but it's missing in pipeline-editor:
```js
app.docRegistry.addFileType({
      name: PIPELINE,
      extensions: ['.pipeline'],
      icon: pipelineIcon
    });
```
