### ISSUE TITLE
Elyra v 0.22 with Tekton Task fails because resource limit is not specified

### ISSUE THREAD

**Issue by nakfour** [elyra-ai/elyra#1658]
**Describe the issue**
We are running Elyra image in Open Data Hub with Kubeflow + Tekton. The Elyra UI forces you to specify CPU and RAM with minimum 1. When running the Tekton Task it fails with this message
```
1 error occurred: * failed to create task run pod "lambda-8aec1-download-or-generate-data-qz5sd": Pod "lambda-8aec1-download-or-generate-data-qz5sd-pod-j56mj" is invalid: spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit. Maybe invalid TaskSpec```

Removing the limit in the task yaml makes it run.

**Comment by ptitzler** [comment]
You should be able to clear the selection by removing the numeric value. This should reset the node's `cpu` property in the `.pipeline` file to `null`.

![clear_out](https://user-images.githubusercontent.com/13068832/117889318-34f8de00-b268-11eb-92c6-7b243f5c3f62.gif)

**Comment by nakfour** [comment]
Thanks @ptitzler for the input, I will try it. I was using Elyra 2.2.1 -> quay.io/thoth-station/s2i-lab-elyra:v0.0.7 -> ODH manifest v1.0.10
