### ISSUE TITLE
Duplicated tsconfig base files? 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1662]
**Describe the issue**
Looks like we have both `tsconfig.base.json`, `tsconfig-base.json` and even `tsconfigbase.test.json` and they differ from each other. 
Are they there for a reason? I would understand the `test` one, but do we also need the other two?

![image](https://user-images.githubusercontent.com/382917/117919290-94271480-b2a1-11eb-89fe-5b030aee7087.png)

**Comment by marthacryan** [comment]
I think this is the reason there are extra tsconfigs, not sure if they can be moved into the tests folder? https://github.com/elyra-ai/elyra/pull/1621/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&file-filters%5B%5D=.yml#r623432512
