### ISSUE TITLE
Set ELYRA_RUNTIME_ENV variable in execution environment for a component to determine it's execution environment

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1663]
**Is your feature request related to a problem? Please describe.**
I'm developing the elyra component library and need to know if I'm running inside Kubeflow or in local mode as I need to switch between local data storage and COS data storage for example

**Describe the solution you'd like**
Please provide a ELYRA_RUNTIME_ENV env variable set to either
local, kubeflow, airflow, ....

**Describe alternatives you've considered**
Find some other way (based on env variables already set where I am

**Additional context**
Main purpose now is to support https://github.com/elyra-ai/component-library to change behavior of different components depending on their runtime context

**Comment by kevin-bates** [comment]
Thanks for opening this issue.  

> Please provide a ELYRA_RUNTIME_ENV env variable set to either local, kubeflow, airflow, ....

Please note that the implementation will likely set the value of the system-defined env (proposed as `ELYRA_RUNTIME_ENV`) to the name of the corresponding runtime configuration, with "local" being a special case (as there is no formal runtime configuration named "local" today).  As a result, the known values will be "local", "kfp" and "airflow".  I just want to clarify that "kubeflow" will not be one of the "built-in" options.
