### ISSUE TITLE
Circular graph detection in VPE is broken again

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1673]
**Describe the issue**
![image](https://user-images.githubusercontent.com/13068832/118557046-80eccc80-b719-11eb-81b5-42f95e4daeba.png)

![image](https://user-images.githubusercontent.com/13068832/118557374-ef318f00-b719-11eb-98ce-3edb08818e71.png)

**To Reproduce**
1. Create a 2/3+ -node circular graph in VPE

**Expected behavior**

It should not be possible to create a circular graph

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.3/master

**Comment by bourdakos1** [comment]
@ptitzler this is my fault. When creating the `pipeline-editor` package I had the incorrect assumption that you could connect nodes to form a circular reference, but they were highlighted in red and you wouldn't be able to submit until the cycle is broken.

As a personal preference, I think I would rather be able to create the connection because I might (temporarily) create a circular reference while re-hooking up nodes and would be irritated and confused when the link didn't show up. Maybe this is a case for another user setting?

**Comment by bourdakos1** [comment]
This feature seems to be aimed at preventing confusion of novice users. I think a alternative solution that provides both clarity and doesn't hinder usability, would be to allow the connection, but show an error toast that explains that circular references aren't allowed and an "undo" button on the toast that would rollback to the point where there was no circular reference?

**Comment by kevin-bates** [comment]
> I think I would rather be able to create the connection because I might (temporarily) create a circular reference while re-hooking up nodes and would be irritated and confused when the link didn't show up.

I agree - it would be really frustrating if temporary cycles were disallowed.  In either case, this does imply that "validation requests" would need to occur whenever a connection is introduced.

Hmm, does the "validation service" in #1664 assume that the pipeline is "complete"?  If so, I wonder if cycle detection should remain on the client? (cc: @akchinSTC)

**Comment by ptitzler** [comment]
> would be irritated and confused when the link didn't show up.

Right, but a toast could be displayed to clarify why the attempt to define the dependency failed.

> "undo" button on the toast that would rollback to the point where there was no circular reference?

Supporting this  would probably open the door for other scenarios that lead to more problems. Say, for example, for the sake of argument, one might want to associate a pipeline containing only KFP components with an Airflow runtime. The user might never intend to run/export the pipeline as is but plans to replace the KFP specific components with Airflow equivalents in the future. Fundamentally there's no difference ("users can model anything they want"), but I'm not sure the benefits outweigh the risks because something isn't what it appears to be.

**Comment by bourdakos1** [comment]
> Say, for example, for the sake of argument, one might want to associate a pipeline containing only KFP components with an Airflow runtime. The user might never intend to run/export the pipeline as is but plans to replace the KFP specific components with Airflow equivalents in the future.

@ptitzler To be fair, I have also been arguing for this haha... But I also don't like talking about "slippery slopes" if this will improve the user experience I think we just do it and not worry about features that users will also request down the road. We can draw lines when they need to be drawn

> If so, I wonder if cycle detection should remain on the client?

@kevin-bates I think we might need have duplicate validation code until we have a fully functional python language server. Or use the node language server until the python one is ready?

**Comment by kevin-bates** [comment]
> @kevin-bates I think we might need have duplicate validation code until we have a fully functional python language server. Or use the node language server until the python one is ready?

That's fine. I agree that the server should check cycles (which handles the case of a submission from a different client or via the backend).  My concern is more about the frequency in which we might be calling the validation service and felt this (on each connection edit) was a good example of how things could get a little too "chatty".

**Comment by bourdakos1** [comment]
> My concern is more about the frequency in which we might be calling the validation service and felt this (on each connection edit) was a good example of how things could get a little too "chatty".

yea I think thats where the language server comes in with the websockets and stuff. Those diagnostics come in on every keypress in a normal IDE so I think we would be good as long as we follow the protocol

**Comment by ptitzler** [comment]
>  I think we just do it and 

Can you quantify how many time you found yourself in the situation that you needed to do what you are proposing to support? Do you know of any customer/user who has raised the current behavior as "a usability problem"? With a change like this the VPE behavior is starting to become inconsistent: on the one hand the UI is preventing the user from adding a Java/Go/any-file to the canvas because they are not supported, yet doesn't do the same for cycles. I think we should rather invest time in usability features users are waiting for, like the pipeline level properties, instead of changing what might not be an issue for the majority of users.

**Comment by bourdakos1** [comment]
@ptitzler I think these are two separate scenarios. With your invalid node example we would get an error trying to find a component definition for the file type. After dragging an unsupported file type (say a java file) onto the canvas it would just be a dummy node with no editable properties. All the user could do is delete it. If in the future there was a valid reason that a user brought to our attention of why they needed to drag a java file onto the canvas, I would be open to allowing the behavior. 

With the link example there is a valid user path and it's one that I personally use and find useful (and sounds like kevin maybe also saw as helpful?)

I could ask the same question, can you quantify how many times you found yourself in the situation where being blocked from creating links has been helpful to you? Looking through issues I didn't really see any discussion around the behavior of blocking a user from creating circular references, just a discussion on letting the user know it's not allowed before submitting the pipeline to the server.

If you don't think this is something we should invest time in, then I would argue we leave it as is until we determine that the current implementation is actually an issue

**Comment by ptitzler** [comment]
> I could ask the same question, can you quantify how many times you found yourself in the situation where being blocked from creating links has been helpful to you?

Every single time because I knew right away that I made a mistake. (It's the only reason - aside from buggy code - that a user cannot connect two nodes. It might not have been obvious but that could have been fixed by displaying an error, like it is done for files.) With the proposed behavior  there is no _clear indication_ that the user modeled something invalid until one tries to run/export the pipeline. Changing the display style of the connections (to dashed - if that's intended to convey that there is a problem - don't know) is not sufficient, because a dashed line is not commonly associated with an issue. At a minimum some sort of error icon would need to be attached to the connections to raise awareness.

**Comment by bourdakos1** [comment]
Ah okay, I see, it's a red line, but that isn't accessible. If we make it much more clear that the link is an error, would you be okay with that?

**Comment by ptitzler** [comment]
> would you be okay with that?

Yes. Sorry, I can't tell it's red, just that it is dashed and a different color than the other connections.

**Comment by lresende** [comment]
@ptitzler was this fixed? If so, could you please remove the `needs triage` and add Milestone 3.0.
