### ISSUE TITLE
Add UI to help user identify the pipeline runtime 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1680]
**Describe the issue**
We now support creating pipelines for specific runtimes:
![image](https://user-images.githubusercontent.com/382917/118913644-b42c8880-b8de-11eb-847e-d143c55e4449.png)

But there is no visible information for the user to identify what type of pipeline is in use, maybe an indication on the editor toolbar, similar to the suggestion below:

![image](https://user-images.githubusercontent.com/382917/118913956-46349100-b8df-11eb-8285-aa4b5fa878ff.png)

**Comment by ptitzler** [comment]
Perhaps a good place would be the yet-to-be-added pipeline properties panel.
