### ISSUE TITLE
Elyra 2.2.x cannot process Pipelines that were created using 2.3.x

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1693]
**Describe the issue**
See below

**To Reproduce**
1. Install Elyra 2.2.4
2. Follow the instructions in https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#verifying-runtime-configurations
3. Open the `validate_python` pipeline. (The pipeline was created using a later release!)
4. See validation errors

**Screenshots or log output**

![image](https://user-images.githubusercontent.com/13068832/119413082-d25d0480-bca1-11eb-8126-f412fbedbedc.png)

![image](https://user-images.githubusercontent.com/13068832/119413170-f7517780-bca1-11eb-8ee9-b7477597f34a.png)

Note that the same pipeline "passes" 2.3.x validation.

**Expected behavior**
No validation errors should be displayed

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.4

**Comment by bourdakos1** [comment]
looks like the `cpu`/`gpu`/`memory` are strings so would fail the `value > 0` check

**Comment by bourdakos1** [comment]
If we used to persist cpu/gpu/memory as empty strings at some point we should probably bump the pipeline version to 4 and add a migration that purges empty strings and converts any strings that are supposed to be numbers to numbers

**Comment by bourdakos1** [comment]
Oh misunderstood this is going from the new version to the old version. It looks like the component definition incorrectly sets the default value to an empty string

**Comment by ptitzler** [comment]
Yep, several options:
 - bump pipeline version (least desirable option because we'd have to maintain 2.2.x and 2.3.x example pipelines)
 - 2.3.x sets those properties to something that 2.2.x can handle (change in 2.3 required)
 - 2.2.5+ can handle 2.3 formatted inputs (change in 2.2.4 required)

**Comment by lresende** [comment]
2.3.x should be backward compatible in this scope.

**Comment by bourdakos1** [comment]
yea, this should be an easy fix in 2.3 to use a default that is backwards compatible (it is a bug how it is currently handled in 2.3)

**Comment by bourdakos1** [comment]
This will also need to be fixed in https://github.com/elyra-ai/elyra/pull/1620 

FYI @marthacryan @kiersten-stokes

**Comment by ptitzler** [comment]
The linked PR replaces the existing (invalid) pipeline with a version that was created using Elyra 2.2.4. This way no user is blocked until the issue has been fixed in 2.3.0 and a new release was published.

**Comment by lresende** [comment]
We should add a test case that creates a pipeline, which includes inputs/outputs/env_vars and other node properties and validate against a valid pipeline
