### ISSUE TITLE
How to know the notebook pipeline submit status from the command line?

### ISSUE THREAD

**Issue by morningcloud** [elyra-ai/elyra#1695]
I am triggering a pipeline run via command line with `elyra-pipeline submit pipeline_name.pipeline --runtime-config kubeflow_runtime_name`
This command will return with success status the moment the job is trigger and the pipeline starts running using the remote runtime. However, I want to be able to know if the pipeline is actually complete to trigger further actions as part of CICD. Is there a way to do so at the moment?

**Comment by ptitzler** [comment]
Hi @morningcloud, neither the CLI nor the GUI currently support pipeline execution monitoring for Kubeflow Pipelines or Airflow. However, for Kubeflow you could accomplish what you are looking for using a small script that utilizes the Kubeflow Pipelines SDK's [client](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.client.html).

**Comment by morningcloud** [comment]
Thanks @ptitzler  for the update, I checked the kubeflow pipelines documentation and I have an idea of how to check it. However, to check the status I would need to be able to identify the run id for this specific run. I saw a related issue raised (#1702), but it seems the be related to accessing the run id within the pipeline. How can the run id be identified from CLI?

**Comment by ptitzler** [comment]
Unfortunately the `elyra-pipeline` CLI currently does not support JSON as response format that would allow you to easily consume the response in a programmatic way. The run id is the UUID at the end of the first displayed URL `http://...pipeline/#/runs/details/<RUN_ID>`

```
❯ Job submission succeeded
  Check the status of your job at: http://...:31380/pipeline/#/runs/details/daba42ff-2857-445a-b185-b860ac2de43a
  The results and outputs are in the /.../getenvironment-0527152200 
  working directory in http://...:31339
```

For the time being, you'd have to parse the response 
```
$ elyra-pipeline submit MYPIPELINE.pipeline --runtime-config MYCONFIG | grep -Eo '[0-9a-f]+-[0-9a-f]+-[0-9a-f]+-[0-9a-f]+-[0-9a-f]+'
```

and pass the extracted run_id to an app like the one I hacked together for illustrative purposes:

[wait_for_run_completion.py.gz](https://github.com/elyra-ai/elyra/files/6557119/wait_for_run_completion.py.gz)

**Comment by ptitzler** [comment]
Monitoring support is added in version 3.7. The linked PR includes details how to enable it.
