### ISSUE TITLE
ELYRA_RUNTIME_ENV variable is no longer set during pipeline execution or export

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1696]
**Describe the issue**

I've noticed that the `ELYRA_RUNTIME_ENV` variable that was introduced in https://github.com/elyra-ai/elyra/pull/1668 is no longer set to any value. The problem surfaces in all three runtime environment types (local/kfp/aa).

**To Reproduce**
1. Install 2.3/master
2. Create a pipeline
3. Create a notebook | script that dumps the environment variables
    ```
    import os
    print(os.environ.get('ELYRA_RUNTIME_ENV'))
    ```
4. Add notebook | script to pipeline
5. Run pipeline and inspect notebook output

**Screenshots or log output**

**Expected behavior**

`ELYRA_RUNTIME_ENV` is set properly

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.3/master (pulled 5/25)

**Comment by ptitzler** [comment]
(I updated the original comment with exact recreate steps)
It took me a while to understand the root cause: 

- The environment variable detection code discovers that the notebook | script references the `ELYRA_RUNTIME_ENV` variable, and thus adds it to the list of environment variables for each node. 

![image](https://user-images.githubusercontent.com/13068832/119562214-f03a7000-bd5a-11eb-8c34-701b8a1b38fe.png)

- A user should never set this _"system-owned"_ variable (it'd defeat its purpose) and it remains therefore unset `ELYRA_RUNTIME_ENV=` when the pipeline runs or is exported.

From a code perspective:

- https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_local.py#L121-L122  (and the same for the other processors)
  ```
  envs['ELYRA_RUNTIME_ENV'] = "local"  # sets
  envs.update(operation.env_vars_as_dict()) # overrides with empty value  (see definition below)
  ```
- https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/pipeline.py#L152 # sets the variable to the empty string because it was detected in the notebook | script

**Comment by ptitzler** [comment]
We need to make sure that the user cannot explicitly or implicitly override this environment variable and any other environment variable that is owned by Elyra.

**Comment by kevin-bates** [comment]
Ah - good point/catch.  I'll update the tests to handle this case as well.  We should be able to just reverse the initialization sequences such that operation-provided envs are set first and system-owned env values override.

**Comment by ptitzler** [comment]
From a back-end point of view yes, but the GUI would still surface the variable(s) in the node's properties panel and give the user the impression that it's okay to override the value(s). Thus the usability problem still applies and perhaps needs a front end change as well.

**Comment by kevin-bates** [comment]
I agree.  Seems simple enough to filter `ELYRA_`-prefixed vars (although that isn't necessarily complete as we have a couple `AWS_` vars).  That is outside the scope of this issue in my opinion.  I'll be addressing the override of system-owned envs in the server.
