### ISSUE TITLE
Identify the initial list of Kubeflow pipeline components to be pre-installed with Elyra

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1698]
**Describe the issue**
Similar to what we do with Elyra runtime images, we should identify a subset of runtime-specific components to be pre-installed with Elyra so that we have a usable development environment right after installation.

**Comment by Tomcli** [comment]
KFServing component is commonly used in our team
https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/kfserving/component.yaml

**Comment by Tomcli** [comment]
another one we used in our example is Katib, since the Katib UI can be glitched sometime.
https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/katib-launcher/component.yaml

**Comment by Tomcli** [comment]
We also have components that are specific for certain platform (e.g. IBM Cloud WML, machine learning exchange). Do you want to install those as well?

**Comment by ptitzler** [comment]
- We should at a minimum include those components that a user would require to complete the most common scenarios.
- If possible we should also provide working example pipelines for those scenarios.

**Comment by Tomcli** [comment]
For KFServing component, here is the pipeline example https://github.com/kubeflow/kfserving/blob/master/docs/samples/pipelines/kfs-pipeline.ipynb

For katib, here is the pipeline example
https://github.com/kubeflow/kfp-tekton/blob/master/samples/katib/early-stopping.ipynb
