### ISSUE TITLE
As a pipeline node, I want to have access to a unique pipeline run id

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1702]
**Is your feature request related to a problem? Please describe.**
This feature request was initially raised by @simon-streamotion in https://github.com/elyra-ai/elyra/discussions/1686. 

**Describe the solution you'd like**
- During [local, kfp, airflow] pipeline processing, each pipeline node shall have access to an identifier that is unique for each pipeline run irrespective of how it was started. For example, a pipeline run can be started via the Elyra GUI, via the Elyra CLI, via the KFP UI, via the KFP CLI, etc. This implies that the identifier value is _unknown_ until the pipeline is executed, and can therefore not be generated in advance, e.g. during pipeline pre-processing.
- The identifier shall be a string that is made available to every pipeline node via an environment variable, e.g. `ELYRA_RUN_ID`.
- If possible, that identifier shall include the pipeline name to enable the user to associate the identifier with the entity that is associated with it.

**Describe alternatives you've considered**
No workarounds come to mind.

**Comment by ptitzler** [comment]
Example pipeline that comprises of a notebook, Python script, and R script that display the value of an environment variable named `PIPELINE_RUN_ID`: [i1702-example-pipeline.tar.gz](https://github.com/elyra-ai/elyra/files/6543198/i1702-example-pipeline.tar.gz)

**Comment by ptitzler** [comment]
This can be probably delivered in multiple PRs, one for each runtime environment because changes will have to touch multiple repositories anyways (`elyra` for local, `elyra` and `kfp-notebook` for kfp, and `elyra` and `airflow-notebook` for airflow)

**Comment by kevin-bates** [comment]
> Example pipeline that comprises of a notebook, Python script, and R script that display the value of an environment variable named ELYRA_PIPELINE_RUN_ID:

Your example uses `ELYRA_RUN_ID`.   I think `ELYRA_RUN_ID` is perfectly fine, but previous comments should perhaps be edited so we're consistent.

I do have concerns about how to support invocations "via the KFP UI, [and] via the KFP CLI" since these do not go through the Elyra server.  Also, is there a requirement to have this env available to nodes for operations/components that we do not control (i.e., those that are not Notebook, Python-script, or R-script nodes)?

Forgetting about non-elyra operations/components for the moment, it seems we'd need to have some persistent and well-known entity that is available to all nodes of a pipeline where the first writer (node) wins since we have no runtime-provided ID until then (assuming I'm understanding the sequencing here).  However, you can still have race conditions if there are multiple nodes w/o inputs, and I'm not sure how to go about resolving that in this kind of environment.

How strict is the requirement for native invocations?  I'm curious how we handle the cos-directory in those cases anyway since today's "run ID" is <pipeline-name>-<timestamp> set by the server?

**Comment by ptitzler** [comment]
> Your example uses ELYRA_RUN_ID. I think ELYRA_RUN_ID is perfectly fine, but previous comments should perhaps be edited so we're consistent.

Done.

> I do have concerns about how to support invocations "via the KFP UI, [and] via the KFP CLI" since these do not go through the Elyra server. 

There are two keys that are combined to produce `ELYRA_RUN_ID`:
- The first key is generated when a pipeline is submitted or exported in Elyra. It is derived from the pipeline name and therefore known to the user. This key is static, embedded in the pipeline spec,  and remains the same no matter how many times a user runs a pipeline using the KFP UI/CLI. (Running a pipeline using the KFP UI/CLI requires a prior export in Elyra, hence the key is guaranteed to exist.)
- The second key is generated by KFP before the pipeline nodes are processed and remains the same for all nodes in this pipeline. This key does change every time a pipeline is executed in KFP, which gives use the ability to generate a unique key for each run in KFP.
- The Elyra "notebook" operator has access to both keys and combines them.

It pretty much works the same for Airflow. The only difference is (as far as I can tell) that Airflow doesn't generate an ID but uses a timestamp instead to identify a DAG run. 

Examples of what the key would look like:
Run in Elyra:
 - user runs pipeline from Elyra UI for the first time: `<pipeline-id>-<kfp-generated-key-1>`
 - user runs the same pipeline from Elyra UI for the second time: `<pipeline-id-timestamp>-<kfp-generated-key-2>`
 
Run in KFP:
- user exports pipeline from Elyra UI for the first: `<pipeline-id>`
- user loads pipeline into KFP (either using the SDK or importing the YAML)
- user runs loaded pipeline (either using the SDK or using the KFP UI): `<pipeline-id>-<kfp-generated-key-1>`
- user runs loaded pipeline again (either by running the DSL or using the KFP UI): `<pipeline-id>-<kfp-generated-key-2>`

> Also, is there a requirement to have this env available to nodes for operations/components that we do not control (i.e., those that are not Notebook, Python-script, or R-script nodes)?

Not explicitly, but since the component support is still a WIP I have not started to investigate whether this is possible. Even if it is not, there's probably still value in supporting this only for the file-based ops across all runtimes.

> Forgetting about non-elyra operations/components for the moment, it seems we'd need to have some persistent and well-known entity that is available to all nodes of a pipeline where the first writer (node) wins since we have no runtime-provided ID until then (assuming I'm understanding the sequencing here).  [...]

See answer above.

> How strict is the requirement for native invocations? I'm curious how we handle the cos-directory in those cases anyway since today's "run ID" is - set by the server?

I derived this as an implicit requirement for the sake of consistency. If the `ELYRA_RUN_ID` environment variable is not defined during local execution, then the user would have to add runtime environment specific code to the node's file. ("Use ELYRA_RUN_ID when running on KFP/AA, something else otherwise.") 

For local execution `ELYRA_RUN_ID` could be created on the fly using `uuid.uuid4()` before the first pipeline node is run.

**Comment by kevin-bates** [comment]
Thanks for the explicit details.  It had slipped my mind that the "pipeline-id" portion is available in our NotebookOp operators in the form of the `cos-directory` option (although that might change).  `cos-directory` is derived from `pipeline-name` yet pipeline name is not (currently) conveyed to the bootstrapper - where we need it.  Therefore, it seems like we should introduce a `--pipeline-name` CLI option to the bootstrapper so the two properties are distinct.

Since it sounds like the lack of support for this feature in third-party components isn't a show-stopper, we could combine the `pipeline-name` and `KFP_RUN_ID_PLACEHOLDER` from the current environment to compose `ELYRA_RUN_ID` - as you suggest.  However, if we have no ability to hook into a third-party component in order to set `ELYRA_RUN_ID` _before_ the component's process runs (if there is one), then I don't see this happening for "other" components.  Frankly, the runtime providers should provide a general "prefixing" capability for these kinds of values. 

Do you know what the equivalent to `KFP_RUN_ID_PLACEHOLDER` is in Airflow?  If not, it might be helpful to dump (sorted) the env in a few nodes of a given pipeline run to try to find out (and if it's not apparent from docs).

**Comment by ptitzler** [comment]
> Therefore, it seems like we should introduce a --pipeline-name CLI option to the bootstrapper so the two properties are distinct.

Yep.

> Do you know what the equivalent to KFP_RUN_ID_PLACEHOLDER is in Airflow? 

I found this but haven't had a chance to try it out since it requires rebuilding the airflow image (and we have only one server):
https://stackoverflow.com/questions/55796959/how-to-reference-a-dags-execution-date-inside-of-a-kubernetespodoperator

**Comment by ptitzler** [comment]
> Yep.

Unfortunately I might have to take that back because of semantics. For KFP we'll need to pass the _pipeline version identifier_ because the pipeline name remains the same for each submission:
 - user creates new pipeline `mypipeline.pipeline`
 - user runs pipeline for the first time using the VPE
    - Elyra uploads pipeline `mypipeline` to KF using pipeline name `mypipeline` and pipeline version `mypipeline`.
 - user runs pipeline again using VPE
    - Elyra uploads pipeline `mypipeline` to KF using pipeline name `mypipeline` and pipeline version `mypipeline-<timestamp>`.

This is what it looks like after the same pipeline was run three times from the VPE:

<img width="824" alt="Screen Shot 2021-05-26 at 3 46 11 PM" src="https://user-images.githubusercontent.com/13068832/119740976-aeccc200-be39-11eb-903c-e996ef2b7bab.png">

**Comment by ptitzler** [comment]
> Therefore, it seems like we should introduce a --pipeline-name CLI option to the bootstrapper so the two properties are distinct.

~Yep.~ Sorry, we actually don't have to do that. It's easier to just attach the environment variable to the container that runs the bootstrapper. Therefore only the `NotebookOp` needs to be changed. (I did this in a prototype)

**Comment by kevin-bates** [comment]
Do you mean the bootstrapper?  The NotebookOp doesn't have access to the runtime-specific ID value - right?  The bootstrapper script (running in the image) is what drives the notebook through the papermill process or the python script through the python process and, only it would have the knowledge for how to compose ELYRA_RUN_ID.

If by "attach the environment variable to the container" you mean to partially add ELYRA_RUN_ID (up to where the runtime-specific ID would be appended), I guess you're right, but where, in this scenario, does the placeholder value come from?

**Comment by ptitzler** [comment]
The KFP SDK [defines a placeholder](https://github.com/ptitzler/kfp-notebook/blob/expose-run-id-demo/kfp_notebook/pipeline/_notebook_op.py#L22) that is substituted at runtime. 
See https://github.com/ptitzler/kfp-notebook/blob/expose-run-id-demo/kfp_notebook/pipeline/_notebook_op.py#L245-L252 for the code that produces the env variable. When you export a pipeline to YAML you can see what gets executed when the container is run and which environment variables are defined that are accessible to all processes:

```
  container:
      args: ['mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && curl -H "Cache-Control:
          no-cache" -L https://raw.githubusercontent.com/elyra-ai/kfp-notebook/master/etc/docker-scripts/bootstrapper.py
          --output bootstrapper.py && curl -H "Cache-Control: no-cache" -L https://raw.githubusercontent.com/elyra-ai/kfp-notebook/master/etc/requirements-elyra.txt
          --output requirements-elyra.txt && python3 -m pip install  packaging &&
          python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py
          --cos-endpoint ... --cos-bucket ...
          --cos-directory "..." --cos-dependencies-archive "..."
          --file "getenv.ipynb" ']
      command: [sh, -c]
      env:
      - {name: KFP_RUN_ID_PLACEHOLDER, value: ''}
      - {name: ELYRA_RUNTIME_ENV, value: ''}
      - {name: AWS_ACCESS_KEY_ID, value: ...}
      - {name: AWS_SECRET_ACCESS_KEY, value: ...}
      - name: ELYRA_ENABLE_PIPELINE_INFO
        value: "True"
      - {name: ELYRA_WRITABLE_CONTAINER_DIR, value: /tmp}
      - {name: ELYRA_RUN_ID, value: 'use_run_id-0526162914-{{workflow.uid}}'}
      image: quay.io/ptitzler/pandas
      imagePullPolicy: IfNotPresent
```

You'll notice that the `ELYRA_RUNTIME_ENV` variable you've introduced in https://github.com/elyra-ai/elyra/pull/1668 gets injected the same way. (Above output was produced using a build that does not include the fix, hence the variable value is empty)

**Comment by kevin-bates** [comment]
I didn't realize there was an actual "placeholder".  This makes sense and, yes, alleviates the need for updating the bootstrapper.

Since you're already implementing this, please assign yourself the issue.  We were going to be duplicating efforts here and neither of us has time for that.
