### ISSUE TITLE
Update the pipeline schemas to remove redundant fields

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1710]
**Describe the issue**
There are currently two places where a pipeline's runtime is configured. 
primary_pipeline-> app_data ->ui_data -> runtime 
primary_pipeline-> app_data -> runtime

We should merge the first into the latter to make things less ambiguous. We should also consider moving the runtime field completely out of the primary pipeline scope and up a level to make it clear that the runtime is associated with all pipelines(including supernodes) in the pipeline file.

This might get tricky when defining a generic pipeline as the runtime will be defined as null and the new validation service will only be able to perform a token validation (a check for components that ALL runtimes support) on the pipeline until submission time when a pipeline runtime is selected and a more thorough check can be done. At which point the latter runtime field would be overwritten with the selection(e.g. kfp, airflow, local). 
**Screenshots or log output**
```
      "app_data": {
        "ui_data": {
          "runtime": {
            "name": "kfp",
            "display_name": "Kubeflow Pipelines"
          },
          "comments": []
        },
        "version": 3,
        "name": "untitled4",
        "runtime": "kfp",
        "runtime-config": "kfp",
        "source": "invalid_node_property_image_name.pipeline"
      },
      "runtime_ref": ""
    }
```

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: master branch
 - Operating system: macos

**Comment by kevin-bates** [comment]
Thanks for opening this issue @akchinSTC.  Is there any reason we shouldn't make the leap to the global scope now?  We'll likely need some tolerance for older pipelines anyway (thinking CLI invocations).

Which form will be adopted?  I would recommend going with a 'runtime' stanza similar to the `ui_data` format:
```JSON
          "runtime": {
            "name": "kfp",
            "config": "kfp",
            "display_name": "Kubeflow Pipelines"
          },
```

Is `name` really indicating the schema and `config` indicating the runtime instance name?  If so, we might want to rename `name` to `schema` for clarity as well.

**Comment by akchinSTC** [comment]
> Is there any reason we shouldn't make the leap to the global scope now?
Need to think over the `not` scenario, but cant think of any atm, ill leave it open for others to chime in. 

> Which form will be adopted?
I imagine thats up in the air atm, but your recommendation is a good start. 

> Is name really indicating the schema and config indicating the runtime instance name? If so, we might want to rename name to schema for clarity as well.
Yes to both. (I think). Renaming the `name` to `schema` is a good idea. `runtime-config` is currently the local runtime instance name. Wondering if `config` then can be named something more specific like `local-config-name` since the runtime  these names are entirely up to the user and are unique to each users local workspace.
