### ISSUE TITLE
Please tell me how to run it with parameters.

### ISSUE THREAD

**Issue by nanaones** [elyra-ai/elyra#1721]
https://github.com/elyra-ai/airflow-notebook/blob/25eacb637043cedcaab87b1e846411cf70c767ea/etc/docker-scripts/bootstrapper.py#L205

In order to receive a variable and run the notebook, I need to run the paper mill by passing it a variable, but there doesn't seem to be such a setting right now.

Maybe there is another way I'm not aware of?

As far as I know, passing parameters should be like this:

```python

import papermill as pm

pm.execute_notebook(
   'path/to/input.ipynb',
   'path/to/output.ipynb',
   parameters = dict(alpha=0.6, ratio=0.1)
)
```
in papermill [README.md](https://github.com/nteract/papermill#execute-via-the-python-api)

**Comment by nanaones** [comment]
> Hi @nanaones, we would need to expose the ability to enter parameters on the node property UI which we have talked about but haven't had a chance to do it yet. Having said that, if you modify your code to use env variables, that could be a workaround for today while we work on the support for notebook parameters.
> 
> BTW, I will transfer this issue to the elyra repo for better visibility.

Are there any other examples provided?
Currently I have created a pipeline with Ariflow on EKS.
Environment variables injected from the elyra pipeline were entered as environment variables for the K8s pods but not checked in the notebook.

```python
import os
os.getenvron
```

### elyra pipeline on notebook config
![image](https://user-images.githubusercontent.com/42568844/120423152-d0332e00-c3a4-11eb-8b89-dbc30a43ba57.png)

### on k8s pod's Environment value] Lens 
![image](https://user-images.githubusercontent.com/42568844/120423435-59e2fb80-c3a5-11eb-85c1-62f6f65567b9.png)

### result html
![image](https://user-images.githubusercontent.com/42568844/120423102-b7c31380-c3a4-11eb-9afa-20863a67ee18.png)

**Comment by lresende** [comment]
Could you try follow the pattern below:

USER = os.getenv('VAR')

**Comment by nanaones** [comment]
> Could you try follow the pattern below:
> 
> USER = os.getenv('VAR')

This also doesn't work.

![image](https://user-images.githubusercontent.com/42568844/120428481-ad0d7c00-c3ae-11eb-8833-d760a339e6b8.png)

**Comment by lresende** [comment]
Could you try on a very simple notebook without Spark and see if that works better. Make sure to add some value on the node property for the env var.

**Comment by nanaones** [comment]
> Could you try on a very simple notebook without Spark and see if that works better. Make sure to add some value on the node property for the env var.

Ah... As you said, I've verified that it works via the python3 kernel.
Guess which part might be wrong?
Could my kernel.json settings be wrong?

I don't know what to change.

![image](https://user-images.githubusercontent.com/42568844/120441726-d4b91000-c3bf-11eb-9b8e-85975eebc660.png)

**Comment by akchinSTC** [comment]
Hi @nanaones, could you describe what your deployment environment currently looks like so I can setup a reproduction for the development team here?
e.g. how is spark deployed? colocated in the same k8s cluster or remote? configuration in airflow via connections? etc.
thanks!

**Comment by nanaones** [comment]
> Hi @nanaones, could you describe what your deployment environment currently looks like so I can setup a reproduction for the development team here?
> e.g. how is spark deployed? colocated in the same k8s cluster or remote? configuration in airflow via connections? etc.
> thanks!

Airflow is above EKS.
Jupyter Hub, Livy, YARN, and Spark are installed on EMR.
I installed Elyra from JupyterHub for Jupyter lab users.
This is the same configuration as the notebook in EMR used by AWS.
The kernel images used were created using the following guides from AWS.
(However, only sparkmagic is installed in the default Python image, and the kernel is added via jupyter-kernelspec.
Send a request to EMR's LIVY endpoint via Jupyter's sparkmagic_config.json file in AWS EMR. )

**Comment by nanaones** [comment]
Dear, @akchinSTC 

Our team's senior engineer solved the problem.
It wasn't hard and I used a sparkmagic function called [send_to_spark](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/kernels/kernelmagics.py#L183).
A lot of people think it can be confusing. I hope this part is included in the guide.
`%%send_to_spark`

Ref: 
https://examples.hopsworks.ai/ml/plotting/matplotlib_sparkmagic/
https://towardsdatascience.com/every-data-scientist-can-need-some-spark-magic-853da0b81006

**Comment by thesuperzapper** [comment]
I have raised a separate issue https://github.com/elyra-ai/elyra/issues/2472 about setting dynamic environment variables in Notebook/Script that take their values from the outputs of the upstream tasks.
