### ISSUE TITLE
Update documentation with new feature: creation of pipelines specific to a runtime

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1722]
**Describe the issue**
#1591 introduced a new feature to AI Pipeline Editor to enable creation of pipelines specific to a runtime.
Elyra documentation  need to be updated reflecting these changes.

- `README`
- `user_guide/pipelines.md`

**Comment by ptitzler** [comment]
Pipelines topic is updated with the relevant information by https://github.com/elyra-ai/elyra/pull/1848
