### ISSUE TITLE
Identify the initial list of Apache Airflow pipeline components to be pre-installed with Elyra

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#1728]
**Describe the issue**
Similar to what we do with Elyra runtime images, we should identify a subset of Airflow operators to be pre-installed with Elyra so that we have a usable development environment right after installation.

Related to #1698, which is the same issue but for KFP components

**Comment by akchinSTC** [comment]
First pass went with a list of more generic operators not affiliated with any specific platform or framework, with the exception of Apache Spark. 
```
airflow.operators.bash_operator - standard bash operations
airflow.operators.dagrun_operator - triggers a specific existing dag
airflow.operators.docker_operator - kicks off docker containers on host or remote docker daemon
airflow.operators.email_operator - utility 
airflow.operators.http_operator -  nice to have, operator to call rest endpoints with payloads
airflow.operators.papermill_operator - yes
airflow.operators.python_operator - yes
airflow.contrib.operators.spark_sql_operator - spark operations
airflow.contrib.operators.spark_jdbc_operator - spark operations
airflow.contrib.operators.spark_submit_operator - spark operations
airflow.contrib.operators.kubernetes_pod_operator - needed for notebookop
airflow.contrib.operators.ssh_operator - ssh operations to remote systems
airflow.operators.subdag_operator - trigger other dags to run as sub-pipelines to this parent
```
A more complete list can be found here:
https://airflow.apache.org/docs/apache-airflow/1.10.12/_api/airflow/operators/index.html
and here:
https://airflow.apache.org/docs/apache-airflow/1.10.12/_api/airflow/contrib/operators/index.html

**Comment by kiersten-stokes** [comment]
Thanks for this! For #1620, I had to remove the following operators for the reasons listed below, but hoping to get them back in in later PRs.

- `PythonOperator` - there's an issue with the `python_callable` parameter and handling how that is entered by the user and rendered by the template; will have to consider our options here
- `PapermillOperator` - similar issue with this operator because it requires passing a notebook as a parameter; the operator wants the notebook entered as a JSON object but then parsing presents problems
- `DagRunOperator` - same `python_callable` issue as above
- `SubDagOperator` - parsing is failing for this operator right now since it's hitting some regex edge cases since it has a function as a default argument value
