### ISSUE TITLE
HTML Support in Elyra

### ISSUE THREAD

**Issue by sabary661990615** [elyra-ai/elyra#1730]
**Is your feature request related to a problem? Please describe.**
Right now Elyra has a lot of functionality, but something I find noteworthy is that it has very limited range of support. I want to use it long term, but some things are still holding me back from going full-Elyra. 

**Describe the solution you'd like**
As I have been learning HTML, I have found the Live Preview feature on Brackets to be very useful. I think implementing something similar in Elyra will have a big improvement on its usability. 

**Describe alternatives you've considered**
Frankly, there isn't a clear alternative - they would all require implementation of a browser, at which point not adding a Live Preview seems like a waste.

**Additional context**
This is a link that describes the Live Preview feature on Brackets:
https://www.tutorialbrain.com/text_editor/brackets_live_preview/

**Comment by karlaspuldaro** [comment]
Hello @sabary661990615 
Just to clarify, are you proposing a live html preview to help the UI development in Elyra?
You can use [watch mode](https://elyra.readthedocs.io/en/latest/developer_guide/development-workflow.html#incremental-development) which auto-compiles your front end changes and picks up right away by the browser when you refresh the page.

**Comment by ajbozarth** [comment]
I looked into this a bit and am unsure what functionality you desire over what's already available in core JupyterLab. Currently if you open an html file in lab it opens both an editor and preview tab, which can then be moved side by side and the preview tab automatically update as you edit in the editor as well as having a manual refresh button. 

Are you requesting that we extend that functionality with more features? If so what specific features are you looking for?

**Comment by akchinSTC** [comment]
@sabary661990615 - closing this issue. The enhancement request is a bit out of our wheelhouse and we dont have any plans in the forseeable future to include it in elyra
