### ISSUE TITLE
It's no longer possible to assign a custom node name

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1733]
**Describe the issue**
See steps below

**To Reproduce**
1. Install 2.3/master
2. Create a notebook | script
2. Open VPE
3. Add notebook | script to pipeline
4. Try to edit the node name - there is no longer an entry in the properties view

**Expected behavior**

Node names can be customized. This used to work in 2.2.x

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.3/master

**Comment by lresende** [comment]
@ptitzler Could you check the current behavior on master and see if that works as expected.

**Comment by ptitzler** [comment]
Appears to be resolved in 2.3.0rc1. Confirmed using generic/kfp/aa pipeline
