### ISSUE TITLE
Include file dependencies not in the same directory 

### ISSUE THREAD

**Issue by Shreyanand** [elyra-ai/elyra#1734]
**Is your feature request related to a problem? Please describe.**
I have local file dependencies that are required for running a notebook in the pipeline. However, due to the logical structure of the repository it's not in the same directory as the notebook. As I understand from the [documentation](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#creating-a-pipeline-using-the-pipeline-editor), there is no way of including that dependency other than creating a second copy in the same directory (which would create hassles during updates) 

**Describe the solution you'd like**
A way to include any dependency that exists anywhere in the root of the repository.

**Comment by ptitzler** [comment]
> there is no way of including that dependency other than creating a second copy in the same directory

See related issue https://github.com/elyra-ai/elyra/issues/1706 and the upcoming support for symlinks.

**Comment by ptitzler** [comment]
This has been fixed. Refer to https://elyra.readthedocs.io/en/stable/user_guide/best-practices-file-based-nodes.html#file-input for details
