### ISSUE TITLE
Local pipeline fails to run when using relative script

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1737]
**Describe the issue**
Local pipeline fails to run when using relative script

**To Reproduce**
1.Create a pipeline on `elyra-pipelines`
2.Add a script `factorial.r` from a sibling directory `sample-script`
3.See error:
![image](https://user-images.githubusercontent.com/382917/121425539-5d3b3180-c927-11eb-8df9-13d35fd54f92.png)

**Comment by ptitzler** [comment]
Can you draw the directory layout?

```
elyra-pipelines/mypipeline.pipeline
sample-script/factorial.r
```

If this is your scenario then you need to use a symlink.

**Comment by ptitzler** [comment]
Also likely a duplicate of https://github.com/elyra-ai/elyra/issues/1734 et al

**Comment by lresende** [comment]
> If this is your scenario then you need to use a symlink - support for kfp/aa is already available in master. (#1689)

This is a pipeline that use to work on a released version.

**Comment by lresende** [comment]
This seems like an issue on how the pipeline-editor is now calculating relative paths:
Master which is using pipeline-editor 0.3.0 : `'filename': 'sample-python/factorial.r'`
#1620 which is using pipeline-editor 0.5.0: `'filename': '../sample-python/factorial.r'`

Just as a reminder, the relativeness here is calculated from the workdir and not from where the pipeline is.

**Comment by bourdakos1** [comment]
@lresende the pipeline-editor shouldn’t change the filepaths of nodes in an existing pipeline file. I would guess this is an issue on the JupyterLab side when preparing the file for submission

**Comment by lresende** [comment]
@ajbozarth could you please work with @bourdakos1 on this as you worked on this originally.

**Comment by bourdakos1** [comment]
fixed

**Comment by lresende** [comment]
Verified, thanks @bourdakos1
