### ISSUE TITLE
Unable to edit node properties of nodes inside of a supernode

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1739]
**Describe the issue**
Unable to edit node properties of nodes inside of a supernode

**To Reproduce**
1. Create a supernode
2. Expand the supernode flow
3. open the properties of a node

**Screenshots or log output**
<img width="1462" alt="Screen Shot 2021-06-09 at 5 12 30 PM" src="https://user-images.githubusercontent.com/4212769/121430363-02650280-c946-11eb-9ecc-f24bdc28795d.png">

**Comment by akchinSTC** [comment]
fixed in : https://github.com/elyra-ai/pipeline-editor/pull/127
