### ISSUE TITLE
2.3/rc1 Pipeline editor/properties view: open most logical properties tab

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1746]
**Is your feature request related to a problem? Please describe.**
In version 2.3 the VPE introduces a multi-tab properties view providing access to pipeline properties/node properties/the palette. Use the VPE for a bit and you'll notice that in many cases the displayed properties tab appears to be the one that is least likely to be used.

**Describe the solution you'd like**

Initial up-and-running scenario: User opens pipeline editor with _empty_ file.
- The properties sidebar is automatically opened and the palette tab displayed. (Nothing is opened today.)
- The default text on the canvas displays help-ish information to help a novice user.

Common editoing:The VPE should automagically switch to _the properties tab_ that makes most sense in the context of a user's workflow. For example:

- zero or more nodes in pipeline (none selected) and the user clicks on the canvas (but not on a widget):
   - display pipeline properties (the node properties tab would display the  same message it displays today)
- one or more nodes in the pipeline and the user clicks on one of the nodes/widgets
   - display node properties (current behavior)
 - two or more nodes in the pipeline and the user selects two or more of the nodes
   - display node properties with error message (current behavior)

**Comment by ptitzler** [comment]
Slightly off-topic but semantically related. Currently (and over time there will be more widgets that this applies to) if one clicks on a comment (with the properties sidebar extended) the widget's properties are not displayed, even though it would make sense to do so.

![image](https://user-images.githubusercontent.com/13068832/121708407-6396ee00-ca8c-11eb-8012-00df239d4087.png)

I believe we should treat comments semantically as nodes as well and therefore enable the user to define properties. The only difference to other node types (e.g. file based nodes or component nodes) is that those nodes are ignored during pipeline execution and export.

**Comment by ptitzler** [comment]
The tabs should also have tool tips associated with them

![image](https://user-images.githubusercontent.com/13068832/121709414-60e8c880-ca8d-11eb-8d4f-fc7c70a8b000.png)


e.g.
- Edit pipeline properties
- Edit node properties
- Add nodes to pipeline

**Comment by lresende** [comment]
My personal preference, to better use the available real estate, would be to have the palette on the right side as below. That way the palette is always available, and the properties have a better user experience, as it would show "pipeline properties" when no node is associated, and the node properties when a node is selected. 

![image](https://user-images.githubusercontent.com/382917/122100659-4170d900-cdc8-11eb-8036-1864e32e4ce8.png)

**Comment by ptitzler** [comment]
Where is the properties view in the screen capture? I only see the palette on the left

**Comment by lresende** [comment]
The properties would be as we have today, on the right side, with the `click` behavior change.

**Comment by ajbozarth** [comment]
@lresende I'll jump on this now. 

@bourdakos1 is this code in pipeline-editor?

**Comment by bourdakos1** [comment]
yea, this code would be in the pipeline-editor. However, I think we should have a bit more discussion around the user experience before tackling this

**Comment by bourdakos1** [comment]
I'm really not a fan of the palette panel on the left (but that's just my opinion)

The original design of the right panel was too be more like this (this is also the current behavior in the vscode version):
![image](https://user-images.githubusercontent.com/4212769/122458219-91dd6780-cf7d-11eb-8b58-d4ccbdfef90d.png)

With a column of icons that, when clicked, would open directly to that tab.

We could also add some smart behaviors, like if the side panel is open and you click on a node it switches to node properties and if you click on the background it could switch to the last tab you had open or pipeline properties or palette. This behavior could also be configurable by the user if we wanted

**Comment by ajbozarth** [comment]
I've opened https://github.com/elyra-ai/pipeline-editor/pull/128 to handle this on a surface level. I agree that we should improve the overall UI, but this will at least address the UX issues in the short term.
