### ISSUE TITLE
Pipeline version bump must be performed to prevent failures in legacy releases

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1748]
**Describe the issue**
 Elyra 2.3rc1 produces pipeline files with version identifier 3.0, which is the same 2.x releases use. With the introduction of runtime specific pipeline files a version bump must be performed to prevent failures if a user opens a 2.3.x pipeline file in Elyra < 2.3.

```
{
  "doc_type": "pipeline",
  "version": "3.0",
```

**Comment by lresende** [comment]
Note that the version on the description is actually the pipeline schema version, the pipeline flow version is in the pipelines.app_data.version and is an integer value.

![image](https://user-images.githubusercontent.com/382917/122113083-7c7a0900-cdd6-11eb-8b4d-6b4b938f6a2a.png)

**Comment by lresende** [comment]
This requires #1693 to be fixed first, to avoid breaking backward compatibility on the pipeline json structure/values.
