### ISSUE TITLE
bash operator properties - boolean value is not handled properly

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1753]
**Describe the issue**
Likely not specific to this operator and a general problem:

**To Reproduce**
1. Create AA RTC
2. Create AA pipeline
3. Add bash operator
4. Configure required properties without changing anything else
5. Note that xcom checkbox is selected by default
   ![image](https://user-images.githubusercontent.com/13068832/121746593-f51d5480-caba-11eb-9dd7-2a112c9a2cd2.png)
6. Save the pipeline
7. Open the pipeline in a text editor and locate the `bashoperator_xcom_push` property. It is set to `false`

![image](https://user-images.githubusercontent.com/13068832/121746792-46c5df00-cabb-11eb-8b3a-5ef0824c9798.png)

**Comment by lresende** [comment]
This seems to be generating the proper `common properties` field definition, but the issue seems to be with the control. If you force an update to the value, then it seems to work properly.

```
      {
        "parameter_ref": "bashoperator_xcom_push",
        "control": "custom",
        "custom_control_id": "BooleanControl",
        "label": {
          "default": "xcom_push"
        },
        "description": {
          "default": "If xcom_push is True, the last line written to stdout\n        will also be pushed to an XCom when the bash command completes. (type: bool)",
          "placement": "on_panel"
        },
        "data": {
          "required": false,
          "format": "bool"
        }
      }
```
