### ISSUE TITLE
"Generic Pipeline Editor" item label in command palette has line breaks

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1763]
**Describe the issue**
"Generic Pipeline Editor" item label in command palette has line breaks

**To Reproduce**
Ctrl-Shift-c => search for "pipeline"

**Screenshots or log output**
![Screenshot from 2021-06-15 06-25-55](https://user-images.githubusercontent.com/5694071/121992975-f5f80400-cda2-11eb-9bb1-f79243953295.png)

**Expected behavior**
Either I expect only to see one item called "New Pipeline Editor" or I except to see one item without line break for each editor type (Generic, Airflow, Kubeflow)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: v2.3.0rc1(isch)
 - Operating system: rhel 8
 - Installation source:custom container image build from repo some day ago
 - Deployment type: kind

**Comment by lresende** [comment]
This seems to be related to the 'tooltip for the item, where other items don't have it.
