### ISSUE TITLE
2.3/rc1 "Error making request ..." trying to retrieve the component list

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1766]
**Describe the issue**
A clear and concise description of what the issue is.

Caused by a user error (I unintentionally corrupted the catalog), above generic error message was displayed in the UI. The details didn't provide enough information (Invalid JSON) for a regular user. The motivation for this issue is that in the future the backend may fail when a request is made to retrieve the component list. The error message should indicate which request/operation failed.

**To Reproduce**
1. Corrupt the KFP component catalog
1. Create a KFP pipeline
1. See error

The actual error message varies depending on what is broken / how it is broken.

Example:
![image](https://user-images.githubusercontent.com/13068832/122087771-f4860600-cdb9-11eb-938c-3a97ee67edba.png)

Another example:
![image](https://user-images.githubusercontent.com/13068832/122090044-357f1a00-cdbc-11eb-8dd8-e04ed30596ad.png)

 A user friendly error would indicate that the component catalog could not be loaded.

**Comment by lresende** [comment]
@ptitzler Could you please validate this is still an issue on the latest master.

**Comment by ptitzler** [comment]
The mentioned PR hasn't been merged, so why would this not be an issue anymore?
