### ISSUE TITLE
Add page to kubeflow.org

### ISSUE THREAD

**Issue by DavidSpek** [elyra-ai/elyra#1767]
The kubeflow website [contains a sections](https://www.kubeflow.org/docs/external-add-ons/) with third-party add-ons which also lists [Kale](https://github.com/kubeflow-kale/kale). Since Elyra is similar to Kale and provides great feature for Kubeflow Pipelines I think a page about Elyra should be added to the Kubeflow website. This can be done [here](https://github.com/kubeflow/website/tree/master/content/en/docs/external-add-ons).

**Comment by lresende** [comment]
This is now live: https://www.kubeflow.org/docs/external-add-ons/
