### ISSUE TITLE
2.1/rc1 VPE custom component node tool tip is empty

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1769]
**Describe the issue**
A clear and concise description of what the issue is.

I've added a custom KFP component to the palette and added it to a pipeline. Hovering over the node an empty box is displayed:

![image](https://user-images.githubusercontent.com/13068832/122099927-6dd82580-cdc7-11eb-82e1-901e697c3108.png)

As a user I would expect to see:
- the label (if defined)
- the component name 
- all input properties
- all output properties

For comparison, this is what is displayed for notebook nodes:
- properly configured:
   ![image](https://user-images.githubusercontent.com/13068832/122100367-f3f46c00-cdc7-11eb-9756-4918de87f7e4.png)
- misconfigured  
   ![image](https://user-images.githubusercontent.com/13068832/122100476-17b7b200-cdc8-11eb-8545-ae55153d6596.png)

**To Reproduce**
1. Open VPE
2. Add [custom [KFP] component node](https://raw.githubusercontent.com/ptitzler/kfp-component-tests/main/example-2/component.yaml) to canvas (didn't check behavior for AA)

**Comment by marthacryan** [comment]
On my end, I'm seeing that nodes that don't have any required fields will have empty tooltips until a properties edit occurs and the properties values are copied into the `app_data`. Nodes with required fields will show error messages in the tooltip. My understanding is that this will need to be added to the pipeline-editor package in the NodeTooltip component, by checking the `current_parameters` field in addition to `app_data` when creating the tooltip content. @bourdakos1 Do you agree?

**Comment by bourdakos1** [comment]
I believe we only populate the tooltip with the properties explicitly defined in the pipeline. This means that any defaults or globally set properties won't show up in the tooltips. The `current_parameters` is used in the properties field to show the resolution of the defaults and node properties. However, the initial value of `current_parameters` is only the default value so we need to make sure we pull from both the pipeline data and `current_parameters`.

Implementation wise, I would add a getResolvedProperties function to the pipeline controller that pulls can pull from pipeline properties, node properties, and field default.

I think we should also add some sort of default label to the tooltip if there are no properties
