### ISSUE TITLE
Pipeline JSON Format Change - Version Next

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1773]
**Describe the issue**
These are some of the changes we might consider when bumping the pipeline version:

primary_pipeline[app_data][source] -> primary_pipeline[app_data][filename] -> Consistency with node format
"Notebooks" component id -> "notebook" component id

**Comment by bourdakos1** [comment]
For the next version bump I think we should move all the node properties from directly in app_data to a properties object inside of app_data.

from this:
```json
"app_data": {
  "filename": "load_data.ipynb",
  "runtime_image": "amancevice/pandas:1.0.3",
  "ui_data": {
    "label": "Load Data",
    "image": "data:image/xxx",
    "x_pos": 50,
    "y_pos": 100,
    "description": "Notebook file"
  }
}
```

to this:
```json
"app_data": {
  "properties": {
    "filename": "load_data.ipynb",
    "runtime_image": "amancevice/pandas:1.0.3"
  },
  "ui_data": {
    "label": "Load Data",
    "image": "data:image/xxx",
    "x_pos": 50,
    "y_pos": 100,
    "description": "Notebook file"
  }
}
```

**Comment by ptitzler** [comment]
`description` should  be a child of `properties` because it's not a UI property.

**Comment by bourdakos1** [comment]
@ptitzler label and description are required to be in ui_data by canvas. (This description is different than the user editable description)

**Comment by ptitzler** [comment]
Ah yes, okay. I thought this was was the user-provided value. Never mind.

**Comment by lresende** [comment]
@bourdakos1 suggestion is already being done as part of #1882
