### ISSUE TITLE
Validate 2.2/2.3 pipeline handling

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1783]
Create a pipeline that:
- Have at least three nodes
- Uses environment variables
- Include local file that is used by the node impl
- Produce a file that is used on a subsequent node impl
- Uses Notebook, Python Script, R Script nodes
- Use node content from another sibling folder

Verify that the following scenarios are handled as expected:

### create pipeline using v2.2.4

- [x] VPE: pipeline opens in generic VPE in 2.3
- [ ] VPE: pipeline requires upgrade to v2.3 (pipeline is explicitly saved as generic pipeline)
- [x] VPE: pipeline runs as expected locally
- [x] VPE: pipeline runs as expected on KF
- [x] VPE: pipeline runs as expected on AA
- [x] VPE: pipeline exports and runs as expected on KF
- [x] VPE: pipeline exports and runs as expected on AA
- [ ] CLI: 2.2.4 pipeline cannot be run without prior upgrade (behavior up for discussion)
- [ ] CLI: 2.2.4 pipeline cannot be submitted without prior upgrade (behavior up for discussion)

### create generic pipeline using v2.3.x

- [ ] 2.2.4 VPE: pipeline does not open in VPE (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be run (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be submitted (unsupported version)

### create KF pipeline using v2.3.x

- [ ] 2.2.4 VPE: pipeline does not open in VPE (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be run (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be submitted (unsupported version)

### create AA pipeline using v2.3.x

- [ ] 2.2.4 VPE: pipeline does not open in VPE (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be run (unsupported version)
- [ ] 2.2.4 CLI: pipeline cannot be submitted (unsupported version)

**Comment by karlaspuldaro** [comment]
In summary, the items without check mark didn't meet the expectations:
- A pipeline created in 2.2.4 can be accessed as generic in 2.3.0 editor, run/submitted from CLI, no upgrade request anywhere
- Any pipeline (generic, aa, kfp) created in 2.3.0 can be accessed in the 2.2.4 editor, in my tests, they all show as invalid for missing cpu/memory fields marked as required in previous version
- Any pipeline (generic, aa, kfp) created in 2.3.0 can be run/exported in 2.2.4 CLI

**Comment by ptitzler** [comment]
Most of these should pass once https://github.com/elyra-ai/elyra/issues/1748 was delivered. Not sure though wether the CLI (in 2.2.x and 2.3) perform version checks at all. A quick way to find out before a PR is merged is to edit a 2.3 `.pipeline` and manually increase the pipeline version identifier.
