### ISSUE TITLE
Pipeline editor looses changes when clicking outside node 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1798]
**To Reproduce**
1. Create pipeline
2. Add node configuration (e.g. file dependency **.py)
3. Click on the pipeline
4. Go back to node properties, properties are lost

**Comment by ajbozarth** [comment]
@lresende This is specific to string array properties where you click the `Add Item` button then type in a value. The value is not saved until you click `OK`, if we want to change this behavior to remove the `OK` and `Cancel` buttons we can, but I'm unsure if that's what we want
