### ISSUE TITLE
Pipeline Editor node properties too small on edit mode

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1799]
Open Pipeline Editor node properties, and see in view mode:
![image](https://user-images.githubusercontent.com/382917/122607245-205df180-d02f-11eb-9af7-378a4f7d3cf5.png)

When trying to edit "list based" fields, they become too small on edit mode
![image](https://user-images.githubusercontent.com/382917/122607313-3966a280-d02f-11eb-8673-abde62292996.png)

**Comment by karlaspuldaro** [comment]
Duplicate issue #1717
