### ISSUE TITLE
Pipeline Editor - Runtime specific components use cases

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1806]
## Runtime Specific component - Status Summary

Elyra v2.3 introduces experimental support for custom pipeline components for Kubeflow Pipelines and Apache Airflow. By supporting custom pipeline components, new user stories need to be taken into consideration for future development work. 

### Runtime Specific use cases

As a user, I want to

- Register a custom component in Elyra
     - Registration makes a component available in the pipeline editor.
     - Registration makes a component available for pipeline execution/export.
- Modify a component registration
     - This scenario accounts for the fact that component definitions might change over time. 
- Delete a component registration
     - A deleted component can no longer be utilized in the pipeline editor.  
- Utilize a built-in component registry (without having to install anything extra)
- Utilize shared component registries
    - A shared component registry can be accessed by many users. 
- Add a component node to a pipeline that comprises only custom components
- Add a component node to a pipeline that comprises custom components and Elyra components
- Run a pipeline that includes custom components
- Export a pipeline that includes custom components
- Work with pipelines that were created in a different Elyra deployment
  - Users A and B each use a separate installation (shared nothing) of Elyra    
  - User B wants to use a pipeline that user A created (but might not have the components registered, a different version, etc)
- Learn about components
     - How to manage them
     - How to use them in pipelines

### Current Status - Release 3.0.0
The expected level of support in Elyra 2.3/GA (not released yet). The following convention is used to describe the feature maturity: `not supported`, `experimental` (can be accomplished but not supported by GUI/CLI), `alpha` (somewhat supported by GUI/CLI), `beta` (mostly supported by GUI/CLI), and `stable` (supported by GUI/CLI). 

- Register a custom component in Elyra (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Modify a component registration (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Delete a component registration  (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Utilize a built-in component registry (**alpha**)
     - File based
- Utilize shared component registries  (**not supported**)
- Add a component-node to a pipeline that comprises only of custom components (**alpha**)
    - Main restriction: no data flow between components
- Add a component-node to a pipeline that comprises of custom components and Elyra  components (**alpha**)
    - Main restriction: no data flow between components
- Run a pipeline that includes custom components (**beta**)
- Export a pipeline that includes custom components (**not supported**)
- Work with pipelines containing custom components that were created in a different Elyra deployment (**experimental**)
   - Main restriction: pipeline dependencies must be added manually to the registry

**Legend**: The following convention is used to describe the feature maturity:
-  **not supported**, **experimental** (can be accomplished but not supported by GUI/CLI)
- **alpha** (somewhat supported by GUI/CLI)
- **beta** (mostly supported by GUI/CLI)
- **stable** (supported by GUI/CLI).

**Comment by ptitzler** [comment]
Expected level of support in Elyra 2.3/GA (not released yet). The following convention is used to describe the feature maturity: `not supported`, `experimental` (can be accomplished but not supported by GUI/CLI), `alpha` (somewhat supported by GUI/CLI), `beta` (mostly supported by GUI/CLI), and `stable` (supported by GUI/CLI). 

- Register a custom component in Elyra (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Modify a component registration (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Delete a component registration  (**experimental**)
     - Not supported through GUI/CLI
     - Manual task
- Utilize a built-in component registry (**alpha**)
     - File based
- Utilize shared component registries  (**not supported**)
- Add a component-node to a pipeline that comprises only of custom components (**alpha**)
    - TODO details
- Add a component-node to a pipeline that comprises of custom components and Elyra components (**not supported**)
- Run a pipeline that includes custom components (**beta**)
- Export a pipeline that includes custom components (**not supported**)
- Work with pipelines that were created in a different Elyra deployment (**not supported**)

**Comment by richdevboston** [comment]
So where are the user-contributed components discussed in the documentation????  

I cannot find a library anywhere.  Does that require a paid-subscription access to an IBM Cloud?

**Comment by ptitzler** [comment]
> So where are the user-contributed components discussed in the documentation????

Refer to the "pipeline components" topic in the user guide: https://elyra.readthedocs.io/en/latest/user_guide/pipeline-components.html

> I cannot find a library anywhere. Does that require a paid-subscription access to an IBM Cloud?

Elyra is 100% open source and therefore no subscription of any kind is required to access content or unlock any features. A few basic examples for Kubeflow Pipelines and Apache Airflow are linked to in above documentation topic.

**Comment by ptitzler** [comment]
Version 3.3+ should now fully support custom components. Refer to [this documentation topic](https://elyra.readthedocs.io/en/latest/user_guide/pipeline-components.html)
