### ISSUE TITLE
Can't scroll pipeline editor canvas

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1809]
**To Reproduce**
1. Create a pipeline and add multiple nodes
2. Reduce the window size so that nodes are out of the window
3. Can't scroll pipeline area

This is a blocker for large pipelines such as COVID or any other real production use case

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/382917/122970810-30cddf00-d343-11eb-8586-896074b61680.png)

**Comment by lresende** [comment]
@bourdakos1 FYI

**Comment by bourdakos1** [comment]
@lresende by scroll do you mean zoom scrolling? or panning?

**Comment by lresende** [comment]
Scrolling actually behaves differently on the canvas, click and move the canvas viewport instead of scrolling.
