### ISSUE TITLE
Node property side panel does not follow focus when opened in pipeline properties

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1827]
**Describe the issue**
Node property side panel does not follow focus when opened in pipeline properties

**To Reproduce**
1. Open pipeline with multiple nodes
2. Click on canvas (make sure no node selected)
3. Open property side panel (should open ok on a pipeline property)
4. Click on any (or different) nodes and the panel keeps on pipeline properties

**Comment by ajbozarth** [comment]
ah, this was an intentional choice, I can change it
