### ISSUE TITLE
CLI: Add  "describe pipeline" command

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1831]
**Is your feature request related to a problem? Please describe.**
Elyra recently introduced additional pipeline metadata that a CLI user likely has an interest in. Currently a user has to either use the VPE or browse the `.pipeline` file to access this information, which is not user friendly.

**Describe the solution you'd like**

```
$ elyra-pipeline describe <file.pipeline>
```

would display in a human readable format:
- the pipeline version
- the pipeline description (if defined)
- the pipeline type
- dependencies (e.g. list of custom components that are utilized)

```
$ elyra-pipeline describe --json <file.pipeline>

{
  "version": "4",
  "description": "pipeline description text",
  "type": "generic",
  ...
}
```

would return the same information in machine-readable JSON format. An easy way to test that the generated JSON can be consumed, run 

```
$ elyra-pipeline describe --json mypipeline.pipeline | jq .
```

Constraints:
 - Returns none zero return code if an error is encountered (e.g. no file specified, invalid file specified)

**Comment by 19690ao** [comment]
I'm interested in working on this issue
