### ISSUE TITLE
Integrate Pipeline CLI with new Validation framework

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1837]
**Describe the issue**
Integrate Pipeline CLI with new Validation framework

**Comment by akchinSTC** [comment]
@lresende - is this an umbrella for other issues that we might open or can this be closed by the mentioned merged PR?

**Comment by lresende** [comment]
Once the new validation service is in place, the cli should call it explicitly as it's not integrated with parsing anymore.
