### ISSUE TITLE
Pipeline Editor: Support global environment variables

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#1843]
**Is your feature request related to a problem? Please describe.**
I'm always replicating the same set of environment variables to all pipeline steps 

**Describe the solution you'd like**
A dialog where I can set environment variables which are then passed to all components with the ability to overwrite 
that value in the properties dialog of a component

**Describe alternatives you've considered**
Hacking the env variables into the container image

**Additional context**
For example I have a bucket for checkpointing configured in each component which is always the same - would be nice to specify 
that property globally in the scope of the pipeline and not of each component

See also : #1130 #1768

**Comment by ptitzler** [comment]
Requirements gathering: 
For node-level properties, environment variables are auto-detected for generic components (notebooks/scripts) and the list pre-populated in the properties view. Would you expect the same to happen at the pipeline level?

For example, assume a pipeline comprises of 3 notebooks, each one referencing environment variables. Should the list of environment variables in the pipeline properties display them all?

**Comment by romeokienzler** [comment]
Tnx everybody!
