### ISSUE TITLE
Support image pull secrets on the UI  and Runtime Images configurations file

### ISSUE THREAD

**Issue by andre-lx** [elyra-ai/elyra#1874]
Right now I can't define the imagePullSecrets of the Lambda pod that executes my code to download a custom image from a private repository, and I can only see the Image Pull Policy in the runtime configuration as described also in the docs:

https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html#image-pull-policy-pull-policy

![image](https://user-images.githubusercontent.com/44682155/124803995-b3fd5080-df51-11eb-995b-74adaff95704.png)

I am missing something or right now this is not possible?

Thank you

**Comment by ptitzler** [comment]
If you are referring to [this approach](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) then yes, this is not yet supported by Elyra. However , you might be able to use one of the other approaches listed on [the same page](https://kubernetes.io/docs/concepts/containers/images/) , e.g. `Add image pull secret to service account`, which are transparent.

**Comment by andre-lx** [comment]
That's what I thought @ptitzler.

Thanks for the quick response.

**Comment by ptitzler** [comment]
Support for Kubeflow Pipelines is delivered in https://github.com/elyra-ai/elyra/pull/2092
