### ISSUE TITLE
Add `best practices for custom components` topic to user guide

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1875]
**Is your feature request related to a problem? Please describe.**

The Visual Pipeline Editor exposes explicitly or implicitly defined component metadata in the UI. We need to document what the metadata is. Examples include
- for KFP, the `optional` tag
- for Airflow, embedded keywords that are interpreted

**Describe the solution you'd like**

New _Best practices for custom components_ topic to `User Guide`. 

**Additional context**
Similar to https://elyra.readthedocs.io/en/latest/user_guide/best-practices-file-based-nodes.html

**Comment by kiersten-stokes** [comment]
Component Parsing Heuristics as of 3.0.1 release.
# KFP
## YAML
### Component
- Name
  - Taken from YAML name field 
  - Defaults to None
    - **Potential action item**: run error check to ensure name is present
- Description
  - Taken from YAML description field
  - Whitespace characters such as `\n`, `\t`, `\r` removed and replaced with spaces
  - Defaults to empty string
### Parameters
NOTE: currently there is one parameter for each field in the inputs section of the YAML. **Action item**: include outputs and allow for data exchange (planned for 3.1.0)
- `id` (must be unique)
  - Name as given in 'name' field of parameter definition converted to lowercase and spaces replaced with underscores
  - **Action item**: ensure id is unique; in KFP, there will be cases where the input and output parameters will have the same name, and these must be distinguished in some way
- `name` (as it will appear in Properties tab)
  - Name as given in 'name' field of parameter definition
- `type`
  - Type as given in 'type' field of parameter definition
  - Then, runs a check to see if the parameter is of type inputPath
    - If yes, type is set to `file`
    - **Action item**: We will be changing how this is done in 3.1.x, as all KFP parameters should have the option to be either a file or a value
    - Then, converted to one of `string`, `number`, `boolean`, `dictionary`, `list`, or `file` depending on the parsed type (details below)
      - If the phrase `[blank1] of [blank2]s` is present in the parsed type, where `blank1` corresponds to `dictionary`, `dict`, `set`, `list`, `array` or `arr`, the new type is set as `dictionary` for `blank1`=`dictionary`/`dict` and `list` for `blank1`=`set`/`list`/`array`/`arr`
      - Otherwise,
        - If the word `string` is present in type info, the type is set to `string`
        - Else if `int`/`integer`/`number` is present in type info, the type is set to `number` 
        - Else if `bool`/`boolean` is in the type info, the type is set to boolean
        - Else if `dict`/`dictionary` is in the type info, the type is set to `dictionary`
        - Else if `set`/`list`/`array`/`arr` is in the type info, the type is set to `list`
        - Else if `file` is in type info, type is set to `file`
    - Defaults to `string` if no type is found
- `value`
  - Value as given in the 'default' field of parameter definition
  - Defaults to the corresponding falsy for whatever the type is
    - `string` --> empty string
    - `number` --> `0`
    - `boolean` --> `False`
    - `dictionary` --> empty string
    - `list` --> empty string
    - `file` --> empty string
- `description`
  - Description as given in 'description' field of parameter definition
  - Then converted to include the type exactly as parsed from the parameter definition type field in parenthesis after the given description of the format `[description] (type: [type as-parsed])`
  - Defaults to empty string if no description is found
- `control_id`
  - NOTE: This attribute is used to determine what type of input is allowed when accessing the "Node Properties" panel in the pipeline editor and how the user-entered values are sent to the backend for processing
  - Determined based on the standardized type (rules above)
    - `string` --> `StringControl` (provides a text box for user input)
    - `number` --> `NumberControl` (provides a small text vox for user input)
    - `boolean` --> `BooleanControl` (provides a checkbox for user input)
    - `dictionary` --> `StringControl`
       - On pipeline submit/export, the user-entered value for `dictionary` types is evaluated as a string, which will be converted to a proper `dict` format in the following case:
          - If the value entered starts and ends with curly braces (`{}`) **and** the value can be properly evaluated with `ast.literal_eval()`, a `dict` is returned
          - Else, the value used in component construction is the original user-entered string
    - `list` --> `StringControl`
       - On pipeline submit/export, the user-entered value for `list` types is sent as a string, which will be converted to a proper `list` format in the following case:
          - If the value entered starts and ends with square brackets (`[]`) **and** the value can be properly evaluated with `ast.literal_eval()`, a `list` is returned
          - Else, the value used in component construction is the original user-entered string
    - `file` --> `StringControl`
       - On pipeline submit/export, the KFP processor will look for the filepath, open the file, and send it's content as a value
  - Defaults to `StringControl`
- required
  - True if 'optional' field of parameter definition equates to `False` or if optional field isn't present
  - (in `ComponentParameter` init) Description also checked for certain phrases given below
    - If `not optional` is present, required is set to `True`
    - If `required` is present (and `not required` is not present and `n't required` is not present), required is set to `True`
  - Else, required set to `False`
## Python
Not yet supported. **Action item**: support Python KFP component definitions
# Airflow
### Component
Name is created using the following format: `id-from-component-catalog_ClassNameAsParsed`
This allows us to support operator specs that have multiple class (and hence operator) definitions when needed
Description is an empty string
**Action item**: introduce a regex to parse operator docstring for potential description
### Parameters
NOTE: currently there is one parameter for each init function arg
**Action item**: include args/kwargs and/or use some other method to support operator subclassing, etc.
- `id`
  - Parsed directly from init args for the component
  - Will necessarily be unique
- `name` (as it will appear in Properties tab)
  - Same as id
- `type`
  - Parsed from operator docstring using regex, looking for `:type [param_name]:`
  - If present, converted to one of `string`, `number`, `boolean`, `dictionary`, `list`, or `file` depending on the parsed type (details below)
    - If the phrase `[blank1] of [blank2]s` is present in the parsed type, where `blank1` corresponds to `dictionary`, `dict`, `set`, `list`, `array` or `arr`, the new type is set as `dictionary` for `blank1`=`dictionary`/`dict` and `list` for `blank1`=`set`/`list`/`array`/`arr`
    - Otherwise,
      - If the word `string` is present in type info, the type is set to `string`
      - Else if `int`/`integer`/`number` is present in type info, the type is set to `number`
      - Else if `bool`/`boolean` is in the type info, the type is set to boolean
      - Else if `dict`/`dictionary` is in the type info, the type is set to `dictionary`
      - Else if `set`/`list`/`array`/`arr` is in the type info, the type is set to `list`
      - Else if `file` is in type info, type is set to `file`
  - Defaults to `string` if no type is found
- `value`
  - Parsed from default assignments given with init argument
  - If present, run through `ast.literal_eval()` and newline characters replaced with spaces
  - Defaults to the corresponding falsy version for whatever the type is
    - `string` --> empty string
    - `number` --> `0`
    - `boolean` --> `False`
    - `dictionary` --> empty string
    - `list` --> empty string
    - `file` --> empty string
- `description`
  - Parsed from operator docstring using regex, looking for `:param [param_name]:`
    - If present, any instances of double quotes are replaced with single quotes to standardize in preparation for rendering properties using jinja template
  - Then converted to include the type exactly as parsed from the parameter definition type field in parenthesis after the given description of the format `[description] (type: [type as-parsed])`
  - Defaults to empty string if no description is found
- `control_id`
  - NOTE: This attribute is used to determine what type of input is allowed when accessing the "Node Properties" panel in the pipeline editor and how the user-entered values are sent to the backend for processing
  - Determined based on the standardized type (rules above)
    - `string` --> `StringControl` (provides a text box for user input)
       - On pipeline submit/export, the user-entered value for `string` types is run through `json.dumps()` in order to provide surounding quotation marks for correct rendering in the DAG
    - `number` --> `NumberControl` (provides a small text box for user input)
    - `boolean` --> `BooleanControl` (provides a checkbox for user inputs)
    - `dictionary` --> `StringControl`
       - On pipeline submit/export, the user-entered value for `dictionary` types is evaluated as a string, which will be converted to a proper `dict` format in the following case:
          - If the value entered starts and ends with curly braces (`{}`) **and** the value can be properly evaluated with `ast.literal_eval()`, a `dict` is returned
          - Else, the value used in component construction is the original user-entered string, run through `json.dumps()` as explained above for parameters with a `control_id` of `string`
    - `list` --> `StringControl`
       - On pipeline submit/export, the user-entered value for `list` types is sent as a string, which will be converted to a proper `list` format in the following case:
          - If the value entered starts and ends with square brackets (`[]`) **and** the value can be properly evaluated with `ast.literal_eval()`, a `list` is returned
          - Else, the value used in component construction is the original user-entered string, run through `json.dumps()` as explained above for parameters with a `control_id` of `string`
    - `file` --> `StringControl`
  - Defaults to `StringControl`
- `required`
  - (in `ComponentParameter` init) Description checked for certain phrases given below
    - If `not optional` is present, required is set to `True`
    - If `required` is present (and `not required` is not present and `n't required` is not present), required is set to `True`
  - Defaults to `False`
  - **Potential action item**: change to required for any that don't have a default assignment of `None` as their default value (or similar heuristic)

**Comment by ptitzler** [comment]
Documentation topic was created and basic information added: https://elyra.readthedocs.io/en/latest/user_guide/best-practices-custom-pipeline-components.html
