### ISSUE TITLE
Palette node categories should be defined by backend

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#1878]
Currently, the categories / all of the palette information outside of the node definitions is defined by the frontend (and is somewhat hard-coded), but this should be moved to the backend.

**Comment by kevin-bates** [comment]
Thanks @marthacryan.  Could you please provide a reference to the information that should come from the server that is presently hard-coded in the frontend?

**Comment by lresende** [comment]
Categories comes from the [palette](https://github.com/elyra-ai/elyra/blob/92541ca41b5c0606f91ae8deb81252ad6063f605/elyra/templates/components/canvas_palette_template.jinja2#L3) and this is another [example](https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/resources/palette.json).

**Comment by kevin-bates** [comment]
But the palette already comes from the server, so I'm confused about what the server needs to do/change.  Could you please be more specific?

**Comment by lresende** [comment]
We just need to have a way to send the proper category: e.g. change from Notebook to Generic Component and group the runtime specific components into one or more specific categories. These are being done, temporarily, in the front end today.

**Comment by kevin-bates** [comment]
I see.  Thanks.  So, today, each component is an entry in the `categories` list and this issue wants to introduce a "group" or "group-by" property associated with each component such that, for example, Notebook, Python Script, and R Script components are collected into a "Generic Components" group and custom KFP components are collected into a "Kubeflow Pipeline Components" group?

**Comment by ptitzler** [comment]
Yep. Once we have support for managing components the user should be able to define their own categories and add custom components to them.

**Comment by kevin-bates** [comment]
I guess the source of my confusion is that the palette.json **already** specifies a `categories` list where each entry is actually a **`component`**.  I'm afraid to ask this question, but will anyway...

Are we constrained to the use of a `categories` list in the palette.json?  

I'm assuming that's the case.  If not, we might consider renaming `categories` to `components` so that we can more easily tie implementation to functionality.

**Comment by kiersten-stokes** [comment]
The PR linked above will provide support for components to be assigned to multiple categories. Logic in `to_canvas_palette()` orders the components into their respective categories for rendering
