### ISSUE TITLE
Language server warnings

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1888]
**Describe the issue**
[Upstream issue](https://github.com/krassowski/jupyterlab-lsp/issues/640)

Latest release of `jupyterlab-lsp` (v3.8.0 + `jupyter-lsp` 1.4.0) introduces new server warnings, logged when running jupyterlab, in the format:
```
Failed to validate commands from language server spec finder `x-language-server`: [<ValidationError: "None is not of type 'string'">]
```
for some of  the language server specs [defined here](https://github.com/krassowski/jupyterlab-lsp/tree/master/python_packages/jupyter_lsp/jupyter_lsp/specs) (See full list below)
<details><summary>Command Line Output</summary>
<pre>
[W 2021-07-06 12:28:01.705 ServerApp] Failed to validate commands from language server spec finder `bash-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.705 ServerApp] Failed to validate commands from language server spec finder `dockerfile-language-server-nodejs`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.706 ServerApp] Failed to validate commands from language server spec finder `javascript-typescript-langserver`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.708 ServerApp] Failed to validate commands from language server spec finder `pyright`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.710 ServerApp] Failed to validate commands from language server spec finder `sql-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.712 ServerApp] Failed to validate commands from language server spec finder `unified-language-server`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.712 ServerApp] Failed to validate commands from language server spec finder `vscode-css-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.713 ServerApp] Failed to validate commands from language server spec finder `vscode-html-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.713 ServerApp] Failed to validate commands from language server spec finder `vscode-json-languageserver-bin`:
    [<ValidationError: "None is not of type 'string'">]
[W 2021-07-06 12:28:01.714 ServerApp] Failed to validate commands from language server spec finder `yaml-language-server`:
    [<ValidationError: "None is not of type 'string'">]</pre>
</details>

**To Reproduce**
1. Run jupyter lab with the `--debug` flag and watch for warning logs on terminal

**Expected behavior**
No warnings logged for missing language servers

**Context information**
 - Elyra version: 3.0.0-dev
 - Jupyterlab-lsp version: 3.8.0
 - Jupyter-lsp vresion: 1.4.0
 - Operating system: macOS

**Comment by karlaspuldaro** [comment]
Fixed in upstream by https://github.com/krassowski/jupyterlab-lsp/pull/645
Waiting for new package release before closing the issue here.

**Comment by akchinSTC** [comment]
Closing. Waiting for JL LSP release and this will get picked up
