### ISSUE TITLE
Error contacting server  Endpoint elyra/schema/code-snippets not found.

### ISSUE THREAD

**Issue by richdevboston** [elyra-ai/elyra#1899]
**Describe the issue**

After installing Elyra Snippets manager and rebuilding JupyterLab, I get the error message:

"Error contacting server 
Endpoint elyra/schema/code-snippets not found."

Whenever I click on the Elyra Snippets Tab the same error dialog box pops up and no snippets appear.  I cannot enter any snippets. 

A clear and concise description of what the issue is.

**To Reproduce**

1. Install Elyra Snippets manager from within JupyterLab Extensions Menu, then rebuild JupyterLab. 
2. I get the error message:

"Error contacting server 
Endpoint elyra/schema/code-snippets not found."

The following startup console messages indicate that JupyterLab itself starts up, and is properly configured: 

<details><summary>Log Output</summary>
<pre>
>jupyter lab
[I 2021-07-10 18:39:59.181 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-07-10 18:39:59.212 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance must be an int, but a value of None <class 'NoneType'> was specified.
[I 2021-07-10 18:39:59.884 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-07-10 18:39:59.884 LabApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\envs\webscrapers\lib\site-packages\jupyterlab
[I 2021-07-10 18:39:59.884 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\envs\webscrapers\share\jupyter\lab
[I 2021-07-10 18:39:59.884 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-07-10 18:39:59.884 ServerApp] Serving notebooks from local directory: c:\Users\richadmin
[I 2021-07-10 18:39:59.884 ServerApp] Jupyter Server 1.8.0 is running at:
[I 2021-07-10 18:39:59.884 ServerApp] http://localhost:8888/lab?token=c54e8171d8328578f2c9721f2799e2a82e1b3fa4ce27ec61
[I 2021-07-10 18:39:59.900 ServerApp]     http://127.0.0.1:8888/lab?token=c54e8171d8328578f2c9721f2799e2a82e1b3fa4ce27ec61
[I 2021-07-10 18:39:59.900 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-07-10 18:39:59.916 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/richadmin/AppData/Roaming/jupyter/runtime/jpserver-24272-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=c54e8171d8328578f2c9721f2799e2a82e1b3fa4ce27ec61
        http://127.0.0.1:8888/lab?token=c54e8171d8328578f2c9721f2799e2a82e1b3fa4ce27ec61
[I 2021-07-10 18:40:08.104 LabApp] Build is up to date
[W 2021-07-10 18:40:08.289 ServerApp] 404 GET /elyra/schema/code-snippets?1625956806929 (127.0.0.1) 25.77ms referer=http://localhost:8888/lab
[I 2021-07-10 18:40:10.302 ServerApp] Kernel started: 51058106-2c92-47ba-b078-ac53b08fc790
|[I 2021-07-10 18:40:15.459 ServerApp] Kernel started: 9f7ac74a-d3d0-4af2-9428-5114a86bc0e0
[I 2021-07-10 18:40:15.498 ServerApp] Kernel started: bcadda21-1419-4b34-b825-2484d862ce54
/[W 2021-07-10 18:40:18.720 ServerApp] Got events for closed stream None</pre>
</details>

**Expected behavior**

NO ERRORS.  

**Deployment information**
Describe what you've deployed and how:
 - Elyra version:   WHERE IS THIS DISPLAYED ??   HOW DO I GET THIS INFORMATION?  IT IS NOT IN THE EXTENSION INTERFACE.
 - Operating system: Windows 10
 - Installation source: conda 
 - Deployment type: local installation

**Comment by lresende** [comment]
Could you try the following:
- find the Elyra version with 'pip list | grep -i elyra' 
Then:
- 'pip3 install -upgrade elyra-server==version'

**Comment by ptitzler** [comment]
The output from the verification commands listed in https://elyra.readthedocs.io/en/stable/getting_started/installation.html#verify-installation would also be helpful.
