### ISSUE TITLE
How to add extensions to a docker image and make it persistent?

### ISSUE THREAD

**Issue by sierxue** [elyra-ai/elyra#1900]
My system is Ubuntu 20.04.

First, I use command `docker run -it -p 8888:8888 -v ${HOME}/opensource/jupyter-notebooks/:/home/jovyan/work -w /home/jovyan/work elyra/elyra:dev jupyter lab --debug` to run docker image. Then I install jupyterlab_vim extension, and it works.

But when I restart the docker image with the same command, the jupyterlab_vim disappears. How do I make it persistent?

**Comment by sierxue** [comment]
I've revised Dockerfile in link [https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra](url) by adding `RUN python3 -m pip install jupyterlab_vim && jupyter lab build`, and then build a new image. Finally, it works.

**Comment by ptitzler** [comment]
Your solution is the right approach! Any changes you make in the running container in directories other than `/home/jovyan/work` (this includes `pip install`ing packages) are discarded.

**Comment by sierxue** [comment]
@ptitzler, I greatly appreciate your confirmation!
