### ISSUE TITLE
Pipeline validation reports missing system properties for custom components

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1901]
**Describe the issue**
A clear and concise description of what the issue is.
![missing](https://user-images.githubusercontent.com/13068832/125319296-7bfa6280-e2ef-11eb-9bcd-d697e19e7ddf.gif)

**To Reproduce**
1. Create typed pipeline
2. Open palette
3. Double click on palette entry

**Comment by lresende** [comment]
Fixed by Pipeline Editor 0.10.3
