### ISSUE TITLE
Add parameters for components and pipelines

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1903]
**Is your feature request related to a problem? Please describe.**
KFP pipelines allow to add parameters to components, for example:
````
# Writing bigger data
@func_to_container_op
def repeat_line(line: str, output_text_path: OutputPath(str), count: int = 10):
    '''Repeat the line specified number of times'''
    with open(output_text_path, 'w') as writer:
        for i in range(count):
            writer.write(line + '\n')


# Reading bigger data
@func_to_container_op
def print_text(text_path: InputPath()): # The "text" input is untyped so that any data can be printed
    '''Print text'''
    with open(text_path, 'r') as reader:
        for line in reader:
            print(line, end = '')

def print_repeating_lines_pipeline():
    repeat_lines_task = repeat_line(line='Hello', count=5000)
    print_text(repeat_lines_task.output) # Don't forget .output 
````

It would be great to add similar to Elyra as config parameters

Additionally KFP allows to pass parameters to pipeline itself

````
def caching_pipeline(seconds: float = 60):
    # All outputs of successfull executions are cached
    work_task = do_work_op(seconds)
````

Adding this capability to Elyra will be great as well.

**Comment by ptitzler** [comment]
Reference: https://www.kubeflow.org/docs/components/pipelines/sdk/python-function-components/

**Comment by ptitzler** [comment]
I created https://github.com/elyra-ai/elyra/issues/1920 to reduce the scope of this feature request.  Python function-based components are not yet supported.

**Comment by ptitzler** [comment]
Delivered in https://github.com/elyra-ai/elyra/pull/3053 and https://github.com/elyra-ai/elyra/pull/3001
