### ISSUE TITLE
Add pipeline level env variables

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1904]
**Is your feature request related to a problem? Please describe.**
As described here https://github.com/kubeflow/kfp-tekton/tree/master/sdk#big-data-passing-workspace-configuration, some of the pipeline generation behaviour is defined by env variable, for example:

````
export DEFAULT_ACCESSMODES=ReadWriteMany
export DEFAULT_STORAGE_SIZE=2Gi
````` 
These should be added not to the individual components, but rather to a pipeline as a whole.
At the moment this is not supported.

**Comment by ptitzler** [comment]
Duplicate of https://github.com/elyra-ai/elyra/issues/1843

**Comment by lresende** [comment]
Sorry @blublinsky, I didn't notice the other one for the env vars.
