### ISSUE TITLE
Add ability to add custom Kubeflow components to pallete

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#1905]
**Is your feature request related to a problem? Please describe.**

At the moment there is no support for adding custom kubeflow components  through the editor UI. It would be nice to add this support

**Comment by ptitzler** [comment]
Duplicate of https://github.com/elyra-ai/elyra/issues/1880. Refer to https://github.com/elyra-ai/elyra/discussions/1881 for a temporary manual solution.
