### ISSUE TITLE
Pipeline format potential issues

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1907]
I think we have too much info duplicated across the pipeline file.

For example runtime: 
- `app_data.ui_data.runtime.display_name`
- `app_data.runtime`
- `app_data.properties.runtime`

I think that anything we keep in `ui_data` should safely be deleted and re-generated by the client. This isn't the case for runtime, if deleted it turns the pipeline into a generic pipeline.

both of the pipeline properties `name` and `runtime` seem redundant. 
- `name` is updated when the pipeline is renamed, but only when the pipeline is closed and then reopened. 
- `runtime` never changes and seems completely unused, the "runtime" in the properties editor is the runtime from `ui_data`

sample empty KFP pipeline for reference:
```json
{
  "doc_type": "pipeline",
  "version": "3.0",
  "json_schema": "http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json",
  "id": "elyra-auto-generated-pipeline",
  "primary_pipeline": "primary",
  "pipelines": [
    {
      "id": "primary",
      "nodes": [],
      "app_data": {
        "ui_data": {
          "runtime": {
            "display_name": "Kubeflow Pipelines"
          },
          "comments": []
        },
        "version": 3,
        "runtime": "kfp",
        "properties": {
          "name": "untitled66",
          "runtime": "Kubeflow Pipelines"
        }
      },
      "runtime_ref": ""
    }
  ],
  "schemas": []
}
```

**Comment by lresende** [comment]
the only one that should matter is `app_data.runtime`
