### ISSUE TITLE
Airflow runtime components are showing runtime image as text field

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1912]
**Describe the issue**
Airflow runtime components are showing runtime image as text field instead of allowing user to select from configured runtime images.

![image](https://user-images.githubusercontent.com/382917/125523798-d7910968-6088-4425-9406-68799a943178.png)

If we are showing the `runtime image` field, we should show it as a drop-down list as in the generic components.

**Comment by kiersten-stokes** [comment]
After discussion with @akchinSTC, we are going to remove the runtime image property altogether for Airflow operators. A similar change has already been made in #1882 to remove what we currently call "runtime-specific properties" in the component parsers. This includes the readonly runtime image property that is displayed for KFP (among others).

None of the Airflow operators that currently come pre-included will be affected by this change. Further, this will enable support for additional operators (e.g. the `DockerOperator` and `KubernetesPodOperator`) that define their own `image` property that would collide with or duplicate "our" runtime image property.

One thing that we will have to revisit is what to do when users want to include an operator that subclasses another for which `image` is required (although this problem isn't exclusive to `image`). A potential workaround could be including `*args` and `**kwargs` property fields, which we have discussed incorporating in the past. Further change could include upstream Airflow changes that adds some layer of metadata to an operator that would make parsing for this sort of thing much cleaner.
