### ISSUE TITLE
Remove excess pipeline information from pipeline file

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1914]
**Describe the issue**
When creating a new kfp or airflow (not generic) pipeline, the file created contains component schema information that is not needed. 

**To Reproduce**
1. create a new pipeline either kfp or airflow
2. drag a new pipeline specific component from the palette
3. save pipeline
4. open the pipeline file as raw

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/13340013/125538709-570a050a-03b6-49e3-a848-214633aee0cc.png)

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.0dev
 - Operating system: macos
 - Installation source: master

**Comment by lresende** [comment]
The component source needs to be relative. Please check.

**Comment by akchinSTC** [comment]
Closing issue due to resolution in new releases (3.1+)
