### ISSUE TITLE
Multiple dialogs sometime open when migrating a pipeline

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#1924]
**Describe the issue**
Sometime the migrate pipeline dialog is opened multiple times. This is a UX issue only since the functionality is still only run once, the extra dialogs only confuse the user and don't affect the pipeline migration.

**To Reproduce**
1. Open a pipeline created with an older pipeline version
2. The migrate pipeline dialog will open, click a button 
3. A migrate pipeline dialog will still be open. If you selected migrate button the migration will have happened behind the dialog. If you selected cancel then the pipeline will already be closed. 
4. If you click migrate again nothing happens, but if you click cancel it will try to close the pipeline and you would be prompted to save.

**Expected behavior**
The migrate dialog should only show once and no second dialog should be seen once a choice is made

**Comment by ajbozarth** [comment]
Afaik the `onError` function that handles the migration prompt is being called multiple times in `pipeline-editor`. This is most likely because it is called within this `useEffect` https://github.com/elyra-ai/pipeline-editor/blob/f1360ee09f424cf13ca1609ff67663468e01a5ee/packages/pipeline-editor/src/PipelineEditor/index.tsx#L211 which is most likely being triggered more than once.

**Comment by karlaspuldaro** [comment]
Would this be related to #863 ?

**Comment by bourdakos1** [comment]
You need to wrap `onError` in `useCallback` to memoize it, otherwise `onError` will be a new variable every render which can cause unnecessary `useEffect` re-runs

**Comment by ajbozarth** [comment]
> You need to wrap onError in useCallback to memoize it, otherwise onError will be a new variable every render which can cause unnecessary useEffect re-runs

Ah that makes sense, I'll fix this once I'm done writing the tests for https://github.com/elyra-ai/pipeline-editor/pull/147

**Comment by ajbozarth** [comment]
After some research and discussion with @bourdakos1 this is a symptom of a larger issue that will require a refactor of a lot of our hooks. So we will address this in 3.1 instead. Specifically the use of SWR is causing a lot of hooks to be run over and over when it isn't necessary, one symptom of which is that the update of runtimeImages from unknown to it's actual value via SWR updates pipeline which reruns open, which errors again and opens a migrate dialog even though one is already open.

**Comment by kevin-bates** [comment]
> So we will address this in 3.1 instead. 

This seems significant.  I'm assuming you meant `3.0.1` based on the milestone update.

> Specifically the use of SWR is causing a lot of hooks to be run over and over when it isn't necessary

What is `SWR` and was its use introduced only in 3.0?

Besides the update of runtime images and since those are general metadata instances, does this issue apply to all metadata editor operations?  I.e., should we enumerate all affected areas?

**Comment by bourdakos1** [comment]
> Besides the update of runtime images and since those are general metadata instances, does this issue apply to all metadata editor operations? I.e., should we enumerate all affected areas?

@kevin-bates I believe this is only affecting the pipeline editor extension at the moment.

To clear things up a bit, SWR itself isn't exactly the issue, it's more that our PipelineEditor Widget isn't equipped to handle dynamic data yet. We need to refactor some of our current logic/assumptions so that it is more robust to these types of data changes

**Comment by kevin-bates** [comment]
Thanks @bourdakos1 - that helps a lot.  And [`SWR`](https://swr.vercel.app/) is a strategy for data fetching apparently (and sounds interesting).
