### ISSUE TITLE
Incorrect property type being inferred from airflow operator

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1926]
**Describe the issue**
See : https://raw.githubusercontent.com/apache/airflow/1.10.15/airflow/operators/http_operator.py

Traced the issue to headers param is defaulted to None with no type hints available. Our component parser looks like it resolves in the following order: type hint in init method followed by type in docstring. In this special case, the type is a sentence describing the parameter, resulting in falling back to a default of `string`. 

**To Reproduce**
1. create a new airflow pipeline file in VSE
2. open palette and drag the http_operator
3. look at the properties, see `header` as type string and not dict

**Screenshots or log output**

**Expected behavior**
The parser should parse the operator constructor types correctly but given this special case and lack of typing, it will be difficult to fix without upstream changes or hosting of the operator ourselves

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Operating system: [e.g. macos, linux]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Local execution
 - Kubeflow Pipelines (provide version number, whether multi-user auth enabled)
 - Apache Airflow (provide version number)
 
**Runtime configuration settings**
If the issue is related to pipeline execution, document the runtime configuration settings from the Elyra UI, omitting confidential information.

**Comment by kevin-bates** [comment]
Yuck.  Do the same issues exist for the `data`, `response_check`, and `extra_options` parameters as well?

**Comment by akchinSTC** [comment]
data - yes
response_check - yes, tricky one as this is suppose to be a lambda or other function
extra_options yes
