### ISSUE TITLE
Pipeline Editor : right click -> "open file" does not work

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1931]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create pipeline
2. Add generic node
3. Right click on node and select "open file". Nothing happens.
5. Double click on file. It opens as expected.

![right-click](https://user-images.githubusercontent.com/13068832/126190803-2191f8ce-80b4-4539-bf06-f97a869dc424.gif)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by karlaspuldaro** [comment]
I just pulled the latest master and wasn't able to recreate this issue, opening file from the menu works a expected. 
Tried a new generic pipeline as well as existing ones.
I wonder if this has to do with the file path, it worked for me adding node from files on a sibling directory to the pipeline. How did you add your node?

**Comment by ptitzler** [comment]
Drag and drop 

![1931](https://user-images.githubusercontent.com/13068832/126221558-4003d7c8-9525-407a-8550-03fc9c5cb57d.gif)

**Comment by ptitzler** [comment]
<details><summary>browser console output</summary>
<pre>
serverconnection.js:207 GET http://localhost:8888/api/contents/load_data.ipynb?content=0&1626725845697 404 (Not Found)
handleRequest @ serverconnection.js:207
makeRequest @ serverconnection.js:77
get @ index.js:507
get @ index.js:200
execute @ index.js:324
CommandRegistry.execute @ index.es6.js:372
(anonymous) @ PipelineEditorWidget.tsx:884
(anonymous) @ index.js:1
value @ common-canvas.js:42
value @ common-canvas.js:42
value @ common-canvas.js:42
value @ common-canvas.js:18
value @ common-canvas.js:18
k @ common-canvas.js:18
r.handleClick @ common-canvas.js:18
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Show 4 more frames
serverconnection.js:88 Uncaught (in promise) Error: No such file or directory: load_data.ipynb
    at Function.create (serverconnection.js:107)
    at async Drive.get (index.js:509)
</pre>
</details>

**Comment by lresende** [comment]
If associated artifact can't be found we should give the user a proper error message.

**Comment by karlaspuldaro** [comment]
Ok it seems like there's an issue with the pipeline path. In my previous test cases the pipelines created in the root dir work as expected. I was only able to reproduce it when creating pipelines in subdirectories.
