### ISSUE TITLE
Enable JSON viewer for .pipeline files

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1943]
**Is your feature request related to a problem? Please describe.**

Currently `.pipeline` files can only be opened in the VPE or the plain text editor from the File Browser context menu:

![image](https://user-images.githubusercontent.com/13068832/126681843-4898e41e-697c-4085-97f6-61ac22eba2ec.png)

**Describe the solution you'd like**

Enable the JSON viewer (like it is for Jupyter notebooks) to make it easier to browse the file:
![image](https://user-images.githubusercontent.com/13068832/126681712-46de380a-5229-4f9e-aff4-9517e18aee72.png)

**Comment by akchinSTC** [comment]
@ajbozarth - thoughts?

**Comment by ajbozarth** [comment]
As I mentioned in the dev meeting I took a swing at addressing this sometime last year and actually spent some time on it. 

The options that are show in the context menu are determined by the widget factories. When a widget factory is created it lists the file types that it supports, which would then list that widget as an option in the context menu for that file type. In this case the JSON extension in core creates the factory and sets the file types (json and notebook). File types are separately defined in the doc registry. In pipeline-editor-extension we add the pipeline file type for `.pipeline` files and the `PipelineEditorFactory` is created with the pipeline file type listed. 

To add pipeline files to the JSON factory we would need to add it in core JL. If `.pipeline` was a standard format we might be able to do that (`geojson` file type is also supported), but it is not a standard format so I would expect such a PR would be rejected.

Another option would be to "override" the JSON factory by removing it and then adding an extension that "extends" it ourselves with the pipeline file type support, but the JSON editor does not seem easily extendable to do so.

As my extensive work on this is well over a year old things might have changed on the JL core side that would more easily allow this feature add though if someone else wants to take the time to look into it again.

**Comment by ajbozarth** [comment]
Leaving a note here, it seems the Doc Registry can now be extended, so we "may" be able to implement the "override" idea at the docRegistry level instead. Not sure if it would be useful but I'll make note of this here https://github.com/jupyterlab/jupyterlab/pull/10256

**Comment by ajbozarth** [comment]
IIUC https://github.com/jupyterlab/jupyterlab/pull/11540 has added support for this. Once that is released we'll be able to add this support. As such moving this to the 4.0 sprint (with the assumption that it will be release in lab 4)

**Comment by ajbozarth** [comment]
Once https://github.com/elyra-ai/elyra/pull/2495 is merged this should be pretty trial for me to fix
