### ISSUE TITLE
unable to run a pipeline on Kubeflow pipeline server 1.6

### ISSUE THREAD

**Issue by jazzsir** [elyra-ai/elyra#1951]
**Describe the issue**
A clear and concise description of what the issue is.

I know kfp 1.3 is compatible, but I would like to run with kfp 1.6(kubeflow 1.3) where a notebook contains a token for pipeline server through [projected volume](https://github.com/kubeflow/pipelines/issues/5138#issuecomment-797003710) and Kubeflow pipeline server doesn't accept ID/PW authentication anymore.
It seems like Elyra can't use the token for user authentication instead of ID/PW.

**To Reproduce**
2. Click on 'Run Pipeline'

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
<img width="998" alt="Screen Shot 2021-07-23 at 11 02 44 PM" src="https://user-images.githubusercontent.com/4714923/126794042-70272fe6-a885-44d6-985d-e7348fffb15b.png">
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [2.2.1]
 - Operating system: [linux]
 - Installation source: [official container image]
 - Deployment type: [Kubeflow [notebook server]]
 - Kubeflow pipeline version: 1.6

**Comment by ptitzler** [comment]
The referenced approach appears to be only applicable for deployments where JupyterLab/Elyra runs in a pod on Kubernetes alongside Kubeflow. To support this
- Elyra would have to  have awareness of its runtime environment (e.g. "Kubernetes") 
- a special type of KFP configuration ("in-cluster") would need to be introduced that is only supported in certain environments

**Comment by jazzsir** [comment]
I have a workaround without UI changes.
We can find out the token injected by projected volume from `ML_PIPELINE_SA_TOKEN_PATH` env.
Then, let's do this.

```
if `ML_PIPELINE_SA_TOKEN_PATH` environment variable exists
    use the token
else
    use existing code
```
This code worked find and I would like to submit PR.

**Comment by thesuperzapper** [comment]
For those watching, I have raised some important issues (which I am currently working on) related to Kubeflow Pipelines authentication in Elyra:
- https://github.com/elyra-ai/elyra/issues/2106
- https://github.com/elyra-ai/elyra/issues/2107

**Comment by ptitzler** [comment]
Elyra version 3.3 should now support the feature. Refer to [the updated documentation for details](https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html#kubeflow-authentication-type-auth-type)
