### ISSUE TITLE
VPE: "Open File" for custom component should display the definition or be disabled

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1953]
**Describe the issue**

![image](https://user-images.githubusercontent.com/13068832/126837692-dc0e7c01-42aa-4119-99c1-b9edf018bdf4.png)

**To Reproduce**
1. Create RTS pipeline
2. Add a custom component to canvas
3. Open node's context and observe behavior after selecting "Open File"

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
- Option is either disabled for custom component
- Or launches a viewer for for component definition (YAML file or .py file for AA)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by ptitzler** [comment]
This appears to be a regression. See screen capture in https://github.com/elyra-ai/elyra/issues/1845, which rendered this as disabled

**Comment by ptitzler** [comment]
Still reproducible using 3.0/master pulled on 7/29.

**Comment by karlaspuldaro** [comment]
Need to update pipeline-editor to v0.11.3

**Comment by ptitzler** [comment]
@lresende
