### ISSUE TITLE
Invalid component catalog entry is loaded

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1954]
**Describe the issue**
```
Invalid location for component: download-file -> https://raw.githubusercontent.com/ptitzler/kfp-component-tests/main/component_definitions/download-file/component.yaml (HTTP code 404)
```

![image](https://user-images.githubusercontent.com/13068832/126838919-0e06f43d-f5ae-4a55-99fb-33d2c9074fc5.png)

**To Reproduce**
1. Add a custom component to the catalog that points to an invalid URL
2. Rebuild JL/Elyra
3. Start Elyra and check log
4. Create rts pipeline
5. Open palette; note the component is listed and can be added

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by kiersten-stokes** [comment]
Ah I swear I fixed this before! Maybe something got lost in a merge somewhere. I'll check it out

**Comment by ptitzler** [comment]
In hindsight I think this is a bit more complicated to recreate. Somehow a catalog entry overwrote another.
