### ISSUE TITLE
Custom KFP component labels are not used to name steps

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1963]
**Describe the issue**
A clear and concise description of what the issue is.

Node labels in Elyra were introduced to provide users with the ability to assign KFP steps / AA tasks a more meaningful value than the default component/operation name.

It appears that for KFP the user-specified value is currently not used, as shown in this pipeline, comprising two nodes, each of which is implemented by the same `filter text` component:

![image](https://user-images.githubusercontent.com/13068832/127052790-a090aa79-7109-4276-a71b-bac4d6e9535d.png)

Generated graph:

![image](https://user-images.githubusercontent.com/13068832/127052629-53e84ae8-b881-4b03-a97f-f91fce22a4c8.png)

**To Reproduce**
1. Create a KFP pipeline
2. Add the same custom component to the pipeline twice, assigning a custom label to each node instance.
3. Run the pipeline and observe the generated graph.

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by kiersten-stokes** [comment]
Looks like this should be fairly easy to implement! Luckily, KFP DSL provides a `set_display_name()` function for the `ContainerOp` object that we create during pipeline processing
