### ISSUE TITLE
missing 'Default' value in custom KFP component can cause pipeline execution to fail

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1964]
**Describe the issue**
I ran into this why trying out https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/resources/kfp/filter_text_using_shell_and_grep/component.yaml. 

Note that https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/resources/kfp/filter_text_using_shell_and_grep/component.yaml#L20 defines a default value:
```
- {name: Pattern, optional: true, default: '.*', description: 'Regex pattern'}
```

It's not totally clear to me from the [KFP documentation](https://www.kubeflow.org/docs/components/pipelines/sdk/component-development/#define-your-components-interface) which entity is supposed to supply the default value: kubeflow pipelines? the component implementation? (for the component I've been using the implementation does not handle this!)

Irrespective of what the component does, it appears that the VPE does not always apply the default value

![image](https://user-images.githubusercontent.com/13068832/127056546-eb0e292b-5e65-41c0-a5fd-94f9084baeac.png)

 resulting in a pipeline execution failure:

![image](https://user-images.githubusercontent.com/13068832/127055314-d40420af-85ba-4bfa-953f-db00960705df.png)

**To Reproduce**

![no_default](https://user-images.githubusercontent.com/13068832/127057657-66470d5e-7f74-49c9-9e64-3902461fd16b.gif)

(Not visible in the screen recording that the user saved the pipeline file before openeing it in the JupyterLab text editor)

**Expected behavior**
The default value is persisted in the pipeline file

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by ptitzler** [comment]
Easiest way to recreate is to use the example files that were added by  https://github.com/elyra-ai/examples/pull/59

**Comment by bourdakos1** [comment]
This is a bug in the `pipeline-editor` package. When an input is blurred it replaces empty with the default value artificially shows up when it shouldnt
