### ISSUE TITLE
Add support for JupyterLab 3.1

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1975]
Describe list of affecting areas:
- [ ] CSS Selectors [#1973 ]

**Comment by akchinSTC** [comment]
do we need to explicitly bump or pin any dependencies?

**Comment by lresende** [comment]
@bourdakos1 with #1973 do we need anything else to support Lab 3.1?

**Comment by bourdakos1** [comment]
Nope, just some css selectors changed

**Comment by akchinSTC** [comment]
@ajbozarth - can you add a comment here about the change log items you've tested and close this issue if the testing is complete ?

**Comment by ajbozarth** [comment]
I read through the 3.1 changeling and checked that any updated that may affect Elyra do not. Didn't find any new bugs, but did open https://github.com/elyra-ai/elyra/issues/2001 as a future issue
