### ISSUE TITLE
Update Apache Airflow helm chart example to disable unneeded redis component

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1978]
**Describe the issue**
Current apache helm-chart lists redis as installation enabled but is not actually required when using the kubernetes executor, we should update to false.
https://github.com/elyra-ai/elyra/blob/dcb63e72c12f7e143ca5262f2140a3387f8abd10/etc/kubernetes/airflow/helm/values.yaml#L1420-L1427

**To Reproduce**

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Operating system: [e.g. macos, linux]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]

**Comment by bug-developer021** [comment]
Hi @akchinSTC  ! Could you give the `airflow Chart  Version` that you used ?  I used the latest 8.4.1  with this [config](https://github.com/elyra-ai/elyra/blob/v2.2.x/etc/kubernetes/airflow/helm/values.yaml) .

When I submit the [airflow hello world pipelines](https://github.com/elyra-ai/examples/tree/v2.2.x/pipelines/hello_world_apache_airflow) to airflow runtimes , I  can't see any dags in the airflow web , but the information from jupyterlab  show that submission was succeeded

![jupyterlab](https://user-images.githubusercontent.com/80243243/127722160-c65eb143-8c1d-4df9-8adb-ea261ed5854c.png)


I can see dag files was pushed to github, result files was uploaded to minio. But nothing in the airflow web and no pod was running on the kubernetes.

![airflow-web](https://user-images.githubusercontent.com/80243243/127721815-0c46c7b9-f8bb-4c66-9b3d-ea34d04a05a8.png)


## Environment
- Kubernetes  [1.20.5]
- elyra [2.2.4]

**Comment by bug-developer021** [comment]
I  moved the `hello-world.py` dag from github to `/opt/airflow/dags` and run it, the web shows the dag prepared to run

![screenshot-airflow](https://user-images.githubusercontent.com/80243243/127840511-2b1f6b93-6697-4211-aa90-63f86e3db1d4.png)

I describe the pod, and get the information 
```
Failed to pull image "dummy_image": rpc error: code = Unknown desc = Error response from daemon: pull access denied for dummy_image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
``` 
It seems airflow pod lanuch a pod from `/opt/airflow/pod_templates/pod_template.yaml`

**Comment by bug-developer021** [comment]
Hi! @ptitzler, the dag file  is shown below. It did use the `amancevice/pandas:1.1.1` image

```python
dag = DAG(
    "hello_world-0802074058",
    default_args=args,
    schedule_interval="@once",
    start_date=days_ago(1),
    description="Created with Elyra 2.2.4 pipeline editor using hello_world.pipeline.",
    is_paused_upon_creation=False,
)


notebook_op_d3a109f8_85f7_4bcd_945d_85aa6e69b22e = NotebookOp(
    name="load_data",
    namespace="airflow",
    task_id="load_data",
    notebook="airflow/examples/pipelines/hello_world_apache_airflow/load_data.ipynb",
    cos_endpoint="http://XXXXXX:32000",
    cos_bucket="airflow",
    cos_directory="hello_world-0802074058",
    cos_dependencies_archive="load_data-d3a109f8-85f7-4bcd-945d-85aa6e69b22e.tar.gz",
    pipeline_outputs=["data/noaa-weather-data-jfk-airport/jfk_weather.csv"],
    pipeline_inputs=[],
    image="amancevice/pandas:1.1.1",
    in_cluster=True,
    env_vars={
        "AWS_ACCESS_KEY_ID": "XXXXXXXXXXXXXXX",
        "AWS_SECRET_ACCESS_KEY": "XXXXXXXXXXXXXXXX",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
        "DATASET_URL": "https://dax-cdn.cdn.appdomain.cloud/dax-fashion-mnist/1.0.2/fashion-mnist.tar.gz",
    },
    config_file="None",
    dag=dag,
)

notebook_op_d3a109f8_85f7_4bcd_945d_85aa6e69b22e.image_pull_policy = "IfNotPresent"


notebook_op_0bf32af7_1ce4_41cc_9bdf_051e2bc46d0f = NotebookOp(
    name="Part_1___Data_Cleaning",
    namespace="airflow",
    task_id="Part_1___Data_Cleaning",
    notebook="airflow/examples/pipelines/hello_world_apache_airflow/Part 1 - Data Cleaning.ipynb",
    cos_endpoint="http://XXXXXX:32000",
    cos_bucket="airflow",
    cos_directory="hello_world-0802074058",
    cos_dependencies_archive="Part 1 - Data Cleaning-0bf32af7-1ce4-41cc-9bdf-051e2bc46d0f.tar.gz",
    pipeline_outputs=["data/noaa-weather-data-jfk-airport/jfk_weather_cleaned.csv"],
    pipeline_inputs=["data/noaa-weather-data-jfk-airport/jfk_weather.csv"],
    image="amancevice/pandas:1.1.1",
    in_cluster=True,
    env_vars={
        "AWS_ACCESS_KEY_ID": "XXXXXXXXXXXXXXXXX",
        "AWS_SECRET_ACCESS_KEY": "XXXXXXXXXXXXXXXXXXXXX",
        "ELYRA_ENABLE_PIPELINE_INFO": "True",
    },
    config_file="None",
    dag=dag,
)

notebook_op_0bf32af7_1ce4_41cc_9bdf_051e2bc46d0f.image_pull_policy = "IfNotPresent"

(
    notebook_op_0bf32af7_1ce4_41cc_9bdf_051e2bc46d0f
    << notebook_op_d3a109f8_85f7_4bcd_945d_85aa6e69b22e
)
```

**Comment by bug-developer021** [comment]
Problem solved when I change ther `airflow-stable/airflow` Chart version to `7.16.0`.
