### ISSUE TITLE
Paste copied node at location you click paste

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#198]
In pipeline editor you can copy and paste whole nodes including their properties, but similar to how drag drop used to work the pasted nodes will node be added where the user rights-clicks and selects paste. We should see if we can solve this.

**Comment by ajbozarth** [comment]
@marthacryan the blocking canvas issue for this was just merged. We should put this back into our queue to fix, I can tackle it  next sprint if you want

**Comment by karlaspuldaro** [comment]
Closing this issue as it's no longer reproducible. The node is pasted where user clicks paste.
Elyra version tested: v2.3.0-dev
