### ISSUE TITLE
Document check-install

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1994]
As proposed in #1980 [PR comment](https://github.com/elyra-ai/elyra/pull/1980#discussion_r679331217), it would be useful to expose the command `make check-install`  to the user.
Currently it is called as the last step of a full `make install` in order to output which jupyter extensions (server/lab) are installed and enabled.

**Describe the solution you'd like**
Add `check-install` to be listed under `make` command

**Describe alternatives you've considered**

Discussion topics: 
- If we expose this command, should it be renamed?
- Do we formally document it, maybe grouping the topics in [Verify Installation](https://elyra.readthedocs.io/en/latest/getting_started/installation.html?highlight=labextension#verify-installation) into a single command?

**Comment by akchinSTC** [comment]
@lresende - can you remind me again why we didnt want to expose this in the makefile?
