### ISSUE TITLE
Dependencies not set as list for notebooks/scripts that are run as pipeline causes validation failure

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2014]
**Describe the issue**
Dependencies aren't being evaluated properly on `Run as pipeline` from notebook or script (any runtime). I think the value of `dependencies` in the pipeline JSON is being treated as a list, but it is being sent as a string.

**To Reproduce**
1. Open a notebook or script
2. Click on `Run as pipeline`
3. Submit with `Include file dependencies` box checked (in log output below, the default value of `*.py` is what was entered as the value here)

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Error Message</summary>
<pre>
{
  "severity": 1,
  "source": "Elyra Pipeline Validation Service",
  "type": "invalidFilePath",
  "message": "Property has an invalid path to a file/dir or the file/dir does not exist",
  "data": {
    "nodeID": "17226d56-5b20-4c13-a660-5455c6272cd9",
    "nodeName": "basic.ipynb",
    "propertyName": "dependencies",
    "value": "/Users/kierstenstokes/repos/elyra/p"
  }
}
{
  "severity": 1,
  "source": "Elyra Pipeline Validation Service",
  "type": "invalidFilePath",
  "message": "Property has an invalid path to a file/dir or the file/dir does not exist",
  "data": {
    "nodeID": "17226d56-5b20-4c13-a660-5455c6272cd9",
    "nodeName": "basic.ipynb",
    "propertyName": "dependencies",
    "value": "/Users/kierstenstokes/repos/elyra/y"
  }
}
</pre>
</details>

<details><summary>Debug Log Output</summary>
<pre>
[D 2021-08-04 12:24:17.609 ServerApp] Pipeline SchedulerHandler now executing post request
[D 2021-08-04 12:24:17.609 ServerApp] JSON payload: {'doc_type': 'pipeline', 'version': '3.0', 'json_schema': 'http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json', 'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'primary_pipeline': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'pipelines': [{'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodes': [{'id': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'type': 'execution_node', 'op': 'execute-notebook-node', 'app_data': {'component_parameters': {'filename': 'examples/basic.ipynb', 'runtime_image': 'continuumio/anaconda3:2020.07', 'outputs': [], 'env_vars': [], 'dependencies': '*.py', 'include_subdirectories': False, 'cpu': '', 'gpu': '', 'memory': ''}, 'ui_data': {'label': 'basic.ipynb'}}}], 'app_data': {'name': 'basic', 'runtime': 'kfp', 'runtime-config': 'kfp_cloning', 'version': 4, 'ui_data': {'comments': []}, 'source': 'basic.ipynb'}}], 'schemas': []}
[D 2021-08-04 12:24:17.620 ServerApp] Validation checks completed. Results as follows: {'title': 'Elyra Pipeline Diagnostics', 'description': 'Issues discovered when parsing the pipeline', 'issues': [{'severity': 1, 'source': 'Elyra Pipeline Validation Service', 'type': 'invalidFilePath', 'message': 'Property has an invalid path to a file/dir or the file/dir does not exist', 'data': {'nodeID': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodeName': 'basic.ipynb', 'propertyName': 'dependencies', 'value': '/Users/kierstenstokes/repos/elyra/examples/p'}}, {'severity': 1, 'source': 'Elyra Pipeline Validation Service', 'type': 'invalidFilePath', 'message': 'Property has an invalid path to a file/dir or the file/dir does not exist', 'data': {'nodeID': '08e97edd-8fa7-4978-8958-fa7f46ab183c', 'nodeName': 'basic.ipynb', 'propertyName': 'dependencies', 'value': '/Users/kierstenstokes/repos/elyra/examples/y'}}]}
[W 2021-08-04 12:24:17.621 ServerApp] 400 POST /elyra/pipeline/schedule?1628097857604 (::1) 12.52ms referer=http://localhost:8888/lab/tree/examples/basic.ipynb</pre>
</details>

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.0.rc4

**Comment by lresende** [comment]
> Dependencies aren't being evaluated properly on `Run as pipeline` from notebook or script (any runtime). I think the value of `dependencies` in the pipeline JSON is being treated as a list, when it is really a string.

Not sure I understand this above. The idea about dependencies is that you can specify a list of files that should be made available into the runtime while executing the node.

When I run a pipeline from pipeline editor, the value seems to be properly set as list:
```
'id': '10da9752-fcf6-48c3-a04a-1f3591bca592',
			'type': 'execution_node',
			'op': 'execute-python-node',
			'app_data': {
				'label': 'setup.py',
				'component_parameters': {
					'filename': 'elyra-pipelines-examples/producer-consumer/scripts/setup.py',
					'runtime_image': 'elyra/elyra-example-anaconda-py3:latest',
					'include_subdirectories': False,
					'outputs': [],
					'env_vars': [],
					'dependencies': ['setup.txt']
				},
```

So, I believe the issue might actually be that the "submit as pipeline" is not setting it as a list? Rather than an issue on the validation side? 

@akchinSTC @ajbozarth

**Comment by kiersten-stokes** [comment]
@lresende @akchinSTC yes, I think you're right. Below is the payload for submitting a notebook/script as pipeline

```
{
   "doc_type":"pipeline",
   "version":"3.0",
   "json_schema":"http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json",
   "id":"08e97edd-8fa7-4978-8958-fa7f46ab183c",
   "primary_pipeline":"08e97edd-8fa7-4978-8958-fa7f46ab183c",
   "pipelines":[
      {
         "id":"08e97edd-8fa7-4978-8958-fa7f46ab183c",
         "nodes":[
            {
               "id":"08e97edd-8fa7-4978-8958-fa7f46ab183c",
               "type":"execution_node",
               "op":"execute-notebook-node",
               "app_data":{
                  "component_parameters":{
                     "filename":"examples/basic.ipynb",
                     "runtime_image":"continuumio/anaconda3:2020.07",
                     "outputs":[
                        
                     ],
                     "env_vars":[
                        
                     ],
                     "dependencies":"*.py",
                     "include_subdirectories":false,
                     "cpu":"",
                     "gpu":"",
                     "memory":""
                  },
                  "ui_data":{
                     "label":"basic.ipynb"
                  }
               }
            }
         ],
         "app_data":{
            "name":"basic",
            "runtime":"kfp",
            "runtime-config":"kfp_cloning",
            "version":4,
            "ui_data":{
               "comments":[
                  
               ]
            },
            "source":"basic.ipynb"
         }
      }
   ],
   "schemas":[
      
   ]
}
```
