### ISSUE TITLE
Double-click on a node should expand properties view (not opening the notebook)

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2017]
**Is your feature request related to a problem? Please describe.**
All other low-code/no-code tools open the properties view when a node is double-clicked - Elyra opens the notebook

**Describe the solution you'd like**
Either:
Expand the properties view on a double-click and move functionality to open the notebook to the context menu

Or:
Expand the properties view on a double-click and add functionality to open the notebook to an icon inside the node

**Describe alternatives you've considered**
No alternative - working with Elyra when coming from other tools gives a little odd experience

**Additional context**
Related to #467 and #479

**Comment by ptitzler** [comment]
@bourdakos1 also suggested this a while ago.

**Comment by bourdakos1** [comment]
We have the `pipeline-editor` built so opening properties vs notebook file is toggle-able. We will probably introduce this as a user setting as to not disrupt the current expected user experience. More info here: https://github.com/elyra-ai/pipeline-editor/issues/92

**Comment by ptitzler** [comment]
https://github.com/elyra-ai/elyra/pull/2517 will add support to customize the double click behavior. (You'll have to change the default to switch to the desired behavior you are looking for.)

**Comment by romeokienzler** [comment]
@ptitzler thanks u made my day!
