### ISSUE TITLE
Adding a code snippet into a script editor does not trigger language check

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#2018]
**Describe the issue**
Regression - Adding a code snippet into a script editor does not trigger language check. 
It still works as expected on notebooks.

After a quick investigation, looks like the widget class names are being mapped to something else during runtime, so [this statement](https://github.com/elyra-ai/elyra/blob/db8f0db786b580cfa2080bd788fc1df11dd8ad3e/packages/code-snippet/src/CodeSnippetWidget.tsx#L126) that checks for script editor is never true.

**To Reproduce**
1. Open a Python or R Editor
2. Open the code snippets tab
4. Click the insert button on the snippet item (Make sure to pick a code snippet of a language different from the open editor)
5. Notice the snippet is automatically added to the editor without displaying a warning dialog

**Expected behavior**
Language check should be triggered and display a warning when there is a language mismatch when inserting a code snippet into a script editor

**Context information**:
 - Elyra version: 3.0.0
 - Operating system: macos
 - Browser: Chrome

**Comment by karlaspuldaro** [comment]
Closing as it was no longer reproducible. Works as expected in v3.2.0-dev.

**Comment by kiersten-stokes** [comment]
Just as an FYI, I am still able to reproduce this issue using `pip install` as of 3.3.0 rc0. Dev environment works as expected
