### ISSUE TITLE
Filter text example pipeline fails to execute

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2024]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Git clone git clone git@github.com:elyra-ai/examples.git into your JL workspace
2. Open JL
3. In the file browser navigate to `pipelines/kubeflow_pipelines_component_examples/filter_file_component/`
4. Create a KFP RTC
5. Open the `.pipeline` file and run it

**Expected behavior**
The pipeline executes successfully.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0
 - Operating system: [e.g. macos, linux]
 - Installation source: PyPI

**Comment by kiersten-stokes** [comment]
For some context, this is part of a current limitation related to relative paths for executing runtime-specific components. For component parameters of type `file`, the frontend does not currently calculate the path relative to the JL root directory (or `notebook-dir`). As a result, the backend won't find the relevant file when it is processing and constructing the custom component and execution of the pipeline will therefore fail.

The workaround right now would be to start JupyterLab from `examples/pipelines/kubeflow_pipelines_component_examples/filter_file_component/`, but this is obviously unacceptable in the long term. A potential solution is detailed in #1991

**Comment by akchinSTC** [comment]
A "proper" fix for this would require #1991.  As such this issue and issue #2025 may need to be deferred until 3.1.0

Workarounds in no particular preference or order:
1. Editing the pipeline file that contains the component and modify the `data` component parameter field to include the absolute path to the file required.
2. Modifying the properties pane to allow for manual input of an absolute path to the `data` file, similar to what the `dependencies` field has (in appearance, not in function)
![image](https://user-images.githubusercontent.com/13340013/129262580-2af571ee-0fe9-4369-bf01-918e50830adb.png)
![image](https://user-images.githubusercontent.com/13340013/129263070-60a98e7e-8c71-4032-9563-97629a854dc8.png)
3. Adding a symlink to the `data` file in the users workspace root directory. e.g.
`/[JL starting directory]/[symlink to data file]`
this symlink would contain the relative path to the data file needed and be identically named.

thoughts? @lresende @ptitzler

**Comment by ptitzler** [comment]
The original intent was to provide examples that work as is, to the extend possible, without the need for any modification. Since the proposed workarounds all require manual user intervention and additional instructions, we might as well [update the README](https://github.com/elyra-ai/examples/tree/master/pipelines/kubeflow_pipelines_component_examples/filter_file_component) to indicate that (for the time being)  with instructions on how to run the pipeline in light of this limitation.

**Comment by lresende** [comment]
If I understood this correctly, I would say we need to fix the issue related to relative paths. Updating the readme or anything else is more like a workaround to get the sample to work and will fail when you move to other machines/git checkout which was why we created the relative path solution, to begin with.
