### ISSUE TITLE
Run notebook example pipeline fails to execute

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2025]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. `git clone git@github.com:elyra-ai/examples.git` into your JL workspace
2. Open JL
3. In the file browser navigate to `pipelines/kubeflow_pipelines_component_examples/run_notebook_component/`
4. Create a KFP RTC
5. Open the `.pipeline` file and run it

**Expected behavior**
The pipeline executes successfully.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0
 - Operating system: [e.g. macos, linux]
 - Installation source: PyPI

**Comment by ptitzler** [comment]
See https://github.com/elyra-ai/elyra/issues/1967, which exhibited the same symptom and was supposedly fixed by https://github.com/elyra-ai/elyra/pull/1983

**Comment by kiersten-stokes** [comment]
As taken from the related #2024:
> For some context, this is part of a current limitation related to relative paths for executing runtime-specific components. For component parameters of type `file`, the frontend does not currently calculate the path relative to the JL root directory (or `notebook-dir`). As a result, the backend won't find the relevant file when it is processing and constructing the custom component and execution of the pipeline will therefore fail.

The workaround right now would be to start JupyterLab from `examples/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/`, but this is obviously unacceptable in the long term. A potential solution is detailed in #1991
