### ISSUE TITLE
Improve requirements for elyra wheel

### ISSUE THREAD

**Issue by casassg** [elyra-ai/elyra#2036]
**Is your feature request related to a problem? Please describe.**

As a user, I want to use Elyra w other systems and dependencies. However, currently Elyra adds a lot of dependencies even when I don't necessarily need them to use the parts that I need. This makes it hard to use Elyra as I quite often may run into dependency conflicts.

This is made even worse in the case of monorepos where third party management must be done in a lock step release. As users who want to use Elyra will get stuck in old versions of dependencies, unless Elyra is upgraded.

**Describe the solution you'd like**

Break up install_requires into multiple extra _require instead so that as a user, I can explicitly say what part of Elyra I need to be installed w the wheel.

**Comment by ptitzler** [comment]
A good start would be to do this for the `kfp-tekton` dependency, which enables support for the Tekton backend in Kubeflow Pipelines.

Doing so would require (based on initial discussions in https://github.com/elyra-ai/elyra/pull/2034):
- updates to `setup.py`
- addition of defensive code that checks whether the `kfp-tekton` package is installed and handles impacted user scenarios gracefully (e.g. disallow use of KFP runtime configurations that are configured for Tekton)
- updates to several documentation topics (e.g. [install](https://elyra.readthedocs.io/en/stable/getting_started/installation.html), [runtime configuration](https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html)) 
- updates to the [repository readme](https://github.com/elyra-ai/elyra/blob/master/README.md)
