### ISSUE TITLE
Error registering processor "EntryPoint('kfp' ... - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2049]
**Describe the issue**

During startup Elyra raises the following error if an KFP component specification does not define any inputs:

```
Error registering processor "EntryPoint('kfp', 'elyra.pipeline.processor_kfp', 'KfpPipelineProcessor', Distribution('elyra', '3.1.0.dev0'))" - 'NoneType' object is not iterable
```

**To Reproduce**
1. Create a KFP component specification that does not define any input parameters
2. Add component to registry
3. Start JL
4. See error in console
5. Open KFP pipeline editor
  
![image](https://user-images.githubusercontent.com/13068832/129639688-befaef78-a866-4222-be9f-5204ca81d65a.png)

**Expected behavior**
Component specifications without any inputs are treated as valid.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master

**Comment by kevin-bates** [comment]
@ptitzler - could you please provide a component definition that leads to this issue?

**Comment by ptitzler** [comment]
https://github.com/ptitzler/kfp-component-tests/tree/main/component_definitions/requirement-examples/kfp-components/0-n
