### ISSUE TITLE
elyra-pipeline CLI does not report any warning messages

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2060]
**Describe the issue**
A clear and concise description of what the issue is.

If I interpret https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/validate.py#L509 correctly, the following pipeline should produce a warning:

![image](https://user-images.githubusercontent.com/13068832/129944140-c58f7c0e-967d-458d-a02b-418624fef3f0.png)

However, the CLI does not display any warning message(s)

**To Reproduce**

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]
 - Operating system: [e.g. macos, linux]

**Comment by ptitzler** [comment]
Possibly the same issue surfaces in the VPE. I tried to trigger https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/validate.py#L445 by creating a label (1k+ chars) but neither the CLI nor the VPE surface it.

**Comment by kevin-bates** [comment]
Hmm - I wonder if you're using a slightly different version of master than myself.  I see the following warnings:

```
$ elyra-pipeline submit --runtime-config kf_cloning1 elyra/my_pipeline/isolated-nodes.pipeline 

────────────────────────────────────────────────────────────────
 Elyra Pipeline Submission
────────────────────────────────────────────────────────────────

- (Warning) - Property value has exceeded the max length allowed ({label_name_max_length}). This value may be truncated by the runtime service
- (Warning) - Property value contains invalid characters. Invalid characters may be replaced by the runtime service. Node labels must start with lower case alphanumeric and contain only lower case alphanumeric, underscores, dots and dashes
- (Warning) - This node is not connected to any part of the pipeline
- (Warning) - This node is not connected to any part of the pipeline

❯ Job submission succeeded
  Check the status of your job at: http://cloning1.fyre.ibm.com:32352/pipeline/#/runs/details/c18fd910-dceb-44f6-b379-8a9c888362b1
  The results and outputs are in the /kbates/isolated-nodes-0818135158 
  working directory in http://cloning1.fyre.ibm.com:31467


────────────────────────────────────────────────────────────────
 Elyra Pipeline Submission Complete
────────────────────────────────────────────────────────────────
```

That said, there are  some issues...
1. The max-length violation warning is not denoted as an `f-string`, resulting in the templated value for the max length.
2. I believe we should, whenever possible, display contextual information in the message itself.  Things like "node name", "property name" and "property value" should be present in the message.  I understand these are supplied as "data" to the validation response, but that information would be valuable in the message text itself.

Given the messages above, I think something like the following would be helpful...
```
- (Warning) - The node label ('this-is-a-really-long-filename_that-is-more-than-63-characters-long.ipynb') has exceeded the max length allowed (63). This value may be truncated by the runtime service
- (Warning) - The node label ('this-is-a-really-long-filename_that-is-more-than-63-characters-long.ipynb') contains invalid characters. Invalid characters may be replaced by the runtime service. Node labels must start with lower case alphanumeric and contain only lower case alphanumeric, underscores, dots and dashes.
- (Warning) - This node ('this-is-a-really-long-filename_that-is-more-than-63-characters-long.ipynb') is not connected to any part of pipeline 'isolated-nodes'
- (Warning) - This node ('this-is-a_short_node_label') is not connected to any part of pipeline 'isolated-nodes'
```

We could consider truncated max length values or placing values at the end of the message as well.

Here's the corresponding pipeline file (appended with `.txt`):
[isolated-nodes.pipeline.txt](https://github.com/elyra-ai/elyra/files/7010178/isolated-nodes.pipeline.txt)

**Comment by kevin-bates** [comment]
While troubleshooting this issue, I noticed that the validation gives precedence to the label value stored in `['app_data']['ui_data']['label']` when `['app_data']['ui_data']` exists and, if not present, only then falls back to validating `['app_data']['label']` - which I thought was correct.

However, the UI gives precedence to `['app_data']['label']` over `['app_data']['ui_data']['label']` because I see the shorter value persisted in `['app_data']['label']` displayed in the UI when `['app_data']['ui_data']['label']` contains a longer (and invalid) value.

**Comment by ptitzler** [comment]
>  if you're using a slightly different version of master than myself.

I did another rebuild and now the CLI output does include warning messages. Not sure what happened.

> I believe we should, whenever possible, display contextual information in the message itself.

I believe it would be okay to not include the contextual information in the raw _validation message_ if the renderer (CLI/VPE) produces output does expose the information. Example/CLI:

```
 - [Warning] Node "XYZ": <validation message> 
```

Also note that formatting of warning messages is different from error messages.

We should also consider the scenario where a user might want to not run a pipeline that triggers warning messages, as they might indicate issues that prevent the pipeline run from completing successfully.

**Comment by ptitzler** [comment]
Will re-open should the problem re-appear
