### ISSUE TITLE
Incompatible versions for kfp and kfp-notebook when building Elyra 3.0.1 docker images

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2061]
**Describe the issue**
Incompatible versions for kfp and kfp-notebook when building Elyra 3.0.1 docker images

```
#10 23.03 conda 4.9.2 requires ruamel_yaml>=0.11.14, which is not installed.
#10 23.03 kfp-tekton 0.8.1 requires kfp==1.6.3, but you'll have kfp 1.7.1 which is incompatible.
```

**Comment by lresende** [comment]
FYI @casassg

**Comment by lresende** [comment]
just tried this with published docker image, and although the warning during install, the image works ok and can submit pipelines to the KFP server.

**Comment by casassg** [comment]
What pip version are you using for the image building? pip >=20 should pick this up and install kfp 1.6.3

**Comment by DavidSpek** [comment]
I'm guessing pip downgraded kfp to 1.6.3.

**Comment by ptitzler** [comment]
I don't think there's anything that we can do about this 
- until `kfp-tekton` relaxes its requirements OR
- https://github.com/elyra-ai/elyra/pull/2043 is delivered and it is decided to also publish Elyra container images that don't install this extra; see
   - https://github.com/elyra-ai/elyra/tree/master/etc/docker/kubeflow
   - https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra

**Comment by akchinSTC** [comment]
blocked due to https://github.com/elyra-ai/elyra/pull/2043

**Comment by casassg** [comment]
#2043 should be unblocked now!
