### ISSUE TITLE
ERROR after running make install-server

### ISSUE THREAD

**Issue by 19690ao** [elyra-ai/elyra#2065]
**Describe the issue**
There's an ERROR related to the version of pyflakes displayed after running `make install-server`.
```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
flake8 3.8.4 requires pyflakes<2.3.0,>=2.2.0, but you'll have pyflakes 2.3.1 which is incompatible.
```
Everything still seems to work as intended (ie. local updates to the CLI work as intended), but I would think this shouldn't be happening.

**To Reproduce**
Run `make install-server` in the command line.

**Deployment information**
 - Operating system: Linux

**Comment by ptitzler** [comment]
No longer reported in 3.7+
