### ISSUE TITLE
run local pipeline demo has error 

### ISSUE THREAD

**Issue by HGladiator** [elyra-ai/elyra#2073]
os: win10
python:3.7.10
elyra:3.0.1

subprocess.CalledProcessError: Command '['python3', 'E:\\Code\\Elyra_examples/pipelines/setup_validation/python_script.py', '--PYTHONHOME', 'E:\\Code\\Elyra_examples/pipelines/setup_validation']' returned non-zero exit status 9009.

pls help me! thx!

**Comment by ptitzler** [comment]
Transferred issue to the main repo, since this appears to be a setup problem.

**Comment by ptitzler** [comment]
Can you please
- Confirm whether you tried to run a custom pipeline - not any of the existing examples?
- If you've used your own pipeline, could you please share the `.pipeline` file? The path to the Python script `E:\Code\Elyra_examples/test/print_version.py` appears to be invalid - it should not contain any forward slashes. Did you start JupyterLab in `E:\Code\Elyra_examples`  and created `print_version.py` in the `test` subdirectory? I don't have access to a Windows environment to confirm whether this generally works as expected. It's possible that somehow OS specific path handling is used somewhere in the Elyra code that we'd need to locate and fix.
- Confirm that python3 is in your PATH

**Comment by ptitzler** [comment]
> Possible bug: https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_local.py#L291 sets PYTHONHOME to the script's directory location, which doesn't seem right. Perhaps the intention was to set PYTHONPATH?

@lresende @kevin-bates

**Comment by kevin-bates** [comment]
I looked at this when you last at-ed me and agree that this is doesn't seem right.  I will need to defer to @lresende who authored that portion of things.  I suspect this was done in order to make files in the local directory available, but prepending the current `PYTHONPATH` with the script directory is likely the better way to go.

I wasn't aware envs could be added to the `python` command as options like that (and it doesn't appear to work).  Here's a little script that dumps the value of `PYTHONHOME` using `print(f"PYTHONHOME: {os.getenv('PYTHONHOME')}")`. I don't currently have `PYTHONHOME` set in my environment...
```bash
$ echo $PYTHONHOME

$ python abc_test.py --PYTHONHOME=/tmp
PYTHONHOME: None
```

**Comment by ptitzler** [comment]
You are right. I missed the obvious problem. Since the current approach does not work and nobody ever reported an issue with respect to module load issues, should we just remove the [no-op] flag and not set any `PYTHON*` variable(s) in the subprocess?

**Comment by kevin-bates** [comment]
> Since the current approach does not work and nobody ever reported an issue with respect to module load issues, should we just remove the [no-op] flag and not set any PYTHON* variable(s) in the subprocess?

I think so - at least until we hear (and demonstrate) otherwise.

**Comment by kiersten-stokes** [comment]
> Since the current approach does not work and nobody ever reported an issue with respect to module load issues, should we just remove the [no-op] flag and not set any `PYTHON*` variable(s) in the subprocess?
>> I think so - at least until we hear (and demonstrate) otherwise.


I can open a one-liner PR for this in a bit

**Comment by ptitzler** [comment]
... or add to https://github.com/elyra-ai/elyra/pull/2077, which already addresses a subset of the problems that were identified in this issues

**Comment by kevin-bates** [comment]
I agree, just piggyback on #2077.  Thanks!

**Comment by lresende** [comment]
@HGladiator do you still see any issues on a Windows environment? I gave it a quick try using 3.1.0 and it seems to be working ok for the example pipeline.

**Comment by HGladiator** [comment]
remove python3.exe, 
and try example pipeline using 3.1.0 , here is run success! 

You all so excellent and efficient !

**Comment by ptitzler** [comment]
Glad to hear! Closing this issue because all TODO's listed in https://github.com/elyra-ai/elyra/issues/2073#issuecomment-906218034 were addressed in https://github.com/elyra-ai/elyra/pull/2077 and delivered in version 3.1.0. Thanks again for helping us to improve our support for Windows!
