### ISSUE TITLE
Conflicting algorithm is used to calculate pipeline name 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2088]
**Describe the issue**
A conflicting algorithm is used to calculate pipeline name 

Some code/tests are looking for it at
```
pipeline_definitions['pipelines'][0]['app_data'].pop('name')
```

But pipelines are using it as:
```
pipeline_definitions['pipelines'][0]['app_data']['properties'].pop('name')
```

**Comment by bourdakos1** [comment]
@lresende the pipeline-editor package doesn't make use of the pipeline name field, but the elyra extension sets it here: https://github.com/elyra-ai/elyra/blob/a31afee97c716feacec1b43feee66b119de71397/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L258

```ts
pipelineJson.pipelines[0].app_data.properties.name = pipeline_name;
```
