### ISSUE TITLE
elyra-pipeline describe doesn't report pipeline type properly for empty pipelines

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2095]
**Describe the issue**

This surfaces an issue that might also exist elsewhere. The root cause is that the VPE does not set certain `app_data.properties` in the base (empty) `.pipeline` file.

**To Reproduce**
1. Create an empty generic pipeline (Launcher > generic pipeline tile > close VPE)
2. Create an empty kfp pipeline (Launcher > kfp pipeline tile > close VPE)
3. Create an empty airflow pipeline (Launcher > airflow pipeline tile > close VPE)
4. Run `elyra-pipeline describe` for each one of the pipelines and inspect the output
5. Also note that the pipeline name cannot be reported because it wasn't persisted by the VPE.

```
$ elyra-pipeline describe untitled1.pipeline
Name: None
Description: None
Type: None
Version: 4
Nodes: 0
File Dependencies:
    None Listed

$ elyra-pipeline describe untitled2.pipeline
Name: None
Description: None
Type: None
Version: 4
Nodes: 0
File Dependencies:
    None Listed

$ elyra-pipeline describe untitled3.pipeline
Name: None
Description: None
Type: None
Version: 4
Nodes: 0
File Dependencies:
    None Listed


```

**Expected behavior**
The proper pipeline type is displayed.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.1+/master

**Comment by akchinSTC** [comment]
Waiting for #2082
