### ISSUE TITLE
Refactor KFP pipeline "code" generation to produce KFP Python DSL

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2097]
**Is your feature request related to a problem? Please describe.**
https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_kfp.py#L403 produces output that does not look like vanilla KFP Python DSL code, as documented [here](https://www.kubeflow.org/docs/components/pipelines/sdk/sdk-overview/). 

**Describe the solution you'd like**
Produce KFP Python DSL code that KFP developers are familiar with, not something that seems to be undocumented.

**Comment by akchinSTC** [comment]
Closed by #2301
