### ISSUE TITLE
The startup page does not display properly

### ISSUE THREAD

**Issue by caexy** [elyra-ai/elyra#2105]
**Describe the issue**
Jupyter-lab could not display the Launcher correctly, the entire startup page is blank.
**To Reproduce**
1. Go straight to Jupyter Lab
2. See error

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
PS C:\Users\DELL> jupyter lab build
[LabBuildApp] JupyterLab 3.1.10
[LabBuildApp] Building in C:\Users\DELL\AppData\Roaming\Python\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
PS C:\Users\DELL> jupyter-lab
C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\jupyter_server\transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[I 2021-09-07 02:08:50.353 ServerApp] elyra | extension was successfully linked.
[I 2021-09-07 02:08:50.353 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2021-09-07 02:08:50.353 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2021-09-07 02:08:50.369 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2021-09-07 02:08:50.369 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-09-07 02:08:50.369 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2021-09-07 02:08:50.369 ServerApp] jupytext | extension was successfully linked.
[W 2021-09-07 02:08:50.384 NotebookApp] 'root_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-09-07 02:08:50.384 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-09-07 02:08:50.384 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-09-07 02:08:50.384 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-09-07 02:08:50.384 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-09-07 02:08:50.384 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[I 2021-09-07 02:08:50.384 ServerApp] nbdime | extension was successfully linked.
[W 2021-09-07 02:08:50.400 ServerApp] WARNING: The Jupyter server is listening on all IP addresses and not using encryption. This is not recommended.
[I 2021-09-07 02:08:50.619 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-09-07 02:08:50.650 ServerApp] Registering processor "EntryPoint('airflow', 'elyra.pipeline.processor_airflow', 'AirflowPipelineProcessor', Distribution('elyra', '2.2.4'))" with type -> airflow
[I 2021-09-07 02:08:50.650 ServerApp] Registering processor "EntryPoint('kfp', 'elyra.pipeline.processor_kfp', 'KfpPipelineProcessor', Distribution('elyra', '2.2.4'))" with type -> kfp
[I 2021-09-07 02:08:50.650 ServerApp] Registering processor "EntryPoint('local', 'elyra.pipeline.processor_local', 'LocalPipelineProcessor', Distribution('elyra', '2.2.4'))" with type -> local
[I 2021-09-07 02:08:50.650 ServerApp] elyra | extension was successfully loaded.
C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\jupyter_server\transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[I 2021-09-07 02:08:50.713 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, r-languageserver, sql-language-server, texlab, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2021-09-07 02:08:50.886 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2021-09-07 02:08:50.886 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2021-09-07 02:08:50.886 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2021-09-07 02:08:50.886 LabApp] JupyterLab extension loaded from C:\Users\DELL\AppData\Roaming\Python\Python38\site-packages\jupyterlab
[I 2021-09-07 02:08:50.886 LabApp] JupyterLab application directory is C:\Users\DELL\AppData\Roaming\Python\share\jupyter\lab
[I 2021-09-07 02:08:50.886 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-09-07 02:08:50.886 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2021-09-07 02:08:50.886 ServerApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 2021-09-07 02:08:50.886 ServerApp] jupytext | extension was successfully loaded.
[I 2021-09-07 02:08:51.021 ServerApp] nbdime | extension was successfully loaded.
[I 2021-09-07 02:08:51.021 ServerApp] Serving notebooks from local directory: D:\notebook
[I 2021-09-07 02:08:51.021 ServerApp] Jupyter Server 1.10.2 is running at:
[I 2021-09-07 02:08:51.021 ServerApp] http://DESKTOP-NUHJB50:8888/lab
[I 2021-09-07 02:08:51.021 ServerApp]  or http://127.0.0.1:8888/lab
[I 2021-09-07 02:08:51.021 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
C:\Users\DELL\anaconda3\lib\json\encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.1 or2.2.4
 - Installation source: conda
 - Deployment type: local installation
 - Operating system: win10

**Comment by caexy** [comment]
![image](https://user-images.githubusercontent.com/62989881/132252662-de144270-2b7f-49c0-a388-d759e49bf43a.png)

**Comment by lresende** [comment]
Have you built jupyterlab after Elyra installation - `jupyter lab build`?
Have you tried to [validate the Elyra installation ](https://elyra.readthedocs.io/en/stable/getting_started/installation.html#verify-the-server-extensions)to make sure the extensions are properly registered?

**Comment by lresende** [comment]
Please re-open with more information if you are still seeing issues on Windows platform.

**Comment by caexy** [comment]
Yes, everything is fine. But the page is blank.
