### ISSUE TITLE
create "Authentication Type" selector in Kubeflow Pipelines Runtime

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2107]
Currently, Elyra assumes that all Kubeflow Pipelines APIs are either unsecured or secured by dex (which also needs to be generalized: https://github.com/elyra-ai/elyra/issues/2106). 

There are effectively infinite ways that a Kubeflow Pipelines API could be secured (Istio IngressGateways can be secured in many ways), but we should am to support the most common ones:
- unsecured (no istio auth)
- dex
- `KF_PIPELINES_SA_TOKEN_PATH`
    - https://github.com/kubeflow/pipelines/issues/5138#issuecomment-797007907
    - https://github.com/kubeflow/website/pull/2905

We should allow the user to EXPLICITLY specify HOW they want to authenticate with the Kubeflow Pipelines API. The best way to do this is by extending the "Runtimes" editing screen to include an `Authentication Type` dropdown.

### Picture of current Kubeflow Pipelines "Runtime Configs":
![Screen Shot 2021-09-07 at 11 58 29 am](https://user-images.githubusercontent.com/5735406/132272702-c5bd6205-0331-4e6a-9eb4-6d3d76d6a554.png)

**Comment by thesuperzapper** [comment]
@lresende what are your thoughts?

**Comment by thesuperzapper** [comment]
@lresende this is also related to: https://github.com/elyra-ai/elyra/issues/2108

**Comment by kevin-bates** [comment]
To support this, I think we'll need to extend the metadata tooling (UI and CLI) to know how to deal with `oneOf` and, ideally, references `$ref`.  I think we'd define a schema similar to the following - which illustrates 3 (fictional) authentication types:
```json
{
  "type": "object",
  "properties": {
    "authentication": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/auth_1_def" },
        { "$ref": "#/definitions/auth_2_def" },
        { "$ref": "#/definitions/auth_3_def" }
      ]
    }  
  },
  "definitions": {
    "auth_1_def": {
      "type": "object",
      "properties": {
        "user": { "type": "string" },
        "password": { "type": "string" },
        "auth_type": { "enum": ["auth_1"] }
      },
      "required": ["auth_type", "user", "password"]
    },
    "auth_2_def": {
      "type": "object",
      "properties": {
        "token": { "type": "string" },
        "auth_type": { "enum": ["auth_2"] }
      },
      "required": ["auth_type", "token"]
    },
    "auth_3_def": {
      "type": "object",
      "properties": {
        "xxx": { "type": "string" },
        "auth_type": { "enum": ["auth_3"] }
      },
      "required": ["auth_type"]
    }
  },
}
```
An instance for the `authentication` property would look something like:
```json
{
  "authentication": {
    "auth_type": "auth_1",
    "user": "foo",
    "password": "bar"
  }
}
```

We could remove the references (`$ref`) and embed the definitions to help the tooling, but `oneOf` (as well as `allOf` and `anyOf`) would (should) need to be supported.

If we added "file support" to the CLI tooling (meaning instances are pulled from a file), we could alleviate the need (i.e., buy time) to deal with `oneOf`, but we should probably add object-valued support to the CLI options.  For example, `user`, `password` and `auth_type` values would be specified using a _dotted notation_ perhaps: `elyra-metadata install ... --authentication.user='foo;' --authentication.password='bar;' --authentication.auth_type='auth_1'`.

I suspect this will be a fair amount of work, but can't really speak for the metadata editor.

cc: @marthacryan @ajbozarth

**Comment by ptitzler** [comment]
A few clarifying questions about the fictitious example:
- `"auth_type": { "enum": ["auth_1"] }` Is the intention here to support different providers that require the same semantic input but process it differently? If it is, this approach would make it hard to define a name/value"pair" ("DEX with X/dex1") for each provider - `name` being a user friendly verbose representation
- missing required for `xxx`?
   ```
      "properties": {
        "xxx": { "type": "string" },
        "auth_type": { "enum": ["auth_3"] }
      },
      "required": ["auth_type"]
   ```

**Comment by kevin-bates** [comment]
> Is the intention here to support different providers that require the same semantic input but process it differently?

Yes, I think that scenario needs to be considered.

> If it is, this approach would make it hard to define a name/value"pair" ("DEX with X/dex1") for each provider - name being a user friendly verbose representation

I don't know about DEX, but this comment implies it's a "flavor" available in various authentication types.  If so, couldn't this be conveyed as optional parameters for each defined auth type to which it applies?

> missing required for xxx?

Not necessarily.  Although this example is purely contrived, such a schema might suggest an 'anonymous' mode (purely for example) where `xxx` is simply an override of the anonymous user.  The important requirement to these `oneOf` entries is that the `auth_type` be specified and each (mutually exclusive) value equates to identifying the authentication mode.

If we know the types of authentication we'd like to support and can provide their parameters (required and optional), we could draft a potential schema.
