### ISSUE TITLE
improve the Kubeflow Notebooks Docker image

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2110]
Currently, we provide docker images ([`elyra/kf-notebook`](https://hub.docker.com/r/elyra/kf-notebook)) for using Elyra with Kubeflow Notebooks, you can find the [Dockerfile here](https://github.com/elyra-ai/elyra/blob/master/etc/docker/kubeflow/Dockerfile).

__We can improve this Dockerfile in the following ways:__
- ~Stop using a `requirements.txt` approach, just explicitly use `pip install` (makes it more clear)~
- Don't switch `root` when installing python packages (as this makes the files not owned by the `jovyan` user)
- Update the base FROM image to: `public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:v1.3.0`
- ~Explicitly install the `kfp` package (We could also just let Elyra's requirements do this)~
- I don't think `yarn` is strictly needed (is this a dependency of Elyra)?

__Applying the above changes would give us the following Dockerfile:__
```Dockerfile
FROM public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:v1.3.0

# install - kfp + elyra
RUN python3 -m pip install --no-cache-dir --use-deprecated legacy-resolver \
    kfp==1.7.2 \
    elyra==3.0.1

# build JupyterLab plugins
RUN jupyter lab build
```

**Comment by lresende** [comment]
Thanks for the feedback @thesuperzapper, would you like to provide a pull request with these updates?

**Comment by thesuperzapper** [comment]
@lresende done!

See PR: https://github.com/elyra-ai/elyra/pull/2114

**Comment by lresende** [comment]
> Shouldn't the Dockerfile include some reference to the source code in the repository? For example, if I wanted to make changes to the elyra distribution and test it in my stack, I would also need to update the Dockerfile which is making development tedious. I'd love to see closer integration to the source rather than installing directly from PyPI.

I guess a couple of the other Dockerfile have it, but this one does not.

**Comment by thesuperzapper** [comment]
@lresende I think we should have a "prod" one which installs from PyPi, and a "dev" one which compiles by building from the local repo.

**Comment by lresende** [comment]
> @lresende I think we should have a "prod" one that installs from PyPi, and a "dev" one that compiles by building from the local repo.
> 
> (Most users will want a container image with exactly what they would get from `pip` for production, and will never need to use the "dev" one)

Completely agree, [here](https://github.com/elyra-ai/elyra/blob/0fd0f539d29e59a51964bf820910800302053a5c/etc/docker/elyra/Dockerfile#L40)is how we implemented for the `elyra-image` but I guess we could go one step deeper and use your local clone as the source instead of using a master clone/checkout.

**Comment by lresende** [comment]
@marcjimz Do you want to create a new issue to enhance the way we build our docker images using local source when building dev.

**Comment by marcjimz** [comment]
@lresende will do. I gave this a shot this afternoon but could use a pointer or two, was running into permission issues.

**Comment by marcjimz** [comment]
https://github.com/elyra-ai/elyra/issues/2116
