### ISSUE TITLE
Elyra Docker Images to build directly from source

### ISSUE THREAD

**Issue by marcjimz** [elyra-ai/elyra#2116]
**Is your feature request related to a problem? Please describe.**
When developing new features, currently there is no way to directly build a Docker image (say for KF Notebooks or Elyra) directly from source. This makes building and testing Docker images a bit troublesome especially in a Kubernetes based environment. 

**Describe the solution you'd like**
Would like to see a Docker file and pattern for which the core Pythaon distribution is built as part of the image build. I am thinking this can be done natively in the Docker root folder, however, context is important. Alternatively we can consider implementing this build as part of the makefile.

**Comment by marcjimz** [comment]
I tried this afternoon by adding this snippet to the Dockerfile, but I ran into some explicit permission issues upon loading the image.

```
  # install elyra
  COPY elyra-3.0.1.tar.gz elyra-3.0.1.tar.gz
  RUN tar -zxvf elyra-3.0.1.tar.gz && cd elyra-3.0.1 && python3 -m pip install --quiet --no-cache-dir --use-deprecated=legacy-resolver .
```

Of course, I was manually building the python tar ball in the root directory.

**Comment by thesuperzapper** [comment]
I am sure you already know this, but make sure you use [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/), and put the actual building into a separate stage (to minimize the size of the resulting docker image).

**Comment by marcjimz** [comment]
> I am sure you already know this, but make sure you use [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/), and put the actual building into a separate stage (to minimize the size of the resulting docker image).

Definitely understood, my issue was moreso getting the tar ball generated from the python source to install correctly in the container. Once I can get it install with permissions working writing the multi-layer build is straight forward.

I haven't had a chance to pick this up over the weekend but will try again later this week.

**Comment by akchinSTC** [comment]
@marcjimz - nudge nudge, how are things going with this?
