### ISSUE TITLE
Bump pipeline schema version due to change in pipeline op and component name changes

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2138]
**Describe the issue**
Pipeline component names were updated in 3.1.0 requiring a bump in pipeline schema version and update to the migration logic for older piplines.

See raw pipeline output.

**To Reproduce**
1. Open pipeline created prior to 3.1.0 
2. 
**Screenshots or log output**
```
Pipeline < 3.1.0
"type": "execution_node",
"op": "run-notebook-using-papermill",

Pipeline >= 3.1.0
"type": "execution_node",
"op": "run_notebook_using_papermill_Runnotebookusingpapermill",
```

**Expected behavior**
Older pipelines should be given the migration dialog box and option to update. 

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]
 - Operating system: [e.g. macos, linux]

**Comment by kiersten-stokes** [comment]
Here is the mapping of `op`s:

`run-notebook-using-papermill` --> `run_notebook_using_papermill_Runnotebookusingpapermill`
`filter-text` --> `filter_text_using_shell_and_grep_Filtertext`
`bash-operator_BashOperator` --> `bash_operator_BashOperator`
`email-operator_EmailOperator` --> `email_operator_EmailOperator`
`http-operator_SimpleHttpOperator` --> `http_operator_SimpleHttpOperator`
`spark-sql-operator_SparkSqlOperator` --> `spark_sql_operator_SparkSqlOperator`
`spark-submit-operator_SparkSubmitOperator` --> `spark_submit_operator_SparkSubmitOperator`
`slack-operator_SlackAPIPostOperator` --> `slack_operator_SlackAPIPostOperator`

**Comment by ajbozarth** [comment]
@akchinSTC is @kiersten-stokes list complete because while testing I found that download_op isn't on that list but it's in my pipeline?

**Comment by kiersten-stokes** [comment]
> @akchinSTC is @kiersten-stokes list complete because while testing I found that download_op isn't on that list but it's in my pipeline?

@ajbozarth download_op was never in a released version, I believe @akchinSTC only just added it on his branch
