### ISSUE TITLE
VPE/palette doesn't auto-refresh after component registry entry was deleted

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2152]
**Describe the issue**
A clear and concise description of what the issue is.

The VPE component palette displays deleted entries after they have been removed from the registry. Open/close of the VPE does not resolve the issue.

![image](https://user-images.githubusercontent.com/13068832/133586224-28fa8831-58c6-45c1-8715-8bb4504a9a32.png)

It appears that the cache is not invalidated when a component registry entry is deleted.

**To Reproduce**
1. Create a component registry entry
2. Open VPE - the entry is displayed as expected
3. Delete the component registry entry
4. Open VPE - the entry is still displayed

**Expected behavior**
The palette should reflect the current state of the registry or provide the means to manually trigger a re-load.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.1+

**Comment by kiersten-stokes** [comment]
PR #2157 added the backend support for cache updates on registry modification. This still requires the user to reload or open a new pipeline, etc. in JL in order to see the changes on the frontend, so this will remain open until the corresponding frontend piece is added.

**Comment by ptitzler** [comment]
This is resolved in version 3.7.
