### ISSUE TITLE
Consider sorting components in palette for consistent display

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2171]
**Is your feature request related to a problem? Please describe.**
With threading now implemented to read and parse component definitions, the order in which the components are rendered may change depending on the order in which threads execute.

**Describe the solution you'd like**
Discussion is needed to determine where the sorting should be done. 

**Describe alternatives you've considered**
We can also consider just leaving it as-is as a visual for when components are updating.

**Comment by ptitzler** [comment]
Seems now broken in master:

![image](https://user-images.githubusercontent.com/13068832/140419928-5e6fbab5-dd27-498d-b1f2-e42ce3977b08.png)

**Comment by ptitzler** [comment]
I believe sorting is currently performed in a case sensitive manner, whereas it should not. e.g. `'load data' == 'load dATA'`
