### ISSUE TITLE
Attaching PVC to elyra pipeline

### ISSUE THREAD

**Issue by Subhraj07** [elyra-ai/elyra#2185]
Currently it is heavily depend upon minio but if the data is huge reading and writing data from minio would be a challenge so if this feature can be added it would be useful.

**Comment by ptitzler** [comment]
Hi @Subhraj07, could you please review https://github.com/elyra-ai/elyra/issues/1586 and let me know if your requirements would be met if that one was implemented?

**Comment by akchinSTC** [comment]
https://github.com/elyra-ai/elyra/issues/1843 - related
