### ISSUE TITLE
Node Tooltip doesn't render when component isn't found

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#2194]
**Describe the issue**
When the component for a node isn't in the registry the Node Tooltip renders empty.

**To Reproduce**
1. Create a pipeline and add a node
2. Open the pipeline in "Editor" and change the `op` for that node to something invalid (add a number to the end)
3. Note the error visual in the pipeline 
4. mouse over the node and note the empty tooltip

**Screenshots or log output**
![img](https://user-images.githubusercontent.com/13952758/136076375-2ee5884b-4bf8-4685-8ddb-336a669ec1a5.png)

**Expected behavior**
The tooltip should render with an error message explaining why the node's invalid

Discovered while testing: https://github.com/elyra-ai/pipeline-editor/pull/168

**Comment by ptitzler** [comment]
related to #2192
