### ISSUE TITLE
Cleanup website repository

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2201]
Cleanup website repository
- [x] - Rename repository to `elyra-website` or `website`
- [x] - Remove "allow merge commits" option
- [x] - Review repository security 
- [x] - Rename main branch to master for consistency purposes
- [x] - Cleanup commit history (squash as two commits - Initial commit from @sydrosa and initial content from @quarryboy)
- [x]  Publish website on elyra's github.io

**Comment by akchinSTC** [comment]
@lresende - went with a different approach with #5 on your checklist
heres the updated repo link: https://github.com/elyra-ai/website/commits/master
website test link : https://quarryboy.github.io/elyra-ai-site/
