### ISSUE TITLE
Airflow pipeline submission is freezing due to black dependency 

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2204]
**Describe the issue**
Pipeline submission for airflow dag freezes during run

![image](https://user-images.githubusercontent.com/13340013/136447829-6cfc8607-704d-4968-98eb-ef8e8f18fe3e.png)

**To Reproduce**
1. create aa pipeline
2. click run and submit the pipeline
3. See error

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
```
[D 2021-10-07 09:20:19.136 ServerApp] Loading metadata instance from cache: 'airflow_test'
Generating grammar tables from /Users/akchin/opt/anaconda3/envs/test-3.2/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /Users/akchin/Library/Caches/black/21.9b0/Grammar3.8.0.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/akchin/Library/Caches/black/21.9b0/tmpy5isx0z2'
Generating grammar tables from /Users/akchin/opt/anaconda3/envs/test-3.2/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /Users/akchin/Library/Caches/black/21.9b0/PatternGrammar3.8.0.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/akchin/Library/Caches/black/21.9b0/tmpsuo6ewmf'
```

**Expected behavior**
pipeline creation should complete and be pushed to github

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.2.0rc0

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Apache Airflow 
 
**Runtime configuration settings**
If the issue is related to pipeline execution, document the runtime configuration settings from the Elyra UI, omitting confidential information.

**Comment by kevin-bates** [comment]
I'm unable to reproduce this as well.  Using `black==21.9b0` (FWIW).

**Comment by kevin-bates** [comment]
@akchinSTC - is this still an issue for you?
