### ISSUE TITLE
Add GitHub release functionality to Elyra release script

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2214]
**Is your feature request related to a problem? Please describe.**
We currently only create and push tags in our release script. To bring Elyra more in line with similar projects (such as JupyterLab), we could consider adding Github releases as well.

Current:
<img width="164" alt="Screen Shot 2021-10-08 at 3 20 36 PM" src="https://user-images.githubusercontent.com/31816267/136620475-35651a55-d31c-4832-9696-a8c7a5c298ea.png"> 

Potential:
<img width="191" alt="Screen Shot 2021-10-08 at 3 22 23 PM" src="https://user-images.githubusercontent.com/31816267/136620571-55396fc8-27f3-45ce-84e0-b98887604e1d.png">

**Describe the solution you'd like**
Add `gh` (Github CLI tool) commands to the `Pushing Release and Tag to git` section of `create-release.py`. 

Instructions would also have to be added to the release documentation. 

We'd probably also want to make this portion of the release script optional, so if the release manager does not have `gh` install or is not authenticated that a warning message is issued but no error is thrown.

Include a link to the changelog in the release description.

**Describe alternatives you've considered**
We could also use the Release prompts on Github.com to perform the same function.

**Additional context**
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_create

**Comment by lresende** [comment]
At the community meeting today was decided that we are going to start manually creating release contents on the "release" entry.
