### ISSUE TITLE
Allow for data exchange between custom Airflow components

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2217]
**Describe the issue**
Companion to https://github.com/elyra-ai/elyra/issues/1761. Allow for exchange of data between Apache Airflow operators in Elyra pipelines.

### Apache Airflow

Apache Airflow uses the concept of Xcoms or Cross Communication. Xcoms are small amounts of data that are shared between tasks (nodes). The data is represented by a key-value pair with the key being a string and a value that is serializable in JSON or pickable(pickle). These Xcoms can be pushed and pulled between tasks and by default are scoped to the DAG run (pipeline run)

Xcoms are built into the Airflow BaseOperator so all operators inherit them and are accessed via the task_instance(ti) object and xcom_push and xcom_pull helper methods.

```
t1 = BashOperator(
    task_id="t1",
    bash_command='echo "{{ ti.xcom_push(key="k1", value="v1") }}" "{{ti.xcom_push(key="k2", value="v2") }}"',
    dag=dag,
)
t2 = BashOperator(
    task_id="t2",
    bash_command='echo "{{ ti.xcom_pull(key="k1") }}" "{{ ti.xcom_pull(key="k2") }}"',
    dag=dag,
)
t1 >> t2
```
Limitations:

Note that there are size limitations to the amount of data that can be passed via Xcoms. Best practices seems to suggest that objects around a few KBs are ok to pass via Xcoms but anything larger should be handled via by file path reference (volumes, s3) 
[MAX XCOM Size](https://airflow.apache.org/docs/apache-airflow/1.10.15/_modules/airflow/models/xcom.html#XCom) is 48KB

Resources:
A good guide : https://marclamberti.com/blog/airflow-xcom/

### Implementation

Expectations after completion:
- Users will be able to construct a pipeline consisting of generic components and airflow components
- Users will be able to exchange information between `airflow component` -> `airflow component` via `xcoms`
- Airflow components will be expected to be subclassed from the airflow `BaseOperator`
- Airflow component xcom pushes will be limited to **the** single default key `return_value`
- Users will continue to be able to exchange input and output between `generic components` ->` generic components`
- Users will **not** be able to exchange inputs and outputs  between `generic components` -> `airflow components` and vice versa
- Users will **not** be able to include any local dependencies/files with `airflow components`

- By restricting composition of an operator to subclass the [BaseOperator](https://github.com/apache/airflow/blob/1.10.15/airflow/models/baseoperator.py), we have a base structure to work off of. 
  - Xcom push is set to `true` by default
  - Xcom return key is `return_value` as specified [here](https://github.com/apache/airflow/blob/5786dcdc392f7a2649f398353a0beebef01c428e/airflow/models/xcom.py#L40).
  - By default the `return_value` will be the return value of the `execute` method.
  - The restriction on the number of return values (a single value) is not ideal, we can explore allowing more via parsing of the operator for calls to the [`xcom_push`](https://github.com/apache/airflow/blob/5786dcdc392f7a2649f398353a0beebef01c428e/airflow/models/baseoperator.py#L1050-L1062) method to get additional xcom keys. 
    -  These extra xcom_keys will need to be made available via component parameter for the component in the registry. 
  - All Airflow operator parameters inputs will be able to take an xcom as its value. Airflow does not make the distinction through parameter typing (unlike kfp with inputpath and outputpath)
    - This complicates the UI a bit, every node property in the UI will need to be able to take in an output from a parent node
      - The node properties UI (controller) will need to be flexible enough to change a component property from taking a value directly from the user to referencing a value from the output of a previous node (xcom).
        -  ~proposal - airflow components by default will all be of new controlid "placeholder" type. When user decides to enter value directly instead, the UI falls back to the original component parameter type under ['data']['format']. Again, will need to determine if something like this possible with the UI, as the parameters that are generated by the component registry template could be just sent directly to the canvas framework for rendering.~  
        - Component parameters fields will be updated with additional identifiers for the front end to use to render the node properties. 
        - `OneOfControl` - new custom control id will allow for a parameter to be "one of" the different control types under ['data']['controls']. This will allow a component parameter to flip between two different types of inputs (direct input and upstream output).
```
{
                "parameter_ref": "elyra_parameters",
                "control": "custom",
                "custom_control_id": "OneOfControl",
                "label": {
                    "default": "Parameters"
                },
                "description": {
                    "default": "Map with notebook parameter values. (type: JsonObject)",
                    "placement": "on_panel"
                },
                "data": {
                    "controls": {
                         "NestedEnumControl": {
                              "format": "inputpath".   ## Should change this to "xcom" / airflow terminology or make it more neutral
                          },
                         "StringControl":{
                              "format": "string"
                         }
                     }
                    "required": true
                }
            }
```

```
               "type":"execution_node",
               "op":"bash-operator_BashOperator",
               "app_data":{
                  "label":"BashOperator",
                  "component_parameters":{
                     "runtime_image":"alpine:latest",
                     "component_source":"https://raw.githubusercontent.com/apache/airflow/1.10.15/airflow/operators/bash_operator.py",
                     "component_source_type":"url",
                     "bash_command": {
                              "value": "01ea88e3-3f21-4dd0-a526-b6bd09792b01",
                              "option": "return_value"
                     "xcom_push":true,
                     "env":"{\"TEST_ENV\": \"Hello World\"}",
                     "output_encoding":"utf-8",
```

- [x] Create new controlID `OneOfControl`
- [x] Update component parsers for both kfp and airflow reflect new parameter format in canvas template rendering
- [x] Validation type checking needs to be updated for all properties since they can double as xcom pulls as well as their original types
- [x] Update kfp/aa parsing pytest suites

**Comment by akchinSTC** [comment]
> * proposal - airflow components by default will all be of new controlid "placeholder" type. When user decides to enter value directly instead, the UI falls back to the original component parameter type under ['data']['format']. Again, will need to determine if something like this possible with the UI, as the parameters that are generated by the component registry template could be just sent directly to the canvas framework for rendering.

@ajbozarth - would something like this be possible? dynamic node property rendering? e.g. check box, changes to dropdown for previous outputs, otherwise takes in value of specified type in component definition.
