### ISSUE TITLE
Elyra does not appear to support Kubeflow 1.4

### ISSUE THREAD

**Issue by sergiynesterenko90** [elyra-ai/elyra#2230]
**Describe the issue**
I am trying to submit run an elyra notebook as a pipeline, but am having an issue with the runtime configuration. The pipeline server seems to be responding with an issue related to creating the pipeline, and as a result the pipeline does not run. 

**To Reproduce**
1. Set up kubeflow on google cloud (I used https://github.com/kubeflow/manifests tag v1.4.0). 
2. Create an elyra notebook in kubeflow (I used kf-notebook:3.2.0 image)
3. In elyra, set up runtime 
4. Click "Run as Pipeline" in the notebook. 

**Screenshots or log output**
<details><summary>Log Output</summary>
<pre>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 265, in process
    kfp_pipeline = client.upload_pipeline(
  File "/opt/conda/lib/python3.8/site-packages/kfp/_client.py", line 1225, in upload_pipeline
    response = self._upload_api.upload_pipeline(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 69, in upload_pipeline
    return self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 163, in upload_pipeline_with_http_info
    return self.api_client.call_api(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 407, in request
    return self.rest_client.POST(url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'date': 'Thu, 14 Oct 2021 22:12:57 GMT', 'content-type': 'text/plain; charset=utf-8', 'x-envoy-upstream-service-time': '23', 'server': 'envoy', 'transfer-encoding': 'chunked'})
HTTP response body: {"error_message":"Error creating pipeline: Create pipeline failed: templates.elyra-test templates.elyra-test: failed to resolve {{workflow.annotations.pipelines.kubeflow.org/run_name}}","error_details":"templates.elyra-test templates.elyra-test: failed to resolve {{workflow.annotations.pipelines.kubeflow.org/run_name}}\ngithub.com/argoproj/argo-workflows/v3/errors.New\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.6/errors/errors.go:49\ngithub.com/argoproj/argo-workflows/v3/errors.Errorf\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.6/errors/errors.go:55\ngithub.com/argoproj/argo-workflows/v3/workflow/validate.ValidateWorkflow\n\t/go/pkg/mod/github.com/argoproj/argo-workflows/v3@v3.1.6/workflow/validate/validate.go:228\ngithub.com/kubeflow/pipelines/backend/src/common/util.ValidateWorkflow\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/template_util.go:71\ngithub.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreatePipeline\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:265\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipeline\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:119\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nCreate pipeline failed\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:275\ngithub.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).CreatePipeline\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/resource/resource_manager.go:267\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipeline\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:119\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nError creating pipeline\ngithub.com/kubeflow/pipelines/backend/src/common/util.Wrap\n\t/go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:275\ngithub.com/kubeflow/pipelines/backend/src/apiserver/server.(*PipelineUploadServer).UploadPipeline\n\t/go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/pipeline_upload_server.go:121\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/handlers.py", line 118, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor.py", line 114, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 299, in process
    raise RuntimeError(
RuntimeError: Failed to upload Kubeflow pipeline: 'elyra_test' - Check Kubeflow Pipelines runtime configuration: 'elyra-pipeline'
</pre>
</details>

**Expected behavior**
I expected the notebook pipeline to run. I have tested this deployment of kubeflow with kfp directly which seems to work fine. Have also tested the object store. 

**Deployment information**
 - Elyra version: 3.2.0
 - Operating system: linux
 - Installation source: manifest for kubeflow, docker image for elyria notebook
 - Deployment type: Kubernetes on GCP

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines 1.4.0 - multi-user enabled. 
 
**Runtime configuration settings**
api-endpoint: http://istio-ingressgateway.istio-system.svc.cluster.local/pipeline/
user/pass: (hidden, but I know they are right)
pipelines engine: Argo
cloud object storage endpoint: http://minio-service.kubeflow.svc.cluster.local:9000 
user/pass: (hidden, but I know they are right)

**Comment by sergiynesterenko90** [comment]
Sure enough, I deployed kubeflow 1.3.0 on a different cluster, and everything seems to work like a charm. Feel free to close (unless helpful for work on integration with 1.4.0).

**Comment by ptitzler** [comment]
Thanks for letting us know! Can you please provide the output of `pip list | grep kfp`?

**Comment by ptitzler** [comment]
If you have access to the (container) log file, can you please check if it contains a response body

```
       raise ApiException(http_resp=r)
    kfp_server_api.exceptions.ApiException: (500)
    Reason: Internal Server Error
    HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Express', 'date': 'Fri, 15 Oct 2021 20:49:40 GMT', 'content-type': 'text/plain; charset=utf-8', 'x-envoy-upstream-service-time': '98', 'server': 'istio-envoy', 'transfer-encoding': 'chunked'})
    HTTP response body: {"error_message":"Error creating pipeline: Create pipeline failed: templates.lambda templates.lambda.tasks.python-notebook templates.python-notebook: failed to resolve {{workflow.annotations.pipelines.kubeflow.org/run_name}}","error_details":"templates.lambda templates.lambda.tasks.python-notebook templates.python-notebook: failed to resolve {{workflow.annotations.pipelines.kubeflow.org/run_name}}
```

The key is this part of the response 
```
failed to resolve {{workflow.annotations.pipelines.kubeflow.org/run_name}}
```

which is likely caused by [this code in Elyra](https://github.com/elyra-ai/elyra/blob/master/elyra/kfp/operator.py#L256)
