### ISSUE TITLE
Why does Conda-forge only have Elyra==2.2.4？

### ISSUE THREAD

**Issue by HonorWithPupils** [elyra-ai/elyra#2232]
**Describe the issue**
Why does Conda-forge only have Elyra==2.2.4？

**To Reproduce**

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/81359581/137423100-9aa50873-4708-40b4-aaae-3d6aa8e70680.png)
![image](https://user-images.githubusercontent.com/81359581/137423131-4f46ed0f-c37c-4930-9540-52c943e3b583.png)

**Expected behavior**

**Deployment information**

**Comment by akchinSTC** [comment]
See related : 
https://github.com/conda-forge/staged-recipes/pull/16307
https://github.com/kubeflow/pipelines/pull/7165
