### ISSUE TITLE
Elyra < 3.3 fails with "Error contacting server: endpoint elyra/schemaspace not found"

### ISSUE THREAD

**Issue by andre-lx** [elyra-ai/elyra#2245]
**Describe the issue**
Hi. 

Looks like the old versions (tested with 3.1.1 and 3.1.0) are broken. 

The instalation seems to be ok, but when we open an jupyterlab you can see this message:

![image](https://user-images.githubusercontent.com/44682155/138269769-224e50f7-9de1-4e1f-8c60-89caa7b7192f.png)

![image](https://user-images.githubusercontent.com/44682155/138270070-5756546e-d07b-4dca-a6e5-c8641066e589.png)

https://github.com/elyra-ai/elyra/compare/v3.1.1...v3.2.1#diff-d0e5e5d4b31372d3dad3a0c68e167de16dd4c10ce9bd340631d4503bacd55c20R42

It looks like, even with the installation of old versions, he pulls the server from the most recent versions. In this example the error talks about `schemaspace` where in version 3.1.1 is namespace

**To Reproduce**

`pip install elyra==3.1.1` and `jupyter lab build`

**Expected behavior**
The installation of old version should be possible.

**Comment by ajbozarth** [comment]
Thanks for bringing this to our attention @andre-lx we will be doing patch releases to fix this for 3.x, once v3.0.2, v3.1.2, and v3.2.2 are released you should no longer see the issue on those releases
