### ISSUE TITLE
VPE: provide guidance on how to add to the component palette

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2281]
**Is your feature request related to a problem? Please describe.**

When a new user opens the Visual Pipeline Editor for the first time it's not easy to figure out what to do. The standard text "Your flow is empty. Get started by adding a node" isn't helpful because
- a user has to figure out where components are (the palette is hidden by default)
- there is no "intuitive" way to add items to the palette

**Describe the solution you'd like**
Something like this, that directs the user 

![image](https://user-images.githubusercontent.com/13068832/140589019-f325b700-5a30-4f72-b94e-23065b881c93.png)

Since this guidance is typically only required a few times, a user should be able to disable it permanently.

**Additional context**

This is similar to what we already provide for runtime configurations:

![image](https://user-images.githubusercontent.com/13068832/140589163-406d5e71-3d86-4adc-b19a-29bc24195051.png)

**Comment by lresende** [comment]
Why not add to the existing text?

**Comment by ptitzler** [comment]
If that's possible for text + links that would be a much better solution

**Comment by ptitzler** [comment]
Fixed by #2304
