### ISSUE TITLE
Pipeline portability with runtime specific component. 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2283]
**Describe the issue**
While working on #2272 I started seeing a couple of issues that I believe would break pipeline portability when it's using custom components. 

As for portability requirements, I believe we should support:
  - User should be able to install/uninstall components
  - User should be able to add runtime specific components to a pipeline
  - A pipeline should work on a remote machine if the same component is installed

But when I use a custom component on a new pipeline (using the latest master) what I get is the reference below, which has a component location that is unique to my environment. 
```
...
"component_source": "{'catalog_type': 'local-directory-catalog', 'component_ref': {'base_dir': '/Users/lresende/opt/anaconda/envs/dev/share/jupyter/components/kfp', 'path': 'calculate_hash.yaml'}}",
...
```

Some other issues are:
 - How to handle versioning
 - How to handle name conflict

Note that I also saw #2262 but that wasn't what I was seeing, and the master code was still putting the full absolute path for the component location. 

NOT A CONTRIBUTION

**Comment by ptitzler** [comment]
For filesystem catalogs the `base_dir` is only included for reference in the `component_source` property. It is not used (or should at least not be used) to calculate the hash, which is used to match op references in the pipeline files with components that are available locally in your environment. Therefore this should work as is in any environment, as long users have the file identified by `path` is present.

**Comment by kiersten-stokes** [comment]
> It is not used (or should at least not be used) to calculate the hash, which is used to match op references in the pipeline files with components that are available locally in your environment

Correct! For directory-catalog-based components, the hash is calculated using the relative path **from** the base directory.

**Comment by lresende** [comment]
Thank you for the explanation of the latest behavior.
