### ISSUE TITLE
Permanently remove the ability to export KFP pipelines to Python DSL

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2301]
**Is your feature request related to a problem? Please describe.**
In Elyra versions prior to v3.1 it was possible to export pipelines to KFP Python DSL. The feature was disabled with the introduction of custom components. 

**Describe the solution you'd like**
Permanently remove the ability to export pipelines to Python DSL. Users can still export to static YAML files.

**Comment by kiersten-stokes** [comment]
The PR for this will also close #1756 and #1760

**Comment by akchinSTC** [comment]
Will also close #2097
