### ISSUE TITLE
Generalize status code handling

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#232]
Per [this comment](https://github.com/elyra-ai/elyra/pull/231#pullrequestreview-339297287) we should probably relax some of the status code interpretation in order to better facilitate server-side changes or even other servers in general without having to update front-end code to handle the addition of success (and error) codes.

In particular, we should expand the set of success status codes from 200 (which is currently all that the elyra server returns) to also include 201 (when resources are created via POST), 204 (when resources are deleted), etc.

**Comment by ajbozarth** [comment]
This will be partially addressed in #433 with the addition of a 201 return and will be cleaned up in the implementation for #400
