### ISSUE TITLE
It took a long time to get Jupyter Lab started.

### ISSUE THREAD

**Issue by silvewheat** [elyra-ai/elyra#2328]
Hello,
When I start jupyter lab, it takes an unusual amount of time on some steps (red arrows). Is there any way to improve the startup speed by turning off some options?

![image](https://user-images.githubusercontent.com/19344997/143985282-c2eca12e-d93c-4533-bad4-c3697939c32d.png)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.2.2
 - python: 3.8
 - Installation source: PyPI
 - Deployment type: local installation
 - Operating system: linux
![image](https://user-images.githubusercontent.com/19344997/143984939-659a0102-254e-4088-a8fb-fa349553312b.png)

**Comment by akchinSTC** [comment]
Hi @silvewheat and thanks for opening up an issue!

Could you provide us with additional information so we can better diagnose the issue?

- current system hardware specs, if running in a container, then the resources allocated to the container
- internet connection, using VPN?
- turn on the debug flag e.g. add `--debug` when starting jupyterlab with elyra, and provide us with log output

**Comment by ptitzler** [comment]
Perhaps related to https://github.com/elyra-ai/elyra/issues/2164 (retrieval of example components takes a very long time or fails). Above information should enable us to confirm whether network connectivity is causing the issue.

**Comment by silvewheat** [comment]
It is indeed related to #2164 . I have seen that 'Connection aborted.' error sometimes.
The full log (add --debug) was uploaded.
It take a long time in:

    Attempting read of component definition file at location 'https://raw.githubusercontent.com/apache/airflow/1.10.15/airflow/operators/http_operator.py'...

and:

    Attempting read of component definition file at location 'https://raw.githubusercontent.com/apache/airflow/1.10.15/airflow/contrib/operators/spark_submit_operator.py'...

and:

    Attempting read of component definition file at location 'https://raw.githubusercontent.com/kubeflow/pipelines/1.6.0/components/basics/Calculate_hash/component.yaml'...
[jupyter_log.txt](https://github.com/elyra-ai/elyra/files/7630523/jupyter_log.txt)

Can I use some offline model to run elyra? The internet connection is not good (no VPN installed in the server).
hardware: Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
system: Ubuntu 20.04.3 LTS

**Comment by ptitzler** [comment]
Thank you @silvewheat! The upcoming 3.3 release will avoid this issue:
 - the example components (which are loading slowly in your env) are no longer installed by default and therefore no attempt is made to fetch them when JupyterLab is started
 - if you install the example components explicitly (via `pip install`) they are stored locally, eliminating the need to download them every time JupyterLab is started

**Comment by ptitzler** [comment]
@silvewheat I am going to go ahead and close the issue now that [3.3rc2 is available](https://pypi.org/project/elyra/3.3.0rc2/). Unless last minute testing reveals any blocking issues, this will be the GA code base, which should no longer surface the issue you've encountered.

**Comment by silvewheat** [comment]
I installed the 3.3rc2, and the problem solved!
Thank you!
