### ISSUE TITLE
Generic pipeline not displaying the correct dialog/options on export

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2332]
**Describe the issue**
Export displays an incorrect dialog when no runtimes are defined for generic pipelines. This isn't an issue for runtime type-specific pipelines

**To Reproduce**
1. Remove all defined runtimes
2. Create a generic pipeline
3. Click export
4. See dialog box below

**Screenshots or log output**
<img width="321" alt="Screen Shot 2021-12-01 at 4 11 12 PM" src="https://user-images.githubusercontent.com/31816267/144325667-2d17df00-3479-4065-aab5-c023da0907a6.png">

**Expected behavior**
Should display an error message similar to the below and prompt to open `Runtimes`

<img width="321" alt="Screen Shot 2021-12-01 at 4 39 15 PM" src="https://user-images.githubusercontent.com/31816267/144325786-a8e5c3c1-98fa-4769-801b-d5980715a90f.png">

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.3.0rc1
 - Installation source: PyPI

**Comment by karlaspuldaro** [comment]
This bug was surfaced when writing new integration tests for exporting generic pipelines in #2327

**Comment by ajbozarth** [comment]
This is caused by #2320 
in that PR we removed `actionType === 'export' || ` that would cause the error case to enter that if block where the error handling was. The title definition should be handled if a separate if block than the error handling. I'll open a PR with the fix
