### ISSUE TITLE
Kubeflow Pipeline Token Auth does not read local environment variable KF_PIPELINES_SA_TOKEN_PATH

### ISSUE THREAD

**Issue by alexisc67** [elyra-ai/elyra#2352]
**Describe the issue**
Authentication fails when using token authentication for Kubeflow pipelines. Our deployment mounts the token in a path that is different to the default path of var/run/secrets/kubeflow/pipelines/token. Therefore we set the env variable using:
KF_PIPELINES_SA_TOKEN_PATH=/var/run/secrets/kubernetes.io/serviceaccount/token
The Run does not work. 

**To Reproduce**
1. Go to Elyra and setup a kubeflow pipeline runtime that uses a token
2. Make sure the token is NOT in the default path of  /var/run/secrets/kubeflow/pipelines/token
3. In a Terminal, set the variable KF_PIPELINES_SA_TOKEN_PATH to the place where the token is mounted
4. Open pipeline example such as 'hello-generic-world.pipeline' and Run selecting the runtime you created in 1
4. See the error

Kubeflow authentication failed: Kubernetes service account token could not be read from /var/run/secrets/kubeflow/pipelines/token: [Errno 2] No such file or directory: '/var/run/secrets/kubeflow/pipelines/token'.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.3.0
 - Operating system: Azure AKS, Kubeflow 1.4, Notebook server

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines 1.4, Multi user with KUBERNETES_SERVICE_ACCOUNT_TOKEN auth
 - Argo workflows
 
**Runtime configuration settings**
If the issue is related to pipeline execution, document the runtime configuration settings from the Elyra UI, omitting confidential information.

**Comment by ptitzler** [comment]
This is odd. I just completed your listed steps in a _local environment_ the environment variable value is picked up and the result is as expected:
 - install 3.3.0
 - open terminal window
 - `export KF_PIPELINES_SA_TOKEN_PATH=/no/such/file`
 - `jupyter lab`
 - create KFP runtime configuration, selecting `KUBERNETES_SERVICE_ACCOUNT_TOKEN` as auth type (specifying no credentials)
 - create KFP pipeline
 - pipeline run fails with:

![image](https://user-images.githubusercontent.com/13068832/145275734-aff4e8ba-2532-4bdc-89f4-20bedfbf13b0.png)

You've indicated that you are using Azure AKS. If you've completed the steps there, can you please confirm that the environment variable was configured properly?

**Comment by ptitzler** [comment]
If you were running the test in a container in Kubernetes, can you list the environment variables in the pod where JupyterLab/Elyra is running, e.g. by issuing 

```
kubectl exec <CONTAINER_ID> --namespace <YOUR_NAMESPACE> -- env
```

If the output does not include `KF_PIPELINES_SA_TOKEN_PATH` then this is likely caused by something in your setup.

**Comment by alexisc67** [comment]
I performed the steps from the Notebook Server within Kubeflow. You ran the steps in your machine. Let me check the env in the pod following your suggestion. Thanks

![image](https://user-images.githubusercontent.com/12430569/145324180-6c3d2921-c4ba-40b8-ab7f-9d019b402f1f.png)

**Comment by kevin-bates** [comment]
Hi @alexisc67, based on your responses it appears you're setting the environment variable from a terminal session launched from Lab/Elyra. This is not sufficient to set the variable into the server process. Instead, set/export the variable _prior_ to starting the Lab/Elyra server. If your server resides in a container then the env should be set via the container launch facility, whatever that might be, so that it's present when Elyra goes to use it.

**Comment by alexisc67** [comment]
The issue was resolved adding a configuration poddefault to the namespace running the notebooks for:
KF_PIPELINES_SA_TOKEN_PATH=/var/run/secrets/kubeflow/pipelines/token

Thanks!

**Comment by techwithshadab** [comment]
Hi @alexisc67,
How did you added configuration poddefault? I'm also running into same issues and on executing `kubectl exec <CONTAINER_ID> --namespace <YOUR_NAMESPACE> -- env` there is no `KF_PIPELINES_SA_TOKEN_PATH` variable
