### ISSUE TITLE
Not able to submit Elyra pipeline on Airflow Airflow runtime with Google Cloud Object Storage Endpoint

### ISSUE THREAD

**Issue by harish-gaggar-infra** [elyra-ai/elyra#2357]
**Issue**
After configuring Google Cloud Storage as an endpoint in the Apache Airflow runtime, trying to submit job, It copies notebook files at Google Cloud Storage but not at Airflow DAG, hence no job appear at Airflow

**Steps to reproduce the behavior**
1. On Mac/Linux machine, run **_docker run -it -p 8888:8888 elyra/elyra: 3.3.0  jupyter lab --debug_**
2. Access browser http://127.0.0.1:8888/lab
3. Upload any sample notebook file
4. At Runtime - Select "New Apache Airflow Runtime Configuration"
@ Apache Airflow section - fill up all required details (Airflow & Git configurations) 
@ Cloud Object Storage section- For "Cloud Object Storage Endpoint ", I have used "**https://storage.googleapis.com:8080**" (Not sure if there is actually any port for GCS endpoint but seems defining port is mandatory in this field". Beside, this "Cloud Object Storage Endpoint ", please fill other details like bucker userid, password and bucket name.
5. At Home Page- Click on Airflow Pipeline Editor, drag notebook (that uploaded as requested in 3'rd point above)- Right click on notebook , open properties- define label, select images as pandas 1.1.1)- save pipeline-submit job (by selecting airflow run configuration that defined in point 4 above)
6. Below message appear as expected
Packaging and submitting pipeline ...This may take some time "

This job is not successful as it never creates any DAG files at Google Cloud Storage/Or any Git PR.

Logs

> {Code}
> [I 2021-12-10 05:04:54.888 ElyraApp] airflow 'untitled-1210050454' - processing pipeline dependencies to: https://storage.googleapis.com:8080 bucket: elyrapoc folder: untitled-1210050454 
> [D 2021-12-10 05:04:54.889 ElyraApp] Creating pipeline component:
>      componentID : f1f5195c-22e1-48b7-b612-ab054aefa7a7 
>      name : 1 
>      parent_operation_ids : [] 
>      component_parameters: {
>     	filename: 1.ipynb, 
>     	runtime_image: amancevice/pandas:1.1.1, 
>     	outputs: [], 
>     	env_vars: [], 
>     	dependencies: [], 
>     	include_subdirectories: False, 
>     	inputs: [], 
>     	cpu: None, 
>     	gpu: None, 
>     	memory: None, 
>     } 
>      archive : 1-f1f5195c-22e1-48b7-b612-ab054aefa7a7.tar.gz
> [I 2021-12-10 05:04:54.889 ElyraApp] airflow 'untitled-1210050454':'1' - processing operation dependencies for id: f1f5195c-22e1-48b7-b612-ab054aefa7a7 
> [I 2021-12-10 05:04:54.893 ElyraApp] airflow 'untitled-1210050454':'1' - generated dependency archive: /tmp/elyra/1-f1f5195c-22e1-48b7-b612-ab054aefa7a7.tar.gz (0.003 secs)
> [D 2021-12-10 05:04:56.037 ServerApp] Accepting token-authenticated connection from 172.17.0.1
> [D 2021-12-10 05:04:56.038 ServerApp] Found kernel python3 in /opt/conda/share/jupyter/kernels
> [D 2021-12-10 05:04:56.040 ServerApp] 200 GET /api/kernelspecs?1639112696019 (172.17.0.1) 3.65ms
[D 2021-12-10 05:10:31.641 ServerApp] Accepting token-authenticated connection from 172.17.0.1
[D 2021-12-10 05:10:31.645 ElyraApp] Schemaspace 'runtime-images' is using metadata directory: /home/jovyan/.local/share/jupyter/metadata/runtime-images from list: ['/home/jovyan/.local/share/jupyter/metadata/runtime-images', '/usr/local/share/jupyter/metadata/runtime-images', '/usr/share/jupyter/metadata/runtime-images', '/opt/conda/share/jupyter/metadata/runtime-images']
[D 2021-12-10 05:10:31.645 ElyraApp] Loading metadata instance from cache: 'tensorflow_2x_py3'
[D 2021-12-10 05:10:31.646 ElyraApp] Loading metadata instance from cache: 'r'
[D 2021-12-10 05:10:31.646 ElyraApp] Loading metadata instance from cache: 'pytorch-runtime'
[D 2021-12-10 05:10:31.647 ElyraApp] Loading metadata instance from cache: 'anaconda'
[D 2021-12-10 05:10:31.647 ElyraApp] Loading metadata instance from cache: 'tensorflow_2x_gpu_py3'
[D 2021-12-10 05:10:31.647 ElyraApp] Loading metadata instance from cache: 'tensorflow_py3'
[D 2021-12-10 05:10:31.648 ElyraApp] Loading metadata instance from cache: 'pytorch-devel'
[D 2021-12-10 05:10:31.649 ElyraApp] Loading metadata instance from cache: 'pandas'
[D 2021-12-10 05:10:31.649 ElyraApp] Loading metadata instance from cache: 'tensorflow_gpu_py3'
[D 2021-12-10 05:10:31.778 ServerApp] 200 GET /elyra/metadata/runtime-images?1639113031595 (172.17.0.1) 138.43ms
[D 2021-12-10 05:10:31.783 ServerApp] Accepting token-authenticated connection from 172.17.0.1
[D 2021-12-10 05:10:31.786 ServerApp] Accepting token-authenticated connection from 172.17.0.1
[D 2021-12-10 05:10:31.787 ServerApp] Retrieving pipeline components for: airflow runtime
[D 2021-12-10 05:10:31.788 ServerApp] Retrieving active runtime information from PipelineProcessorRegistry...
[D 2021-12-10 05:10:31.795 ServerApp] Schemaspace 'component-catalogs' is using metadata directory: /home/jovyan/.local/share/jupyter/metadata/component-catalogs from list: ['/home/jovyan/.local/share/jupyter/metadata/component-catalogs', '/usr/local/share/jupyter/metadata/component-catalogs', '/usr/share/jupyter/metadata/component-catalogs', '/opt/conda/share/jupyter/metadata/component-catalogs']
[D 2021-12-10 05:10:31.798 ServerApp] 200 GET /elyra/pipeline/runtimes/types?1639113031601 (172.17.0.1) 12.32ms
[D 2021-12-10 05:10:31.800 ServerApp] Loading metadata instance from cache: 'apache_airflow_examples'

> {Code}

**Deployment information**
 - Elyra version: 3.3.0
 - Installation source: official container image
 - Deployment type: Docker
 - Operating system: macos, linux

**Comment by ptitzler** [comment]
Elyra uses minio and the S3 API to access cloud storage.

1) It appears that the API endpoint URL should be https://storage.googleapis.com. Can you update the runtime configuration  and try again?

 2) If that does not work, can you please 
- confirm that you've configured a default project https://cloud.google.com/storage/docs/migrating#defaultproj
- confirm that you've created  HMAC keys, e.g as mentioned here https://cloud.google.com/storage/docs/migrating#keys and used those keys as your credentials.

**Comment by harish-gaggar-infra** [comment]
Hi @ptitzler - Already tried using "https://storage.googleapis.com" but got the below error message 

> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
>     result = await result
>   File "/opt/conda/lib/python3.9/site-packages/elyra/pipeline/handlers.py", line 120, in post
>     response = await PipelineProcessorManager.instance().process(pipeline)
>   File "/opt/conda/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 147, in  [@process](url)
>     res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
>   File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/opt/conda/lib/python3.9/site-packages/elyra/pipeline/airflow/processor_airflow.py", line 124, in process
>     github_client.upload_dag(pipeline_filepath, pipeline_name)
>   File "/opt/conda/lib/python3.9/site-packages/elyra/util/git.py", line 75, in upload_dag
>     self.github_repository.create_file(path=pipeline_name + ".py",
>   File "/opt/conda/lib/python3.9/site-packages/github/Repository.py", line 2090, in create_file
>     headers, data = self._requester.requestJsonAndCheck(
>   File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
>     *self.requestJson(
>   File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
>     return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
>   File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 519, in __requestEncode
>     url = self.__makeAbsoluteUrl(url)
>   File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 591, in __makeAbsoluteUrl
>     assert o.hostname in [
> AssertionError: None

`

Also, I have also used "INTEROPERABILITY" feature to get Access Key and Secret for gcs bucket and added that to airflow configuration. Actually, I might mentioned in the Gitter that once I submit a job, it is able to create directory inside the GCS bucket with just a  notebook zip file but not any converted DAG file or so. This means, it is able to connect to GCS bucket. But it seems it just copying notebook files at GCS bucket as a zip files and not able to convert pipeline into Airflow DAG for further operations. 


![elyra_gcs](https://user-images.githubusercontent.com/84102457/145864132-cdf7eb29-82ce-43a5-a182-b2019113d8a8.png)

![ElyraAirflow](https://user-images.githubusercontent.com/84102457/145864490-586d565c-629d-4c90-b0d3-95014f8bea84.png)

**Comment by ptitzler** [comment]
That's progress! It appears that DAG upload to GitHub failed. Can you please provide your runtime configuration values for:
 - github api endpoint
 - github dag repository
 - branch

**Comment by harish-gaggar-infra** [comment]
https://github.com
harish-gaggar-infra/elyra_gcp_poc.git
master

**Comment by ptitzler** [comment]
Got it. The GitHub API endpoint is not correct: https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#github-api-endpoint-github-api-endpoint

**Comment by harish-gaggar-infra** [comment]
Thank you @ptitzler, It's working now. I just wanted to know is Kubernetes is the dependencies for Elyra pipeline to run in Airflow? I observed that DAG created with KubernetesPodOperator.
https://github.com/harish-gaggar-infra/elyra_gcp_poc/blob/master/demo7-1213214340.py#L39  

Is there are any way to create Airflow DAG for non Kubernetes platform?

**Comment by akchinSTC** [comment]
Elyra should run on airflow on non-k8s platform if you do not use the Generic Operators. (custom operators only e.g. bash_operator, email_operator etc.)
Our Generic Operators use the k8spod operator as a base class so k8s is a requirement for using them. Hope this helps

**Comment by harish-gaggar-infra** [comment]
Thank you @akchinSTC , one last question, Is there any way to avoid these secret https://github.com/harish-gaggar-infra/elyra_gcp_poc/blob/master/untitled5-1214021143.py#L30 during DAG file creation as I am referring non K8 env.

**Comment by ptitzler** [comment]
> 1. Is there any way to avoid these secrets https://github.com/harish-gaggar-infra/elyra_gcp_poc/blob/master/untitled5-1214021143.py#L30 during the DAG file creation as I am referring non K8 env.

If you leave the secret name empty in your runtime configuration Elyra the _clear text credentials_ will be passed to the task as environment variables. (Note that this implies that anybody with access to the GitHub repository and or Airflow can see the credentials since they are embedded in the DAG.)

> 2. When we drag .ipynb file at pipeline editor, is it configured to run on KubernetesPodOperator only or we can customize to run that using BashOperator like using papermill?

It's not possible to configure which operator is used to process _generic nodes_ that process Jupyter notebooks, Python scripts, and R scripts. However, you could implement a custom operator and use that one in your pipelines. For custom operator support details see [this blog post](https://medium.com/ibm-data-ai/elyra-3-3-pipelines-custom-components-and-catalogs-74cf198fdf48?source=friends_link&sk=ef91a56fbbae97bbaea77ff169d549dd) and [the documentation](https://elyra.readthedocs.io/en/latest/user_guide/pipeline-components.html).

> 3. Is there any way to push pipeline at Github at specific directory (like /dags), as it seems like by default dags files created at the github home directory

Currently this is not possible but support could probably be added.

**Comment by rajaji15** [comment]
hi @ptitzler  

Elyra Pushing the DAG's to Github and Python files to S3. But not creating pipeline is Airflow Runtime on K8s cluster.

Is it due to airflow version or any lead would be helpfule
