### ISSUE TITLE
Error when reading folders from previous step when using wildcard

### ISSUE THREAD

**Issue by alexisc67** [elyra-ai/elyra#2369]
I have an issue when passing a set of files from one step to the next one. 

In a step I set to output files from two folders:
data/train/tacos/\*.jpg
data/train/burrito/\*.jpg

When running this step the files are uploaded correctly to the storage in minio.

When executing the next step, there is an error presented that can't find a folder. It replaces the asterisk used in the item by %2A as you can see below in the path after tacos.

`minio.error.S3Error: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /mlpipeline-shared/elyra330azurepipeline02-1218202920/data/train/tacos/%2A.jpg, request_id:..`

I am using Elyra 3.3.0 running on Kubeflow Notebooks 1.4. Argo, Azure Kubernetes, minio, Token auth.

```
http://minio-service.kubeflow:9000
 "HEAD /mlpipeline-shared/elyra330azurepipeline02-1218202920/data/train/tacos/%2A.jpg HTTP/1.1" 404 0
Traceback (most recent call last):
  File "bootstrapper.py", line 634, in <module>
    main()
  File "bootstrapper.py", line 622, in main
    file_op.process_dependencies()
  File "bootstrapper.py", line 112, in process_dependencies
    self.get_file_from_object_storage(file.strip())
  File "bootstrapper.py", line 293, in get_file_from_object_storage
    file_path=file_to_get)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1073, in fget_object
    version_id=version_id,
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1911, in stat_object
    query_params=query_params,
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 422, in _execute
    no_body_trace=no_body_trace,
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 396, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /mlpipeline-shared/elyra330azurepipeline02-1218202920/data/train/tacos/%2A.jpg
```

**Comment by lresende** [comment]
Output wildcards are not yet supported see #1250 for some discussion...

**Comment by alexisc67** [comment]
Ok.

**Comment by alexisc67** [comment]
Close this one, since it is in this issue aready. https://github.com/elyra-ai/elyra/issues/1250

**Comment by chanansh** [comment]
The documentations says wildcards are supported... 
https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#output-files

> A list of files generated by the notebook inside the image to be passed as inputs to the next step of the pipeline. Specify one file, directory, or expression per line. Supported patterns are * and ?. Example: data/*.csv
