### ISSUE TITLE
use latest nbconvert

### ISSUE THREAD

**Issue by raybellwaves** [elyra-ai/elyra#2386]
Just tried a conda install with other packages and got 

Encountered problems while solving:
  - package elyra-2.2.4-pyhd8ed1ab_0 requires nbconvert >=5.6.1,<6.0, but none of the providers can be installed

Checked https://github.com/elyra-ai/elyra/issues?q=is%3Aissue+is%3Aopen+nbconvert and didn't see an issue raised so raising this

**Comment by kevin-bates** [comment]
This has been [fixed since the 3.0 release](https://github.com/elyra-ai/elyra/commit/7ccc300bd83fd3d8a0cec8f9256d20ea499efc4a) but, IIRC, we're having issues with conda packaging (cc: @akchinSTC).

Might you be able to instead use `pip install elyra`?

**Comment by akchinSTC** [comment]
yes, we're still working getting some of the dependencies published so we can get elyra 3.x on conda-forge. 
For now if possible, please use pypi to install elyra.

**Comment by ptitzler** [comment]
Conda-forge release progress updates will be posted in https://github.com/elyra-ai/elyra/issues/2232.
