### ISSUE TITLE
Copyright headers need annual update

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#2389]
Elyra Copyright headers need to be updated to include current year.

As per [this comment](https://github.com/elyra-ai/elyra/pull/2390#issuecomment-1011567436), all other repositories in the elyra org must be updated.

**Comment by akchinSTC** [comment]
Going to need to coordinate this so we dont create too conflicts during merge. 
Also copyrights should be updated when the file has been modified.

**Comment by lresende** [comment]
> Also copyrights should be updated when the file has been modified.

Not necessarily, we can just go ahead and update all files in all repos, this is what we have been doing before. 

> Going to need to coordinate this so we don't create too conflicts during merge.

Git is intelligent enough to make merging easier if there are no changes on the same line.
