### ISSUE TITLE
CLI: Add support for metadata export

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2404]
**Is your feature request related to a problem? Please describe.**
As a user I want to have the ability to back up [and restore - out of scope for this ER] metadata with the intent to store a copy in a custom file system location. In combination with import (again, out of scope for this enhancement request) this would allow for
 - backup (disaster recovery)
 - improved testing
 - cloning of deployments

**Describe the solution you'd like**
```
elyra-metadata export <schemaspace> [--schema_name=<schema>] [--valid-only] --directory=<path>
```
- `<schemaspace>` (required): one of the supported schemaspaces, like `runtimes`, `code-snippets`, or `runtime-images`
- `schema_name` (optional): if supplied and applicable, only instances of the provided `<schema>` are exported
-  `valid-only` (optional): if specified, only valid instances are exported. The default is to export all instances, which is identical to the behavior of the `elyra-metadata list` command
- `directory` (required): 
    - local file system `path` where the exported metadata will be stored
    - the specified directory is created if it does not exist
    - the exported `<schemaspace>` metadata is stored in a subdirectory of `<path>`, named after the `<schemaspace>`, e.g. `<path>/runtimes` or `<path>/code-snippets`. 
    - The export format is the [JSON] format that is used  internally to store metadata.

### Examples

- Export all (valid and invalid) runtime configurations to `/tmp/foo`

  ```
  elyra-metadata export runtimes --directory=/tmp/foo
  ```

  This command creates the `/tmp/foo/runtimes` directory and stores all valid and invalid runtime configuration instances in that directory.

- Export all Kubeflow Pipelines runtime configurations to `/tmp/foo`

  ```
  elyra-metadata export runtimes --schema_name=kfp --directory=/tmp/foo
  ```

  This command creates the `/tmp/foo/runtimes` directory and stores all valid and invalid Kubeflow Pipelines runtime configuration instances in that directory.

- Export all valid Kubeflow Pipelines runtime configurations to `/tmp/foo`

  ```
  elyra-metadata export runtimes --schema_name=kfp --valid-only --directory=/tmp/foo
  ```

  This command creates the `/tmp/foo/runtimes` directory and stores all valid Kubeflow Pipelines runtime configuration instances in that directory.

Note:
 - The exported metadata format should be importable as is. [This PR](https://github.com/elyra-ai/elyra/pull/2378) introduces CLI functionality that would already allow for import of these files, e.g. `elyra-metadata install <namespace>`, but should probably not be seen as a replacement for an `elyra-metadata import` command.

**Comment by kevin-bates** [comment]
Thanks @sandhya-nayak!

Regarding the output directory (e.g., `/tmp/foo/runtimes`), I think we should tolerate its existence as well.  I suppose we could talk about whether the contents should be cleared or not.  I'm inclined to not clear contents.

When we get around to `import`, I think we should tolerate the specification of either `/tmp/foo` or `/tmp/foo/runtimes` when a schemaspace of `runtimes` is specified, since I believe the latter form will be more natural for folks.

**Comment by sandhya-nayak** [comment]
As discussed in the Weekly Dev meeting, I'll be adding a "--clean" flag which would indicate that the user wants to clean out the folder for the schemaspace within the "--directory" (for e.g. delete everything inside /tmp/foo/runtimes). In the absence of the "--clean" flag, any exported file will overwrite the existing file with the same name leaving the others untouched.
