### ISSUE TITLE
Remove support for the deprecated `component-registries` schemaspace

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#2405]
**Is your feature request related to a problem? Please describe.**
The `component-registries` schemaspace has been deprecated as of 3.3, at which time it was replaced by the `component-catalogs` schemaspace. A `migrate` script was also provided (via the CLI) that converted a user's existing `component-registries` instances into `component-catalog` instances. We expect that most people that had user-created `component-registries` instances have, by now, migrated those instances and that support can be dropped.

Note that a user upgrading directly from Elyra < v3.3 to a version that no longer supports this schemaspace will not see any of their instances and will need to install a down-level release in order to migrate to `component-catalogs`.

This will likely also require documentation changes.

**Describe the solution you'd like**
Completely remove support for and references to the `component-registries` schemaspace.

**Describe alternatives you've considered**
Leave as-is until a major release.

**Comment by ptitzler** [comment]
> [...] that a user upgrading directly from Elyra < v3.3 to a version that no longer supports this schemaspace 

For later reference - impacted are versions 3.1 and 3.2: https://github.com/elyra-ai/elyra/pull/2083 introduced the schemaspace
