### ISSUE TITLE
Move to support Jupyterlab 3.3

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#2415]
Jupyterlab 3.3 will bring select non-api changing features and fixes originally planned for 4.0

Elyra has been waiting on some of these features and fixes and this issue is to track that list of issues and track the update to use 3.3 if pinning to the new minor release is required

3.3 blocked issues:
- [x] https://github.com/elyra-ai/elyra/issues/2374

Issues specifically blocked by https://github.com/jupyterlab/jupyterlab/pull/11079
- [ ] https://github.com/elyra-ai/elyra/issues/2269
- [ ] https://github.com/elyra-ai/elyra/issues/2337
- [ ] https://github.com/elyra-ai/elyra/issues/2338

Tracking Issue for back ported PRs to 3.3 https://github.com/jupyterlab/jupyterlab/issues/11643

**Comment by ajbozarth** [comment]
@karlaspuldaro https://github.com/elyra-ai/elyra/issues/2375 is blocked by https://github.com/jupyterlab/jupyterlab/pull/10758 do you know if that PR is API breaking (meaning has to wait till 4.0)? Because if it isn't you can raise it on https://github.com/jupyterlab/jupyterlab/issues/11643 to have it back ported to 3.3 and we'll add it here

**Comment by ajbozarth** [comment]
https://github.com/elyra-ai/elyra/issues/1943 can be added to this if/when https://github.com/jupyterlab/jupyterlab/pull/11540 is back ported to 3.3

**Comment by karlaspuldaro** [comment]
I believe #2375 is a 4.0 since we will be updating the libraries to v4

**Comment by karlaspuldaro** [comment]
#2019 can be added to this list

**Comment by lresende** [comment]
When doing this, could we also try running something like the code below  (run from Jupyterlab source directory) to update the transient dependencies? Note that, as we are trying to update the lab dependencies as well, we should probably run twice, one with the regex filtering and one without:
```
jlpm run  update:dependency  --regex '^(@jupyterlab|@lumino|typescript|rimraf)' latest --regex --path ~/opensource/elyra/elyra
```
