### ISSUE TITLE
Airflow | Kubeflow Pipelines tiles are displayed in unpredictable order in the launcher

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2423]
**Describe the issue**

The order in which the two tiles is displayed appears to be somewhat random.

![image](https://user-images.githubusercontent.com/13068832/151422609-04e17131-f395-4b42-bdd0-4779d5fc1a09.png)

![image](https://user-images.githubusercontent.com/13068832/151423486-aab05910-c3df-41f5-99e6-a27d7bc30e20.png)

Sometimes KFP is displayed first, sometimes AA. Because the behavior is not predictable I sometimes click on the "wrong" tile. For example, 9/10 of the times the AA  VPE tile is third one in the list.

**To Reproduce**
1. Open JL
2. Inspect the 'Elyra' group in the launcher window

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.5/master

**Comment by samali0996** [comment]
I'm interested in working on this issue!

**Comment by karlaspuldaro** [comment]
Thank you @samali0996 :)
