### ISSUE TITLE
R icon missing intermittently from tile in elyra launch page

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2462]
**Describe the issue**
See picture
![image](https://user-images.githubusercontent.com/13340013/153083669-db226d18-869d-460f-a1c2-9cddaaaebf23.png)

**To Reproduce**
1. Install and start elyra
2. Should see missing icon picture in splash

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
R Icon to be visible in tile

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.6.0rc0
 - Installation source: pypi
 - Deployment type: local
 - Operating system: macos

**Comment by ptitzler** [comment]
During today's dev meeting @ajbozarth suspected that this might be caused by the svg we are using. If that's the case we might want to consider switching to the icon that JupyterLab is using. (See https://github.com/elyra-ai/elyra/issues/2463)

**Comment by karlaspuldaro** [comment]
I was not able to reproduce this issue in 3.6.0rc0, although it's somewhat noticeable the R icon seems to be the last item to finish rendering in previous elyra versions as well. Given the rendering inconsistency of this specific icon, I agree to consider the change proposed by @ptitzler .

**Comment by karlaspuldaro** [comment]
I was finally able to reproduce this in v3.8.0. 
The R icon only disappears from the launcher card when some left side tab is open (eg. open code snippets widget). If file browser tab is open, the icon renders in launcher as expected.
@ajbozarth can you confirm this pattern, any ideas why the side bar widgets would affect the icon rendering?

**Comment by ajbozarth** [comment]
I've given up and decided to just recode our r-logo. I'll open a PR in a bit
