### ISSUE TITLE
quality of life - open "node properties" on double-click

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2470]
## Background 

Currently, opening the "node properties" menu (image 1) is not intuitive and requires multiple clicks. 
To open the menu, you must either right-click on a node (image 2)  or know about the small button at the top right (image 3).

## Proposal

I believe the intuitive behavior is that double-clicking on a node expands/collapses the "node properties" menu.

### Image 1

![Screen Shot 2022-02-10 at 12 04 52](https://user-images.githubusercontent.com/5735406/153317007-5c9f098f-1b0b-468d-8389-b258ef1a0a14.png)

### Image 2
![Screen Shot 2022-02-10 at 12 04 04](https://user-images.githubusercontent.com/5735406/153316914-4cd53969-5d1c-4c97-a2b6-a64f58081a39.png)

### Image 3
![Screen Shot 2022-02-10 at 12 06 17](https://user-images.githubusercontent.com/5735406/153317128-7b93c28d-d9ef-4480-acdb-56548560e621.png)

**Comment by ptitzler** [comment]
Duplicate of https://github.com/elyra-ai/elyra/issues/2017, which requires https://github.com/elyra-ai/elyra/issues/2275 to make the behavior customizable.
