### ISSUE TITLE
Allow for manual list refresh in the metadata editor

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2504]
**Is your feature request related to a problem? Please describe.**

In certain scenarios the list of metadata instances displayed in the GUI might not reflect the actual instances that are stored in the file system. In this case a user has to navigate to a different metadata panel to trigger an implicit reload of the list. Since this is not intuitive, we should add a refresh button:

![image](https://user-images.githubusercontent.com/13068832/155766712-e75a3364-c916-47fe-a3e7-0d7a3de4651c.png)

**Describe the solution you'd like**

See JupyterLab file browser
![image](https://user-images.githubusercontent.com/13068832/155766182-881e6277-6a40-4029-b282-77ad4a028b19.png)

**Comment by thesuperzapper** [comment]
Related to https://github.com/elyra-ai/elyra/issues/2238

**Comment by thesuperzapper** [comment]
@ptitzler I think the component catalog refresh is the most important metadata-type to allow manual refreshing ASAP, given how likley catalogs are to change, and how cumbersom the manual refresh is right now.

To refresh a catalog right now, you have to:
1. Open the edit menu for the catalog
2. Click "SAVE & CLOSE" (without making any changes) 
3. Close and reopen any open ".pipeline" files.

___PS:__ this is especially important if we include an Artifactory connector in the core project like proposed in https://github.com/elyra-ai/examples/pull/99, as it would be expected to update often._
