### ISSUE TITLE
Components installed via Elyra CLI do not appear in KFP Editor

### ISSUE THREAD

**Issue by lehrig** [elyra-ai/elyra#2515]
**Describe the issue**
Successfully added components using the Elyra CLI (`elyra-metadata install component-catalogs ...`)  **do not appear** in the Kubeflow Pipeline Editor.

**To Reproduce**
1. Go to 'Component Catalogs' view
<img width="431" alt="Bildschirmfoto 2022-03-01 um 19 34 27" src="https://user-images.githubusercontent.com/9555494/156228216-23a9f4f2-a978-47c7-865b-d414fec78a0b.png">

2. Confirm that the catalog is empty.
3. Inside Jupyter Lab, open a terminal and add any component catalog using the Elyra CLI:

```
elyra-metadata install component-catalogs \
       --display_name="filter components" \
       --description="filter text in files" \
       --runtime_type=KUBEFLOW_PIPELINES \
       --schema_name="url-catalog"\
       --paths="['https://raw.githubusercontent.com/elyra-ai/elyra/master/etc/config/components/kfp/filter_text_using_shell_and_grep.yaml']" \
       --categories='["filter content"]' 
```
<img width="958" alt="Bildschirmfoto 2022-03-01 um 19 38 28" src="https://user-images.githubusercontent.com/9555494/156228818-67459d34-770e-4745-bf1b-7d7b05553e03.png">

4. Confirm that the catalog got applied successfully
`elyra-metadata list component-catalogs`
<img width="902" alt="Bildschirmfoto 2022-03-01 um 19 39 45" src="https://user-images.githubusercontent.com/9555494/156228992-65c356d2-bbd7-4b55-a398-aa3fa0e2e2b3.png">

5. On the side bar menu, go to another view and then back to the 'Component Catalogs' view to get this update:
<img width="435" alt="Bildschirmfoto 2022-03-01 um 19 42 11" src="https://user-images.githubusercontent.com/9555494/156229321-44ea29c5-77fa-4bb0-be6e-2ebf75072a9e.png">

6. Open a new Kubeflow Pipeline Editor and note that the new component does not appear (this is the referred bug!):
<img width="991" alt="Bildschirmfoto 2022-03-01 um 19 44 10" src="https://user-images.githubusercontent.com/9555494/156229605-35547039-c532-4bdf-af56-6b941a186f03.png">

7. To hot-fix the bug, simply edit the component catalog and directly "SAVE & CLOSE" using the UI (!!). A new Kubeflow Pipeline Editor will then show the new component.

**Expected behavior**
The added component should appear in a new Kubeflow Pipeline Editor.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.6.0
 - Operating system: linux (RHEL 8.4 on ppc64le; SELinux enabled)
 - Installation source: custom container image (https://github.com/lehrig/kubeflow-ppc64le-images/blob/main/Dockerfile.all-in-one -> quay.io/ibm/kubeflow-notebook-image-ppc64le:elyra3.6.0-py3.8-tensorflow-cpu2.7.0)
 - Deployment type: Kubeflow (v1.4.1) Notebook Server on OpenShift v4.8

**Comment by lehrig** [comment]
We already discussed two potential causes:
1. Caching; disabling it might help (see https://github.com/elyra-ai/elyra/pull/1846#issuecomment-870979724)
2. SELinux; disabling it might help

We'll test these potential solutions next

**Comment by thesuperzapper** [comment]
Related to:
- https://github.com/elyra-ai/elyra/issues/2504
- https://github.com/elyra-ai/elyra/issues/2238

**Comment by ptitzler** [comment]
Starting with version 3.7:
 - Elyra should recognize out-of-process updates (atm out-of-process updates are metadata updates that are performed using the `elyra-metadata` CLI)
 - users have the option to manually refresh the metadata instance list  (see previous comment)
