### ISSUE TITLE
Refresh system-owned runtime images

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2516]
**Is your feature request related to a problem? Please describe.**
The Elyra distribution [includes a set of system-owned runtime image configurations](https://github.com/elyra-ai/elyra/tree/master/etc/config/metadata/runtime-images) to make it easier for Visual Pipeline Editor users to get started with Jupyter notebooks, Python scripts, and R scripts.  Many of those configuration were created more than a year ago and are likely referencing images that could be considered stale. For example, the Pandas image uses Pandas 1.1.1 whereas the latest available version is [1.4.1](https://hub.docker.com/r/amancevice/pandas/tags).

**Describe the solution you'd like**
- Identify the latest version for each container image
- Update the existing system owned configurations

**Comment by ptitzler** [comment]
Great. Thank you! The issue was assigned to you.

**Comment by Hema-Mathiyazhagan** [comment]
for this issue, I would like to go with "Identify the latest version for each container image" option as updating the existing system owned configurations may lose patch fixes in the recent releases. For example pandas 1.4.1 has solved many regression issues related to read_csv option. we might lose these updates if we go with updating existing configuration.

**Comment by yarnabrina** [comment]
@lresende Can we not just use the `latest` tags instead of a fixed version?

**Comment by ptitzler** [comment]
> @lresende Can we not just use the `latest` tags instead of a fixed version?

The problem with using `latest` is that existing Elyra assets (notebooks etc) might break when `latest` resolves to a version that contains breaking changes.. By pinning to a specific version we have ensured that this doesn't happen.

**Comment by Hema-Mathiyazhagan** [comment]
@ptitzler @karlaspuldaro can we close this issue as the PR is merged?

**Comment by ptitzler** [comment]
Done! It appears that the PR description didn't include one of the magic keywords `closes`, `fixes` etc and therefore it wasn't associated with this issue.
