### ISSUE TITLE
Cannot connect to notebook with elyra/kf-notebook image

### ISSUE THREAD

**Issue by edwardzjl** [elyra-ai/elyra#2541]
Hi there, I'm new to elyra, I want to try elyra on my kubeflow cluster (version 1.4.0).

Following [this doc](https://elyra.readthedocs.io/en/stable/recipes/using-elyra-with-kubeflow-notebook-server.html) (it seems a bit out-dated as on newer version of kubeflow the `Notebook Servers` has been changed to `Notebooks`), I created a notebook with image `elyra/kf-notebook:3.6.0`

The notebook launched successfully and is in `Running` state:

![image](https://user-images.githubusercontent.com/7287580/157372999-9bfd9c3e-74e5-454c-bd8f-7735ef7ec689.png)

But I cannot connect to it. Once I click the `CONNECT` button it gives me a 404 page:

![image](https://user-images.githubusercontent.com/7287580/157373075-7034d298-d554-41e6-bc4a-3127e3b804bf.png)

**Comment by thesuperzapper** [comment]
@edwardzjl do you see any logs on the notebook Pod? (Using something like `kubectl logs ...`)

**Comment by thesuperzapper** [comment]
@edwardzjl I see that you have selected "type 2" for the notebook, I believe this is for RStudio (which will not work with JupyterLab). Make sure you select "JupyterLab" when specifying your image (including if using "custom image"):

![Screen Shot 2022-03-09 at 15 47 28](https://user-images.githubusercontent.com/5735406/157374753-5770bf8b-48d6-4585-981a-cc4300cac991.png)

**Comment by edwardzjl** [comment]
Thank you very much, I don't know why `type 1` and `type 2` does not show the correct icon, I accidentally clicked `type 2` before launching the notebook.

It works now, I'm going to close this issue. Thank you!
