### ISSUE TITLE
"run details" link is invalid for KUBERNETES_SERVICE_ACCOUNT_TOKEN

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2545]
Currently, when using `KUBERNETES_SERVICE_ACCOUNT_TOKEN` authentication type for Kubeflow Pipelines, the `"run details"` link provided in the popup after each pipeline run will never link to a valid URL.

![Screen Shot 2022-03-09 at 18 38 33](https://user-images.githubusercontent.com/5735406/157394900-22cd2321-9d2b-472e-a402-c1b205565bed.png)

This is caused by the requirement to set `"api_endpoint"` as the `xxx.svc.cluster.local` internal Service address (e.g. `http://ml-pipeline-ui.kubeflow.svc.cluster.local/pipeline`) when using `KUBERNETES_SERVICE_ACCOUNT_TOKEN`, and this endpoint is not going to be accessible from the user's browser.

We should add a new field to `KUBEFLOW_PIPELINES` runtimes, which allows specifying the `"public_endpoint"` (e.g. `https://kubeflow.example.org/pipelines`), which we will use for any user-presented links. 

NOTE: the code which generates the link provided as "run details" can be found at [elyra/pipeline/kfp/processor_kfp.py#L366](https://github.com/elyra-ai/elyra/blob/33c087091ec5612a6d8471a0333719bcfd046c0e/elyra/pipeline/kfp/processor_kfp.py#L366).

**Comment by ptitzler** [comment]
Side notes: 
- the general issue should also surface for other KFP authentication type configurations
- the issue also surfaces in the RTC preview. A fix should also prevent the display of the API endpoint as a link and display the 'public' link, if one was specified.
   
   ![image](https://user-images.githubusercontent.com/13068832/157501443-6c59b355-5d94-4596-ad03-25632b0f2721.png)
