### ISSUE TITLE
Export pipeline (YAML) via CLI command

### ISSUE THREAD

**Issue by eyalcha** [elyra-ai/elyra#2571]
**Is your feature request related to a problem? Please describe.**
Currently the only way to export the pipeline yaml file is from the UI. I would like to be able to generate this file from an external tool that will have interface to Elyra deployment. 
This file is needed when creating a pipeline in Kubeflow pipelines from external tool and still using Elyra as the development environment.

**Describe the solution you'd like**
I would like an option to export the pipeline configuration (yaml) using CLI or REST API.

**Comment by kevin-bates** [comment]
Hi @eyalcha - yeah, we should definitely add an export option to the pipeline CLI, not sure why that isn't the case already.

Here's the REST API for pipeline export: https://github.com/elyra-ai/elyra/blob/53a353884ca74797d909351f9a04ba49a03021cc/elyra/api/elyra.yaml#L343-L370

As best as I can tell you should be able to load the pipeline file as JSON and reference that in the `pipeline` field of the request body JSON.
