### ISSUE TITLE
Remove support for elyra-metadata CLI command 'install'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2580]
**Is your feature request related to a problem? Please describe.**
With the delivery of https://github.com/elyra-ai/elyra/pull/2578, support for the `elyra-metadata install` command was deprecated. The command is replaced by `elyra-metadata create` and `elyra-metadata update`.

**Describe the solution you'd like**
- Update source code in https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/metadata_app.py
   - remove class `SchemaspaceInstall`
   - remove class `Install`
   - update class `MetadataApp` (remove all references to `install`)
   - remove all tests in https://github.com/elyra-ai/elyra/blob/master/elyra/tests/metadata/test_metadata_app.py named `test_install_*`
- Updates to the documentation and other assets in this repository should _not_ be required, because https://github.com/elyra-ai/elyra/pull/2578 addressed those already.

**Comment by Hema-Mathiyazhagan** [comment]
@ptitzler I would like to work on this issue. can you assign this issue to me?

**Comment by ptitzler** [comment]
Can do, but it's probably best to defer working on a PR. There will be _at least_ one more release between now and version 4.0. As a result we will not be able to merge the PR until those releases were published and some additional work might be required when we are ready to incorporate it into the 4.0 code base.
