### ISSUE TITLE
Metadata editor field not populating existing metadata instances

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2592]
**Describe the issue**
When a user opens a previously created metadata instance the editor widget shows mostly empty properties

**To Reproduce**
1. Open an existing metadata instance (of any type except code snippet) in the editor. 

![image](https://user-images.githubusercontent.com/13068832/160016097-a2449d05-a54c-4727-b204-8cf442ed6783.png)

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7/master

**Comment by lresende** [comment]
Thanks for raising this, I thought this was a local env issue, and it was driving me crazy.
