### ISSUE TITLE
Notebook kernel launch items disappears if language changed to Chinese

### ISSUE THREAD

**Issue by yuhuishi-convect** [elyra-ai/elyra#2597]
**Describe the issue**
If the Chinese language pack is installed and the language setting is changed to Chinese, then the notebook launch items disappear from the launcher. 

**To Reproduce**

```bash

python -m venv .venv
source .venv/bin/activate

pip install -r <(cat<< EOF
jupyterlab==3.3.2
jupyterlab-language-pack-zh-CN==3.3.post2
ipykernel==6.9.2
elyra==3.6.1
EOF
)

jupyter lab
```

Then set language to Chinese in the settings menu and refresh.

**Screenshots or log output**

Language set as Chinese

![image](https://user-images.githubusercontent.com/74702693/160207179-1b39abf9-113e-4333-8701-c3c699e92dff.png)

Language set as English

![image](https://user-images.githubusercontent.com/74702693/160207143-91a134fe-e365-4877-bbb1-a55e2692b7d8.png)

**Expected behavior**

Assume the displayed launcher layout should be same

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.6.0
 - Installation source: conda
 - Deployment type: docker
 - Operating system: linux

**Comment by ptitzler** [comment]
@yuhuishi-convect Have you tried the same scenario using a plain vanilla JupyterLab installation?

**Comment by yuhuishi-convect** [comment]
> @yuhuishi-convect Have you tried the same scenario using a plain vanilla JupyterLab installation?

No I didn't see the issue in vanilla jupyterlab

Language set as English
![image](https://user-images.githubusercontent.com/74702693/160897760-3cf4a49d-aeda-4232-a22a-467220f0e70b.png)

Language set as Chinese
![image](https://user-images.githubusercontent.com/74702693/160897850-4026862d-bfd0-40a9-97b8-3c7042715838.png)

**Comment by ptitzler** [comment]
@ajbozarth?

**Comment by yuhuishi-convect** [comment]
Thanks for the very prompt fix @ajbozarth

**Comment by ajbozarth** [comment]
I've opened https://github.com/elyra-ai/elyra/pull/2613 to address this. The issue was cause by our overriding of the Launcher without using the translation service.

I've also opened https://github.com/elyra-ai/elyra/issues/2614 as a future task of moving the rest of Elyra to support translation
