### ISSUE TITLE
Timeout is 0s 

### ISSUE THREAD

**Issue by Shreyanand** [elyra-ai/elyra#2607]
**Describe the issue**
Elyra creates a  kubeflow pipeline yaml with Timeout as 0s. This doesn't give the pipeline time to execute. 

**To Reproduce**
1. Go to Jupyterhub with Elyra image
2. Configure Kubeflow runtime
3. Add a notebook to a pipeline
4. Run the pipeline

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
The error that we see:

`failed to create task run pod "lambda-108fc-pdf-text-extraction-pgphp":        
Pod "lambda-108fc-pdf-text-extraction-pgphp-pod-k8xs8" is invalid:         
spec.activeDeadlineSeconds: Invalid value: 0: must be between 1 and         
2147483647, inclusive. Maybe invalid TaskSpec`

Yaml screenshot:
![Screenshot from 2022-03-29 10-38-05](https://user-images.githubusercontent.com/8916126/160637048-e49bc3d1-cacc-4715-98f6-b8ad42b4df78.png)

**Expected behavior**
Timeout should be higher for the pipeline to execute. If we go to the kubeflow instance and submit the same yaml with a higher timeout, it works.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.4
 - Operating system: linux
 - Installation source: 
 - Deployment type: Open Data Hub

**Pipeline runtime environment**
 - Kubeflow Pipelines (provide version number, whether multi-user auth enabled)

@HumairAK

**Comment by akchinSTC** [comment]
odh manifest changes are in progress for the new image, will update this when that PR is open and subsequently merged

**Comment by HumairAK** [comment]
We're using https://github.com/kubeflow/kfp-tekton/tree/v1.1.1
We'll attempt this with the latest elyra image and follow up

**Comment by Shreyanand** [comment]
@ptitzler Using the updated image fixed the issue, thanks!
