### ISSUE TITLE
Bootstrapper fails if installing editable package in docker image

### ISSUE THREAD

**Issue by eyalcha** [elyra-ai/elyra#2608]
**Describe the issue**
When installing python package in runtime docker image with editable option (-e), the bootstrapper fails to run.
The command that was used to  install the package is: ```RUN pip install -e ./model_utils```

**Screenshots or log output**
The installed packages:
```
# pip freeze
certifi==2021.10.8
joblib==1.1.0
minio==7.1.5
# Editable install with no version control (model-utils==0.0.4)
-e /model_utils
numpy==1.22.3
pandas==1.4.1
python-dateutil==2.8.2
pytz==2022.1
scikit-learn==1.0.2
scipy==1.8.0
six==1.16.0
threadpoolctl==3.1.0
urllib3==1.26.9
```
The error is:
```
[D 06:36:56.914] Parsing Arguments.....
[I 06:36:56.916] 'model-0329063649':'pre' - starting operation 
[I 06:36:56.916] 'model-0329063649':'pre' - Installing packages 
Traceback (most recent call last):
  File "/jupyter-work-dir/bootstrapper.py", line 652, in <module>
    main()
  File "/jupyter-work-dir/bootstrapper.py", line 635, in main
    OpUtil.package_install(user_volume_path=input_params.get('user-volume-path'))
  File "/jupyter-work-dir/bootstrapper.py", line 524, in package_install
    current_packages = cls.package_list_to_dict("requirements-current.txt")
  File "/jupyter-work-dir/bootstrapper.py", line 571, in package_list_to_dict
    package_name, package_version = line.strip('\n').split(sep="==")
ValueError: not enough values to unpack (expected 2, got 1)
```

Note that if .git is present in the python package, the package will be shown as follow:
```
-e git+ssh://git@github...........git@e7836767b866db106d1fae7e38415529bce02262#egg=model_utils
```

**Expected behavior**
The bootstrapper should ignore the -e and load the package (or ignore it)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: Master
 - Installation source: [custom container image]
 - Deployment type: [local installation, Docker, Kubernetes]
 - Operating system: [macos]

**Comment by ptitzler** [comment]
To address the general issue we need to improve how the output of the `pipe freeze` command is 
 processed to allow for entries that don't meet the currently supported patterns:
 - https://github.com/elyra-ai/elyra/blob/master/elyra/kfp/bootstrapper.py#L520-L544 (KFP)
 - https://github.com/elyra-ai/elyra/blob/master/elyra/airflow/bootstrapper.py#L333-L357 (Airflow)
