### ISSUE TITLE
Submitting python or R script alone with dependency box checked results in failure

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2610]
**Describe the issue**
Submitting python or R script by itself, without any dependencies(additional files), with the dependency box checked results in a failure

**To Reproduce**
1. Open the Python or R script editor
2. Paste in any python cmds e.g. print("Hello World")
3. Select Run as Pipeline
4. Leave the Include File Dependencies box checked 
5. click Ok

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

![image](https://user-images.githubusercontent.com/13340013/160717956-f968d28a-38fa-4a43-9338-c29ae1d27850.png)

![image](https://user-images.githubusercontent.com/13340013/160717415-c2060350-420e-40c1-834e-04ff4327fac3.png)

**Expected behavior**
 
**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7.0rc0
 - Installation source: pypi
 - Deployment type: local
 - Operating system: macos

**Comment by karlaspuldaro** [comment]
@akchinSTC I tried reproducing this and I was able to successfully submit a pipeline from both python and r scripts, using the default checked box for file dependencies, for existing files and newly created ones, no request errors. What am I missing? 🤔

**Comment by akchinSTC** [comment]
@karlaspuldaro - that worked and the entry box remains grayed out to provide an example for users. Thanks for this

**Comment by lresende** [comment]
If I understood it correctly, the suggested fix on #2637 is disabling the check to enable dependencies by default. But if the user goes and checks the box, isn't it going to see the same issue? Shouldn't we try to fix the actual problem and avoid the issue when the checkbox is checked?

NOT A CONTRIBUTION

**Comment by kevin-bates** [comment]
I think the proposed fix is to remove the default _value_ (.e.g, `*.py` or `*.r`).  It sounds like the box can remained checked by default.  I would suggest we not have the box checked by default if there are no defaulted values though.  (Sorry if that change was also made.  I only see the `defaultValue` removed, so I assume the box is still checked.)

**Comment by karlaspuldaro** [comment]
@lresende @kevin-bates is correct, we just removed the default value from the input box, the check box is still checked as default and the placeholder value is still there grayed out to guide users on what kind of input is expected.
We can leave the box unchecked by default as well.

**Comment by kevin-bates** [comment]
Ah, thanks @karlaspuldaro, I didn't realize the text (value) was grayed out - that makes sense.  Would it be possible to not have the box checked with the text grayed out and when the box gets checked, enable the grayed out default value?  That seems like a more intuitive user experience (to me).

**Comment by lresende** [comment]
I still think we have a bug on the backend and we are trying to mask it via these UI changes. 

NOT A CONTRIBUTION

**Comment by kevin-bates** [comment]
> I still think we have a bug on the backend and we are trying to mask it via these UI changes.

@lresende - I see what you are saying and have included the failed request's complete stack trace. Seems like the request needs to fail more gracefully when no dependencies are found.

I could see a nice UX being something that would _ignore_ the lack of dependencies only when a wild-card is used to express them and fail when they've been specified explicitly, but that might be more difficult, so the two cases (where neither expression yields files) should probably be handled gracefully.

<details>
  <summary>Complete stack trace of submit request</summary>

```
[I 2022-04-05 16:28:09.553 ElyraApp] kfp 'untitled':'untitled' - processing operation dependencies for id: cdd8d815-9de6-489f-9ee4-f132a6d6da8f 
[E 2022-04-05 16:28:09.561 ElyraApp] Dependencies were not found building archive for operation: untitled
    Traceback (most recent call last):
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 384, in _upload_dependencies_to_object_store
        dependency_archive_path = self._generate_dependency_archive(operation)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 368, in _generate_dependency_archive
        archive_artifact = create_temp_archive(
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/util/archive.py", line 124, in create_temp_archive
        raise FileNotFoundError(filenames_set - matched_set)  # Only include the missing filenames
    FileNotFoundError: {'*.py'}
[E 2022-04-05 16:28:09.563 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1649201287849 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1649201287849', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 384, in _upload_dependencies_to_object_store
        dependency_archive_path = self._generate_dependency_archive(operation)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 368, in _generate_dependency_archive
        archive_artifact = create_temp_archive(
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/util/archive.py", line 124, in create_temp_archive
        raise FileNotFoundError(filenames_set - matched_set)  # Only include the missing filenames
    FileNotFoundError: {'*.py'}
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 243, in process
        kfp_argo_compiler.Compiler().compile(pipeline_function, pipeline_path, pipeline_conf=pipeline_conf)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1175, in compile
        self._create_and_write_workflow(
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1227, in _create_and_write_workflow
        workflow = self._create_workflow(pipeline_func, pipeline_name,
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/kfp/compiler/compiler.py", line 1005, in _create_workflow
        pipeline_func(*args_list, **kwargs_dict)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 226, in <lambda>
        pipeline_function = lambda: self._cc_pipeline(  # nopep8 E731
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 543, in _cc_pipeline
        self._upload_dependencies_to_object_store(runtime_configuration, cos_directory, operation)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 409, in _upload_dependencies_to_object_store
        raise FileNotFoundError(
    FileNotFoundError: Node 'untitled' referenced dependencies that were not found: {'*.py'}
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/handlers.py", line 125, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 147, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/envs/elyra-dev/lib/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 247, in process
        raise RuntimeError(
    RuntimeError: Failed to compile pipeline 'untitled' with engine 'Argo' to: '/var/folders/4w/qxgsbhyx1y93qlk9mnzwjryc0000gn/T/tmpj2jo4mcs/untitled.tar.gz'
[E 2022-04-05 16:28:09.566 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "904",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
      "X-Xsrftoken": "2|a34dac9b|23f1949905e4e197499df20dc5812ce7|1648499639",
      "Authorization": "token 91b1f288ecf0807a26a6428cc5184ebe1f6ba7b7947703bd",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Sec-Gpc": "1",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/alice/Kubernetes/untitled.py",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1646962480|23:username-localhost-8889|44:MDA2YzgyNzQwNzcwNDI1YmJiNTVjOTRlZGVhNDMyMDc=|22f00454036963a563adccef1d3c10b85b8acad285443174978098d3e29ce574\"; _xsrf=2|a34dac9b|23f1949905e4e197499df20dc5812ce7|1648499639; username-localhost-8888=\"2|1:0|10:1649201285|23:username-localhost-8888|44:NWU2OTZhNzVlYmFhNDU0YjliNmYyYjE0ZmI2ODA5MGU=|f4ada548736947b50391fa1d8625312b12581ddba68a582cd5e4b98acb58b44f\""
    }
[E 2022-04-05 16:28:09.566 ServerApp] 500 POST /elyra/pipeline/schedule?1649201287849 (::1) 1713.37ms referer=http://localhost:8888/lab/tree/alice/Kubernetes/untitled.py
```
</details>

@karlaspuldaro - when attempting to reproduce this, did you ensure that the directory in which your Lab file explorer was listing did not have any additional python or R files besides the script being submitted?  I found that if simply touched another file (e.g., `foo.py`) then the submission worked fine.  It failed only when there were no other python files present (besides the script itself).

**Comment by karlaspuldaro** [comment]
@kevin-bates Thank you for the info, and I was able to reproduce the issue now, the request failure happens on the scenario you described and requires better handling dependencies on the backend.
On the frontend do we still want the file dependency box unchecked by default as part of these changes?

**Comment by kevin-bates** [comment]
> On the frontend do we still want the file dependency box unchecked by default as part of these changes?

I personally think so, but the problem is certainly lessened with a fix to the backend.  That said, I think there could be some ambiguity that folks might think their actual script is considered a dependency by virtue of it also satisfying the wildcarded `*.py`, when, based on the above, it is not.  So if the box were not checked by default, it might make _that_ particular area less ambiguous to the user.

**Comment by lresende** [comment]
Changing the front-end behavior might also have unexpected consequences on the folks that have their script to work when they have other dependencies. I would say we fix the actual "backend problem" and let users provide feedback on the UI as things have been working the current way for a while.

NOT A CONTRIBUTION
