### ISSUE TITLE
Pipeline CLI: allow for logging-friendly output

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2617]
**Is your feature request related to a problem? Please describe.**
Currently some of the `elyra-pipeline` commands display an 'animation' that indicates that a long running task is still in progress. 

![image](https://user-images.githubusercontent.com/13068832/161099136-7c114a20-1eef-40be-b8b5-a4bc50c2ac10.png)

While this is useful if a user runs a command in a terminal window, it ends up generating a lot of output on STDOUT, which creates issues if the command is run in batch, such as via CI:

```
d1a6ac164' for up to 60 minutes...ESC[K^M⠴ESC[0m Monitoring status of pipeline run '0422e768-9735-4e75-be71-e15d1a6ac164' for up to 60 minutes...ESC[K^M⠦ESC[0m Monitoring status of pipeline run '0422e768-9735-4e75-be71-e15d1a6ac164' for up to 60 minutes...ESC[K^M⠧ESC[0m Monitoring status of pipeline run '0422e768-9735-4e75-be71-e15d1a6ac164' for up to 60 minutes...ESC[K^M⠇ESC[0m Monitoring status of pipeline run '0422e768-9735-4e75-be71-e15d1a6ac164' for up to 60 minutes...ESC[K^M⠏ESC[0m Monitoring status of pipeline run '0422e768-9735-4e75-be71-e15d1a6ac164' for up to 60 minutes...ESC[K^M⠋ESC[0m Monitoring status of pipeline run '0422e76
```

**Describe the solution you'd like**
One of
- Find a solution that renders without problems when the CLI is run in a terminal window or in batch (where the output is captured and stored in a file)
- Add support for an option that suppresses the animation, so that captured output doesn't contain useless information

**Comment by kevin-bates** [comment]
This is discussed in Issue #31 in https://github.com/pavdmyt/yaspin (i'd rather not introduce a reference on that issue so am not adding the direct link).  In addition, PR #10 in https://github.com/cloudscale-ch/cloudscale-cli addresses this by checking `sys.stdout.isatty()` when the program is loaded - which seems like a reasonable approach (at least until yaspin addresses #31).
