### ISSUE TITLE
failed to build custom elyra image

### ISSUE THREAD

**Issue by pengyuan** [elyra-ai/elyra#2626]
**Describe the issue**
A clear and concise description of what the issue is.

1. use the latest elyra repository;
2. cd root dir;
3. add requirements.txt to etc/docker/elyra directory;
4. execute bash:  make elyra-image TAG=dev;
5. failed.

error infomation:

**make: *** No rule to make target 'install-all'.  Stop.**

seems like Makefile does not exist...

**To Reproduce**
6. Scroll down to '....'
7. See error

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7.0
 - Installation source:  custom container image
 - Deployment type: Docker
 - Operating system: centos

**Comment by pengyuan** [comment]
this project has so many bugs...

**Comment by pengyuan** [comment]
this project has so many bugs...

**Comment by pengyuan** [comment]
fixed.

Makefile:

rsync -ah --progress --delete --delete-excluded ./ build/docker/elyra/ \
			 --exclude ".git" \
			 --exclude ".github" \
			 --exclude-from ".git/ignores.tmp";

change to:

rsync -ah --progress --delete --delete-excluded ./ build/docker/elyra/;

it works.

seems --exclude flag occurs error without warning, than rsync copy nothing.

**Comment by ptitzler** [comment]
> make: *** No rule to make target 'install-all'. Stop.

seems like Makefile does not exist...

Please run the `make` command from the repository root directory. We should clarify that in the https://github.com/elyra-ai/elyra/tree/master/etc/docker/elyra README.

**Comment by ptitzler** [comment]
Same for the README in https://github.com/elyra-ai/elyra/tree/master/etc/docker/kubeflow
