### ISSUE TITLE
elyra 3.7.0 does not support gitlab as airflow dag repository

### ISSUE THREAD

**Issue by pengyuan** [elyra-ai/elyra#2627]
**Describe the issue**

there is only github option,  no gitlab.

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/2572263/161426073-252ab699-72f3-43da-ba96-4aea54241d11.png">

**To Reproduce**

1. make elyra-image tag=3.7.0
2. docker run -it elyra/elyra:3.7.0 jupyter lab
3. select runtime, create airflow runtime

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]
 - Operating system: [e.g. macos, linux]

**Comment by pengyuan** [comment]
so many bugs,  the version seems has not  been well tested.

**Comment by lresende** [comment]
Per documentation:
https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html?highlight=gitlab#git-type-git-type

Identifies which git type shall be used to store DAGs. Supported types are GitHub and GitLab. **GitLab is only supported if the [gitlab dependency is installed](https://elyra.readthedocs.io/en/stable/getting_started/installation.html#packaging)**. This setting is required.

**Comment by lresende** [comment]
> so many bugs, the version seems to have not been well tested.

And as an open-source project, we really appreciate the community involvement in reporting and helping fix the issues via pull requests. Thank you for the recent issue reports.

**Comment by lresende** [comment]
> so many bugs, the version seems to have not been well tested.

And as an open-source project, we really appreciate the community involvement in reporting and helping fix the issues via pull requests. Thank you for the recent issue reports.

**Comment by pengyuan** [comment]
> Per documentation: https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html?highlight=gitlab#git-type-git-type
> 
> Identifies which git type shall be used to store DAGs. Supported types are GitHub and GitLab. **GitLab is only supported if the [gitlab dependency is installed](https://elyra.readthedocs.io/en/stable/getting_started/installation.html#packaging)**. This setting is required.

thanks, very helpful link...I just did not notice it.

**Comment by ptitzler** [comment]
For reference (in case other users encounter the same issue:

**Comment by ptitzler** [comment]
The GitLab prerequisites are only installed one uses

```
$ pip install elyra[all]
```

```
$ pip install elyra[gitlab]
```

Related content in installation documentation:

https://elyra.readthedocs.io/en/latest/getting_started/installation.html#packaging

![image](https://user-images.githubusercontent.com/13068832/161572153-ccb5886d-b44c-4572-9c12-e72b41a67f11.png)
