### ISSUE TITLE
Make elyra work on kubeflow notebooks inside opendatahub/openshift

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2634]
**Describe the issue**
Elyra currently doesn't run on  kubeflow notebooks inside opendatahub/openshift

**To Reproduce**
1. Provision OpenShift in IBM Cloud
2. Install OpenDataHub Kubeflow
3. Start notebook using elyra/kf-notebook:3.7.0 (custom image)
4. find appropriate pod and get logs

[**Screenshots or log output**](https://gist.github.com/romeokienzler/93f315fa851a3ccc477748b27efb4a5a)

**Expected behavior**
Elyra runs properly (or at least gives same error as described [here](https://github.com/opendatahub-io/kubeflow/issues/12))

**Deployment information**

-  openshift:4.8.31_1546 on IBM Cloud
-  ODH operator 1.1.2 stable
-  Kubeflow version: build version dev_local (version number can be found at the bottom left corner of the Kubeflow dashboard):
-  kfctl version: (use kfctl version):
- Kubernetes platform: openshift
- Kubernetes version: openshift:4.8.31_1546
- Elyra 3.7.0 (see image above)

**Comment by romeokienzler** [comment]
@akchinSTC as discussed, I've used this [kfdef](https://raw.githubusercontent.com/opendatahub-io/manifests/v1.4.0-rc.2-openshift/openshift/kfdef/kfctl_openshift_v1.4.0_odh.yaml)

**Comment by ptitzler** [comment]
Container images for Kubeflow Notebook servers are now available for ODH. See https://github.com/elyra-ai/elyra/discussions/3006 for details.
