### ISSUE TITLE
Dockerhub elyra/kf-notebook:latest is 3.6.0 instead of 3.7.0

### ISSUE THREAD

**Issue by RobinKa** [elyra-ai/elyra#2659]
**Describe the issue**
`elyra/kf-notebook:latest` on Dockerhub points to the 3.6.0 image instead of the actual latest one (3.7.0).

See https://hub.docker.com/r/elyra/kf-notebook/tags

**Screenshots or log output**
![image](https://user-images.githubusercontent.com/2614101/163167237-251e2231-343e-4765-aec8-b717c0bbd982.png)

**Comment by kevin-bates** [comment]
Hi @RobinKa - thanks for bringing this to our attention!  I've retagged `latest` images for `elyra` and `kf-notebook` and pushed those tagged images to the respective registries (`docker.io` and `quay.io`).

We'll leave this issue open until it's resolved from a _process_ standpoint.
