### ISSUE TITLE
Add voila as a additional optional extension 

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2662]
**Is your feature request related to a problem? Please describe.**
Including a more robust visualization dashboard/widget when using elyra

**Describe the solution you'd like**
Include the voila package as part of the elyra installation

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/13340013/163279408-50f96ac8-f656-4e25-89b6-39768ff48aee.png)

https://github.com/voila-dashboards/voila

**Comment by kevin-bates** [comment]
We decided not to explicitly add Voila within the Elyra bundle.  Users are free to install Voila's lab extension and make it available within the same Lab instance as Elyra.
