### ISSUE TITLE
Confirm that `env_vars` contains no keys before writing pipelines

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [elyra-ai/elyra#2674]
When creating piplines, it is important to strip out any access keys or secret from the env_vars data.

```
 "pipelines": [
    {
      "id": "primary",
      "nodes": [
        {
          "id": "...",
          "type": "execution_node",
          "op": "execute-notebook-node",
          "app_data": {
            "component_parameters": {
              "filename": "notebooks/notebook_filename.ipynb",
              "outputs": [],
              "env_vars": [ NO KEYS HERE ]
```

**Comment by kiersten-stokes** [comment]
We've decided to move forward in implementing support for Kubernetes secrets. A single environment variable backed by a secret necessitates entering 3 string values:

1. the environment variable name (as it appears in the notebook or script)
2. the secret name (as shown in a `kubectl get secrets` command on the runtime instance)
3. the secret key (as a single secret can have multiple keys, each of which has its own value)

Based on some offline discussion, there are a few items that we need to finalize before implementing a full solution:

Design:
- what will the new control for a multi-valued property (e.g. a Kubernetes secret property) look like? and will it be considered a 'keyValueEntries' type?
- what will the new pipeline JSON look like for the above control?
- how will copying/pasting such a property between nodes work?
- how will the case be handled where an environment variable and kubernetes secret variable with the same name both have values?
- should a refresh button be available (similar to how it is with vanilla env vars now)?

Admin:
- should we merge the backend code first and followup with a frontend-focused PR (with some backend changes required)?

The backend code has been mostly implemented; draft PR to come soon.

**Comment by ptitzler** [comment]
> should a refresh button be available (similar to how it is with vanilla env vars now)?

What would be the purpose of the button? Elyra does not have any Kubernetes connectivity and wouldn't be able to auto-detect or validate secrets.

**Comment by kiersten-stokes** [comment]
> What would be the purpose of the button? Elyra does not have any Kubernetes connectivity and wouldn't be able to auto-detect or validate secrets.

It would behave just like the env vars one currently does. Basically, parse the notebook or script for certain uses (e.g. `os.getenv`) and populate the **name** of the env var only - the secret name and key still have to be entered manually (like the value does for 'vanilla' env vars now). Right now, these cases will appear in the 'Environment Variables' property area but not the 'Kubernetes Secrets' area, which could be a potential cause for confusion.

**Comment by kevin-bates** [comment]
Yeah, I agree about the confusion with regular envs, but given Patrick's use case he raised in the community meeting regarding the Local ("JupyterLab") use case, I think we should leave it alone and was wondering if the following might be worth a look.

Clearly, the local runtime doesn't know about this three-part "Kubernetes Secret" stuff, nor do I think we should make or try to massage 3-parts into 2-part (env name and value) that the local runtime would consume.  Instead, if we let envs just flow (from pipeline defaults to node envs) AND let the 3-part "Kubernetes Secret" env _replace_ normal envs, then, assuming we can detect the target runtime at the time of "default propagation", NOT propagate "Kubernetes Secrets" when its a local runtime, else perform the replacement.  By "replacement", I mean to remove the duplicated env from the "envs list" and add it to the "secrets list" (where the latter uses the necessary operations for conveying secrets information).

This will still be confusing for users to see their k8s secret env listed in their "detected" envs, but perhaps we can name and/or document the "Kubernetes Secrets" header (and/or help text) as "Kubernetes Env Secrets" or somehow convey this too is an env and let the user know these values will replace the regular envs where applicable.

We should also note that for things like DB credentials, each of these "secret envs" will very likely have a "normal env" that denotes the user name corresponding to the credential.  So in that respect, having the pair in the env list won't be too much of a surprise.  We just need to let the user know from where (and when) the actual value corresponding to the "secret env" is derived.

**Comment by ptitzler** [comment]
Delivered in https://github.com/elyra-ai/elyra/pull/2715
