### ISSUE TITLE
Extend 'elyra-pipeline describe' to identify PVC and notebook|script dependencies

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2685]
**Is your feature request related to a problem? Please describe.**
The `elyra-pipeline describe` command was introduced, among other things, to provide users with the means to understand what kind of dependencies a particular pipeline file has. Consider the following scenario:
 - User 1 creates a pipeline in environment 1. This pipeline has several dependencies, which would prevent it from running successfully in any other environment.
 - User 2 wants to run this pipeline in environment 2 and needs to know what the prerequisites are that need to be in place.

The command currently lists the following pipeline dependencies:
 - files (not including the referenced notebooks or scripts)
 - custom components

**Describe the solution you'd like**
 Extend the `describe` command to also list
 - the notebooks/scripts that the pipeline file references if it includes generic components
 - information about mounted volumes/pvcs (supported by Elyra 3.8+)

The ultimate goal is to enable user 2 to confirm (to the extend possible) that environment 2 has all prerequisites in place that the pipeline needs to run.

**Comment by ptitzler** [comment]
[Somewhat related; adding for the sake of completeness] A missing dependency that might also result in pipeline processing errors is if user 2's runtime configuration requires the [presence of a secret](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#cloud-object-storage-credentials-secret-cos-secret) in the target cluster. However, since this dependency is introduced by the runtime configuration and not the pipeline itself, one might consider this to be out of scope for the 
`elyra-pipeline describe` command, which currently does not require a runtime configuration to be provided.

**Comment by binayakdutta** [comment]
Updates:

1.  Extend  Pipeline.type in ~/elyra/pipeline/pipeline_defintion.py to default return value to "Generic" when "runtime_type" attribute is missing. Working Assumption being that "runtime_type" is specified for custom runtimes  

2. Extended  elyra-pipeline descrbee function at ~/cli/pipeline_app.py to add additional properties for 

a. mounted_volumes : when present

b. scripts : when Pipeline is Generic only

==
<img width="452" alt="image" src="https://user-images.githubusercontent.com/9624108/166895472-5001477f-4f8a-4184-921a-79429834e88a.png">

==

@ptitzler , @kiersten-stokes  I will reach out to consult and understand  next steps
