### ISSUE TITLE
'elyra-metadata' help should display a link to the documentation

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2718]
**Is your feature request related to a problem? Please describe.**
The `elyra-pipeline` CLI displays a documentation link when help is invoked, e.g.
```
$ elyra-pipeline --help
Usage: elyra-pipeline [OPTIONS] COMMAND [ARGS]...

  Run Elyra pipelines in your local environment or submit them to an external
  service, such as Kubeflow Pipelines or Apache Airflow.

  Find more information at: https://elyra.readthedocs.io/en/latest/
```

The link is specific to the version of Elyra that is installed, e.g. `https://elyra.readthedocs.io/en/v3.8.0/` for version 3.8.

**Describe the solution you'd like**
It would be helpful if the `elyra-metadata` command would do the same. The current output is 
```
$ elyra-metadata --help

Manage Elyra metadata.

Subcommands
-----------
...

```

**Comment by sgonsal** [comment]
Hi @ptitzler I can work on this issue. I'll assign this to me

**Comment by Ishan854** [comment]
Please Sir help me to deploy my  kubeflow pipeline locally using elyra I am trying from one month I do not know where I am lagging behind please help me so that I can move ahead

**Comment by ptitzler** [comment]
@Ishan854 please [open an issue](https://github.com/elyra-ai/elyra/issues) and provide us with more detailed information what you are trying to do what what obstacles you are facing. Thank you.
