### ISSUE TITLE
CLI-created runtime does not appear even after refresh

### ISSUE THREAD

**Issue by lehrig** [elyra-ai/elyra#2725]
**Describe the issue**
After a Kubeflow notebook server has started, we automatically add Elyra runtimes via
```elyra-metadata install runtimes...```
(see https://github.com/lehrig/kubeflow-ppc64le-notebook-images/blob/main/post_jupyter_start.sh)

However, this runtime does not appear in Elyra's runtimes view. Using the "refresh" functionality does not help. Strangely, what does help is to add an arbitrary other runtime using the UI. See this video where I recorded the observed behavior: https://ibm.box.com/shared/static/3lj4iotwcv0653qgzi8e3vfrm7huymmk.mov 

**To Reproduce**
1. Automatically add a runtime to a new Kubeflow notebook server using Elyra's CLI
2. Check for available runtimes

**Screenshots or log output**
See this video: https://ibm.box.com/shared/static/3lj4iotwcv0653qgzi8e3vfrm7huymmk.mov 

**Expected behavior**
A runtime should directly appear (or at least show up after hitting "refresh").

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.8.0
 - Operating system: linux (RHEL 8.4 on ppc64le; SELinux enabled)
 - Installation source: custom container image (https://github.com/lehrig/kubeflow-ppc64le-notebook-images -> quay.io/ibm/kubeflow-notebook-image-ppc64le:elyra3.8.0-py3.8-tensorflow-cpu2.7.0)
 - Deployment type: Kubeflow (v1.5.0) Notebook Server on OpenShift v4.8

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines (v1.5.0, multi-user auth enabled using OpenShift OAuth)
 
**Runtime configuration settings**
![Bildschirmfoto 2022-05-12 um 17 25 23](https://user-images.githubusercontent.com/9555494/168111271-ce1701a4-9e3a-4c41-80a3-9d84a3c9680e.png)
(see https://github.com/lehrig/kubeflow-ppc64le-notebook-images/blob/main/post_jupyter_start.sh)

**Comment by ptitzler** [comment]
Related issue: https://github.com/elyra-ai/elyra/issues/2515

**Comment by yarnabrina** [comment]
We also use Kubeflow notebook server, but our base image is [this](https://gallery.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter). There we use the `create` sub-command and it works fine.

Since `install` was recently deprecated, I'm just throwing a guess, can you please try with `create` once?

https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html#id1

**Comment by lehrig** [comment]
Increasing delay to 20 did not help.

**Comment by lehrig** [comment]
Thanks @ptitzler & @kevin-bates for the call!

Here's a summary:
- there is no race condition (so the sleep is unimportant); we were able to reproduce the issue also from within the notebook after it started
- the issue can be observed for any kind of metadata (components, runtimes, runtime images, code snippets)
- the issue only happens for the first creation of metadata of a given kind (e.g., the issue occurs for the first creation of a runtime)
- once a second creation of a given kind happens, the issue is actually fixed
- alternatively, creating an arbitrary file inside the metadata folder of a given kind (e.g., `~/.local/share/jupyter/metadata/runtimes`) also fixes the issue

I've therefore added a hot fix to my script:
```
touch /home/jovyan/.local/share/jupyter/metadata/runtimes/hotfix2725.fix
rm -f /home/jovyan/.local/share/jupyter/metadata/runtimes/hotfix2725.fix
```
(see https://github.com/lehrig/kubeflow-ppc64le-notebook-images/commit/eb4eda887e099a35d6fa33dcf6f0df1255207210)

We _suspect_ the underlying reason is the persistent volume mounted into /home/jovyan as being provided by the NFS Provisioner.

**Comment by lehrig** [comment]
Could that be an explanation? https://www.avidandrew.com/understanding-nfs-caching.html

**Comment by kevin-bates** [comment]
Thanks for the link!  Yes, it's likely something along those lines.

**Comment by ptitzler** [comment]
@lehrig, based on our findings that the issue doesn't seem to be caused by Elyra and that there isn't really anything we can do to prevent it, are you okay with closing the issue?

**Comment by lehrig** [comment]
Yes, I would agree that this is not caused by Elyra but rather by the underlying storage system.
