### ISSUE TITLE
Syntax for mounting PVC Volumes is confusing

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2738]
Currently, we use a very esoteric syntax for mounting PVCs to pipelines `/mnt/path=existing-pvc-name`.

The current UI asks the user to specify a list of strings, without even explaining what the syntax is in the UI.

__Screenshot of current state in the "node properties" section:__

![Screen Shot 2022-05-25 at 12 28 01](https://user-images.githubusercontent.com/5735406/170166638-ec5621f4-496b-4a3d-8e28-9b1516b79f90.png)

We can make this MUCH easier to use by making it a list with TWO fields, one for "mount path" and the other for "PVC name". 
(OR: At very least, we can update the text above the list to explain the `MOUNT_PATH=PVC_NAME` syntax)

**Comment by ptitzler** [comment]
We are planning to address this (and the same usability issue for [inputting secrets](https://github.com/elyra-ai/elyra/pull/2715) (available in 3.9+)) in version 3.10. There's some front-end infrastructure work ongoing  that will add support for more user-friendly widgets. @ajbozarth and @marthacryan are the owners.

**Comment by Fantailed** [comment]
To add to this, is there a way of knowing the absolute path of the working directory beforehand? It seems that right now it's `<working dir of runtime image>/jupyter-work-dir`, which changes depending on the runtime used.  
Ideally, is there a way to make the working dir fixed? Or to specify volume mounts relatively?

**Comment by akchinSTC** [comment]
@ptitzler - pushing this off given the time frame left for 3.11 and resource constraints. can discuss if do not agree.
