### ISSUE TITLE
Enable including code-snippets into Python Scripts or Notebook cells

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#278]

**Comment by karlaspuldaro** [comment]
A few points discussed with the team:
- When inserting code snippet into notebook cell or python editor and there is a language mismatch, display a warning message before inserting the code
- When inserting code snippet into a markdown file, wrap the snippet into a code block with syntax highlight by language

Future enhancements:
- Add snippet insertion config for markdown files, where user can opt for in-line or code block wrapper
