### ISSUE TITLE
Review/address 'Elyra Tests: Test Server' warnings

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2782]
**Describe the issue**
The most recent CI 'Elyra Tests: Test Server' tests produce 700+ warnings. 

**To Reproduce**
1. Open https://github.com/elyra-ai/elyra/actions
2. Choose one of the 'Elyra Tests'
3. Review the 'Test Server' log

Many warnings are deprecation messages that will result in an error in the future.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.10/main

**Comment by ptitzler** [comment]
Earmarking 3.11 for investigation

**Comment by ptitzler** [comment]
Warning related to KFP/generic components:
> FutureWarning: Please create reusable components instead of constructing ContainerOp instances directly. Reusable components are shareable, portable and have compatibility and support guarantees.

To resolve, the [implementation of generic components](https://github.com/elyra-ai/elyra/blob/main/elyra/kfp/operator.py#L70) would have to be redone as a custom component. Sizing estimate: ~med

**Comment by kevin-bates** [comment]
Following the merge of #2833 and #2829, there are still 1688 warnings.  However, 1632 (all but 56) of these can be attributed to the recent release of tornado 6.2 vs. 6.1.

Each of the following entries produce 544 warning each in our test - adding to 1632:
```
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/tornado/ioloop.py:350: DeprecationWarning: make_current is deprecated; start the event loop first
    self.make_current()

/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pytest_tornasync/plugin.py:65: DeprecationWarning: make_current is deprecated; start the event loop first
    loop.make_current()

/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pytest_tornasync/plugin.py:67: DeprecationWarning: clear_current is deprecated
    loop.clear_current()
```

Of the remaining 56 warnings...

15 can be attributed to (KFP SDK?):
```
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/kfp/dsl/_container_op.py:75: PendingDeprecationWarning: `dsl.ContainerOp.image` will be removed in future releases. Use `dsl.ContainerOp.container.image` instead.
    warnings.warn(
```

14 to (Papermill):
```
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/traitlets/config/configurable.py:85: DeprecationWarning: Passing unrecognized arguments to super(PapermillNotebookClient).__init__(input_path='/tmp/pytest-of-runner/pytest-0/test_pipeline_execution_bad_py0/pipeline/node1.ipynb').
  object.__init__() takes exactly one argument (the instance to initialize)
  This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
    super().__init__(**kwargs)
```

13 to (Test resources):
```
  <unknown>:26: DeprecationWarning: invalid escape sequence \_
```

11 to (KFP SDK?):
```
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/kfp/dsl/_container_op.py:1257: FutureWarning: Please create reusable components instead of constructing ContainerOp instances directly. Reusable components are shareable, portable and have compatibility and support guarantees. Please see the documentation: https://www.kubeflow.org/docs/pipelines/sdk/component-development/#writing-your-component-definition-file The components can be created manually (or, in case of python, using kfp.components.create_component_from_func or func_to_container_op) and then loaded using kfp.components.load_component_from_file, load_component_from_uri or load_component_from_text: https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.components.html#kfp.components.load_component_from_file
    warnings.warn(
```

2 to (package installation tests):
```
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
    warnings.warn(
```

and 1 to (test resource):
```
  /home/runner/work/elyra/elyra/elyra/tests/pipeline/airflow/test_component_parser_airflow.py:320: DeprecationWarning: invalid escape sequence \_
    parsed_description = """a string parameter with a very long description
```

I believe the 14 (13+1) warnings related to `invalid escape sequence \_` can be addressed within our test resources.   I suspect most of these are related to the `image` fields of the test pipeline files.

The others, however, are upstream dependencies, with perhaps the exception of `Creating a LegacyVersion has been deprecated ` that is associated with 2 warnings, both in the `test_pacakge_installation` area - which we may be able to address.
