### ISSUE TITLE
Empty Output Files Directory Should Be Valid With Wildcard

### ISSUE THREAD

**Issue by cupdike** [elyra-ai/elyra#2789]
Validation fails on the Output Files directory when a directory with a wildcard for files is specified (e.g. `data/*`).  Since output files may be generated by the pipeline node, this should be valid.

**To Reproduce**
Create a node with Output Files set to  `data/*` where that directory is empty.  Try to run the pipeline triggering validation.
Note that if you drop an empty file into the directory, it will pass validation.

**Screenshots or log output**
{
  "severity": 1,
  "source": "Elyra Pipeline Validation Service",
  "type": "invalidFilePath",
  "message": "Property(wildcard) has an invalid path to a file/dir or the file/dir does not exist.",
  "data": {
    "nodeID": "9eccdc64-edbe-4dad-8ae5-0d90405a5c13",
    "nodeName": "elyra.trainer.ipynb",
    "propertyName": "dependencies",
    "value": "/home/jovyan/MNIST/data/*"
  }
}

**Expected behavior**
The pipeline should pass validation in this condition.

**Deployment information**
Describe what you've deployed and how:
 - Elyra 3.9.1

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines 1.0.4

**Comment by cupdike** [comment]
Closing this.  It's because I had defined File Dependencies in the second node on the mistaken notion that they were treated like inputs from the prior node.  It makes sense that files should exist at a location specified by File Dependencies.  Apologies for the noise...

**Comment by ptitzler** [comment]
+1. We've updated the `elyra-pipeline describe` CLI command to list more dependencies, as shown [in section `Pipeline CLI: identify pipeline dependencies` in the release notes](https://github.com/elyra-ai/elyra/releases/tag/v3.9.0). Unfortunately there is currently no equivalent functionality in the pipeline editor. In your specific scenario the command would have listed  `data/*` as a dependency and might have made it easier to identify the root cause.

**Comment by cupdike** [comment]
> Pointed out by the team, I dont think we currently support wildcards in output file declarations, see #995

Just so you are aware, the docs suggest they are supported: https://elyra.readthedocs.io/en/v3.9.0/user_guide/pipelines.html
> Output Files
> Optional. A list of files generated by the notebook inside the image to be passed as inputs to the next step of the pipeline. Specify one file, directory, or expression per line. Supported patterns are * and ?.
Example: data/*.csv

**Comment by ptitzler** [comment]
If the amount of data (or number of files) you want to exchange between generic nodes is rather large, using the [data volume support we've introduced in version 3.8](https://github.com/elyra-ai/elyra/releases/tag/v3.8.0) is probably the better performing option.
