### ISSUE TITLE
Display what's new link after a new version of Elyra was installed

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2795]
**Is your feature request related to a problem? Please describe.**
In a managed environment (where administrators maintain the installed software) it's not easy for a user to determine what the currently installed version is and whether this is a version that is different from the version that was previously served. Many tools display release notes upon startup to notify the user that something has changed, enabling them, for example to identify and explore new features. Elyra currently does not do this, and users have to manually perform the following steps in JupyterLab to access the information:
 - open a terminal window
 - run `elyra-pipeline --version` or `pip show elyra`
 - open the launcher
 - click the `documentation` tile. which opens the documentation for the installed version
 - click the `changelog` link
 - click the `github release page` link

**Describe potential solutions**

- Option 1: 
   - Add a `release notes` tile to the launcher that opens the release document for the installed version (e.g. https://github.com/elyra-ai/elyra/releases/tag/v3.9.0)
  
    ![image](https://user-images.githubusercontent.com/13068832/176053584-4b8e815c-7cdf-4c8c-accb-0725b280ebfa.png)

- Option 2: 
  - Upon startup, Elyra checks whether the user has viewed the release notes message (e.g. by checking for the existence of a file that gets created after the user has seen the message)
  - if the user has not seen the message for the installed version before, it is displayed. The user can _opt in_ to see the message again the next time jupyterlab is started

Thoughts about other approaches that would help user stay up-to-date?

**Comment by salonee13** [comment]
I would like to work on this issue
