### ISSUE TITLE
Clarification needed: What is an "air-gapped" environment???

### ISSUE THREAD

**Issue by richlysakowski** [elyra-ai/elyra#2801]
The documentation uses this term without ever defining it:

"air-gapped" environment

What is this, and where are the scripts provided to create such an environment?  

Please fix the documentation and provide the script to make it easy to create an environment with an "air-gap"

Thank you.

**Comment by lresende** [comment]
Air-gapped environment details --> https://en.wikipedia.org/wiki/Air_gap_(networking)

**Comment by shalberd** [comment]
Yes, a strange term. In issues related to Kubeflow and Open Data Hub, that type of environment is typically called a disconnected or offline environment. Maybe it is due to modern times and the London subway ("mind the gap") or the U.S. clothing store "Gap Inc" :-)

**Comment by ptitzler** [comment]
This might be one of those things that you recognize when you see/use one 😉 
That said, we can add a link to the documentation.
