### ISSUE TITLE
Update kfp to 1.8.13

### ISSUE THREAD

**Issue by guimou** [elyra-ai/elyra#2816]
Elyra currently inherits a hard requirement from kfp:  https://github.com/elyra-ai/elyra/blob/a0b99d2e3b3484b3e8b3e155ef9eb1dd69e3b3d9/setup.py#L95
It prevents updating other libraries which require typing-extensions=>4.
For example, for a custom notebook image I created I had to drop the S3 Browser integrated in Jupyter (https://github.com/IBM/jupyterlab-s3-browser). It was either that, or drop Elyra, or keep everything on 1+ years old versions...

KF project [told me](https://github.com/kubeflow/pipelines/pull/7801#issuecomment-1151064795) that a backport to correct that on their side should come with kfp 1.8.13. So as soon as it's available, could you have a look at it and release an Elyra version that will lift this constraint?

Thanks!

**Comment by ptitzler** [comment]
Adding this temporarily to [3.10 milestone](https://github.com/elyra-ai/elyra/milestone/60). If this kfp sdk patch release drops before then we should be able to remove the cap.

**Comment by ptitzler** [comment]
Now available: https://pypi.org/project/kfp/1.8.13/
