### ISSUE TITLE
RAM requests can't exceed 99 Gb

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2822]
Currently, we limit the RAM request for nodes to 99 Gb, but there are many situations where you might want more than that.

If we are going to have a limit at all, it should be like 1 Tb.

![Screen Shot 2022-07-07 at 15 39 13](https://user-images.githubusercontent.com/5735406/177699995-7061924c-7e11-4fe7-9e7e-31e44b15236e.png)

**Comment by ptitzler** [comment]
I guess 99 was an arbitrary limit, which could be increased my modifying https://github.com/elyra-ai/elyra/blob/main/elyra/templates/components/generic_properties_template.jinja2#L116
