### ISSUE TITLE
pip3 install --upgrade elyra[all] fails

### ISSUE THREAD

**Issue by leucir** [elyra-ai/elyra#2834]
**Describe the issue**
Following the documentation https://elyra.readthedocs.io/en/latest/getting_started/installation.html, when tried to run the command `pip3 install --upgrade elyra[all]`, the following error happens `no matches found: elyra[all]`

`pip install --upgrade elyra` works fine. 

**To Reproduce**
1. Go to your terminal
2. Type on pip3 install --upgrade elyra[all]
3. See error: no matches found: elyra[all]

**Expected behavior**
Fix documentation

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: latest
 - Installation source: conda
 - Deployment type: local
 - Operating system: macos

**Comment by kevin-bates** [comment]
In perusing the documentation just now, I see this has already been added to the Troubleshooting section of the Developer's guide: https://elyra.readthedocs.io/en/stable/developer_guide/troubleshooting.html

Is this the correct location?  I would imagine this is more of a "user" issue.

Adding "Needs Discussion" label.

**Comment by ptitzler** [comment]
We've discussed this in today's dev meeting. Proposed actions:
 - Move the  existing _Troubleshooting_ documentation topic source code (https://github.com/elyra-ai/elyra/blob/main/docs/source/developer_guide/troubleshooting.md) to the `getting_started`   (https://github.com/elyra-ai/elyra/tree/main/docs/source/getting_started) directory
 - Update https://github.com/elyra-ai/elyra/blob/main/docs/source/index.rst to reflect above location change
 - Update _Installation_ topic (https://github.com/elyra-ai/elyra/blob/main/docs/source/getting_started/installation.md) to replacing all occurrences of `elyra[...]` with `'elyra[..]'`
 - 
@leucir would you like to contribute those changes? The documentation development instructions are located in https://elyra.readthedocs.io/en/stable/developer_guide/contributing.html#contributing-to-the-elyra-documentation

**Comment by leucir** [comment]
Sure, I will work on this issue, and create the PR for review.
