### ISSUE TITLE
Document how we publish Elyra container images for Open Data Hub

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2844]
**Is your feature request related to a problem? Please describe.**
Elyra is an upstream dependency for [Open Data Hub](https://opendatahub.io/). We/the maintainers currently take care of creating and integrating the container images. There is currently no documentation that outlines the process we are following.

**Describe the solution you'd like**
Create a topic in the developer guide or a wiki entry that contains the relevant information. In a nutshell:

- Create a PR in https://github.com/opendatahub-io/s2i-lab-elyra ([example PR](https://github.com/opendatahub-io/s2i-lab-elyra/pull/41))
- Wait for above PR to be merged
- Create a PR in https://github.com/opendatahub-io/odh-manifests ([example PR](https://github.com/opendatahub-io/odh-manifests/pull/579))
- Wait for above PR to be merged

**Comment by shalberd** [comment]
Nice, thanks a lot.
