### ISSUE TITLE
Allow to specify annotation for steps execution pods 

### ISSUE THREAD

**Issue by blublinsky** [elyra-ai/elyra#2849]
We are using KFP integrated with DAPR, where DAPR interactions is all driven by annotations. As a result, we do need to enable
annotating pods.

We would like to be able to specify annotations on the specific pods, similar to how environment variables are currently supported. In a most simplistic approach, a drop-down on the pod allowing for specifying a set of annotations for a given step

modifying the resulting YAML file, which does not seem to be practical

Here is an example of how we are doing this now:

````
    ray_op(
              times = times, 
              ray_address = ray_address,
              exp = exp,
              runid = runid)\
        .add_env_variable(
            k8s_client.V1EnvVar(name="PUBSUB_NAME", value="pubsub"))\
        .add_env_variable(
            k8s_client.V1EnvVar(name="TOPIC_NAME", value="postevents"))\
        **.add_pod_annotation(
            name="dapr.io/enabled", value="true")\
        .add_pod_annotation(
            name="dapr.io/app-id", value="ray-processor")**
````

**Comment by ptitzler** [comment]
Implementation constraints:
 - zero or more annotations should be configurable as pipeline defaults
 - zero or more annotations should be configurable for generic or custom components
 - validation should verify that the input meets the  [syntax/character requirements](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set)
