### ISSUE TITLE
Add documentation for dev container image

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2859]
**Describe the issue**
#1638 introduced a new [`Dockerfile`](https://github.com/elyra-ai/elyra/tree/main/etc/docker/elyra_development), which can be used to perform basic Elyra development. We need to add documentation (README.md, similar to the ones for `elyra` and `kf-notebook`) and update [`developer_guide/development-workflow.html`](https://elyra.readthedocs.io/en/latest/developer_guide/development-workflow.html) to enable users.

**Comment by ptitzler** [comment]
fwiw the `Dockerfile` doesn't seem to work. A build results in the following error
```
...
Preparing to unpack .../nodejs_16.16.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (16.16.0-deb-1nodesource1) ...
Setting up nodejs (16.16.0-deb-1nodesource1) ...
rm: cannot remove 'setup_16.x': No such file or directory
```

If one removes the [problematic command](https://github.com/elyra-ai/elyra/blob/main/etc/docker/elyra_development/Dockerfile#L25) other errors are raised.

**Comment by kiersten-stokes** [comment]
FWIW, I do see the error with the `rm setup_16.x` command, but after I remove that, I don't run into any additional errors
