### ISSUE TITLE
Standardize code "style" across packages

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#289]
We are using a variety of code styles (var naming, function declaration, modularization) across our packages. We should take stock of the different styles and as a team choose a general code style and update our packages to match.

This will be three phases:
1. Go through code (ts/tsx files in particular) and take not of the different styles we use
   - variable naming conventions (eg camelCase vs underscore)
   - how we declare functions (`functionName() {}` vs `functionName = () => {}`)
   - how we break up and spread out code across files in a package 
2. Meet as a team and decide which methodology we want to use for each styling
3. Go through the code and update to match the chosen styling.

**Comment by akchinSTC** [comment]
- looking up current styles
- which style we want
- change to default chosen style

**Comment by ajbozarth** [comment]
Decisions based on scrum today:
- camelCase vars 
- `functionName() {}` style functions
I will be adding eslint rules for these as well as fixing them

**Comment by ajbozarth** [comment]
Opened followup issue #395 to handle the third bullet in phase 1
