### ISSUE TITLE
Add support for three-valued BooleanControl

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2906]
**Is your feature request related to a problem? Please describe.**

The `BooleanControl` widget enables users to specify a boolean property value by checking/unchecking a box. This implementation does not support scenarios where users should be able to choose from three values: true, false, and null, with null representing 'not set'.

**Example**
 Enable users to prevent use of cached node outputs
 - user explicitly declines use of cached node outputs
 - user explicitly accepts use of cached node outputs
 - user defers the decision to the runtime environment (Elyra does not have  any insights into how the environment is configured) 

**Describe the solution you'd like**
Perhaps a select box with three options. The label text for each option should be customizable, and the returned values be one of true/false/null. 

**Describe alternatives you've considered**
It might probably be possible to implement a one-off solution using `EnumControl` but it wouldn't be re-usable.

**Comment by kiersten-stokes** [comment]
I think the RJSF stuff will really simplify using an enum for this. I'll play around with some options and report back!
