### ISSUE TITLE
Specify default image

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2934]
**Is your feature request related to a problem? Please describe.**
I'm dragging and dropping notebooks to the canvas and always need to select the same container image to pass validation, although the large majority of notebooks are happy with the same image 

**Describe the solution you'd like**
In the metadata editor for the images add an option where one image can be set as default image. Then, when dragging notebooks to the canvas, this one is automatically selected

**Describe alternatives you've considered**
Doing it by hand which is a little teadious

**Comment by ptitzler** [comment]
Functionality is already available. Refer to https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#runtime-image
