### ISSUE TITLE
Seeing Unicode values for a file name instead of Chinese characters

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#295]
Upstream issue in jupyter lab git extension repository here:
https://github.com/jupyterlab/jupyterlab-git/issues/543

**Comment by ajbozarth** [comment]
upstream pr is merged and will be included in 0.10 I will leave this open for tracking our update to 0.10 once it is released

**Comment by lresende** [comment]
Upstream pr has been merged.
