### ISSUE TITLE
Runtime configuration named 'local' is treated as local runtime

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2964]
**Describe the issue**

**To Reproduce**
1. Create a KFP RTC and name it local
   ```
   $ elyra-metadata list runtimes
   Available metadata instances for runtimes (includes invalid):

   Schema    Instance                         Resource                                                                             
   ------    --------                         --------                                                                             
   kfp       local                            /Users/patti/Library/Jupyter/metadata/runtimes/local.json   
   ```
3. Create a valid KFP pipeline that runs a notebook
4. Run the pipeline using the 'local' RTC
5. Observe the output. It indicates that the pipeline was executed locally. this can be confirmed by inspecting the notebook's cell outputs.

![2022-10-10_16-18-09 (1)](https://user-images.githubusercontent.com/13068832/194966724-68faa333-3a04-49c9-8cee-2989c7054b73.gif)

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.12

**Comment by kevin-bates** [comment]
This is occurring in the server where it tries to determine the runtime.  In this case, `runtime_config` has a value of "local". 

https://github.com/elyra-ai/elyra/blob/797a17b3d41fed15499c1e158ba4e7bfb639e852/elyra/pipeline/validation.py#L198-L199

However, the front end will also submit generic pipelines for local processing by setting `runtime_config` to the string "local" - as does the CLI utility.

https://github.com/elyra-ai/elyra/blob/71a1ffdc2e8ea93c04ab1ee038489a2d6782ab44/elyra/cli/pipeline_app.py#L504

As a result, I think we should explore letting the `None` value for `runtime_config` indicate that local processing takes place (for now).   Ideally, it seems like we should determine the runtime from `runtime_config`'s schema name - but that can only happen once the Local runtime processor supports runtime configuration metadata.
