### ISSUE TITLE
LFAI onboarding tasks 

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2975]
- [x] Technical Steering Committee formation
   - [x] Elect TSC members
   ~~- [ ] Elect a TSC chair (optional)~~
- [x] Create new “CONTRIBUTING” file in root of repository
   - [x] Contains TSC members and contributors - No limit
   - [x] Set roles and descriptions
   - [x] Set requirements for promotions e.g. Contributors to Committer status 
     - [x] Using Apache guidelines for contributor to committer, 3 positive, no negative votes from existing committer pool
     ~~- [ ] TSC selection and election process~~ 
- [x] Provide list of URLs to Elyra logos/trademarks - waiting for legal
- [x] Code of conduct 
       - https://github.com/elyra-ai/community/blob/main/code-of-conduct.md
- [x] Documentation
    - [x] All provided docs need to be changed to Creative Commons Attribution 4.0 International License (available at http://creativecommons.org/licenses/by/4.0/
      - [x] CC4.0 license added to PR, waiting for guidance on what files actually req it.
      - [x] Add/update PR message template that tests should be included
      
  
OpenSSF Silver Badge Standard TODO:

Documentation:
- [ ] High level design architecture
- [x] Coding e.g. PEP-8 etc. styles for languages
- [x] Create roadmap - one year outlook
- [x] Security - what users can expect and not expect'
- [x] How to uninstall Elyra
- [ ] Release process GPG public key location and verification
Build: 
- [x] Move to using requirements lock files for releases for reproducibility
- [x] Create GPG keypair for packages OR continue personal GPG set and publish our public keys.
   - [ ] Personal and it's already published
- [x] Does pip installation honor DESTDIR? 
Misc:
- [ ] - Accessibility in Elyra
     - @marthacryan - https://github.com/jupyter/accessibility?
- [x] - Internationalize standards i18n ?
   - [x] We follow Jupyterlab ones ->https://jupyterlab.readthedocs.io/en/latest/extension/internationalization.html

**Comment by lresende** [comment]
Please reopen if anything outstanding.
