### ISSUE TITLE
Local execution modifies my notebooks

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2983]
**Describe the issue**
Local execution modifies my notebooks

**To Reproduce**
1. Create a generic pipelines
2. run it in local execution mode
3. the involved notebooks are touched and changed

**Expected behavior**
notebooks untouched and unchanged

**Comment by kevin-bates** [comment]
I think this request makes sense.  However, the current behavior is that local execution mode is considered the equivalent of what would happen if you were to run the notebook or python/R scripts directly from Jupyter Lab.  In that case, notebooks are updated in-place.

I think this issue needs to be predicated on the promotion of "local" to its own (official) runtime (schema).  This would allow for configuring things like output locations, among other things.

Also, if there are those that feel strongly about preserving the "in-place" behavior we have today, we could make the semantics such that providing a local runtime instance name (i.e., metadata based on the `local` schema) is optional.  In that case, we would continue to support the `null` runtime name and let the behavior be as today.  Should the user want some richer behavior, like non-destructive operation, or even [docker support](https://github.com/elyra-ai/elyra/pull/2324), they would need to provide a runtime instance name that contains the configuration attributes relative to those kinds of features.
