### ISSUE TITLE
Refactor code generation for Kubeflow Pipelines

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2986]
**Is your feature request related to a problem? Please describe.**

- Refactor the Kubeflow Pipelines processor to generate Python DSL as intermediary output format
- Expose the generated DSL in the export wizard in addition to the already support static configuration file (YAML)

**Additional context**
- The changes have no impact on regular users because the changes are completely transparent.
- Advanced users will be able to customize the generated Python DSL, if desired.
- With these changes in place, support for pipeline parameters can be added.

**Comment by dvaldivia** [comment]
Exposing the kubeflow inout parameters for a component is highly desirable, so pipelines can be hooked into AutoML, I think even a simpler approach would be to expose add support for populating a component parameter inputs from kubeflow itself, just like we have a dropdown today for "put a string, read file, read output" we should have a "read from kubeflow" or similar

**Comment by ptitzler** [comment]
Perhaps I am misunderstanding your comment, but pipeline parameters will enable users to do that, as outlined [here](https://github.com/elyra-ai/elyra/discussions/2970). The _motivation_ section in the linked doc includes a screen capture of how pipeline parameters are exposed in the Kubeflow Central dashboard.
