### ISSUE TITLE
URL pipeline catalog doesn't reflect updates on remote side

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2996]
**Describe the issue**
URL pipeline catalog doesn't reflect updates on remote side

**To Reproduce**
1. provide url with kfp pipeline yaml
2. create url catalog using elyra ui
3. use component (e.g. submit to kfp)
4. change kfp pipeline yaml (contents of url)
5. changes are ignored

Workaround: Delete url component catalog and recreate

**Expected behavior**
Changes are reflected (e.g. new kfp yaml submitted to kfp)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: v3.11.1
 - Operating system:linux
 - Installation source: pypi
 - Deployment type: local

**Pipeline runtime environment**

 - Kubeflow Pipelines build version dev_local DEX_STATIC_PASSWORDS

 
**Runtime configuration settings**
![image](https://user-images.githubusercontent.com/5694071/199742637-bdec35f8-7bed-450f-b046-232c62fd001a.png)

**Comment by kevin-bates** [comment]
I thought there was a way to force a catalog refresh - do you see such an option available within the context of the catalogs?

**Comment by ptitzler** [comment]
You are right, there is:
 - reload all catalog entries
 - reload a single catalog entry

![image](https://user-images.githubusercontent.com/13068832/199747633-959f2770-925f-443d-b334-085cf3006562.png)

Depending on the catalog type it might take a little bit for the changes to be reflected in the pipeline editor.

**Comment by ptitzler** [comment]
I'm guessing that you saw the functionality if you are using version version 3.7 or above, but am not completely sure whether the issue you are reporting is that the outdated component definition is rendered when you view/use if the the pipeline editor. In case it is, I created https://github.com/elyra-ai/elyra/pull/2997 to document the feature and included important disclaimers that explain why the pipeline editor might not render what you expect.

We do have an open requirement to expose the catalog load status that should remove some of the current uncertainty.

**Comment by romeokienzler** [comment]
please ignore - problem sat in front of the keyboard - thanks for your help and sorry for wasting your time @ptitzler et. al.
