### ISSUE TITLE
Pipeline files clutter the root level of the cos bucket

### ISSUE THREAD

**Issue by Shreyanand** [elyra-ai/elyra#3005]
**Describe the issue**
[The documentation](https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#cloud-object-storage-bucket-name-cos-bucket) for setting the storage point for pipeline files only allows for the root level of the bucket. This clutters the root level of the bucket with pipeline runs (local [issue](https://github.com/os-climate/aicoe-osc-demo/issues/115)).
 
**To Reproduce**
1. Create a kubeflow runtime for a pipeline
2. Execute the pipeline and see the resulting folder in the root level

**Screenshots or log output**
![Screenshot from 2022-11-09 10-58-06](https://user-images.githubusercontent.com/8916126/200864210-1f2b31ab-3000-415f-a1c2-9a92b359cfe0.png)

**Expected behavior**
A workaround for not cluttering the root level. Maybe a way to specify a path for storing the pipeline files.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version:  Not sure
 - Operating system:  linux
 - Installation source: official container image
 - Deployment type:  Open Data Hub

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines
 
**Runtime configuration settings**
-

**Comment by ptitzler** [comment]
Hi @Shreyanand,

You can configure a prefix to organize the objects that Elyra is uploading to cloud storage in your pipeline properties:

![image](https://user-images.githubusercontent.com/13068832/200869990-bf1399f9-6d9f-4fa8-bef6-942103977ce3.png)

Reference: https://elyra.readthedocs.io/en/stable/user_guide/pipelines.html#generic-node-properties

**Comment by ptitzler** [comment]
> Elyra version: Not sure

The easiest way to find out is documented here: 
https://elyra.readthedocs.io/en/stable/getting_started/troubleshooting.html#how-to-identify-the-installed-elyra-version

**Comment by ptitzler** [comment]
I'm going to go ahead and close this issue because there's nothing for us to do at this point. If the current functionality doesn't meet your needs please re-open.

**Comment by Shreyanand** [comment]
Thanks for the solution @ptitzler! We're currently on 3.6.0 version and so it needs to be updated.
