### ISSUE TITLE
Update documentation to reflect recent changes to the export dialog

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#3028]
After the merge of #2999, we will need a few small documentation updates.

[This section](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html?highlight=export#exporting-a-pipeline-from-the-visual-pipeline-editor) will require a new screenshot and the addition of new step to indicate that a custom filename can now be provided.

**Comment by ptitzler** [comment]
Delivered in https://github.com/elyra-ai/elyra/pull/3039
