### ISSUE TITLE
KFP: Cannot select file as input to node

### ISSUE THREAD

**Issue by Lejboelle** [elyra-ai/elyra#3060]
I have a component that takes a string as input, .e.g,:

```
name: Test string inputs
description: Test Elyra string inputs
inputs:
- {name: string_input, type: String, description: some string}
implementation:
  container:
    image: python:3.9
    command:
    - sh
    - -ec
    - |
      program_path=$(mktemp)
      printf "%s" "$0" > "$program_path"
      python3 -u "$program_path" "$@"
    - |
      def _make_parent_dirs_and_return_path(file_path: str):
          import os
          os.makedirs(os.path.dirname(file_path), exist_ok=True)
          return file_path

      def test_str(string_input):
          print(string_input)
          

      import argparse
      _parser = argparse.ArgumentParser(prog="Test string input", default=argparse.SUPPRESS)
      _parser.add_argument("--string-input", dest="string_input", type=json.loads, required=True, default=argparse.SUPPRESS)
      _parsed_args = vars(_parser.parse_args())

      test_str(**_parsed_args)
    args:
    - --string-input
    - {inputValue: string_input}
```

But when I try add a string through a txt file (using the **Please select a file to use as input** option), it doesn't get selected when pressing **select** in the browser. 
The issue is also present for other input types (int, list, dict, etc.).

There were no issues in Elyra 3.13, but after upgrading to 3.14.1 the issue is present.

- Elyra version: 3.14.1
- Operating system: linux
- Deployment type: Kubeflow [notebook server]
- Kubeflow version: 1.6.0

**Pipeline runtime environment**
 - Kubeflow Pipelines

**Comment by ptitzler** [comment]
This does appear to be a regression. The console log contains the follow error

![image](https://user-images.githubusercontent.com/13068832/209306469-327793e2-73ae-469d-8df6-b496d855f854.png)
