### ISSUE TITLE
Pipeline parameter type integer or float cannot take negative number as input

### ISSUE THREAD

**Issue by Lejboelle** [elyra-ai/elyra#3061]
First of all, thanks for adding pipeline parameters to Elyra. On to the issue.
When I add a integer or float pipeline parameter, I'm not able to specify a negative number as input. Is this a design or a bug?

If number >= 0: OK
![Selection_032](https://user-images.githubusercontent.com/21076664/208422771-fe97192b-48b5-464d-88c8-cee9e3174387.png)

If number < 0: NOT OK
![Selection_033](https://user-images.githubusercontent.com/21076664/208422787-21403f7e-023d-4437-8ec0-3888532daa42.png)

**Deployment information**
- Elyra version: 3.14.1
- Operating system: linux
- Deployment type: Kubeflow [notebook server]
- Kubeflow version: 1.6.0

**Pipeline runtime environment**

- Kubeflow Pipelines

**Comment by ptitzler** [comment]
You are right! It looks like the [current implementation does reject negative values](https://github.com/elyra-ai/elyra/blob/main/packages/ui-components/src/FormDialog.tsx#L142), but this is not the desired behavior.
