### ISSUE TITLE
Elyra Conda install on py37 fails because of jupyter_core>=4.11.2

### ISSUE THREAD

**Issue by rxm7706** [elyra-ai/elyra#3069]
https://github.com/elyra-ai/elyra/blob/080ebbb26bd864531f961e48be26d18f377a53db/pyproject.toml#L23

the only available python 3.7 build on conda-forge for jupyter_core is 4.11.1
https://anaconda.org/conda-forge/jupyter_core/files?version=4.11.2
https://anaconda.org/conda-forge/jupyter_core/files?version=4.11.1

This causes incompatibility when elyra is installed on python 3.7 with other packages - who are managing with jupyter_core>=4.11.0,<5.0

**Comment by kevin-bates** [comment]
I believe this is an issue with the `jupyter_core` feedstock.  Both 4.11.2 and 4.12 PRs for conda-forge have been merged, but those packages are not present. I have opened an issue in the feedstock.  Let's see how that turns out before we decrease its floor.

**Comment by kevin-bates** [comment]
Conda-forge dropped support for Python 3.7 last August: https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7

Although the maintainers _could_ build a `jupyter_core` manually, I have recommended they do not spend time on this and that we will decrease our floor value from `4.11.2` to `4.11`.  Looking at the Git logs between `4.11.0` and `4.11.2`, there really aren't significant changes - nearly all are from the `pre-commit-ci` bot.

Given that most of the Jupyter stack has dropped 3.7 support around the same time, we encourage you to move to a more current Python release.

**Comment by kevin-bates** [comment]
You may also want to use `pip install --upgrade jupyter_core` following your conda-based installation to get the latest versions relative to Python 3.7.  That said, I'm going to submit a PR that should satisfy conda installations, albeit two revisions behind the `pip` version.

**Comment by kevin-bates** [comment]
@rxm7706 - it just occurred to me that merging any kind of PR for this won't work since the corresponding patch release can't be created for conda and Python 3.7 - where it would be required.

As a result, I believe your only recourse is to issue `pip install --upgrade jupyter_core` following your conda-specific installation.

Of course, the more sustainable resolution is to upgrade to Python 3.8 or greater.

**Comment by rxm7706** [comment]
@kevin-bates thank you for looking into this. 
would have loved to mix pip and conda-forge, or upgrade to py 3.8 - that's a bit away for us unfortunately.

I think its possible to build a patch for elyra by including a conda_build_config.yaml in the recipe directory
it would look something like this

```
# conda_build_config.yam patch to make conda-forge build python 3.7
python:
  - 3.7.* *_cpython   # [not (osx and arm64)]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
python_impl:
  - cpython           # [not (osx and arm64)]
  - cpython
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20              # [not (osx and arm64)]
  - 1.20
  - 1.20
  - 1.21
  - 1.23
```

**Comment by kevin-bates** [comment]
Thanks for the suggestion @rxm7706!  Unfortunately, this is all over my head, and I have no idea what this is trying to do or how it addresses the issue.  I also find the `numpy` reference odd.  Could you please provide a summary of what this is doing and how it might resolve the conda/python 3.7 issue? (Thank you)

(Sorry, I was going to suggest you go ahead and create a PR in the [feedstock repo](https://github.com/conda-forge/elyra-feedstock) but see that you had already done that a couple of days ago.  Are the changes in https://github.com/conda-forge/elyra-feedstock/pull/47 part of what you're getting at in your previous comment?  (Also, I am now watching that repo.))

cc: @akchinSTC, @lresende
