### ISSUE TITLE
Make exception information more user friendly

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#307]
From #279.  Author: @lresende

Looks like we are receiving more details on the client-side, but I would like to make this a little more user-friendly. Maybe we could get inspired on the old Windows error dialog boxes:

![image](https://user-images.githubusercontent.com/382917/75687877-58cb9780-5c53-11ea-953a-422fa5cf2de0.png)

And have something like:

```
Error title
Error Message ...
Error details in a collapsable section (closed by default)?
```

In order to accomplish this, we might need to send more specific error details from the backend. In the past, I have accomplished something similar by distilling some of this info into specific response HTTP headers.

**Comment by kevin-bates** [comment]
Hi @karlaspuldaro - I hope to get some time to look into things on the back end tomorrow.  I think we could probably define a mixin class that the back-end handlers can derive from that deals with exception formatting.

Three obvious fields are things like 'title', 'message' and 'details'.  I'm not sure about 'error code'  since the handlers don't necessarily have the context of what happened and trap general exception instances, but I'll look into the viability of that.  If an error code thing is 'where we want to go with this' then that usually implies a "registry" of codes, and I'd prefer we not go there outside of the general HTTP error codes (of which only a few are applicable).

At any rate, my plan would be to provide you with a branch on my fork that you can use to develop a front-end solution.

**Comment by karlaspuldaro** [comment]
Thank you @kevin-bates 
I agree with those fields. As far as I could tell, if I'm not mistaken, I see [handler.py](https://github.com/elyra-ai/elyra/blob/master/elyra/scheduler/handler.py) is logging the exception. I wonder if there would be the place we parse the fields we need, or would that be in [submission.tsx](https://github.com/elyra-ai/elyra/blob/master/packages/application/src/submission.tsx), ie. in line 115 where we get the response object with the exception details (including the status code/text if we decide to add it)

**Comment by kevin-bates** [comment]
handler.py is in the backend and SchedulerHandler is what we'd extend with something like `RichExceptionMixin` that the other metadata handlers would also use.  This mixin would likely host the `send_error_message()` method and that method would be responsible for constructing the response payload.  What I'm not certain about is whether we can place a json doc into error responses - but I suspect we can.

Yes, I think submission.tsx is an appropriate location, although you'd also want this when fetching metadata - or any other request against the server.  I'm wondering if we could stuff the JSON into the response "message" and the front-end could check if that field is JSON or just a string (since generic messages still need to be tolerated in cases where the return path isn't under our control).  But if JSON, it could then access the various fields.  I suspect "reason" is the string-ized version of the exception class ('ValidationError', 'RuntimeError' and stuff like that).

I also need to research how stack traces are accessed in exception objects, etc.  I believe there's some kind of 'exc_info' field for that, but I'm not sure.

**Comment by karlaspuldaro** [comment]
I think json needs to be parsed as string then converted back to json when reading the response? I might be wrong.
And I agree in setting this up on the backend to cover the standard handler we want for any other case that might consume that.

Meanwhile, this is what I got so far on the front end (content of fields will be adjusted accordingly):
Detail msg collapsed as default:
![PipelineSubmissionError-collapsed](https://user-images.githubusercontent.com/25207344/76570145-1728c100-648b-11ea-8b2e-66a4a5a66910.png)

Detail msg box expanded:
![PipelineSubmissionError-expanded](https://user-images.githubusercontent.com/25207344/76570156-1a23b180-648b-11ea-8091-024b4deb9285.png)

**Comment by kevin-bates** [comment]
Hmm.  That seems nice and requires zero changes on the backend.  

The text "Pipeline submission failed with the following error:" is provided by the front-end though.  I'm wondering if the front-end can provide it's contextual message - which would be "Error submitting pipeline", then strip the "... with the following error:" from the details, leaving only what the server is returning.  But still add 'Check the ... details' suffixes message.  Perhaps with a blank line between the server message and it.  (and don't embed in parenthesis, if its doing that.)

**Comment by kevin-bates** [comment]
Sorry, I just discovered the "Pipeline submission failed " portion is from the server: https://github.com/elyra-ai/elyra/blob/master/elyra/scheduler/handler.py#L41

Here's an example of the mixin used in EG that applies JSON-formatting... https://github.com/jupyter/enterprise_gateway/blob/c409160141a8d3c80ec1dd106de31574726f9990/enterprise_gateway/mixins.py#L85
Its fields are 'reason', 'message', and (conditionally) 'traceback'.

**Comment by lresende** [comment]
> Here's an example of the mixin used in EG that applies JSON-formatting... https://github.com/jupyter/enterprise_gateway/blob/c409160141a8d3c80ec1dd106de31574726f9990/enterprise_gateway/mixins.py#L85
> Its fields are 'reason', 'message', and (conditionally) 'traceback'.

On line 122, where the stack trace is being joined, should we add some sort of line break there?

**Comment by kevin-bates** [comment]
I don't think that will be necessary.  @karlaspuldaro will provide screenshots when the PR is ready.

**Comment by karlaspuldaro** [comment]
Here's what the most updated version looks like
Details collapsed by default:
![image](https://user-images.githubusercontent.com/25207344/76770031-ac6dd300-6773-11ea-89fe-05457ab2148e.png)
In case we don't receive a traceback, we won't see the "Error details:" line/button

Details expanded with auto scroll:
![image](https://user-images.githubusercontent.com/25207344/76770087-c3142a00-6773-11ea-81e1-a55df886eb0e.png)
