### ISSUE TITLE
Define runtime images in sha256 digest instead of tag format

### ISSUE THREAD

**Issue by shalberd** [elyra-ai/elyra#3074]
**Is your feature request related to a problem? Please describe.**
@akchinSTC @Hema-Mathiyazhagan 

for openshift ImageContentSourcePolicy / airgapped / restricted network environments referral from a certain source of an image to a custom target location in e.g. a Harbor container registry, the image-references in basic Kubernetes objects need to be in sha256 digest format. The main goal is to enable lookup from public internet repo images to custom repo locations, and that is only possible when images are referenced in digest-format.

Could you modify the runtime images https://github.com/elyra-ai/elyra/tree/main/etc/config/metadata/runtime-images  image_name field to refer to the images in digest-format?

e.g. anaconda [repo](https://hub.docker.com/layers/continuumio/anaconda3/2021.11/images/sha256-6771ed1289b6cb1d7653c24ace4c4d4336f9ff48b2942c7c33808abaa6eaa17d?context=explore) 

implicit here (docker.io) / path:tag from the regular tag notation

`continuumio/anaconda3:2021.11`

instead to

`docker.io/continuumio/anaconda3@sha256:a2816acd3acda208d92e0bf6c11eb41fda9009ea20f24e123dbf84bb4bd4c4b8`

**Describe the solution you'd like**

Images are referenced in digest format so as to support the overall initiative for airgapped / disconnected mode including Openshift image mirroring and ImageContentSourcePolicy. See also https://github.com/opendatahub-io/odh-dashboard/issues/855  and https://github.com/opendatahub-io/opendatahub-operator/issues/182

**Describe alternatives you've considered**
Considered building a custom elyra image wiht own runtime-images config. However, I think having the default to digest format from now on should be no issue for main branch elyra, too. 

**Additional context**
A big overall wish in the community to support airgapped and make ready image-references, as one part of that.
https://github.com/opendatahub-io/odh-manifests/issues/567
Part of ODH 1.5.0 milestone. Also good to ensure images are what they pretend to be, as a tag can be the same even after updates to an image, but image sha256 digests are always unique and I guess also OS-specific (Linux/AMD64).

**Comment by akchinSTC** [comment]
@shalberd -Ill start working on the changes =)

**Comment by shalberd** [comment]
about not using docker.io for the full path, I guess that is ok, as in Opensource Openshift OKD and OCP, there is a setting called [unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]](https://www.ibm.com/docs/en/scalecontainernative?topic=agsnrrhocpc-air-gap-setup-network-restricted-red-hat-openshift-container-platform-clusters-optional-5131) that works with ImageContentSourcePolicy as well. You just need to change to the @sha256: format everywhere. It is pretty special. Usually, it is image_name:image_tag, but with digest format, the @sha256: comes right after the image name and before the hash.
