### ISSUE TITLE
(Question) How can I install pip packages??

### ISSUE THREAD

**Issue by kimkihoon0515** [elyra-ai/elyra#3083]
How can i install pip packages in runtime Image??
Should I make a custom image that has all packages i need?

**Comment by lresende** [comment]
A runtime image is a docker image that is used when executing the pipeline node.
The most flexible way to customize it, is by creating your own image.
If you are running a notebook node or something, you could install a package from the the notebook cell (e.g. `!pip install xxx` )

**Comment by ptitzler** [comment]
For production deployments consider using custom container images to avoid the need to install packages on the fly each time a pipeline notebook or script is executed. Refer to https://elyra.readthedocs.io/en/stable/user_guide/best-practices-file-based-nodes.html#runtime-image for details.
