### ISSUE TITLE
Number parameters results in invalid code generation

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#3085]
**Describe the issue**
When the user overrides an integer parameter in the submission dialog, the code generation uses a string value instead of a number value.

This is what the generated code looks like for valid Integer input
![image](https://user-images.githubusercontent.com/6673460/214120610-304a1b4f-8d05-469b-bb7d-f55207bb8585.png)

**Comment by ptitzler** [comment]
I confirmed the behavior for numeric default values and custom values. This does appear to be caused by the Kubeflow Pipelines compiler. The Elyra Python DSL code generator produces the following code, which uses numbers, not strings:

```
inputs:
- {name: number, type: Integer, description: 'one', default: 1, optional: false}
...
@kfp.dsl.pipeline(name="test")
def generated_pipeline(
    number: int = 1,
):
```

The KFP compiler translates that to

```
  arguments:
    parameters:
    - {name: number, value: '1'}
```
