### ISSUE TITLE
Add openshift oauth token support to KFP runtime

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#3107]
**Is your feature request related to a problem? Please describe.**
In the near future in ODH, the KFP API will be protected by an openshift oauth proxy sidecar, which will require any request to have a valid bearer token to proceed. 

**Describe the solution you'd like**

openshift oauth token support added, changes needed in
- kfp metadata schema
- kfp runtime processor
- tests updated

**Describe alternatives you've considered**
N/A

**Additional context**
Metadata section:
![image](https://user-images.githubusercontent.com/13340013/218165127-47658faa-182c-42f9-b9e9-cbb5542f81a6.png)

**Comment by accorvin** [comment]
Thanks @akchinSTC for creating this issue! @humairak can you add any additional context that might be useful around how we're adding auth in front of the KFP API? Will the user need to be able to do anything beyond simply providing their OpenShift auth token? Do we require it in any specific format to to be passed via any specific header?

**Comment by HumairAK** [comment]
A [bearer token](https://swagger.io/docs/specification/authentication/bearer-authentication/) as `authentication type` should be sufficient for us. 

To make the ui future proof and more flexible, I would add an "add your own custom headers/values" section that you can tag onto the request to the api server. For instance [KFP api server accepts](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/common/config.go#L31) a `KUBEFLOW_USERID_HEADER` that can be customized for multi-user isolation mode, so you can't hard code it. We intend to use an oauth proxy to add this header, but someone else might not.

**Comment by akchinSTC** [comment]
@HumairAK - Thanks! As far as a test environment goes, do you have personal or test branch of the deployment manifests I need to test my changes or can I just use the master branch of [odh-manifests](https://github.com/opendatahub-io/odh-manifests)?

**Comment by HumairAK** [comment]
@akchinSTC I set up branch here for you to try out: https://github.com/HumairAK/odh-manifests/blob/odh-dsp-auth-demo/data-science-pipelines/base/auth/AUTH_NOTES.md you should be able to follow these instructions and try querying the api server accordingly with auth header. Let me know if there are any issues.

**Comment by akchinSTC** [comment]
thank you!
