### ISSUE TITLE
Error making request

### ISSUE THREAD

**Issue by NicoLaval** [elyra-ai/elyra#3115]
**Describe the issue**

When I run "manually" my scripts, all's good.
When I run a small pipeline, all's good.
When I run a bigger pipeline, I've a UI issue "Error making request", while the process is still running in the background.
I can't find any error in browser networks or in backend logs.

**Screenshots or log output**

![ok](https://user-images.githubusercontent.com/30119477/221430935-4eff0c96-3729-4d1a-b962-058a96deabe5.PNG)

![ko](https://user-images.githubusercontent.com/30119477/221430944-f4005620-a7bb-4f31-aea4-90b87788ef0d.png)

**Deployment information**

 - Elyra version: 3.2.1
 - Operating system: linux
 - Installation source: mamba
 - Deployment type: Kubernetes

**Pipeline runtime environment**

 - Local execution

**Comment by ptitzler** [comment]
This is unfortunately a known issue (https://github.com/elyra-ai/elyra/issues/1573) that has yet to be addressed.

**Comment by ptitzler** [comment]
@NicoLaval are you running JupyterLab locally or via JupyterHub? For running in JupyterHub you can try increase the timeout, as mentioned in https://github.com/elyra-ai/elyra/issues/1573#issuecomment-822610210
