### ISSUE TITLE
Can I change these Elyra runtime artifacts urls??

### ISSUE THREAD

**Issue by kimkihoon0515** [elyra-ai/elyra#3122]
According to `https://github.com/elyra-ai/elyra/blob/main/docs/source/recipes/running-elyra-in-air-gapped-environment.md`
Elyra downloads a few dependencies to the container. By default these dependencies are located in here
```
  https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/kfp/pip.conf
  https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/kfp/bootstrapper.py
  https://raw.githubusercontent.com/elyra-ai/elyra/main/elyra/airflow/bootstrapper.py
  https://raw.githubusercontent.com/elyra-ai/elyra/main/etc/generic/requirements-elyra.txt
```
Can I change theses url??
I changed some parts of your codes and these original codes don't work for me.

**Comment by lresende** [comment]
There are a few environment variables to look up for these files in another location. 
https://elyra.readthedocs.io/en/stable/recipes/running-elyra-in-air-gapped-environment.html?highlight=gap#runtime-environment-dependencies

**Comment by ptitzler** [comment]
> There are a few environment variables to look up for these files in another location.

+1. Also (not documented) If your modified files are stored in GiHub, e.g. your fork, you could set the `ELYRA_GITHUB_ORG` and `ELYRA_GITHUB_BRANCH` environment variables instead. If you do Elyra will use their values to generate the URLs.

**Comment by kimkihoon0515** [comment]
@ptitzler thx for the help. I have one more question.
I want to change the directory where cos objects are saved.
I can only set bucket for the directory but what i want is to set specific directory in my bucket just like this,
ex) {cos_endpont}/{cos_bucket}/{folder_name}/{objects}
Can you tell me what files should i change??

**Comment by ptitzler** [comment]
There is no need to change the source code to accomplish that if you are not using an outdated version. We've introduced the object storage path prefix pipeline property that does exactly what you are looking for. Details are at https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#generic-node-properties
