### ISSUE TITLE
How can I override the default images in elyra? 

### ISSUE THREAD

**Issue by GabeChurch** [elyra-ai/elyra#3132]
Quick question, if I am in a situation where I need/want to override the default images in elyra (I mount a curated image list for users) how would I go about doing so?

**Comment by ptitzler** [comment]
Hi @GabeChurch!

Unfortunately there is currently no way to exclude these default/example runtime image configurations _during the Elyra installation_. As a workaround I've created [a document in the Elyra discussion forum](https://github.com/elyra-ai/elyra/discussions/3133) to describe how to remove them and add your own runtime image configurations post installation. The described process should be straight forward to implement for container-based deployments of JupyterLab/Elyra if you are using a custom `Dockerfile`  for your deployment.

For example:

```
...
RUN pip install elyra
...
# Add commands to remove default/example runtime image configurations (see doc)
RUN ... 
# Add commands to add custom runtime image configurations (see doc)
RUN ...
```

If any clarification is needed, please feel free to leave a comment in the discussion thread.

**Comment by guimou** [comment]
@GabeChurch 
See full example:
- Here to remove the builtin images: https://github.com/opendatahub-io-contrib/workbench-images/blob/a8b91a230465db81e64be10649c3b99f11e401bc/jupyter/datascience/py39/Dockerfile#L47
- Here to add your one: https://github.com/opendatahub-io-contrib/workbench-images/blob/a8b91a230465db81e64be10649c3b99f11e401bc/jupyter/datascience/py39/Dockerfile#L54
- With a set of JSON file like this to define your images: https://github.com/opendatahub-io-contrib/workbench-images/blob/main/jupyter/datascience/py39/runtime-images/datascience-ubi9-py39.json

**Comment by lresende** [comment]
Information provided above.
