### ISSUE TITLE
Add support for JupyterLab 4.x

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#3137]
**Is your feature request related to a problem? Please describe.**
[JupyterLab 4.0 is now available as a beta](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0b0). We need to evaluate that release and identify what it takes to leverage that release.

- [ ] installation documentation and repository readme https://github.com/elyra-ai/elyra/pull/3145

Resources:
 - [JupyterLab extension v3 -> v4 migration guide](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html)
 - [Elyra issues tagged with `external:jupyterlab 4.0`](https://github.com/elyra-ai/elyra/labels/external%3Ajupyterlab%204.0)

Extensions:

- [ ] Jupyterlab-lsp - current version of jupyterlab-lsp python package depends on jupyterlab being <v4-alpha, v5 release is required for JL 4.0 support [tracker](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/917)

**Comment by LiutongZhou** [comment]
Jupyterlab 4.0.2 is released. Looking forward to V4 support

**Comment by dhendry** [comment]
+1 for JupyterLab 4.x support.

Thanks so much for a useful set of extensions!

**Comment by skukhtichev** [comment]
@lresende There is a jupyterlab-lsp dependency mentioned in the description. jupyterlab-lsp 5.0 with JL4.0 support was released some time ago. Is there a timeline for enabling JupyteLab 4 support in Elyra?
