### ISSUE TITLE
404 links on the getting_started/tutorials.html page

### ISSUE THREAD

**Issue by gregsheremeta** [elyra-ai/elyra#3154]
**Describe the issue**
These two links are 404 on the docs [getting_started/tutorials.html](https://elyra.readthedocs.io/en/v2.0.1/getting_started/tutorials.html) page:

    Learn how to [create a notebook pipeline and run it in your local JupyterLab environment](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world).

    Learn how to [create a notebook pipeline and run it on Kubeflow Pipelines](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world_kubeflow_pipelines).

I didn't see any obvious replacement candidates in https://github.com/elyra-ai/examples/tree/main/pipelines

**Comment by kevin-bates** [comment]
Hi @gregsheremeta - I agree with your assessment. 

I think https://github.com/elyra-ai/examples/tree/main/pipelines/introduction-to-generic-pipelines _could_ be associated with the "local Juptyerlab environment" topic, while https://github.com/elyra-ai/examples/tree/main/pipelines/run-generic-pipelines-on-kubeflow-pipelines seems sufficient for the "Kubeflow Pipelines" topic.

While we're at it, it seems like could _add_ a similar Airflow topic (mirroring the Kubeflow topic) that points at: https://github.com/elyra-ai/examples/tree/main/pipelines/run-generic-pipelines-on-apache-airflow

The reason I suspect these might be the right links is based on the content of the paragraph just prior to the [prerequisites section](https://github.com/elyra-ai/examples/tree/main/pipelines/introduction-to-generic-pipelines#prerequisites).

Also, in digging into some of the history in the examples repo, I found this: https://github.com/elyra-ai/examples/pull/82, and I suspect the Elyra docs were probably not updated to reflect those changes.

Would you like to contribute a pull request with these updates?

**Comment by fresende** [comment]
@gregsheremeta You should use the latest stable version documentation link: https://elyra.readthedocs.io/en/stable/
