### ISSUE TITLE
No redirection of user when deploying Elyra & JupyterHub in a Kubernetes environment 

### ISSUE THREAD

**Issue by ilpint** [elyra-ai/elyra#3159]
Following the instructions in [deploying Elyra and JupyterHub](https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html) 
I have setup a working Elyra in a Kubernetes environment, but the automatic redirection to user url does not work. 

After login, the singleuser app is started but the user is never redirected to the correct url:  

http://server:port/user/username/lab

Also using the control panel "My Server" button the user get Error 404 because is redirected to http://server:port/user/username

The url http://server:port/user/username/lab is perfectly working, the server is up and running but url must be manually inserted by the user. No clues in logfiles of hub or proxy pods.

**Expected behavior**
The user is redirected to the default_url after server start

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [3.14.3]
 - Installation source: [official container image]
 - Deployment type: [Kubernetes]
 - Operating system: [linux]

Our config file is

```
proxy:
  service:
    type: NodePort
    nodePorts:
      http:  32082
      https: 32443

hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      use_search_user_to_check_groups: True 
      bind_dn_template:
        - uid={username},ou=people,dc=ingv,dc=it
      server_address: xxxxx.it
      server_port: 389
    storage:
      dynamic:
         storageClass: longhorn
  extraConfig:
    myConfig: |-
      from kubespawner import KubeSpawner
      from tornado import gen
      import yaml

      class CustomKubeSpawner(KubeSpawner):
          def get_env(self):
              env = super().get_env()
              env['KG_HTTP_USER'] = self.user.name
              env['KERNEL_USERNAME'] = self.user.name
              env['KERNEL_NAMESPACE'] =  'enterprise-gateway-3'
              return env
      c.JupyterHub.spawner_class = CustomKubeSpawner
      c.Spawner.start_timeout = 500
      c.Spawner.working_dir = u'/home/jovyan'

singleuser:
   # let default 
  defaultUrl: "/lab"
  image:
      name: elyra/elyra
      tag: 3.14.3
  storage:
    dynamic:
      storageClass: longhorn
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    KG_URL: http://enterprise-gateway.enterprise-gateway-3:8888
    JUPYTER_GATEWAY_URL: http://enterprise-gateway.enterprise-gateway-3:8888
    JUPYTER_GATEWAY_REQUEST_TIMEOUT: "600"
  networkPolicy:
    egressAllowRules:
            privateIPs: True
debug:
  enabled: true

```

**Comment by lresende** [comment]
The best and always up-to-date instructions to deploy JupyterHub are in https://z2jh.jupyter.org/en/stable/
From your details above, you might be missing a `jupyter_server_config.py` with `c.NotebookApp.default_url = '/lab'`

**Comment by ilpint** [comment]
Thank you for the answer, @lresende . 
I found jupyter_server_config.py (and jupyter_notebook_config.py) in /etc/jupyter  in the running server with the Elyra image. 
I looked for jupyter_server_config in the documentation [https://z2jh.jupyter.org/en/stable/](https://z2jh.jupyter.org/en/stable/) and did not find any reference to the need of c.NotebookApp.default_url = '/lab' in this config file, so I do not know where the file need to be edited or created. 
Could you please give me a suggestion on where the jupyter_server_config.py should go?

Just to add some more context, from the server terminal i can see the environment variable correctly set: 

```JUPYTERHUB_DEFAULT_URL=/lab```

 and in the server log the (right?) ServerApp running:
```
[I 2023-06-13 10:44:51.933 SingleUserNotebookApp mixins:576] Starting jupyterhub-singleuser server version 1.4.2
[W 2023-06-13 10:44:51.939 SingleUserNotebookApp _version:70] jupyterhub version 3.0.0 != jupyterhub-singleuser version 1.4.2. This could cause failure to authenticate and result in redirect loops!
[I 2023-06-13 10:44:51.940 SingleUserNotebookApp serverapp:2686] Serving notebooks from local directory: /home/jovyan
[I 2023-06-13 10:44:51.940 SingleUserNotebookApp serverapp:2686] Jupyter Server 1.23.6 is running at:
```
Not sure if the warning can explain the incorrect behavior.

**Comment by lresende** [comment]
This shouldn't be an elyra specific issue, please find more details on https://z2jh.jupyter.org/en/stable/ as this is JupyterHub with a JupyterLab image, which by the way, has a few additional extensions from Elyra.
