### ISSUE TITLE
make generic pipelines to DAG rendering work with Airflow 2.x

### ISSUE THREAD

**Issue by shalberd** [elyra-ai/elyra#3166]
**Describe the issue**
Currently, even when using generic pipeline editor with python files and notebooks, the rendered DAG is not compatible with Airflow 2..6.0 or higher, or any Airflow 2.x, for that matter :-)
`
Broken DAG: [/opt/airflow/dags/repo/SvensWetterapprootpvc-0202162036.py] Traceback (most recent call last): File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/opt/airflow/dags/repo/SvensWetterapprootpvc-0202162036.py", line 2, in <module> from airflow.contrib.kubernetes.volume_mount import VolumeMount ModuleNotFoundError: No module named 'airflow.contrib.kubernetes'`

**To Reproduce**
1. Create a generic pipeline
2. Submit it to the Airflow runtime with Airflow 2.x

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**
DAg is rendered correctly for use in Airflow 2.x

Starting with jinja template
https://github.com/elyra-ai/elyra/blob/main/elyra/templates/airflow/airflow_template.jinja2

and elyra/elyra/pipeline/airflow/processor_airflow.py

possible hints
https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html

https://airflow.apache.org/docs/apache-airflow/2.5.3/howto/upgrading-from-1-10/index.html

https://airflow.apache.org/docs/apache-airflow/2.5.3/core-concepts/dags.html

https://github.com/apache/airflow/pull/21653

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: latest
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]
 - Deployment type: Open Data Hub pre-RedHat takeover
 - Operating system: [e.g. macos, linux]

**Comment by ianonavy** [comment]
My team was able to get generic pipeline DAGs to work with Airflow 2.5.3 on this commit (https://github.com/kflow-ai/elyra/commit/f9d132954e008d30145f18794aa543d97f121a5f). We don't have unit tests working locally, so this commit isn't ready for a PR. Perhaps we can work with an active maintainer to get this in proper shape for an upstream merge?

Off the top of my head, we need automated tests to work and potentially test with both earlier and later versions of Airflow. My understanding from [this comment](https://github.com/elyra-ai/elyra/issues/3165#issuecomment-1601094554) is we may actually want to take a different approach to keep Airflow 1 support at the same time.

![screenshot of Airflow 2.5.3 showing a working pipeline generated from a dev build of Elyra](https://github.com/elyra-ai/elyra/assets/790279/fde47fca-aa1b-489d-9fef-fb73a420eccf)

**Comment by shalberd** [comment]
Do we really need to test it with Airflow 1.x?

By the way, your code looks really good, I have exactly that in my local code base right now :-)

**Comment by shalberd** [comment]
@ianonavy yup, we will certainly work with @lresende

**Comment by shalberd** [comment]
@ianonavy "Off the top of my head, we need automated tests to work and potentially test with both earlier and later versions of Airflow." we will deprecate airflow 1.x support with elyra 4.0 and I am thinking of adding more unit tests aside from the existing ones, too.

**Comment by shalberd** [comment]
@lresende I will add some new documentation to this PR changing some things in
https://elyra.readthedocs.io/en/latest/recipes/configure-airflow-as-a-runtime.html
so it is clear what is now Airflow 2 ready. Plus also, some configuration options in Airflow 2 have changed etc.
