### ISSUE TITLE
Unable to use KUBERNETES_SERVICE_ACCOUNT_TOKEN authentication method

### ISSUE THREAD

**Issue by annhov** [elyra-ai/elyra#3177]
Hi!
I have a custom Elyra notebook server running on Kubeflow. The notebook is running on the pod, where the serviceaccounttoken is defined in the same namespace as Kubeflow and the environment variable KF_PIPELINES_SA_TOKEN_PATH points to that mounted secret.
But when selecting the KUBERNETES_SERVICE_ACCOUNT_TOKEN method, it fails on uploading the pipeline to Kubeflow using ArgoClient. Is there any specific way the token should be added to be able to execute pipelines?

1. Create a new Kubeflow pipeline.
2. Fill in the runtime configuration like this:
![runtimeconfigsnip](https://github.com/elyra-ai/elyra/assets/115209554/34dbc86c-4607-4715-9e37-a8ad8c38cf3b)
3. Try running the pipeline with this runtime config.

If applicable, add screenshots or log output to help explain your problem.
[logs.txt](https://github.com/elyra-ai/elyra/files/12247494/logs.txt)

**Expected behavior**
Pipeline can be submitted using SA token.

**Deployment information**
 - Elyra version: [e.g. 1.5.3]
 - Operating system: linux
 - Installation source: custom container image
 - Deployment type: Kubernetes

**Pipeline runtime environment**
Kubeflow Pipelines version 1.6, single-user

**Comment by harshad16** [comment]
@annhov seems like from log you included that it doesn't have enough permission to by-pass your proxy.
perhaps check locally with the service-account token, are you able to connect to server?

**Comment by annhov** [comment]
@harshad16 thanks for the reply. The problem was resolved by using internal DNS to access KF API: http://ml-pipeline.kubeflow:8888/
