### ISSUE TITLE
ODH Quick Install links are broken

### ISSUE THREAD

**Issue by chuyqa** [elyra-ai/elyra#3186]
**Describe the issue**
The ODH quick install links in 
https://github.com/elyra-ai/elyra/blob/6cb0e3df35eefbb736190fd60e22dbe446a093d3/docs/source/recipes/deploying-elyra-with-opendatahub.md?plain=1#L21C56-L21C122 Point to a 404 page. 

It seems ODH folks updated their URLS to:

https://opendatahub.io/docs/quick-installation/ (v1)
https://opendatahub.io/docs/quick-installation-new-operator/ (v2)

**To Reproduce**
1. Go to https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-with-opendatahub.html 
2. Click on the quick install link.

**Comment by lresende** [comment]
Hey @chuyqa good to see you again .... care to send a PR? otherwise will take care of it...

**Comment by lresende** [comment]
@fresende would you like to help here?

**Comment by harshad16** [comment]
@lresende I have opened a PR, with the updated docs: https://github.com/elyra-ai/elyra/pull/3188
