### ISSUE TITLE
Link to Contributing doc is broken

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#3210]
**Describe the issue**
When clicking the link to the contribution guidelines in [this doc](https://github.com/elyra-ai/elyra/blob/main/CONTRIBUTING.md), we get a 404 error. It is likely there is a typo in the link:
https://github.com/elyra-ai/community/blob/main/contributing.md

**Expected behavior**
The doc link should point to https://github.com/elyra-ai/community/blob/main/CONTRIBUTING.md

**Comment by karlaspuldaro** [comment]
Since this is the landing contribution doc in Elyra, it would be useful to also add a reference to the[ developer guide ](https://github.com/elyra-ai/elyra/blob/main/docs/source/developer_guide/contributing.md)

**Comment by BDFL669** [comment]
Kindly assign me to fix this issue

**Comment by varunpatel07** [comment]
Hi, can I work on this if issue is still open?

**Comment by BDFL669** [comment]
I already made a PR for this issue but thanks for offering 🙏
