### ISSUE TITLE
No logging in container for python scripts nodes

### ISSUE THREAD

**Issue by paloma-rebuelta** [elyra-ai/elyra#3222]
**Describe the issue**
Hello! I have a problem with my elyra pipelines not showing logs.
I have looked for issues on github but couldn't find anything related, and i am not sure if I am missing some needed config or if this is a bug.
When I run an elyra pipeline with two nodes, one a jupyter notebook and one a python script, only the jupyter notebook one shows the logging. I am not sure why this is the case as they are both managed the same way.
This problem also happens if the pipeline only has python scripts, just using this example as it shows the difference well.
I have added screenshots of my example, and in the logs screenshot there's the jupyter notebook one that clearly shows the expected outputs, whereas the other one doesn't have anything
Any help would be really appreciated!

**To Reproduce**
1. Create a pipeline with a python script node. This python script should have print functions or a logging.logger 
2. trigger the pipeline using kubeflow pipelines and look into the logs. the logging is missing

**Screenshots or log output**
![Screenshot 2024-04-08 at 18 00 40](https://github.com/elyra-ai/elyra/assets/82956400/e9647a02-a32e-4f2d-85db-067bf558295b)
![Screenshot 2024-04-08 at 18 00 31](https://github.com/elyra-ai/elyra/assets/82956400/39344821-360b-48f2-ae07-7968e0ce9d0a)
![Screenshot 2024-04-08 at 18 01 13](https://github.com/elyra-ai/elyra/assets/82956400/18e903e0-711c-4936-8d44-1b8ac6a469a7)
![Screenshot 2024-04-08 at 18 08 12](https://github.com/elyra-ai/elyra/assets/82956400/c107755f-15ed-45d2-8de2-35f78dde84f0)
![Screenshot 2024-04-08 at 18 08 24](https://github.com/elyra-ai/elyra/assets/82956400/d6962b7a-3b5c-4246-be76-e82db88c0471)

**Expected behavior**
I would expect identical logging for both nodes, given the fact that the code is the same. I haven't managed to get anything to output in the python script nodes. 

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 3.15.0]
 - Installation source: custom container image
 - Deployment type:  Kubernetes, Kubeflow [notebook server]

**Comment by shalberd** [comment]
A coworker of mine just today approached me with the same problem. Will verify ... I am having him submit both python and jupyter generic pipeline nodes / tasks as well. Hr mentioned the same: why don't I see the log infos in Airflow Task logs ... very similar to me to your problem described here.

**Comment by romeokienzler** [comment]
This is how we do it

` result = subprocess.run(command_array, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=os.environ.copy())
output = result.stdout.decode('utf-8')`

**Comment by shalberd** [comment]
Hi @paloma-rebuelta @romeokienzler just a quick update on my code change. I decided to let the called process error exception trickle up in subprocess by means of "check=True", as it's been before here in that part of Elyra code.
PR will follow:

```
            t0 = time.time()
    
            run_args = ["python3", python_script]
        
            with open(python_script_output, "w") as log_file:
                print("Processing file:", python_script)
                try:
                    result = subprocess.run(run_args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True)
                    output = result.stdout.decode('utf-8')
                    logger.info(f"Output: {output}")
                    logger.info(f"Return code: {result.returncode}")
                except subprocess.CalledProcessError as e:
                    logger.error("Output: %s", e.output.decode("utf-8"))
                    logger.error("Return code: %s", e.returncode)
```

See some samples, in my case Airflow, using different python content:

![Bildschirmfoto 2024-04-24 um 16 00 54](https://github.com/elyra-ai/elyra/assets/21118431/8b71d32b-515c-4d6c-bee7-46f3d332d085)
![Bildschirmfoto 2024-04-24 um 16 01 15](https://github.com/elyra-ai/elyra/assets/21118431/aa09009d-627e-48cc-afc2-57d54b791a5e)

![Bildschirmfoto 2024-04-24 um 16 02 08](https://github.com/elyra-ai/elyra/assets/21118431/da7207e1-9a12-4c4e-a4c0-1c08933bfaf9)
![Bildschirmfoto 2024-04-24 um 16 03 02](https://github.com/elyra-ai/elyra/assets/21118431/88e7ba6b-6858-483d-97fb-ebd5c7a338b3)

![Bildschirmfoto 2024-04-24 um 16 05 13](https://github.com/elyra-ai/elyra/assets/21118431/8d186f7b-4009-4f88-8f27-282c43319cd3)
![Bildschirmfoto 2024-04-24 um 16 06 53](https://github.com/elyra-ai/elyra/assets/21118431/7c8e9163-4ec4-4141-bf8f-f279694e9ce3)

**Comment by shalberd** [comment]
@harshad16 regarding notebook logs and cell output that @paloma-rebuelta sees when exucuting Jupyter notebooks code (see her first code example ipynb that I also ran today), when airflow or kfp log level is only set to INFO (not debug), it seems the log info or cell output is not written:

```
[2024-05-13, 17:31:49 UTC] {pod_manager.py:466} INFO - [base] [I 17:31:48.057] Output Notebook: notebook_log_test-output.ipynb
[2024-05-13, 17:31:49 UTC] {pod_manager.py:466} INFO - [base] 
Executing:   0%|          | 0/1 [00:00<?, ?cell/s][I 17:31:49.020] Executing notebook with kernel: python3
[2024-05-13, 17:31:49 UTC] {pod_manager.py:466} INFO - [base] 
Executing: 100%|██████████| 1/1 [00:00<00:00,  1.03cell/s]
Executing: 100%|██████████| 1/1 [00:01<00:00,  1.19s/cell]
[2024-05-13, 17:31:49 UTC] {pod_manager.py:466} INFO - [base] [I 17:31:49.259] 'NotebookLog':'notebook_log_test' - notebook execution completed (2.110 secs)
```
so we have to do some more work in bootstrapper.py for NotebokFileOps, too, it seems, with regards to logger and stdout and stderr ... I'll test this out.
