### ISSUE TITLE
Add support to run Elyra on binder

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#328]
Similar to JupyterLab, we should have a binder buttom on our readme as well as in our PRs.

**Comment by akchinSTC** [comment]
- discuss addition of python sample and pipeline

**Comment by akchinSTC** [comment]
Seeing an issue with binder when attempting to build and hits the application package, will discuss at scrum

**Comment by akchinSTC** [comment]
Idea is that, each PR will have a binder associated with the changes so devs can quickly test PRs and request changes if needed

**Comment by lresende** [comment]
I have pushed 0.8.0-dev to npm to help with the issue described above

**Comment by akchinSTC** [comment]
Making progress..seeing an issue with the git extension, ill try and hash out this weekend
[![Binder](http://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/akchinSTC/elyra-1/binder-328-v2?urlpath=lab)
