### ISSUE TITLE
Validate Elyra release on JupyterHub

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#329]

**Comment by kinow** [comment]
Tested just now as I use JupyterHub in another project, but a friend sent me the link to the Elyra project.

Worked with no issues. Just `cd` to another directory, created a `jupyterhub_config.py` with just one line `c.Spawner.default_url = '/lab'`. Used a virtualenv for the tests.

![image](https://user-images.githubusercontent.com/304786/76392968-74fbd100-63d7-11ea-99e2-4ff2a125fce9.png)

![image](https://user-images.githubusercontent.com/304786/76392979-7b8a4880-63d7-11ea-8bed-52928a77bb2a.png)

![image](https://user-images.githubusercontent.com/304786/76392989-804efc80-63d7-11ea-83a4-20bb3ac1f290.png)

![image](https://user-images.githubusercontent.com/304786/76393001-8513b080-63d7-11ea-8940-83315b4f30ad.png)

(stopped the server, restarted it, then tried the elyra python file, no issues :+1:)

**Comment by lresende** [comment]
Great @kinow, looks like you validated this on a local JupyterHub env? If so, I will let this open a little more for us to validate on the Kubernetes env, and make sure our docker images, etc are working ok on the containerized hub env.

**Comment by kinow** [comment]
>Great @kinow, looks like you validated this on a local JupyterHub env?

Yup, local only. 

>If so, I will let this open a little more for us to validate on the Kubernetes env, and make sure our docker images, etc are working ok on the containerized hub env.

Good idea :+1: and thanks for Elyra!

**Comment by akchinSTC** [comment]
Verified elyra is working on IKS (IBM Kubernetes Service).
Few things that needed to be configured:
- New storage class created with correct uid/gid for jovyan, using the ibm.io/ibmc-file provisioner. TODO, look into using fsGroup w/ block storage as workaround 
- Built elyra image on top of jupyterhub singleuser 0.9.0-beta.4 image and configure kubespawner to use it.
- Configure default spawner url to '/lab'
