### ISSUE TITLE
Update PythonEditor integration with Jupyterlab TOC after release

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#332]
Placeholder for updating the integration with JupyterLab TOC after the new release + yarn.lock updates

**Comment by lresende** [comment]
The Elyra JupyterLab 2.x branch has been updated to use latest TOC release that supports JupyterLab 2.x

**Comment by ajbozarth** [comment]
So I was wrong about this being a versioning thing. The more I look into this the more it seems that it's a side effect of leveraging a function that assumes the tracker is `IEditorTracker` and not something with the same class def. As such I believe leaving the `as unknown as` in the code is the best solution for now, so I will be closing this.
