### ISSUE TITLE
remove supernode in pipeline editor?

### ISSUE THREAD

**Issue by Tomcli** [elyra-ai/elyra#359]
On the Elyra pipeline dashboard, users can create supernode to cluster their notebook nodes. However, it seems like the kfp processor doesn't have any logic for supernode and it will fail during submission. Is there any documentation on this? Thank you.

<img width="785" alt="Screen Shot 2020-03-12 at 10 15 21 AM" src="https://user-images.githubusercontent.com/10889249/76547451-6ac6ea80-644a-11ea-8ba7-b94f80792de1.png">

<img width="808" alt="Screen Shot 2020-03-12 at 10 11 15 AM" src="https://user-images.githubusercontent.com/10889249/76547411-5a167480-644a-11ea-8a21-9e1ac1ee1aba.png">

**Comment by lresende** [comment]
We are currently not supporting the canvas supernode concept. Do you have specific requirements that supernode would help, that you cannot do with the regular pipeline? We could probably easily support it, but we need to investigate its details.

**Comment by Tomcli** [comment]
I don't think need any support on the supernode. I just found out that I can create a supernode on the UI  but it doesn't do anything. Probably we should remove it for now if we are not supporting it.

**Comment by kevin-bates** [comment]
I swapped out label 'enhancement' for 'bug' since this is something that breaks things and @Tomcli doesn't need the supernode.  Should we decide to support supernodes, we can create a new issue as an 'enhancement'.

**Comment by lresende** [comment]
Currently it's not possible to disable the supernode capabilities, but I have created an issue to support this: https://github.com/elyra-ai/canvas/issues/22
