### ISSUE TITLE
Issue Labeling Strategy

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#365]
We need to be able to easily identify items base on:
 - Type/Kind
 - Os/Platform
 - priority
 - etc

How about we look into what other projects such as [Kubeflow](https://github.com/kubeflow/kubeflow/labels) and/or [Kubernetes](https://github.com/kubernetes/kubernetes/labels) and try to apply a sub-set of labels they are using? [JupyterLab Git ](https://github.com/jupyterlab/jupyterlab-git/labels)seems to have some good set of labels as well?

**Comment by kevin-bates** [comment]
[Notebook's labels](https://github.com/jupyter/notebook/labels?page=1&sort=name-asc) are very similar to Lab Git, I wonder why? :smile:

If we're going to create "sections", I prefer how juptyer does this with "section colors" over the k8s examples provided above.

My only issue with labels is that, over time, they tend to die off, so it takes disciplined management. It also requires that labels be very clear.  Too much ambiguity only diminishes their usefulness.

**Comment by lresende** [comment]
> If we're going to create "sections", I prefer how juptyer does this with "section colors" over the k8s examples provided above.

Yes, it seems that all these one use a set of related colors for each `set` of labels
Do we want to start with the Jupyter ones? 

> 
> My only issue with labels is that, over time, they tend to die off, so it takes disciplined management. It also requires that labels be very clear. Too much ambiguity only diminishes their usefulness.

Yes, we could probably mitigate it with a small subset of labels, and self-explanatory related to which one to pick

**Comment by akchinSTC** [comment]
Agree with kevin that the section colors would work better. Lets go with the jupyter ones for now and a small subset (priority, component and type?)

**Comment by kevin-bates** [comment]
This is a good scrum item.  I'm beginning to wonder if individual colors might be better. Those sections seem good.  We can probably thin some of the entries as well.

**Comment by akchinSTC** [comment]
Updated existing labels with the following:
component:
kind:
priority:
area:
