### ISSUE TITLE
Code Snippets requests data on extension activated

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#390]
As discussed in #241 , the user is required to configure Code Snippet extension by creating a `code-snippets/` folder in `api/metadata/`, where json files are fetched to render in the UI.

The client side fetches and renders data as soon as the extension activates, and if it is not yet configured, the application throws an error dialog with the message 
`'Metadata namespace 'code-snippets' was not found!'`

We should only request data from the server when the extension is in use (eg. when clicking on the snippet icon on the left side bar, or on page restore when snippet list is already on display).

**Comment by kevin-bates** [comment]
This sounds like a good plan.  I assume that when the snippet icon is clicked, and the code-snippets namespace is still raising a 404, you'll indicate that code-snippets must be configured or perhaps (since there's no way to create snippets today) just silently display an empty list.  Is that the plan?

**Comment by karlaspuldaro** [comment]
@kevin-bates correct. As discussed in today's scrum, both are valid, I like the idea of a detailed info on how to set it up since our app currently does not support add code snippets from the UI directly yet. The error handling can be treated as a new issue. As for now, the fix for the problem above will still display an error dialog, although instead of a popup on the first page load, it happens once the code snippet extension is in use.

**Comment by karlaspuldaro** [comment]
Fixed in [this commit](https://github.com/elyra-ai/elyra/pull/241/commits/ff20a1731648d75580ffaa826859116e0cbbda4e) in #241
