### ISSUE TITLE
`ValueError` when running `make clean install`

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#419]
in clean new Node.js environments when running the command:

```
make clean install
```

it fails with the error:

```
ValueError: "<path_to_parent_directory>/elyra/packages/application" is not a valid npm package
```

you can get past this issue by globally installing some NPM packages:
```
npm install -g lerna@3.19.0
npm install -g rimraf@3.0.0
npm install -g typescript@3.7.3
npm install -g yarn@1.21.0
```
however, this only works around the problem.

the problem appears to stem from the `clean` script in the NPM packages which is deleting the  package's `node_modules` directory.

`clean` is probably not needed in the `package.json` since the `Makefile` is already cleaning up the packages/directories. however, if `clean` is needed it probably shouldn't be removing the `node_modules` directory.

**Comment by lresende** [comment]
Fixed by #420
