### ISSUE TITLE
Improve the right-click menu of the editor

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#424]
Track upstream issue [#2778](https://github.com/jupyterlab/jupyterlab/issues/2778) on JupyterLab

Adding basic commands to the right-click on file editor:
- select all
- cut
- copy
- paste
- undo
- redo

Requires future follow up on Python Runner extension

**Comment by karlaspuldaro** [comment]
PR: https://github.com/jupyterlab/jupyterlab/pull/8425

**Comment by lresende** [comment]
Merged in Jupyterlab
