### ISSUE TITLE
Dialogs should have the option to be expanded

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#426]
As an example, error dialogs might have stack trace information, which contents might span to multiple lines and not very very easily seen on the small fixed size of the current dialogs. It would be good to enable users to enlarge it (e.g. like the editable version of this GitHub textbox)

![image](https://user-images.githubusercontent.com/382917/79030275-0e401380-7b4d-11ea-9ec5-e7582cef025a.png)

**Comment by lresende** [comment]
@vabarbosa this is very similar to the #431 where you enable the text field to be resizable... might need a little more css to enable the dialog to be a little bigger or expandable.

**Comment by vabarbosa** [comment]
so after investigating we have a few ways to approach the issue:

1. wrap all Elyra dialog messages in a `<textarea>` before calling JupterLab's `showDialog()`

    ```javascript
    import React from 'react';
    import { showDialog, Dialog } from '@jupyterlab/apputils';

    const dialogMessage = 'Lorem ipsum dolor sit amet consectetur';

    showDialog({
      title: 'Some dialog title',
      body: <textarea defaultValue={dialogMessage}></textarea>,
      buttons: [Dialog.okButton()]
    });
    ```

2. create and use Elyra's own `showDialog()` which extends JupyterLab's `showDialog()`

    for example in a `elyrautils.tsx` file in `packages/application`:

    ```javascript
    import { showDialog as showJpDialog, Dialog } from '@jupyterlab/apputils';
    import React from 'react';

    export const showDialog = function<T>(
      options: Partial<Dialog.IOptions<T>> = {}
    ): Promise<Dialog.IResult<T>> {
      if (typeof options.body === 'string') {
        options.body = <textarea defaultValue={options.body}></textarea>;
      }
      return showJpDialog(options);
    };
    ```

    then all Elyra dialog messages would call Elyra's `showDialog()` instead of JupyterLab's `showDialog()`:

    ```javascript
    import React from 'react';
    import { showDialog } from '@elyra/application';

    const dialogMessage = 'Lorem ipsum dolor sit amet consectetur';

    showDialog({
      title: 'Some dialog title',
      body: dialogMessage,
      buttons: [Dialog.okButton()]
    });
    ```

3. Update JupyterLab's `showDialog()` to wrap dialog body in a `<textarea>` and not changes would e needed in Elyra

    in `jupyterlab/packages/apputils/src/dialog.ts`:

    ```javascript
    export function showDialog<T>(
      options: Partial<Dialog.IOptions<T>> = {}
    ): Promise<Dialog.IResult<T>> {
      if (typeof options.body === 'string') {
        options.body = <textarea defaultValue={options.body}></textarea>;
      }
      const dialog = new Dialog(options);
      return dialog.launch();
    }
    ```

all three options would require some additional minimal CSS updates. for example:

```css
.jp-Dialog-body textarea.jp-mod-styled {
    border: 0 none;
}
```


the end result for any of the above option is a dialog with a resize handle to be able to change the size of message/body area:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/13156555/79475277-77080f80-7fd5-11ea-91b0-c083df6541bd.png">

**Comment by kevin-bates** [comment]
No useful comment although I found the use of [Lorem ipsum](https://www.lipsum.com/) interesting. 🎓

**Comment by ajbozarth** [comment]
As stated in scrum I vote option 3 if the community responds to it well, otherwise if it's rejected then we should go with option 2. I do worry that it will take more than just that one line to css to make sure that the current lab dialogs still look the same though

**Comment by vabarbosa** [comment]
yes, i expect additional css will be involved (given different browser behavior, etc), but it shouldn't be too much more.

**Comment by vabarbosa** [comment]
created [Jupyter Lab issue #8300](https://github.com/jupyterlab/jupyterlab/issues/8300)

**Comment by vabarbosa** [comment]
submitted [Jupyter Lab pull request #8301](https://github.com/jupyterlab/jupyterlab/pull/8301)

**Comment by lresende** [comment]
The above PR has been merged, thanks @vabarbosa.

**Comment by vabarbosa** [comment]
@lresende i am reopening this because now that Jupyter Lab Dialogs can be resized we should clean up some of the Elyra Dialog CSS which are forcing a fixed max-width and height so then it does grow/resize as expected:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/13156555/80613158-e38a0200-8a0a-11ea-97b4-d713ad316fe8.png">

i will go ahead and submit a PR to resolve this
