### ISSUE TITLE
Refactor README into user documentation

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#428]
Our readme is becoming huge, and I believe it would be better if we use that structure and start creating a user documentation mixed with a getting started guide.

**Comment by kjdoyle** [comment]
What technologies should be used for the documentation? I would think hosting on readthedocs, but after:

Technology: RST or Markdown
Theme: Pydata( https://jupyter-server.readthedocs.io/en/latest/index.html) or regular ( https://jupyterlab.readthedocs.io/en/stable/ )

**Comment by kevin-bates** [comment]
Hmm - good point about referencing the lab theme.  Kinda thinking since Elyra is a "lap-app", we should probably follow their lead.  

Do others agree?

I also tend to prefer working in markdown files, but that's probably just a familiarity thing.

**Comment by kjdoyle** [comment]
I took a first stab at this. Since existing content is in markdown I kept to markdown for now and used the same theme as JupyterLab ( sphinx_rtd_theme ).

**Comment by kevin-bates** [comment]
Wow - that was quick!  I'll try to take this for a spin tomorrow.
