### ISSUE TITLE
Update arrow icons in code snippets

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#430]
Currently the arrows for expanding a code snippet in the UI are `v` for unexpanded and `^` for expanded. This usage matches the UX for opening and closing an expandable section, as we do in our error dialog, because the down arrow says "click for more info" and the up arrow says "hide more info." For code snippets the expanded section is more like subsection. As such it would make more sense for unexpanded content to use `>` and expanded content to use `v` this would match how the git extension handled its expandable sections.

**Comment by kjdoyle** [comment]
I'm interested in working on this, if no one else is.

**Comment by ajbozarth** [comment]
go ahead, it's a small change, should just be updating the css vars to use the different direction arrows from lab.

**Comment by kjdoyle** [comment]
Looks like we should wait till the jupyterlab 2.0 code is merged in as it is very different to do the icons compared to copying in new ones now and code-snippets isn't in that branch currently. Also found that the error dialog has the icons in the wrong way to, so we can fix those up at the same time too.

**Comment by vabarbosa** [comment]
@kjdoyle @ajbozarth if i am not mistaken, i believe this has just been addressed in https://github.com/elyra-ai/elyra/pull/439

<img width="454" alt="image" src="https://user-images.githubusercontent.com/13156555/80443786-08cd2200-88de-11ea-9888-15c51c2b494f.png">

**Comment by ajbozarth** [comment]
@vabarbosa yep I snuck it in there while I was already having to update the arrow vars. I will be updating it further in #443 when I update code snippets to use LabIcons. So we can close this after either one is merged
