### ISSUE TITLE
All endpoints should be documented in swagger docs

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#434]
Just realizing that /api/scheduler is not documented in the swagger docs.  In addition, PR #433 may introduce /api/export.  Both of these need to be documented in the swagger docs.

**Comment by kevin-bates** [comment]
Sorry, I just remembered that we chose not to document /api/scheduler at this time, and /api/export is probably in the same boat.  Closing.

**Comment by kevin-bates** [comment]
Once we settle on the model for transport as a result of #527 this issue can be started.

**Comment by vabarbosa** [comment]
#513 will be updating the endpoints which will required updates to swagger doc accordingly. i assume at that time this could also be addressed.
