### ISSUE TITLE
Dialogs are non-modal

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#435]
When submitting pipelines, the resulting dialogs are non-modal. e.g. if you have a slow internet connection, you and click multiple times, a queue of the same dialogs builds up and you loose state where you actually are in the submission process

**Comment by romeokienzler** [comment]
Just noticed this again - I was thinking the pipeline is still submitting but I had a network issue and only saw the "underlying" dialog once I've closed the previous one.
I suggest not waiting for an upstream fix in jupyterlab but moving those outputs to the status panel

**Comment by ptitzler** [comment]
One problem with modal dialogs is that they prevent the user from doing anything else. In some scenarios this would be a major issue, e.g. when a pipeline is executed locally, which might take a long time.

**Comment by romeokienzler** [comment]
agree, that's why I suggested:

>I suggest not waiting for an upstream fix in jupyterlab but moving those outputs to the status panel

Do you know if this is possible?

**Comment by lresende** [comment]
Duplicate of #1064
