### ISSUE TITLE
README references use of a docker image without providing a tag or references to one

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#441]

**Comment by ptitzler** [comment]
The relevant section: https://github.com/elyra-ai/elyra#optional-
> Docker - If using the docker image

**Comment by akchinSTC** [comment]
@kjdoyle would you mind removing this line in your current documentation PR?

**Comment by kjdoyle** [comment]
@akchinSTC done. Fixed in the README and installation doc topic of the PR.

**Comment by akchinSTC** [comment]
awesome..thanks
