### ISSUE TITLE
[DISCUSS] Sharing configuration data between frontend and server

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#442]
## Introduction

We've had a number of issues arise in which it would be beneficial to share configuration-related information between the frontend and server without having to hard-code this information.  This issue presents a proposal to address this item.

Clearly, we could create our own "configuration service" in which the server manages configuration and provides a REST API to enable its access for the frontend services.  That would probably be fairly straightforward.  However, this proposal focuses on using the _existing_ configuration service and config manager classes already built into the Notebook Server (and, is also in the upcoming Jupyter Server).  

## Configuration Manager Service
The existing configuration manager service is available to users (and frontend services) via the `/api/config` endpoint.  The actual endpoint is `/api/config/section_name` where _section_name_ identifies the "section" of the overall configuration entries.

The configuration manager service uses the [`ConfigManager`](https://github.com/jupyter/notebook/blob/master/notebook/services/config/manager.py#L14) class.  By default, this class instance locates its paths to search using the [`jupyter_config_path()`](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py#L184) method from `jupyter_core`, where each path entry has `/nbconfig` appended to it.  For example, on my system, the following directories will be searched:
```
'/etc/jupyter/nbconfig', '/usr/local/etc/jupyter/nbconfig', '/opt/anaconda3/envs/notebook-dev/etc/jupyter/nbconfig', '/Users/kbates/.jupyter/nbconfig'
```
Note that this path order is _reversed_ from what `jupyter_config_path()` returns (nor does it include '/nbconfig').  This is because the `ConfigManager` wants to treat any configuration values in the later directories as overrides of earlier values.

The `/nbconfig` addition comes from [configurable traits](https://github.com/jupyter/notebook/blob/master/notebook/services/config/manager.py#L40-L48) on `ConfigManager` named `read_config_path` and `write_config_path` which append `juptyer_config_path()` with `nbconfig` to form the default location. 

For each of these directories, ConfigManager's [`get(section_name)` method searches for the _section_name_](https://github.com/jupyter/notebook/blob/master/notebook/services/config/manager.py#L23-L25).

### Section name
The configuration manager service takes the _section_name_ from the endpoint and looks for _either_ of the following:
- a file of the name _section_name_.json
- or a directory of the name _section_name_.d that contains a file _section_name_.json

I propose the section name for Elyra be **elyra** and, to simplify configuration, we will not use the subdirectory approach.  As a result, the `ConfigManager` instance will look for the `elyra` section in a file named `elyra.json`, located in one or more of the directories on `juptyer_config_path()` where the precedence follows the directory order listed above and "next" directory overrides previous directories.

## Elyra.json
Gathering information from the related issues (see below), here's an example of how an `elyra.json` file might look:
```JSON
{
  "export_formats": ["tgz", "tar.gz", "zip", "yaml", "yml", "py"],
  "docker_images": {
    "tensorflow/tensorflow:1.12.3-py3": "Tensorflow 1.12.3",
    "tensorflow/tensorflow:1.12.3-gpu-py3": "Tensorflow 1.12.3 w/ GPU",
    "tensorflow/tensorflow:2.0.0-py3": "Tensorflow 2.0",
    "tensorflow/tensorflow:2.0.0-gpu-py3": "Tensorflow 2.0 w/ GPU",
    "pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime": "Pytorch 1.2 w/ CUDA-runtime",
    "pytorch/pytorch:1.2-cuda10.0-cudnn7-devel": "Pytorch 1.2 w/ CUDA-devel",
    "amancevice/pandas:0.25.0-jupyter": "Pandas"
  },
  "support_supernodes": False
}
```
### Deployment
We would like to have this JSON file located within the repository since it contains "factory defaults".   It will also be installed when elyra is installed - similar to the schema files.  One possible location would be `elyra/configuration`, but where its located doesn't matter so long as it's accessible by code. 

Upon Elyra's startup, we could then have some code - likely when the extension is loaded - that copies the file to _as early a directory as possible_ (i.e., furthest from the user's home directory) in the configuration path.  If an `elyra.json` file is already there, we should attempt to honor any overrides that may have taken place.  **_How to distinguish missing values (removed by user) from removed values (removed by repo)?_**  I think we have this issue no matter how we go about this.

By placing the file in an _early directory_ we minimize the conflicts where a user may have altered configuration and need that override to still take place.

## Usage
Here are examples of how the various parts of Elyra might go about accessing the configuration based on the example `elyra.json` file above.  I "hand-wave" quite a bit with respect to the frontend, but I think the idea is conveyed:

**Frontend usage:**
```
response = {GET "/api/config/elyra"}
elyra_config = response.body
available_images = elyra_config.get("docker_images")
allow_supernodes = elyra_config.get("support_supernodes")
export_formats = elyra_config.get("export_formats")
```
**Server usage:**
```python
from notebook.services.config.manager import ConfigManager

cm = ConfigManager()
elyra_config = cm.get("elyra")
available_images = elyra_config.get("docker_images")
allow_supernodes = elyra_config.get("support_supernodes")
export_formats = elyra_config.get("export_formats")
```
Related issues: #360, #376, #407

**Comment by lresende** [comment]
I believe this was created during the Classic Notebook timeframe and would require the user to always go to terminal for configuration. 

How about we experience with the new front-end settings editor added to Jupyterlab and accessible via the UI for the users? I have a quick prototype in #447

![image](https://user-images.githubusercontent.com/382917/80440816-6fdade80-88be-11ea-95a1-1284b25e717a.png)


Now, related to #407, I am not sure if this should be a configuration, or actually a "feature" based on what is the exporters registered for each of the runtime processors, and that's why I still want to make the exporters an extension on the Elyra backend side.

**Comment by kevin-bates** [comment]
> would require the user to always go to terminal for configuration.

I guess I don't understand this.  The configuration lives in a file, along with all other configuration.  By using the service we're making it accessible to the front-end.  Is there a requirement to allow configuration to be set from the front-end?

So long as there's a way to get at the same configuration by both front and back ends, I'm good with whatever the solution is.  Some of the example config items above probably don't need to be validated by the server.  For example, the docker image is just used by the server.  Not sure about export formats.  

We should probably talk about what the requirements are first.
