### ISSUE TITLE
Pandas version conflicts?

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#453]
As discussed with @lresende, we get an issue when running a [pipeline](https://github.com/CODAIT/covid-notebooks/blob/master/pipelines/us_data_romeo.pipeline) - it looks like a pandas version conflict although we are pip - installing the newest version of pandas on top of the notebook. also locally it runs fine with that version of pandas. Maybe there is an issue in the TensorFlow 1.12.3 image, but only guessing...here the [error](https://gist.github.com/romeokienzler/70c4141c2ba30fbf62e3ce71b985e7f3)

**Comment by lresende** [comment]
I believe this is similar to [kfp-notebook#15](https://github.com/elyra-ai/kfp-notebook/issues/15) and @akchinSTC and @yil532 are testing a solution, hopefully this will be in tomorrow.

**Comment by akchinSTC** [comment]
looks like the TF images prior to 1.13 had pandas pre-installed (0.23.4) which didn't have the explode routine(0.25.0) available. Bumping to 1.15.2, pandas will install as version 1.0.3.

**Comment by romeokienzler** [comment]
@akchinSTC @lresende thanks a ton! confirming that it is working!
