### ISSUE TITLE
Cleanup stale branches from Elyra repo after lab 2.x support merged

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#459]
Are we all ok deleting the following elyra branches? 
* remotes/origin/jupyterlab-2.0
* remotes/origin/jupyterlab-2.0-backup-20200217
* remotes/origin/jupyterlab-2.0-backup-20200317
* remotes/origin/jupyterlab-2.0-backup-20200323
* remotes/origin/jupyterlab-2.0-rebased-20200217
* remotes/origin/kspuldaro-code-snippet-display
* remotes/origin/lresende-code-snippet-backup-20200331
* remotes/origin/lresende-update-dependencies

@akchinSTC @marthacryan @karlaspuldaro @ajbozarth @kevin-bates 
Please vote with thumbs up and thumbs down.

**Comment by ajbozarth** [comment]
should we also delete `ui-tests`?

**Comment by marthacryan** [comment]
> should we also delete `ui-tests`?

Yes and `extension-tests`

**Comment by ajbozarth** [comment]
So delete everything but `master` then :)

**Comment by lresende** [comment]
Done, removed all branches but master.
