### ISSUE TITLE
command "jupyter serverextension list" doesn't show elyra version installed

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#466]
(tf2.0) Romeos-MacBook-Pro-3:analysis romeokienzler$ jupyter serverextension list
config dir: /Users/romeokienzler/opt/anaconda3/envs/tf2.0/etc/jupyter
    elyra  enabled 
    - Validating...
      elyra  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.2.6 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.10.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 1.1.0 OK

**Comment by kevin-bates** [comment]
Thanks Romeo - a fix for this was submitted just a day or so ago via #452 and I'm assuming you're not running with that version.

**Comment by akchinSTC** [comment]
building with master, I see the version number 
![image](https://user-images.githubusercontent.com/13340013/80748527-e9024d80-8ad9-11ea-815b-67782fbafcda.png)

**Comment by lresende** [comment]
We didn't backport to JupyterLab 1.x branch, I will use this issue for that.

**Comment by lresende** [comment]
This has been fixed in Elyra 1.0.0 and we won't backport to old releases.
