### ISSUE TITLE
Documentation on how to add pipeline processor

### ISSUE THREAD

**Issue by OElesin** [elyra-ai/elyra#481]
This is an excellent project. However, only supports KubeFlow pipelines as processor. Can you please provide some documentation on how to add more pipeline processor? 

I would love to see if this can work with [AWS Step Functions Data Science SDK](https://github.com/aws/aws-step-functions-data-science-sdk-python).

Thanks in advance!

**Comment by lresende** [comment]
@OElesin There are some initial [pipeline documentation](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html) in our repo, but the overall flow is `Pipeline Editor` -> `Scheduler Handler` -> `Parsing` -> `Processor`. The processor is pluggable and there is one per runtime. We currently have the (Kubeflow Pipeline processor)[https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_kfp.py] and an in-progress [Airflow Pipeline processor](https://github.com/akchinSTC/elyra-1/tree/akchin-airflow-update) by @akchinSTC

**Comment by akchinSTC** [comment]
Hello! I have a work in progress PR for airflow that I've just rebased that should be more up to date here : https://github.com/elyra-ai/elyra/pull/490

**Comment by ptitzler** [comment]
Tracked in https://github.com/elyra-ai/elyra/issues/2100
