### ISSUE TITLE
Markdown tables not properly rendered in docs

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#486]
Tables in markdown files are not displayed as expected when rendered in HTML documentation

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/13156555/81014470-e92c8100-8e2a-11ea-8c3f-a6df0b94aa84.png">

Markdown in Sphinx is supported through `recommonmark`, which unfortunately does not support tables. however, we may be able to use the `sphinx-markdown-tables` extension to get markdown table support

**Comment by lresende** [comment]
Just to make it easier to find:
https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html?highlight=define%20the%20properties#using-the-elyra-pipeline-editor, right below the second pipeline image.
