### ISSUE TITLE
Simplify how new components are added to Pipeline editor

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#500]
Currently adding new components to the pipeline editor requires the backend implementation, and updates to multiple canvas related JSON files (pallet, common properties, etc). KFP provides component definitions that can be used to introspect and generate these to simplify the user experience when adding new components.

- [ ] Generate pipeline editor configuration dynamically via REST API (see #454)
- [ ] Investigate how we could introspect KFP component YAML to generate pipeline editor config files
- [x] Integrate discovered components into pipeline editor UI
- [x] investigate the need for a whitelist of components
- [x] how to support multiple runtimes on this scenario (e.g. only display KFP vs airflow components)

Going back to the overall idea here, imagine we have a KFP component like this:

```
name: 'Train Spark Model - IBM Cloud'
description: |
  Train a Spark Model using IBM Cloud Spark Service
metadata:
  annotations: {platform: 'IBM Cloud Spark Service'}
inputs:
  - {name: bucket_name,      description: 'Required. Object storage bucket name'}
  - {name: data_filename,    description: 'Required. Name of the data binary'}
  - {name: model_filename,   description: 'Required. Name of the training model file'}
  - {name: spark_entrypoint, description: 'Required. Entrypoint command for training the spark model'}
outputs:
  - {name: model_filepath,           description: 'Spark Model binary filepath'}
  - {name: train_data_filepath,      description: 'Spark training data filepath'}
implementation:
  container:
    image: docker.io/aipipeline/train_spark:latest
    command: ['python']
    args: [
      -u, train_spark.py,
      --bucket_name, {inputValue: bucket_name},
      --data_filename, {inputValue: data_filename},
      --model_filename, {inputValue: model_filename},
      --spark_entrypoint, {inputValue: spark_entrypoint}
    ]
    fileOutputs:
      model_filepath: /tmp/model_filepath
      train_data_filepath: /tmp/train_data_filepath
```

The idea is that we would produce a `palette.json` for the canvas component that would then include the discovered `Train Spark Model`, and we would also introspect the metadata for this component and harvest inputs, outputs, etc to generate a valid properties.js that would be used by common properties component to allow the user to provide parameters to these components.

**Comment by vabarbosa** [comment]
@lresende @kevin-bates i would interested in assisting with this effort

**Comment by ptitzler** [comment]
This requested functionality was delivered with the introduction of [component catalog connectors](https://elyra.readthedocs.io/en/stable/user_guide/pipeline-components.html#component-catalogs).
