### ISSUE TITLE
Update the `/api` endpoints to `/elyra`

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#513]
`/api` is used as the starting path for Elyra endpoints. e.g., `/api/metadata/code-snippets`.

while `/api` is convenient and also easy to remember, after some discussion and playing around with the swagger docs i have a couple comments:

1. `/api` is very common. there is the possibility that some extension (or Jupyter functionality) comes along which also uses the `/api` path. this clash could cause issues.

1. `/api` is not clearly identifiable as an Elyra specific endpoint. someone could easily assume that `/api/metadata/runtimes` is a Jupyter endpoint and have no way of immediately realizing it is strictly for Elyra.

with that being said, i would think Elyra would want its own/unique path to clearly distinguish its endpoints. e.g.,  `/elyra`.

the possibility of some other 3rd party component or a Jupyter update being introduced that used that same `/elyra` path is much more unlikely. at the same time, the Elyra API endpoints would become clearly recognizable:

- `/elyra/metadata/code-snippets`
- `/elyra/metadata/runtimes`
- `/elyra/schema`
- etc.

it doesn't necessarily have to be `/elyra` (although i think that works well) but something more distinguishable and less common than `/api` should be considered.

i would expect changing/updating the endpoint path is a manageable task but then again i don't know how set in stone the Elyra APIs are to properly speak on how much work would actually be involved. so i leave this here for discussion and thoughts from others?

**Comment by kevin-bates** [comment]
I agree.  In fact, all of the notebook endpoints begin with /api.  I think this change makes sense.

**Comment by kjdoyle** [comment]
I agree with this as well. We always try to differentiate the different APIs with a different prefix.

**Comment by lresende** [comment]
I am ok with either `/api/elyra` or just `/elyra`.

**Comment by kevin-bates** [comment]
I asked about this in today's jupyter_server meeting and the convention is for the server extension to define its own "root".  They referenced both Lab (`/lab`) and Voila (`/viola`) as examples.  As a result, we should go with `/elyra`.

**Comment by vabarbosa** [comment]
nice. thanks for checking.

**Comment by kevin-bates** [comment]
@ajbozarth is currently refactoring front-end methods that, upon completion, will result in fewer areas that reference `/api/xxx` today.  As a result, we should wait until the following issues are closed: #271, #400

**Comment by kevin-bates** [comment]
Per https://github.com/elyra-ai/elyra/pull/554#pullrequestreview-415849381, it would be good to move `/api/scheduler/*` to `/api/pipeline` as well.

**Comment by vabarbosa** [comment]
will take care of this as soon as #271, #400, and #561 are closed
