### ISSUE TITLE
Copy notebook cells to a python file

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#52]
See details at
https://github.com/jupyterlab/jupyterlab/issues/6976

**Comment by karlaspuldaro** [comment]
We can currently drag notebook cells into a python file:
![drag-and-drop-cell-to-editor](https://user-images.githubusercontent.com/25207344/95903936-d072b080-0d64-11eb-93d6-9441a6727d53.gif)

It would be good to add an accessible option to copy/paste cells into the editor using the context menu

**Comment by ptitzler** [comment]
I believe the current behavior sufficiently addresses the original issue, even if it not completely accessible.
