### ISSUE TITLE
Runtime metadata with undocumented field not showing on list of available runtimes

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#522]
Create a runtime configuration like:

```
{
  "schema_name": "kfp",
  "display_name": "KFP with IBM COS (yukked1)",
  "metadata": {
    "api_endpoint": "http://yukked1.fyre.ibm.com:31380/pipeline",
    "cos_endpoint": "https://s3.us-south.cloud-object-storage.appdomain.cloud",
    "cos_username": "xxx",
    "cos_password": "xxx",
    "cod_secure": "True"
    "cos_bucket": "xxx"
  }
}
```

Trying to list with `elyra-metadata list runtimes`

```

Available metadata instances for runtimes (includes invalid):

Schema   Instance     Resource                                                            
------   --------     --------                                                            
kfp      kfp-smashup  /Users/lresende/Library/Jupyter/metadata/runtimes/kfp-smashup.json  
kfp      kfp-weakish  /Users/lresende/Library/Jupyter/metadata/runtimes/kfp-weakish.json  
kfp      kfp-yukked   /Users/lresende/Library/Jupyter/metadata/runtimes/kfp-yukked.json   

```

**Comment by kevin-bates** [comment]
@lresende - this is because you provided invalid json in the first place.  We'll need to fix that, but this will not happen if using elyra-metadata (or the REST API [pending]) to create instances.

Once a valid json file is provided you'll see this instance listed as invalid.

**Comment by lresende** [comment]
Late night user error :)

**Comment by kevin-bates** [comment]
Ok. I was just going to comment, that I'm not sure what we can do about this.  I have, however, added some logging in this area, so at least these kinds of instances will be flagged somehow, but that's about all we can do.  They can't even be treated as validation issues since the file can't even load.

**Comment by kevin-bates** [comment]
Since there is some code behind this, I'm going to reopen and submit a PR shortly.
