### ISSUE TITLE
runtime configuration: elyra-metadata not found

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#525]
Following the instructions in https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html I tried running `elyra-metadata install runtimes` , which failed because the `elyra-metadata ` command was not found.

Please advise.

Output from the validation commands:
```
$ python --version
Python 3.7.7

$ node --version
v12.16.3


$ pip freeze | grep elyra
elyra==0.10.2

$ pip freeze | grep jupyterlab
jupyterlab==1.2.15
jupyterlab-git==0.10.1
jupyterlab-server==1.1.3


$ jupyter serverextension list
config dir: /Users/patti/anaconda3/envs/kubeflow/etc/jupyter
    elyra  enabled 
    - Validating...
      elyra  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.2.15 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.10.1 OK
    nbdime  enabled 
    - Validating...
      nbdime 1.1.0 OK

$ jupyter labextension list
JupyterLab v1.2.15
Known labextensions:
   app dir: /Users/patti/anaconda3/envs/kubeflow/share/jupyter/lab
        @elyra/application v0.10.2  enabled  OK
        @elyra/code-snippet-extension-experimental v0.10.2  enabled  OK
        @elyra/notebook-scheduler-extension v0.10.2  enabled  OK
        @elyra/pipeline-editor-extension v0.10.2  enabled  OK
        @elyra/python-runner-extension v0.10.2  enabled  OK
        @jupyterlab/git v0.10.1  enabled  OK
        @jupyterlab/toc v2.0.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK

```

**Comment by kevin-bates** [comment]
Hi @ptitzler  - This script should reside in your python's `bin` directory following the installation.  The python's bin directory can be found via...
```python
import sys
sys.prefix
```

Perhaps this directory is not in your current PATH.

**Comment by kevin-bates** [comment]
Actually, the issue is that the docs you're using do not reflect the release you're using.  Instead you probably have the previous version of the tool: `jupyter-runtimes`, so a command like `jupyter runtimes install kfp` should display the options you need.

**Comment by ptitzler** [comment]
Yes, thank you. I upgraded to the code in the master branch to make it work. Looks like the PyPI version is behind, hence the disconnect between the docs and the installation. The command can now be found.

**Comment by kevin-bates** [comment]
For others that may take the PyPI version 0.10.2 prior to our next release, the applicable documentation for creating runtime metadata instances can be found here: https://github.com/elyra-ai/elyra/tree/v0.10.2#configuring-runtime-metadata

We only created the readthedocs.io entry post 0.10, but most information relative to 0.10 can be found off that README file.

**Comment by binhphung** [comment]
> Yes, thank you. I upgraded to the code in the master branch to make it work. Looks like the PyPI version is behind, hence the disconnect between the docs and the installation. The command can now be found.

hi bro, I'm having the same problem as you, can you help me? i have updated pypi but no success. and cannot run the command `jupyter runtimes install kfp`
