### ISSUE TITLE
Copy code snippet confirmation message

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#531]
It would be helpful if the copy code snippet button could provide some sort of feedback message to the user, such as `Code snippet copied to clipboard`, as suggested in [this comment](https://github.com/elyra-ai/elyra/pull/475#issuecomment-626865047)

**Comment by vabarbosa** [comment]
hello, is the preference for something like

(a) status bar update: https://jupyterlab.readthedocs.io/en/stable/developer/extension_points.html?#status-bar  
or  
(b) toast notification: https://github.com/jupyterlab/jupyterlab/pull/6389

**Comment by karlaspuldaro** [comment]
@vabarbosa I would vote for something like a floating msg such as the toast notification, if it can be placed closer to the selected copy button somehow. I find the status bar at the bottom of the page can be harder to notice, but maybe that would be simpler to implement.

**Comment by vabarbosa** [comment]
the status would be simpler (and quickest to implement), but i prefer the toast notification as well. however, with the toast notification we have a couple options:

1- create and display a simple/basic alert specifically for the code-snippet copy action
2- create a more generic toast notification system for Elyra that can be re-used by other components/actions as needed
3- help push/move https://github.com/jupyterlab/jupyterlab/pull/6389 along so there would be a consistent toast notification system for JupyterLab which Elyra can then leverage as needed

and with these options i would vote for (3) but i haven't looked too much into it to know for sure how much additional work is needed for it versus how quickly we want this issue addressed.

**Comment by ajbozarth** [comment]
I was thinking of something like how ibmcloud's SSO page does it:
<img width="1792" alt="Screen Shot 2020-05-15 at 2 06 05 PM" src="https://user-images.githubusercontent.com/13952758/82096246-6bcc0080-96b5-11ea-9978-f386eb60543b.png">

**Comment by karlaspuldaro** [comment]
I also think approach 3 is the best as well, since in my opinion this feature is not a high priority, and the open PR would be a useful lab feature

**Comment by vabarbosa** [comment]
> I was thinking of something like how ibmcloud's SSO page does it:
> <img alt="Screen Shot 2020-05-15 at 2 06 05 PM" width="1792" src="https://user-images.githubusercontent.com/13952758/82096246-6bcc0080-96b5-11ea-9978-f386eb60543b.png">

i like this approach. i've assigned to myself and will try to implement something similar
