### ISSUE TITLE
Add ability to create code-snippets from the UI

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#556]
Now that metadata instance can be managed via the REST API, we should minimally add the ability for users to create, update, and delete code-snippets from the web frontend.

**Comment by marthacryan** [comment]
Here are a couple ideas for the UI of creating / editing / deleting code-snippets:
* Edit snippets / snippet info within the widget without a dialog:
![image](https://user-images.githubusercontent.com/6673460/83075481-8e590480-a039-11ea-81af-8ff9e32d9f37.png)
    * There would be a "save" button near the other action buttons. 
    * At the top of the code snippets widget, there would be an "Add snippet" button that would create a blank snippet 
         * name: 'untitled'
         * coding language: '<language>'
         * empty code snippet preview, but it has a code editor embedded in it for easy changes to code snippets
    * Right click the name of the snippet to show a context menu that allows you to rename the snippet or change the coding language (in a dialog)
* Open a dialog that prompts for all fields (name, language, code), and autofills these fields when editing a snippet

**Comment by ajbozarth** [comment]
Though I like the idea of editing directly in the current UI, I believe the cleaner UX would be the second option: 
> Open a dialog that prompts for all fields (name, language, code), and autofills these fields when editing a snippet
which would be opened via an edit button or add new button (in the header) like you described.

**Comment by kevin-bates** [comment]
My only ask is that users not feel like they're filling in an array when typing each line of their code since that's how it gets stored.  The code portion should feel as natural as possible.  

I think it would be ideal if they could also have language-sensitive contexts (highlighting, perhaps even IntelliSense) during their creation and perhaps that's something someone can contribute downstream if it's really difficult.  (I have no idea really.)

**Comment by karlaspuldaro** [comment]
Agree with @ajbozarth on the second option, with add new button in the header, and edit/delete buttons on each snippet item.

Also agree with @kevin-bates about not making the user construct the array of lines themselves. Maybe the codemirror option can come later as an enhancement since that's what's planned for the preview box as well.
