### ISSUE TITLE
Surface input and outputs to the user as part of tooltip

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#571]
e.g. a child node displays a list of propagated inputs from parents and grandparents etc.

**Comment by ptitzler** [comment]
This functionality is available for custom components, as shown here in the node properties view

![image](https://user-images.githubusercontent.com/13068832/152001508-9feed892-f140-4438-b4d5-a6db1c245042.png)

and here in the tool tip

![image](https://user-images.githubusercontent.com/13068832/152001768-2e8ac017-8afe-4f4a-b629-d80c3aa6797f.png)

`Download Data` is the parent node's label, and `data` the name of the node's output.
