### ISSUE TITLE
Pipeline editor is not formatting saved pipelines correctly

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#574]
Currently the pipeline editor is saving the entire pipeline as a single line, making the ability to see diffs impossible.

**Comment by kevin-bates** [comment]
I've spent some time on this today and this isn't doable as long as the `/api/contents` API is used to persist pipelines.  

The server contents API handles three "types" of files; 'notebook', 'directory', and 'file'.  And, even though their models allow for a 'format' field, types of 'file' can only support formats of 'text' or 'base64' and not 'json' - which is the format used 'notebook' types.  So even adding a field of [`format: 'json'` to index.ts](https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/src/index.ts#L112-L114), that "format" specifier will not be honored (and, if it could be set, would actually [result in a 400 exception](https://github.com/jupyter/notebook/blob/6308e979aa01a5f88cb6ce969efa7617f83687b1/notebook/services/contents/fileio.py#L324-L328)).

I'm not sure if it would be worth looking at https://github.com/jpmorganchase/jupyter-fs for pipeline file persistence, nor am I sure they support user-specified formats, but it might be an option.  Also, given the state of https://github.com/jupyter/notebook, we'd probably need modifications of this magnitude to occur in https://github.com/jupyter/jupyter_server which implies a Lab 3.0 timeframe.

**Comment by kevin-bates** [comment]
@ajbozarth had a good idea of pretty-printing the pipeline prior to its submission to the server, so we should try this.  Assigning to Alex.
