### ISSUE TITLE
Add link to KubeFlow pipeline console

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#584]
As a user, I want to have access to previous Kubeflow pipeline runs from within Elyra. Today, a link to the Kubeflow Pipelines is displayed in a dialog window when a pipeline is submitted. However, after the dialog with the link is closed the link is no longer available anywhere in the Elyra UI, forcing the user to manually enter the URL. Since multiple runtimes can be defined in an Elyra installation, there might be multiple kfp consoles that the user can choose from.

**Comment by kevin-bates** [comment]
Thanks @ptitzler.  I think this leads to a need for a general pipeline lifecycle entity on which this kind of information can be associated and from which the front-end can get status updates.  Currently, Elyra is a one-way submission facility and there's no mechanism for monitoring (or managing) a given pipeline's lifecycle.

One approach that might address this particular need is if we included the selected runtime's console URI in that runtime's metadata (e.g., `console_endpoint`).  I'm assuming that `console_endpoint` would be different from the `api_endpoint` that is already included.  If that was also included in the metadata, then it seems like Elyra could offer the ability to present the various console links across all configured runtimes.  This would allow the user to access the KFP console that is facilitating all pipelines for a particular runtime and, based on the pipeline's name, a user could then select the appropriate pipeline instance from which its current status could be obtained.  With this approach, we could continue to defer implementation of a more robust lifecycle management framework - as that is a much larger effort.

**Comment by ptitzler** [comment]
I agree. Not sure though if there is a need to introduce a new endpoint property in the runtime configuration because the UI is already capable of generating a valid "monitoring" URL after the job was submitted.

**Comment by kevin-bates** [comment]
True. The problem is with having _that_ particular link available later on since there's no place to persist it.  By providing a general console endpoint that spans all jobs for that particular pipeline, we then have a persisted "link" that any job - completed or running - could be accessed with.

**Comment by kevin-bates** [comment]
Based on side-bar conversations, it turns out the the `api_endpoint` property in the runtime metadata is indeed the dashboard we need - so we can use that for a generic solution.

**Comment by akchinSTC** [comment]
related? https://github.com/elyra-ai/elyra/issues/34

**Comment by ajbozarth** [comment]
@akchinSTC related yes, but distinct. #34 means to display the actual pipeline runs inside a lab ui. Whereas this is asking for easier access to the runtime history
