### ISSUE TITLE
[Usability] notebook pipeline - notebook properties dialog: sort docker image list

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#601]
While test driving 0.11.0rc2 I've noticed a few fit-and-finish issues.

Steps:
  - Create a new pipeline
  - Add a notebook
  - Open notebook properties

Observations:
  -  Under `Docker Image` the entries should be sorted alphabetically to make it easier/faster to find the desired image.
 - Label `Env Vars` should probably be spelled out `Environment Variables` to simplify translation
 - Help text for `Env Vars` input field should spell out `var` (variable) to simplify translation

![image](https://user-images.githubusercontent.com/13068832/83580189-3bc39080-a4f0-11ea-9a4c-470bafb8c34c.png)

**Comment by lresende** [comment]
Most of these (except the sorting) has been fixed in master. Do you ming if I (or you) change the title to be more specific to the docker image sorting issue?

**Comment by ptitzler** [comment]
Done

**Comment by lresende** [comment]
#959 seems to  e a duplicate, but much more details and some discussion has been gaining traction there.
