### ISSUE TITLE
Error: "missing 1 required positional argument: 'cos_pull_archive'"

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#611]
When attempting to **run** or **export** a pipeline file I receive the following error:

```
TypeError: __init__() missing 1 required positional argument: 'cos_pull_archive'
```

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/13156555/83922966-4d56a380-a74f-11ea-953a-7c75baffa391.png">

**Comment by vabarbosa** [comment]
Linking to PR #600

**Comment by akchinSTC** [comment]
Thanks va, I think this has to do with us not having pushed a new release to pypi yet after the variable name changes. This should get resolved once I bump the version to the latest kfp-notebook once my kfp-notebook pr is merged.

**Comment by lresende** [comment]
I believe cloning `kf-notebook` and doing a `make install` should be a workaround while we wait for the release.
