### ISSUE TITLE
Metadata display_name constraints should be relaxed

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#632]
Currently, all metadata schemas restrict `display_name` fields to the regular expression: `^[a-zA-Z][a-zA-Z0-9-_. (){}]*[a-zA-Z0-9)}]$`.  This prevents display names with apostrophes, international characters, or starting with a digit - to name just a few.  (See [this comment](https://github.com/elyra-ai/elyra/pull/629/files#r438509890))

@vabarbosa will be updating the code-snippets schema in #629 but all of the other schemas should be similarly updated to allow for any characters.

**Comment by vabarbosa** [comment]
if no objections i can include this in the #629

**Comment by kevin-bates** [comment]
I'm all for that!  This might not be what purists want - but it's tough to argue against "done" work. :smile:
