### ISSUE TITLE
Add the endpoint to the 404 message

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#639]
It would be helpful if this message could include the endpoint that is not found.
![image](https://user-images.githubusercontent.com/22599560/84533651-6b675b00-ac9d-11ea-8b5f-fb0721b32bed.png)

**Comment by ajbozarth** [comment]
I'm trying to think how we would want to word this to include the endpoint. Should I just add the endpoint on a second line? or replace  "Elyra service" with the endpoint?

**Comment by kevin-bates** [comment]
How about?

### Error contacting server
#### Endpoint '/whatever/endpoint' not found.

**Comment by ajbozarth** [comment]
that looks good to me, I'll make the change once I'm done reviewing other PRs
