### ISSUE TITLE
Elyra services should avoid errors that imply implementation and consolidate others

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#644]
Per [this comment](https://github.com/elyra-ai/elyra/pull/642#issuecomment-643510594) Elyra services should avoid using errors like `FileNotFoundError` that imply an implementation because metadata persistence may not be file-based, etc. In addition, errors like `ValueError` tend to be overused and not necessarily indicative of the actual error.

We should come up with errors that make sense, then _extend_ appropriate built-in errors with these new names.  For example, when a metadata resource that is expected to exist and does not, we should raise, `ElyraResourceNotFound` and this error should derive from `FileNotFoundError` (and ditto for unexpected existence):
```python
class ElyraResourceNotFound(FileNotFoundError):
    pass

class ElyraResourceAlreadyExists(FileExistsError):
    pass

```
The reason custom errors should derive from built-in errors is to allow applications to still handle errors based on their built-in base classes.

While errors like `ValueError` are valid for most cases, they can also be overused.  For example, should a reference to a non-existent namespace raise `ValueError` (as is the case currently), or should it raise `ElyraResourceNotFound`?

Here are the set of errors raised by the Elyra server (alphabetical order):

`BaseException`
`BucketAlreadyExists`
`BucketAlreadyOwnedByYou`
`FileExistsError`
`FileNotFoundError`
`NotImplementedError`
`PermissionError`
`ResponseError`
`RuntimeError`
`SyntaxError`
`TypeError`
`ValidationError`
`ValueError`

### Custom
Of these, we should probably have custom errors for the following as they imply an implementation from a layer in which we'd like to allow for plugins.
~- [ ] `BucketAlreadyExists`~
~- [ ] `BucketAlreadyOwnedByYou`~
- [x] `FileExistsError`
- [x] `FileNotFoundError`
### Consolidation
In addition, it would be good to consolidate uses of some of the others so that users don't have a long list of different (but similar) exceptions.  For example, `TypeError` and `SyntaxError` could also be considered instances of `ValueError` so perhaps creating a class like the following...
```python
class ElyraInvalidMetadata(ValueError):
    pass
```
### Prefixing
In my examples, I chose to use a prefix of `Elyra`.  This is solely to create a namespace for the custom errors since a custom error like `ResourceNotFound` is likely to be used by other applications.  I would recommend _some_ form of prefix, although it could be context-based as well - like `MetadataResourceNotFound`, but, again, there's a higher degree of collision.

**Comment by kevin-bates** [comment]
I think this should remain open since it’s only 1/2 complete. I’ll add the task checkboxes to better track.

**Comment by kevin-bates** [comment]
@lresende - where do you stand on this?  Do you view the two `Bucket`-related exceptions to be implementation-specific? If not, this issue can be closed.  If so, I would suggest the following mappings...

`BucketAlreadyExists` -> `ObjectStorageAreaAlreadyExists` or `ObjectStorageAlreadyExists`
`BucketAlreadyOwnedByYou` -> `ObjectStorageAreaReadyForUse` or `ObjectStorageReadyForUse`

I find the 'already owned by you' exception to be one of the strangest exceptions I've ever seen!  It is essentially a can-be-ignored version of 'already exists', IMO.

**Comment by lresende** [comment]
So, the issue with this exception is that (at least one implementation) requires the bucket name to be unique across a large scope then the user, so when a user tries to create a `foo` bucket, and some other user already have a `foo` bucket, then you are probably getting the `BucketAlreadyExists` exception. Otherwise, if the bucket exists and its owned by you, then I believe it's something we should ignore as you are getting to the desired final state.

As for the exception,  `BucketAlreadyOwnedByYou` to me sounds more like log.warning and ignore.

As for `BucketAlreadyExists`, if we MUST change, maybe `PersistenceLocationAlreadyExists` or `PersistenceAreaAlreadyExists`...

**Comment by kevin-bates** [comment]
I wasn't asking about the exceptions themselves - it sounds like we agree about the 'already owned by you' exception being strange.  I'm really asking if you think these "Bucket" exceptions are deemed "implementation-specific" as you feel the "File" exceptions were.  Given your use of "MUST" in your response indicates to me that you do not feel these are worthy of change, so I'm going to close this issue (especially since `PesistenceLocation` is worse than `ObjectStorageArea` :smile:  ).
