### ISSUE TITLE
Make install fails on a clean environment

### ISSUE THREAD

**Issue by fresende** [elyra-ai/elyra#649]
Just did a checkout on a clean environment, tried to build, and got the following error.

```
make install
ERROR: pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.
ERROR: pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is not installed.
```

It seems that `make install` should call `make test-dependencies`

**Comment by kevin-bates** [comment]
Hmm - I'm not reproducing this issue, [nor do I find any references to `pytest-astropy` in the repo](https://github.com/elyra-ai/elyra/search?q=astropy&unscoped_q=astropy).

`make install` already calls `test-dependences` by way of `lint-server` by way of `build-server` by way of `install-server` :smile: .   Also, file `test_requirements.txt` makes no mention of `pytest-astropy` or either of the other pytest packages referenced in the messages above - so I'm at a loss on how that reference is surfacing in the first place.

Are you trying to build a specific version of the elyra and you're not working from `master` perhaps?  Please try to determine where the reference to `pytest-astropy` is originating in your environment and we'll go from there.

**Comment by lresende** [comment]
Gave it a quick try and seems to be working on a clean conda env.
