### ISSUE TITLE
doc: user_guide/enhanced-python-support.html doesn't render image as expected

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#652]
Opening https://elyra.readthedocs.io/en/v1.0.0b0/user_guide/enhanced-python-support.html the console contains the following error and the second referenced image is not displayed:
```
Failed to load resource: python-runner-components.png the server responded with a status of 404
```

There are two images on this page. The first one is rendered okay, the second one is not.
The markdown code snippets look as follows:

```
![Enhanced Python Support](../images/python-runner.png)
...
<img src="../images/python-runner-components.png" alt="Python Editor Components" width="50%" height="50%">
```

Digging into the _generated_ HTML code it appears that as part of markdown processing images are copied to a different directory named `_images`, which explains why the `../images/python-runner-components.png` reference in `omg src=...` is invalid.

```

<img alt="../_images/python-runner1.png" src="../_images/python-runner1.png">
...
<img src="../images/python-runner-components.png" alt="Python Editor Components" width="50%" height="50%">
```

**Comment by akchinSTC** [comment]
Can be completed in conjunction with #616
