### ISSUE TITLE
Usability: pipeline export should not be attempted if required parameters are missing

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#658]
A user should not be allowed to export a pipeline if a required export setting is not provided.
Steps:

- Create a pipeline
- Add a notebook
- Click "Export Pipeline"
- **Don't** select a runtime configuration

![image](https://user-images.githubusercontent.com/13068832/84955624-74e13080-b0ac-11ea-9c71-1e7093fe560b.png)

- Click "OK".  The export operation fails.

Expected behavior: the user cannot click "OK" (initiate the export).

**Comment by karlaspuldaro** [comment]
While working on this issue, I noticed that jupyterlab [Dialog widget](https://jupyterlab.github.io/jupyterlab/apputils/classes/dialog.html) does not support disabling/enabling its buttons, unless we access the HTML button element directly, which in my opinion shouldn't be the proper way to do so. 
As a follow up, would it be valid to open a lab issue and propose to add a disable/enable option when passing IButton properties to the dialog?

**Comment by karlaspuldaro** [comment]
https://github.com/jupyterlab/jupyterlab/issues/8614
