### ISSUE TITLE
Pipeline editor should prevent creation of a circular graph

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#660]
![image](https://user-images.githubusercontent.com/13068832/84960363-436d6280-b0b6-11ea-9187-d9013a6b22ef.png)

When above pipeline is executed Kubeflow properly detects the issue, but it'd be nice if the editor would prevent such a construct in the first place.

![image](https://user-images.githubusercontent.com/13068832/84960390-53854200-b0b6-11ea-8864-d4ed4e897e2b.png)

**Comment by akchinSTC** [comment]
This looks like it may have been resolved in canvas v7+

**Comment by vabarbosa** [comment]
duplicate #256?

**Comment by kevin-bates** [comment]
Yes.  Not sure which would be better left open - typically it's the first although I like the picture in this one. :smile:

If we can assume a circular reference should never be tolerated (which I suspect is the case), then I would argue that we leave this issue option and close #256.

**Comment by vabarbosa** [comment]
Fixed in #774
