### ISSUE TITLE
Python editor toolbar aligned to right after installing debugger

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#671]
After installing the JupyterLab debugger

```
jupyter labextension install @jupyterlab/debugger
```

![image](https://user-images.githubusercontent.com/382917/85425053-8a7fab80-b52d-11ea-9c2b-c2372f955761.png)

**Comment by karlaspuldaro** [comment]
Looks like the extension added the css selector that brings our toolbar content to the right end
```
.jp-Document .jp-Toolbar {
    justify-content: flex-end;
}
```
I can add a fix for that

**Comment by lresende** [comment]
we might also want to report these to the JupyterLab debugger project @afshin

**Comment by afshin** [comment]
Thank you!
