### ISSUE TITLE
Improve python exception chaining

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#680]
@cool-RR has been making the rounds across the python ecosystem, and, as of late, the Jupyter eco-system in particular, promoting the use of a helpful feature added that simply (but meaningfully) changes the "chaining message" between traceback entries when the chaining is intentional.  Here's a blog post he wrote about it: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

Although we don't use pyLint for linting, we should scan the code for any `raise` calls that occur within `except` blocks.  When found, we should add the little-known `from e` clause to the `raise` statement. 

For example, the [`raise` statement in this block](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/metadata.py#L212-L218) would be updated to `raise ValidationError(msg) from ve`.

**Comment by cool-RR** [comment]
Woohoo, people are starting to push this change without me! :)

I used my tool on Elyra and found the following places. Some of these may be false positives, since my tool is buggy.

```
elyra/metadata/handlers.py: 37
elyra/metadata/handlers.py: 39
elyra/metadata/handlers.py: 41
elyra/metadata/handlers.py: 60
elyra/metadata/handlers.py: 62
elyra/metadata/handlers.py: 64
elyra/metadata/handlers.py: 66
elyra/metadata/handlers.py: 112
elyra/metadata/handlers.py: 114
elyra/metadata/handlers.py: 116
elyra/metadata/handlers.py: 141
elyra/metadata/handlers.py: 143
elyra/metadata/handlers.py: 145
elyra/metadata/handlers.py: 163
elyra/metadata/handlers.py: 165
elyra/metadata/handlers.py: 167
elyra/metadata/handlers.py: 169
elyra/metadata/handlers.py: 187
elyra/metadata/handlers.py: 189
elyra/metadata/handlers.py: 211
elyra/metadata/handlers.py: 213
elyra/metadata/handlers.py: 230
elyra/metadata/handlers.py: 232
elyra/metadata/metadata.py: 218
elyra/metadata/metadata.py: 342
elyra/metadata/metadata.py: 358
elyra/metadata/metadata.py: 489
elyra/metadata/metadata.py: 499
elyra/pipeline/processor_kfp.py: 61
elyra/pipeline/processor_kfp.py: 72
elyra/pipeline/processor_kfp.py: 108
elyra/pipeline/processor_kfp.py: 281
```

**Comment by kevin-bates** [comment]
Awesome @cool-RR - thank you for running Elyra through your tool.
