### ISSUE TITLE
[Usability/Safari] canceled pipeline migration should (probably) not open the pipeline in the editor

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#692]
1.0.0 Beta 1
- Create a pipeline using an older version of Elyra, e.g. 1.0.0. beta 0.
- Open the pipeline in 1.0.0 beta 1. A migration dialog is displayed.
- Click cancel. The pipeline editor canvas is now empty (?). 

Concerns:
- If a user saves this pipeline the original pipeline is lost.
- If a pipeline that wasn't migrated isn't usable in the currently open version of Elyra it would probably be better to not display it in the editor:
  - Create a pipeline using an older version of Elyra, e.g. 1.0.0. beta 0.
  - Open the pipeline in 1.0.0 beta 1. A migration dialog is displayed.
  - Click cancel. The pipeline editor is closed because, as is, the pipeline cannot be processed.

**Comment by lresende** [comment]
I will take a look at this, but what you describe as the expected behavior is how we actually implemented, having said that, maybe we missed some corner case, let me take a quick look at it and provide more updates here.

**Comment by ptitzler** [comment]
Not sure if it helps  but the pipeline I used when I tried this is attached to https://github.com/elyra-ai/elyra/issues/693

**Comment by lresende** [comment]
@ptitzler I tried both with my test pipeline

![elyra-issue-692](https://user-images.githubusercontent.com/382917/85935304-1124e780-b8a4-11ea-8dd6-1b06634775e3.gif)

And the one you attached to the other issue

![elyra-issue-692-noa-pipeline](https://user-images.githubusercontent.com/382917/85935308-1bdf7c80-b8a4-11ea-8a53-601a82a487b9.gif)

But I cannot reproduce.

Could you please see if there are any more hints on the browser console, or if you run lab with `--debug` do you see any errors or hints on the log?

**Comment by ptitzler** [comment]
Ah yes, it appears to work in Chrome but doesn't work in Safari. There are no warning/error messages in the server log or the browser console.

**Comment by ptitzler** [comment]
![image](https://user-images.githubusercontent.com/13068832/86022987-eb9cf880-b9df-11ea-8294-4ad81d8c0199.png)

**Comment by ptitzler** [comment]
![migrate](https://user-images.githubusercontent.com/13068832/86023261-4d5d6280-b9e0-11ea-9ef7-d27c813ec76d.gif)

**Comment by karlaspuldaro** [comment]
The problem is that it closes the previous tab open, not the pipeline tab. It might have to do with how current widget is being tracked vs timing. I couldn't recreate this in debug mode, it works as expected when I do a step by step on safari. Needs further investigation.

**Comment by ptitzler** [comment]
The pipeline isn't opened in the VPE anymore but the user has to click `cancel` twice.
