### ISSUE TITLE
Code Snippets no longer load if invalid JSON file exists in metadata folder

### ISSUE THREAD

**Issue by vabarbosa** [elyra-ai/elyra#712]
In my `metadata/code-snippets` directory, I currently have two Code Snippet JSON files. One is a valid JSON file and the other is an invalid JSON file:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/13156555/86797429-a612a800-c03d-11ea-8d60-e7147186aa70.png">

**badjson.json**  (missing a double quote and comma)
```json
{
	"schema_name": "code-snippet",
	"display_name": "bad_json",
	"metadata": {
		"description": "bad_json file,
		"language": "python"
		"code": [
			"print('hello')"
		]
	}
}
```

**common-imports.json**  
```json
{
	"schema_name": "code-snippet",
	"display_name": "frequently used imports",
	"metadata": {
		"language": "python",
		"code": [
			"import numpy as np",
			"import pandas as pd"
		]
	}
}
```

Previously, when starting Elyra and accessing the Code Snippet area, an error is shown in the terminal:

```
JSON failed to load for metadata 'badjson' in namespace 'code-snippets' with error: Invalid control character at: line 5 column 33 (char 110).
```

but the valid code snippet is successfully loaded:

![image](https://user-images.githubusercontent.com/13156555/86798532-dc9cf280-c03e-11ea-8c6f-e17dc276f4be.png)

However, with the latest updates the error is still show in the terminal, but there is also an error dialog presented in the ui and the valid code snippet does not get loaded:

![image](https://user-images.githubusercontent.com/13156555/86798818-36052180-c03f-11ea-9434-78ee954d056e.png)

Is this expected behavior or should valid code snippet continue to load (although other invalid code snippets may exist)?

**Comment by kevin-bates** [comment]
Hi Va - I suspect this is due to the metadata refactor. I'll need to look into this as I thought there was a test for this condition.  Thanks for creating this issue.

**Comment by kevin-bates** [comment]
The refactor doesn't handle the case where the invalid file is due to loading from storage - but still handles the case where the JSON can be loaded but its validation against the schema fails.  

I'll fix this today.
