### ISSUE TITLE
Python editor shows wrong line numbers 

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#719]
When you have a script that has empty lines at the beginning, we are seeing wrong line numbers on error reporting. This is probably a side effect of trimming the lines and ignoring them.

In the example below, line 7 should have been line 11. 

![image](https://user-images.githubusercontent.com/382917/86870570-7ee3c700-c08d-11ea-9cc0-58cfafa430b9.png)

Removing the lines at the top then give the right line number on the reported error

![image](https://user-images.githubusercontent.com/382917/86870776-dc781380-c08d-11ea-97fb-ee422ea44147.png)

**Comment by kevin-bates** [comment]
I believe this is a function of the kernel - or some other logic in lab - that is trimming preceding lines.  Here's a similar issue from a notebook...
![image](https://user-images.githubusercontent.com/22599560/86932283-04975f00-c0ee-11ea-8aa8-b98d4c618e5e.png)

**Comment by lresende** [comment]
This is not an Elyra issue but regular Kernel/Notebook as commented above by Kevin.
