### ISSUE TITLE
Pipeline editor: allow for changing of the notebook [name/location]

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#732]
As a user I would like to change the notebook name or location of a node. Currently the node properties display the name/location but do not allow for editing.  Therefore if a user wants to change the name/location of a notebook the following steps need to be completed::

- create a new node for the "renamed" notebook
- select a runtime container
- copy and paste "file dependencies"
- copy and paste environment variables
- copy and paste "output files"
- remove old node
- link notebook nodes

With this proposed enhancement a user would only have to change the name/location of the notebook.

![image](https://user-images.githubusercontent.com/13068832/87073426-3eda2c80-c1d2-11ea-8d2e-d4bda6907beb.png)

**Comment by ajbozarth** [comment]
Bringing this under the umbrella issue #822 to handle updating a node's file location

**Comment by ajbozarth** [comment]
A quick note on implementation: We definitely do not want to make this update via a text fields, but some form of UI. (as per previous discussions around this topic)
