### ISSUE TITLE
Code snippet widget disappears

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#736]
1.0.0 rc0

- Create and save a code snippet
- Click "Delete the code snippet" icon
- Click CANCEL (aka don't delete code snippet) - the widget listing code snippets disappears

![image](https://user-images.githubusercontent.com/13068832/87080865-4226e580-c1dd-11ea-8378-0850a769c7f4.png)

**Comment by ptitzler** [comment]
I had to restart JL to get the widget back

**Comment by ajbozarth** [comment]
This looks like its caused by some awkward promise handling. That is our delete dialog doesn't send the server request to delete on CANCEL, but it still runs the client side update that removes the associated code mirror "editor"

**Comment by ptitzler** [comment]
lgtm in 1.0.0 rc1
