### ISSUE TITLE
Metadata widget: new code snippet tool tip is missing

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#738]
1.0.0 rc0

- Hover over `+` in code snippet widget:
![image](https://user-images.githubusercontent.com/13068832/87082912-88317880-c1e0-11ea-9237-74fdb00a2996.png)

vs

- Hover over `+` in file browser:
![image](https://user-images.githubusercontent.com/13068832/87083035-c75fc980-c1e0-11ea-8886-3cc263e884dd.png)

**Comment by ajbozarth** [comment]
Nice catch, we must have forgotten to add a tooltip for that button 
@marthacryan this should be a quick fix?
