### ISSUE TITLE
code snippet/inserted markdown should not always be escaped

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#739]
1.0.0 rc0

Markdown code snippets should only be escaped when necessary. Two examples where escaping is not needed:

- Create a markdown code snippet (e.g. one that defines a copyright message)

Scenario 1:
- Open a Python notebook, add a markdown cell, and insert the code snippet
- The inserted markdown is escaped, even though it doesn't need to be:
![image](https://user-images.githubusercontent.com/13068832/87084073-781a9880-c1e2-11ea-8fca-d0c5db30e339.png)

Scenario 2:
- Open a markdown document and insert the code snippet
![image](https://user-images.githubusercontent.com/13068832/87084261-ce87d700-c1e2-11ea-88c7-13b57fe058ca.png)

**Comment by ajbozarth** [comment]
this is a bug, our regex is not using toLower so the capitol M is bypassing the markdown handling and treating like code

@karlaspuldaro or @marthacryan if one of you have a moment to fix it
