### ISSUE TITLE
Preview tab in pipeline editor

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#761]
Implement a preview tab which can display an iframe which can be rendered by an optional preview cell the notebook or python script provides. This way, while double-clicking and opening the preview tab on a node the underlying notebook can show sample data

**Comment by lresende** [comment]
Thanks for the suggestion @romeokienzler, is it correct to summarize your idea as:
> Implement a preview tab or integrated with the node hover capabilities on Elyra that can display a rendered output of a previously selected notebook cell.

If so, I have some questions:
- [ ] Are we talking about only displaying a specific cell output that has already been executed (e.g. just showing the output of a given notebook cell)
- [ ] You mentioned Python Script as well, that does not provide support for graphics and the text output is usually just lost of execution

Note that, until we add support for seamlessly bringing back the resulted artifacts to the user workspace, this would only work if the notebook gets executed on the local user env.

**Comment by romeokienzler** [comment]
I know this is a challenging and vague requirement, so let me explain a bit why I think it is useful.

In #760 I've requested parameters to be made available to pipeline nodes. The idea stems from usability of no-code/low-code environments like NodeRED, Apache Nifi, etc. 

So why not using NodeRED and Nifi instead?
- NodeRED doesn't scale and doesn't guarantee data reliability
- Nifi doesn't scale on Kubeflow Pipelines
- Component development is tedious (for both)

For making Elyras pipeline editor a viable no-code / low-code environment three functions are needed
- easy development of component/node functionality in python as script or notebook
- easy parametrization of processing nodes (see #760)
- incremental development / debugging => a way to see what a chain of nodes is doing up to a specific node

ETL and Data Mining Tools (incl. Nifi) have a preview functionality where a subset of the data can be shown in a separate tab whereas NodeRED uses a global (global to a particular flow) debug tab where all nodes are writing stuff in

I'm aware that we are talking here about an editor only, so for generating a preview, there is nothing elyra can do. So we leave this up to the encapsulated component (script or notebook). 

In case of a script, Elyra checks if there is a function present called "elyra_preview" and the output of that function is renered in a separate tab if present. In case of a nb, Elyra checks if there is a cell present annotated with "preview" and this cell is executed and it's output is presented in a preview tab

Does this make sense? Would it be possible to implement without too much hassle?

**Comment by romeokienzler** [comment]
@lresende I'll reopen this issue after v2.3.x and make a concrete suggestion on how this could be implemented using Kubeflow
