### ISSUE TITLE
Metadata CLI: elyra-metadata list  [command] --json returns invalid JSON

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#762]
1.0.0.rc1
Related issue: https://github.com/elyra-ai/elyra/issues/742

Observed behavior (STDOUT) - likely applies to all list operations that return no results
```
$ elyra-metadata list code-snippets --json 
No metadata instances found for code-snippets
```

Expected behavior (STDOUT)
```
$ elyra-metadata list code-snippets --json 
[]
```

The current output breaks programmatic processing:
```
elyra-metadata list code-snippets --json | jq .
parse error: Invalid numeric literal at line 1, column 3
```

**Comment by kevin-bates** [comment]
Sigh.  Good point.  Thanks.
