### ISSUE TITLE
Error submitting pipeline when using IBM Cloud Object Storage: BucketAlreadyOwnedByYou execption

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#778]
Configure you `Elyra Runtime metadata` to point to IBM COS
Create a pipeline, and submit it using the runtime pointing to IBM COS
This will fail with:
```
minio.error.BucketAlreadyOwnedByYou: BucketAlreadyOwnedByYou: message:
Your previous request to create the named bucket succeeded and you already own it.
```

This is happening because the the `bucket_exists` API from the minio client is always returning `False` even when the bucket already exists, and then when the backend code tries to create the bucket the `BucketAlreadyOwnedByYou` exception is raised

**Comment by akchinSTC** [comment]
mind food: Should we consider moving to a more generic s3 client for our operations? Having a flat standard client compatible with most if not all s3 based object stores would be probably be in our best interest moving fwd.

**Comment by lresende** [comment]
Looks like this ended up not being a bug, the issue here is related to how you create your endpoint (location such as us-south vs us-geo) and then what api endpoint you are using to access these buckets.

As in the example below:

![image](https://user-images.githubusercontent.com/382917/88461286-15b6ce80-ce57-11ea-9f94-58201c63378e.png)

If you use an API endpoint such as `https://s3.us-south.cloud-object-storage.appdomain.cloud` which is specific to `us-south` then it won't show the `us-geo`  buckets and you really need to use the `https://s3.us.cloud-object-storage.appdomain.cloud` endpoint to see those. 

After figuring this out, and properly using the right API endpoints, visibility seems to be working ok.

**Comment by kevin-bates** [comment]
Great. Thanks for finding that.
