### ISSUE TITLE
Pipeline editor: Node error indicator should accomodate color blind/challenged users

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#786]
Follow up to https://github.com/elyra-ai/elyra/pull/752
In general using small icons that can only be distinguished by color poses a problem. For background information refer to https://www.color-blindness.com/deuteranopia-red-green-color-blindness/
While small differences in shape sometimes do help (e.g. using a yellow triangle and a red circle) it's probably better to use more easily distinguishable icons that are less ambiguous.

**Comment by bourdakos1** [comment]
I mocked up some options using photoshop's Protanopia and Deuteranopia simulation:
<img width="689" alt="Screen Shot 2020-08-03 at 10 42 44 AM" src="https://user-images.githubusercontent.com/4212769/89195231-7a200f00-d576-11ea-97d4-da699d52ad84.png">
I personally think that option `B` pops the most as "there is an issue". What do you think @ptitzler?

**Comment by ptitzler** [comment]
In general I agree. The issue I see with option A is that a user _could_ consider the annotation to be part of the asset type icon (which in this case identifies a notebook) and miss it. With support for other types coming (e.g. Python scripts) color combinations might therefore be challenging.

One potential concern with option B is that a user could mistake it as a connector, but do to its prominent placement it is (at least with my handicap) highly visible.

**Comment by marthacryan** [comment]
This is the current appearance of the node error indicator: 
![image](https://user-images.githubusercontent.com/6673460/128928254-533cdda2-115f-4e48-8964-8a6ca7623678.png)
Since option B seems to be agreed on as the solution for this, can we close this?
