### ISSUE TITLE
Add ability to "group" fields in the metadata editor

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#789]
In #591, it was noted that the metadata editor for runtimes would be better if it could group the cos fields separately from the kubeflow fields (see current display below). This could be added as an optional field in the ui hints and be picked up by the metadata editor. 
![image](https://user-images.githubusercontent.com/6673460/88705248-e01f1900-d0d4-11ea-8570-1d9a31fd4cf4.png)

**Comment by ptitzler** [comment]
As a clarification, grouping of related properties that belong to the same entity and are displayed under a  "heading", e.g. 
![image](https://user-images.githubusercontent.com/13068832/88721170-4e3ffc00-d126-11ea-8c66-d4b1a37024ec.png) (never mind the order of the input fields in this mockup)
