### ISSUE TITLE
[Metadata editor regression?] Only first required property is checked by UI

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#798]
1.0.0 rc3
I've noticed a UI behavior change that might be a regression:

- Create a new code snippet and enter only a name (there are more properties marked as required) OR
 create a new runtime and enter only a name (there are more properties marked as required)
- Previously the metadata editor would label each input field with "This field is required." (as shown for the name below)

![image](https://user-images.githubusercontent.com/13068832/89155010-4c33ce00-d568-11ea-86d8-f48a92d75d47.png)

- Click "save & close"

An error dialog is displayed:

```
Error making request
Validation failed for instance 'ddd' using the kfp schema with error: 'api_endpoint' is a required property.
Check the JupyterLab log for more details at 2020-08-03 09:11:19
```

For the sake of consistency the behavior should be the same for all input fields.

**Comment by ptitzler** [comment]
Do note that if one edits a properly defined metadata artifact (e.g. a runtime) and deletes the content of a required input the U behaves as expected and displayed the "This field is required." label instead of the error dialog.

**Comment by ajbozarth** [comment]
I'll look into this today
