### ISSUE TITLE
Add "origin" information to generated pipeline PY/DSL

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#799]
- Create a basic pipeline (any pipeline will do)
- Run the pipeline
- Open the pipeline in Kubeflow Pipelines
Note that _version source_ and _description_ are currently empty.

![image](https://user-images.githubusercontent.com/13068832/89157615-19400900-d56d-11ea-8ea2-605b946c37cf.png)

For the sake of traceability Elyra should (if possible) provide this information to enable Kubeflow Pipelines users to identify the pipeline origin. e.g `Elyra <pipeline name>`

**Comment by kevin-bates** [comment]
I'm not sure how this gets specified in the API we use.  Assuming these can be set, I would recommend using something like `Elyra <version>` for `Version source` and perhaps the `description` (or `display_name` if `description` is not set) from the selected runtime metadata instance for `Description`.

**Comment by ptitzler** [comment]
Sorry, I meant to check the YAML spec earlier today but was sidetracked.

Your suggestion would go nicely with an ER I opened a while ago, suggesting to support an optional user-defined pipeline description that could be exposed in various places to allow for a "sneak preview".

**Comment by kevin-bates** [comment]
> I meant to check the YAML spec earlier today

If by this you mean the Elyra YAML, this capability is definitely not there.  IMO, this kind of information should be set by the Elyra backend (not the user) and I'm not finding these kinds of parameters exposed in an obvious manner.  If you're actually referring to a Kubeflow Pipeline YAML spec, please forward its link - thanks.

> Your suggestion would go nicely with an ER I opened a while ago, suggesting to support an optional user-defined pipeline description that could be exposed in various places to allow for a "sneak preview".

You must be referring to #602 - correct?

**Comment by ptitzler** [comment]
> You must be referring to #602 - correct?
Yes!

**Comment by ptitzler** [comment]
For the description:

![image](https://user-images.githubusercontent.com/13068832/89264891-fa587a00-d633-11ea-9ac6-c1b928205486.png)


DSL:

```
@dsl.pipeline(
    name='My first pipeline',
    description='A hello world pipeline.'
)

```
Generated workflow spec:

```

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-first-pipeline-
  annotations: {
         pipelines.kubeflow.org/kfp_sdk_version: 0.5.1, 
         pipelines.kubeflow.org/pipeline_compilation_time: '2020-08-04T09:10:16.542408',
         pipelines.kubeflow.org/pipeline_spec: '{"description": "A hello world pipeline.",
      "name": "My first pipeline"}'
  }
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 0.5.1}
```

**Comment by ptitzler** [comment]
I did a bit of code analysis in https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor_kfp.py and noticed that there are three processing scenarios: run pipeline, export pipeline to yaml, and export pipeline to Python DSL. During processing the first two scenarios currently no description is added, whereas during export to DSL the static string `Elyra Pipeline` is used, which essentially means that the three outputs are not 100% equivalent, even though they should be. (That's a separate issue though.)

**Comment by kevin-bates** [comment]
Thanks Patrick. I've been looking at the same code to see how these can be set.  I suspect we're using a down-level api for at least one of the methods and agree that the processing differences should probably stand some refactoring.

I wasn't so concerned about getting 'Description' set but rather the 'Version source' (assuming we can get on the correct version).  I don't know where that comes into play and gripping is not practical since each iteration in KFP is a version itself.

Is 'Description' something you see coming from the end-user (which would likely be helpful)?  If not, we _could_ embed what I thought would be good for 'Version source' in the description, something like: 'Elyra 1.0.3 pipeline'.  But I think, assuming we can set 'Description', this particular value should come from the user and let 'Version source' be a "system-owned" value (meaning it derives from and is set by the server).

**Comment by ptitzler** [comment]
> Is 'Description' something you see coming from the end-user (which would likely be helpful)? If not, we could embed what I thought would be good for 'Version source' in the description, something like: 'Elyra 1.0.3 pipeline'. But I think, assuming we can set 'Description', this particular value should come from the user and let 'Version source' be a "system-owned" value (meaning it derives from and is set by the server).

I haven't been able to find any information about the version source. I did reach out to a few folks in Slack who might be able to point us in the right direction and am waiting for them to respond. I believe your proposal is good:
 - description = user provided (with a useful default if nothing is specified)
 - version source = Elyra provided (if possible; if not "version source" information could be the default for ^^)

I do believe having identifying information embedded is important for production-ish use cases and would therefore advocate for a staged approach:
 - Stage 1 (quick delivery): description = Elyra generated "static" text (doesn't require any UI updates or changes to the pipeline metadata)
 - Stage 2: &lt;something more comprehensive&gt;

**Comment by ptitzler** [comment]
> I do believe having identifying information embedded is important for production-ish use cases and would therefore advocate for a staged approach

Motivation: in a managed production environment many pipelines might be running over time. If there's a need for an ops person to reach out to the owner of a workflow (e.g. because it was/is be utilizing a large amount of resources in a cluster) it should be possible to access identifying pipeline information that associates a pipeline with the entity that submitted it.
