### ISSUE TITLE
Runtime configuration: bucket name regex rejects valid names

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#800]
I've created a bucket `0ad` in minio (and COS) and tried to configure a Kubeflow Pipelines runtime using this value as bucket name. The following error is displayed:

```
Error making request
Validation failed for instance 'cloning1' using the kfp schema with error: '0ad' does not match '^[a-z][a-z0-9-.]*[a-z0-9]$'.
Check the JupyterLab log for more details at 2020-08-03 09:57:51
```

There might certainly be differences as to which pattern is considered valid on different S3 implementation but we should try to tolerate as much as possible what they have in common. General spec is at https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by kevin-bates** [comment]
This is my mistake.  I used the same document but missed the fact that buckets could also start with a number.  We cannot, however, enforce all of these restrictions via schema attributes, but, as you say, do our best.  I've assigned this to myself and will have a fix shortly.

**Comment by ptitzler** [comment]
No worries. One related scenario I haven't tried (and I'm fairly sure nobody else has tried it either) is the one where a user specifies a bucket name that exists but is owned by a different user. Since bucket names have to be globally unique it's likely that users will run into the scenario eventually and I'm not sure where/when in the workflow this issue would surface. I have a hunch it's during pipeline execution unless we are performing a write test as part of the runtime configuration validation.

**Comment by kevin-bates** [comment]
I agree that this is something that should be checked if it hasn't already.  The minio client has 'BucketAlreadyOwnedByYou` and `BucketAlreadyExists` exceptions - which we trap.  I'm not sure if those are exhaustive, but I suspect the latter would be returned in this case (where a user is attempting to use a bucket they do not own).

This should be tracked in a separate issue.

cc: @akchinSTC, @lresende - do we know what the behavior is in this case?
