### ISSUE TITLE
[Fit and finish] Runtimes widget 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#802]
- Display runtime type (e.g. Kubeflow Pipelines or Apache Airflow). While this might not seem that useful until another runtime is supported we should incorporate the information into the design.
 - Change "Runtime history" label to "Pipeline run history" since there isn't really a runtime history, only a pipeline run history.
![image](https://user-images.githubusercontent.com/13068832/89164438-688b3700-d577-11ea-8113-f8b72caa088a.png)

**Comment by ajbozarth** [comment]
@ptitzler would addressing both of these issue in line fix be okay? 

Eg. `Runtime History` -> `Kubeflow Pipelines History`

That would make what the link is clearer while also clarifying the instance type.

**Comment by lresende** [comment]
Similar to how we use `Cloud Object Storage`, can't we just say something like `Kubeflow Pipelines UI` with some sort of tooltip like `See submitted pipelines and associated executions`?

**Comment by ptitzler** [comment]
@ajbozarth yes, for the time being (only KFP supported) that should be sufficient. However once we support multiple back-ends a user would have to expand each node to find out what it driving pipeline execution. I don't think we can rely on users choosing a meaningful name to make that distinction.

@lresende tool tips are bad from an accessibility point of view. They also won't help should there ever be a need to filter runtimes by type. However, maybe  I'm too optimistic how many runtimes a typical installation would include, lol.
