### ISSUE TITLE
Pipeline editor: palette displays broken image link

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#803]
1.0.0.rc2+

Not sure if this is a known canvas issue. Open the pipeline editor and expand the palette:
![image](https://user-images.githubusercontent.com/13068832/89165872-78a41600-d579-11ea-824f-b1e03c717a9c.png)

**Comment by ajbozarth** [comment]
nice catch, it seems that one of the canvas updates added that to the toolbar and we didn't notice. We should find a way to remove/disable it since we don't actually want it

**Comment by vabarbosa** [comment]
this is the result of [upgrade to canvas 9.0.3](https://github.com/elyra-ai/elyra/pull/794) which [introduced `enablePaletteLayout: 'None'`](https://github.com/elyra-ai/canvas/releases/tag/release_9.0.3) to canvas config
