### ISSUE TITLE
Notebook runtime image is assigned "automagically" 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#804]
I've observed that under certain circumstances a runtime image is automatically assigned when a notebook is dragged onto the canvas. 
- Start JupyterLab and create a new empty pipeline
- Drag a notebook onto the canvas - a runtime image name is not assigned
- Do a bunch of things (not totally sure what triggers the change in behavior)
- Drag another notebook (or another instance of the same notebook) onto the canvas - a runtime image name is assigned

Not sure if there is a auto-assign feature or if this is an initialization bug. I believe I've first observed this in 1.0.0.rc2

**Comment by vabarbosa** [comment]
steps to reproduce:

1. Start Elyra
1. Open an empty pipeline
1. Add notebook to canvas // **runtime mage is not set**
1. Open an existing pipeline
1. In the existing pipeline, open the properties dialog of notebook (which has runtime image set)
1. Cancel the properties dialog
1. Add a notebook to the new or existing pipeline // **runtime image is set**

issue:

whenever the Properties dialog is opened whatever the current values for the **Runtime Image** (and **Include Subdirectories** checkbox) are, it looks like they become the default value for any subsequent new notebooks being added to any pipeline
