### ISSUE TITLE
Runtimes widget disappears when no runtime is defined

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#806]
1.0.0.rc3

- do not create a runtime

**Recreate 1:**

 - create a basic hello world notebook (any notebook will do)
 - create a new pipeline that includes the notebook
 - save the pipeline
 - click on the open runtimes button in the canvas
 - an error message is displayed ("no runtimes found")
  - the runtimes widget disappears

**Recreate 2:**
- Click on the runtimes icon on the left hand side

![image](https://user-images.githubusercontent.com/13068832/89190421-b6b53000-d5a1-11ea-8543-ba373b93ca40.png)

**Comment by ajbozarth** [comment]
I'll look into this today
