### ISSUE TITLE
Runtime configuration editor broken if no runtime was previoisly configured

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#827]
![Screenshot from 2020-08-06 07-52-47](https://user-images.githubusercontent.com/5694071/89496076-f48ca100-d7b9-11ea-8c7a-5e9cf16912ad.png)

**Comment by ptitzler** [comment]
@romeokienzler if you are using 1.0.0.rc3 please upgrade to the latest version. Sounds like you were running into https://github.com/elyra-ai/elyra/issues/806

**Comment by romeokienzler** [comment]
@ptitzler @lresende I've tested on rc3, but can't test on master because of [this issue](https://github.com/elyra-ai/elyra/issues/828)

**Comment by ptitzler** [comment]
1.0.0 resolves a lot of issues that surfaced in 1.0.0.rc3. Closing.
