### ISSUE TITLE
Building of elyra docker image fails on current master

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#828]
tests/integration/pipeline.ts 67ms
tests/integration/pythoneditor.ts 47ms
tests/integration/submitbutton.ts 35ms
tests/integration/toc.ts 41ms
tests/plugins/index.js 31ms
tests/tsconfig.json 38ms
tests/webpack.config.js 139ms
tsconfig-base.json 32ms
Done in 12.00s.
yarn run eslint
yarn run v1.22.4
$ eslint . --fix --ignore-path .gitignore --ext .ts,.tsx,.js
Done in 6.51s.
export PATH=$(pwd)/node_modules/.bin:$PATH && lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 8 packages: "yarn run build"
lerna ERR! yarn run build exited 139 in '@elyra/ui-components'
lerna ERR! yarn run build stdout:
yarn run v1.22.4
$ tsc
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Segmentation fault (core dumped)
error Command failed with exit code 139.
lerna ERR! yarn run build exited 139 in '@elyra/ui-components'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
Makefile:83: recipe for target 'build-ui' failed
make: *** [build-ui] Error 139
The command '/bin/sh -c python -m pip install --upgrade pip &&     python -m pip install setuptools pandas --ignore-installed --upgrade &&     echo "scripts-prepend-node-path=true" >> /home/jovyan/.npmrc &&     echo "prefix=/home/jovyan/.npm-global" >> /home/jovyan/.npmrc &&     mkdir -p /home/jovyan/.npm-global &&     npm install -g yarn &&     npm install -g npm &&     cd /tmp && git clone https://github.com/elyra-ai/elyra.git &&     cd /tmp/elyra && git checkout tags/v1.0.0 -b v1.0.0 && make install' returned a non-zero code: 2

classic.yarnpkg.comclassic.yarnpkg.com
Yarn
Fast, reliable, and secure dependency management.

**Comment by kevin-bates** [comment]
hmm - I'm not reproducing this issue:
```
git fetch upstream
git rebase upstream/master
make docker-image
docker images

REPOSITORY                           TAG                                              IMAGE ID            CREATED             SIZE
elyra/elyra                          1.0.0                                            661aed36eb06        49 minutes ago      3.59GB
```

**Comment by ptitzler** [comment]
`make docker-image` worked for me. Sounds like we need to update the documentation to avoid confusion.
