### ISSUE TITLE
Pipelines: As a user I want to define/use a custom runtime/Docker image to run notebooks in using the UI

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#829]
A user can currently only select from a handful of predefined runtime images. Sometimes these images might not meet the users' requirements and therefore we should provide the ability to specify any image as a source.

Additional considerations:
 - Could images in private repositories be supported?

**Comment by kevin-bates** [comment]
I thought we added support for custom runtime images via #462?  Does this meet your requirement?  

Regarding private image repositories, I think we'd need to convey credentials, but I believe I saw something in the KFP API that would support that.  Not sure we're using the applicable method though.  But, as of now, if any additional credentials are needed to pull the image, then it won't work.

**Comment by ptitzler** [comment]
Ah yes, sorry the request wasn't specific enough. The ER is to add this support for the UI to eliminate the need to use the CLI (for those users who don't want to).

**Comment by ajbozarth** [comment]
@ptitzler so what you want is something similar to the code snippet and runtimes sidebar UI, but for runtime images? If that's the case would you expect another permanent sidebar? Or would a "transient" sidebar that can be opened but is not persisted on page refresh work? If it is the second, we already have that implemented and can add a call to the command to "open" it anywhere you think makes sense

**Comment by ptitzler** [comment]
>  If that's the case would you expect another permanent sidebar? Or would a "transient" sidebar that can be opened but is not persisted on page refresh work? 

My main concern with adding it to the sidebar permanently  is that the "runtime images" wizard is likely used relatively infrequently and therefore doesn't really warrant such a prominent placement. I'm not totally sure what you are referring to when you say "transient" sidebar,  but if it essentially means that sidebar panels are only displayed if they are relevant in the context of what the user is doing, then this sounds like a more user friendly approach. 

For example, currently runtime images are only selected used when a user configures a notebook node in the pipeline editor. Therefore it would be sufficient make it easy for the user to open this wizard as part of the workflow :
- User creates a pipeline and adds a notebook
- User wants to configure the runtime for a notebook and has the ability to access the "runtime images" metadata without having to abort the current work flow (aka click on the "runtime images" sidebar to add a new image)

That said, I do believe there would be value in also making metadata editors accessible from a central location: Let's say a user (for whatever reason) wants to review all configured runtime images. It'd be cumbersome if he/she would be forced to open a pipeline and edit the notebook properties to access the runtime images wizard.
