### ISSUE TITLE
Metadata editor: allow for links to "documentation" to help users understand the purpose

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#838]
1.0.0

Elyra exposes quite a few  metadata editors in the UI, such as the runtime images editor, shown below.

![image](https://user-images.githubusercontent.com/13068832/89634133-29295700-d8a5-11ea-8879-5c7ec8dc5bf3.png)
When a user accesses an editor (which is likely if it is exposed in the sidebar) it might not always be clear what the metadata is used for. While the metadata purpose can sometimes be inferred (e.g. for code snippets), there might also be quite a bit of ambiguity for a novice user who is not (yet) familiar with the workflow that is supported by this metadata.

It would therefore be nice if "the editor" could make additional information available that provides context information that helps new users understand its purpose. In the case of runtime images it might be a short piece of text (or a link to the relevant documentation page) that outlines what a runtime image is ("a Docker image in a public image registry") and maybe give an example what the user can do with it. ("Notebook pipelines can run notebooks in these runtimes.")

Just food for thought.

**Comment by kevin-bates** [comment]
Good idea @ptitzler.  I would recommend we use the [description property of the `metadata` property](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/runtime-image.json#L22) of the corresponding schema object to house this information.

**Comment by ptitzler** [comment]
For illustrative purposes, this is what this might look like.
![image](https://user-images.githubusercontent.com/13068832/107817563-26fbf580-6d2b-11eb-8bc3-602c67b1a578.png)

Constraints:
- The link should be represented in a way that makes it easy to notice.
 - The URL property should be part of the schema definition.
 - This property is optional. Nothing is shown in the UI if the property is not defined.
 - The URL should be validated when the schema information is read and a warning be logged if the URL is invalid. 
 
What should happen in the UI if the URL is invalid? Should it still be displayed in some form to make it obvious that something is broken?

**Comment by ptitzler** [comment]
Delivery of this feature requires
- updates to every schema (addition of an optional static value property)
- a widget that renders the property value

For example:
 - Introduce a new optional property ` reference_url` in the schema, which points to a public URL, such as `https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html` for the [runtime image](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/runtime-image.json)
 - If present, the property value is rendered in a user-friendly fashion in a prominent location when the editor displays a metadata entry during ADD and EDIT operations.
    ![image](https://user-images.githubusercontent.com/13068832/108254633-1b844200-7110-11eb-9b30-66ea44bb8a57.png)
 - The link to the URL opens in a new browser window

**Comment by ptitzler** [comment]
| metadata type | link |
| ----------- | ----------- |
| [Runtime configuration Airflow](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/airflow.json)  and [Runtime configuration KFP](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/kfp.json)| https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html |
| [Runtime image configuration](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/runtime-image.json) | https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html |
| [Code snippet](https://github.com/elyra-ai/elyra/blob/master/elyra/metadata/schemas/code-snippet.json) |   https://elyra.readthedocs.io/en/latest/user_guide/code-snippets.html |
