### ISSUE TITLE
Plugin 'elyra-code-snippet-extension' is already registered.

### ISSUE THREAD

**Issue by eromoe** [elyra-ai/elyra#849]
The steps, 

1. I have  jupyter lab 2.1.5 and 1.0.0rc1 installed . 
2. jupyter lab build  can't  get success, because I only have nodejs 10 . ( 2weeks ago ) 
3. Today , I found the problem update nodejs to 14 , build again .
4. Also notice jupyterlab and elyra updated ， so I update both  and  build again .
5. got this error .

![image](https://user-images.githubusercontent.com/3938751/89856068-d4e6e580-dbca-11ea-8598-a4e180cb387b.png)

6. `jupyter labextension remove @elyra/code-snippet-extension-experimental v1.0.0-beta.1` cause

![image](https://user-images.githubusercontent.com/3938751/89856707-9e11cf00-dbcc-11ea-96bc-8383257f343e.png)

7. jupyter labextension list
```
        @elyra/code-snippet-extension v1.0.0  enabled  OK
        @elyra/metadata-extension v1.0.0  enabled  OK
        @elyra/pipeline-editor-extension v1.0.0  enabled  OK
        @elyra/python-editor-extension v1.0.0  enabled  OK
        @elyra/theme-extension v1.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        ipysheet v0.4.4  enabled  OK
        jupyterlab-drawio v0.7.0  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

```

**Comment by eromoe** [comment]
> The steps,
> 
> 1. I have  jupyter lab 2.1.5 and 1.0.0rc1 installed .
> 2. jupyter lab build  can't  get success, because I only have nodejs 10 . ( 2weeks ago )
> 3. Today , I found the problem update nodejs to 14 , build again .
> 4. Also notice jupyterlab and elyra updated ， so I update both  and  build again .
> 5. got this error .

![image](https://user-images.githubusercontent.com/3938751/89856058-cd274100-dbca-11ea-953d-d27c8a5c2616.png)

**Comment by lresende** [comment]
I haven't seen this before and might be related to the initial jupyterlab build not succeeding before the update. I would recommend uninstalling elyra jupyterlab extensions and updating elyra again.

**Comment by lresende** [comment]
Please re-open if you are still seeing issues trying to deploy code-snippet.
