### ISSUE TITLE
Markdown TOC contains invalid entry

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#857]
1.0.0

Possibly a regression. I believe this worked properly in an earlier release. This example is from the getting started markdown on binder
![image](https://user-images.githubusercontent.com/13068832/90154201-212c5400-dd8a-11ea-8ff0-7afb7819b8d2.png)

**Comment by marthacryan** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/9938
