### ISSUE TITLE
TOC for Python scripts:  display all import statements?

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#858]
The TOC feature in 1.0.0 (didn't try this with earlier versions) displays for Python scripts that include `import` statements only the first one, e.g. `import io` for 

```
import io
import pandas as pd
import requests

```

![image](https://user-images.githubusercontent.com/13068832/90156830-3bb3fc80-dd8d-11ea-9c65-1ba11ce27728.png)

If this behavior is intentional it'd be useful if  all imports would be displayed. If Elyra did, time-saving functionality could possibly be added later on that 
- automatically checks whether the referenced packages are installed in the selected kernel
- enables the user to install the package

Just food for thought.

**Comment by marthacryan** [comment]
This was intentional - I think the idea was that since it's the table of contents, it might be too much detail to include all of the imports, but it'd be useful for you to easily navigate to the imports section at the top of the file. I think @lresende was involved in deciding that, any thoughts?

**Comment by lresende** [comment]
Yes @marthacryan, this seems right, where it's mostly a link to `import section` on the file, similar to when you go to an IDE and you have the collapsed import section that you can then access/expand it.
