### ISSUE TITLE
outline level 3 not rendered

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#878]
### Superconducting Qubits - Transmon
is not rendered for me => https://github.com/romeokienzler/QuantumMachineLearning/raw/07d2f937136872a8851b0cd2758c86f3f0db76c0/quantum_machine_learning.ipynb

**Comment by romeokienzler** [comment]
just noticed if the two different levels are in different cells it works...works as designed?

**Comment by ptitzler** [comment]
Here's a quick test, which confirms Romeo's last observation.

![image](https://user-images.githubusercontent.com/13068832/92026477-f2185b00-ed15-11ea-990e-f1f955f5a892.png)

Different people have different preferences when they create notebooks. Some try to consolidate heading sections into a single comment cell (to reduce the number of clicks required to step through the notebook), others might prefer a heading section per comment cell. 

The current behavior essentially forces the user to structure the notebook in a specific way to take advantage of the TOC feature. It should be the other way around - Elyra should be able to generate a TOC for any notebook.. The example notebooks in `elyra-ai/examples` don't really render well in the TOC and and are therefore not suitable for demo purposes, given the current behavior.

**Comment by ptitzler** [comment]
Removed firefox tag because the behavior is not browser specific.

**Comment by marthacryan** [comment]
fixed by https://github.com/jupyterlab/jupyterlab/pull/9358

**Comment by lresende** [comment]
This has been merged into Jupyterlab
