### ISSUE TITLE
toc extension: idention and collapsing

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#879]
would be a nice feature if - depending on the hierarchy level - the toc entries would be indented - also a collapsing and expansion feature would be helpful

**Comment by lresende** [comment]
it would be actually good to have the toc style/view be more similar to the one below, where it's easier to identify which section you are, and with some indentation. 

![image](https://user-images.githubusercontent.com/382917/91206850-b13c9880-e6bc-11ea-8edf-24c783cfb251.png)

As for collapsing/expanding, we might need to be careful here, as this was one of the functions that were enabled by default, and after multiple complaints, it was changed to disabled and can be enabled on lab settings.

**Comment by romeokienzler** [comment]
@lresende agree on the layout above. Feature request: can the collapse function be disabled by default and enabled in the toc panel via a button?

**Comment by lresende** [comment]
@romeokienzler With the merge of TOC to jupyterlab, the maintainers requested to remove collapsing as it was implemented as a hack and this is going to be re-enabled when some enhancements are available in JupyterLab.

**Comment by romeokienzler** [comment]
Thanks for the update @lresende shall we close this? is there a similar issue open at jupyterlab? otherwise I'll open one there, link it and close this..

**Comment by marthacryan** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/9275

**Comment by romeokienzler** [comment]
@marthacryan thanks so much! closing...
