### ISSUE TITLE
Investigate integration with lab editor based on VS Code editor

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#89]
Looks like Microsoft is working on an editor extension that uses the VSCode editor as it's base. This editor seems to have great python capabilities such as code navigation (e.g. go to implementation, find usages, etc.)

What is the current status of this extension?
Can we update our Python runner to be based on this new editor extension?

**Comment by akchinSTC** [comment]
Closing issue..see the jupyterlab monaco extension - https://github.com/jupyterlab/jupyterlab-monaco
