### ISSUE TITLE
Add indicator for code snippet "Copy to Clipboard" success

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#896]
Usually for "Copy to Clipboard" buttons, there's a toast notification that indicates that the content has been copied 
![image](https://user-images.githubusercontent.com/6673460/91358454-7cae0700-e7b8-11ea-98f7-ccea4e319183.png)
(Note: I don't see any precedent within Jupyterlab)

**Comment by vabarbosa** [comment]
@marthacryan something similar to this was implemented in PR https://github.com/elyra-ai/elyra/pull/773
are you not see this (or is this issue to update/change current implementation)?


<img width="286" alt="image" src="https://user-images.githubusercontent.com/13156555/88209697-19f9a680-cc21-11ea-8e25-4bf8dbb94797.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/13156555/88210428-321df580-cc22-11ea-9ef9-6d6d37c6daab.png">

**Comment by marthacryan** [comment]
Oh shoot you're right! I don't know how I missed that when I was trying it out 😱  Yeah I can close this

**Comment by vabarbosa** [comment]
> Oh shoot you're right! I don't know how I missed that when I was trying it out 😱 Yeah I can close this

you can always propose [changing the duration of how long the message is displayed](https://github.com/vabarbosa/elyra/blob/master/packages/ui-components/src/FeedbackButton.tsx#L50) if it is easily missed:
