### ISSUE TITLE
As a user, I would like to run notebook pipelines from the command line

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#899]
Currently one can only start a pipeline run (local and on kubeflow pipelines) from the Pipeline Editor. By adding the ability to somehow start a run from the command line Elyra users could take advantage of features that are not available in Elyra or JupyterLab, such as automation or scheduling

For example: 
- User X creates a pipeline and tests it using the UI
- Once satisfied that it produces the expected results the user wants to periodically run the pipeline to process new data that is coming in without having to explicitly trigger the run using the Elyra UI

**Comment by lresende** [comment]
Note that scheduling is available in multiple runtimes including Kubeflow Pipelines and that's why we didn't try to reproduce the capability. 

As for a CLI tool, this would be a great tool that someone from the community could help with.

**Comment by ptitzler** [comment]
@ibuleje fyi
