### ISSUE TITLE
Adding a Docker Image (Execution Environment) to Elyra

### ISSUE THREAD

**Issue by mfractal18** [elyra-ai/elyra#901]
I am a junior scientist trying to implement Elyra in my lab. I have a set of Jupyter Notebooks used for data analysis as well as [CellProfiler](https://github.com/CellProfiler/CellProfiler) Modules used for image analysis. I would like to set up an Elyra pipeline that would facilitate my workflow and the passage of files from one Notebook or CellProfiler module to the other. In this context, I wanted to ask if it is possible to add a new docker image (execution environment) in Elyra. More specifically, I would like to add CellProfiler, which runs on python libraries and uses docker, as an execution environment.

**Comment by akchinSTC** [comment]
@mfractal18, thanks for the interest in using Elyra at your lab. Not too familiar with CellProfiler, do you have any examples of existing pipelines with docker that you can share with us? Is it being used as just a python library or does it launch and manage the containers lifecycle?

**Comment by ptitzler** [comment]
Hi @mfractal18, we've just added documentation on how to add your own Docker image as an execution environment: https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html Note though that Docker images are only used to execute notebooks if you run a pipeline on Kubeflows, not locally in JupyterLab.

For execution on Kubeflows Pipelines:
Were you thinking about  using an image from https://hub.docker.com/r/cellprofiler/cellprofiler? If that's the case you can  give it a try as long as the Docker images meets the stated prerequisites. Add a runtime environmental described in above doc and associate it with a notebook that leverages the installed software and let us know what happens. 

For execution in JupyterLab (locally on MacOS/Linux):
If you install CellProfiler in the kernel being used by a notebook this _should_ probably work as is and there's no need to define a runtime environment.

**Comment by ptitzler** [comment]
I did a tiny bit of exploration and tried to use the latest `cellprofiler/cellprofiler` (1 year old) Docker image as is:

```
$ docker run -it --entrypoint=/bin/bash cellprofiler/cellprofiler
root@60f9b6e55438:/usr/local/src/CellProfiler# which python
/usr/bin/python
root@60f9b6e55438:/usr/local/src/CellProfiler# python --version
Python 2.7.12
root@60f9b6e55438:/usr/local/src/CellProfiler# which curl
```

Unless I am missing something this specific image doesn't meet the prerequisites. The latest source code version of Cellprofiler does seem to support Python 3.8+ but I couldn't find a corresponding Docker image to get over the hump.

**Comment by mfractal18** [comment]
Thank you so much for your help. I tried using this same docker image. You are correct the CellProfiler version in this docker image uses Python2. I contacted the CellProfiler developers. They are about to launch CellProfiller 4.0.0. which runs in python3.8. They would also create a docker container for this version. 

Thank you for the added documentation on customizing runtime images. This was a huge help. I will add CellProfiler as a runtime image once the new version is released (approximately in a week).

**Comment by ptitzler** [comment]
Great! Thanks for the update and please keep us posted. I do believe you'll probably still need to create another image based on the new image because `curl` likely won't be pre-installed if the pre-installed libs will be similar: https://github.com/CellProfiler/distribution/blob/master/docker/Dockerfile#L5-L22.  That can be fixed by adding `curl` to the list in a custom image. But we'll cross that bridge when we get there.

**Comment by lresende** [comment]
@mfractal18 it has been a while since the last discussion here, and it seemed you were going to play with new release of CellProfiller. I will be closing this issue, but feel free to re-open if you are still have issues and we will be more than happy to help.

**Comment by mfractal18** [comment]
Thank you @ptitzler, @akchinSTC, and @lresende for your prompt responses to this issue. The lab really appreciates all the help. We are very interested on using Elyra to simplify our data analysis. CellProfiler4 was finally released. This is the [docker file](https://github.com/CellProfiler/distribution/blob/master/docker/Dockerfile) created for this version of CellProfiler, and the [Docker Image](https://hub.docker.com/layers/cellprofiler/cellprofiler/4.0.3/images/sha256-27d0404df555b60a3a1457093321c06d44307ae70725c89842709dde110c720b?context=explore) posted on Dockerhub.

To add this version of CellProfiller as a runtime image, I added curl by creating a new Dockerfile `FROM cellprofiler/cellprofiler:4.0.3` and adding the following line of code `RUN apt-get update && apt-get install -y curl`. This is the [Docker Image](https://hub.docker.com/layers/mlozada/testcurl/0.5/images/sha256-894a3f26aa1273ed3ee8a96539eb80437521cf06782357d60e70af1fbd5cbfa0?context=repo) generated by this file. The image seemed to be added to the list of Elyra Runtime Images. But, It is unavailable in the Runtime Image dropdown menu under the properties configuration window for pipeline nodes. 

`Available metadata instances for runtime-images (includes invalid):

Schema          Instance               Resource                                                                         
------          --------               --------                                                                         
runtime-image   anaconda               /opt/anaconda3/share/jupyter/metadata/runtime-images/anaconda.json               
runtime-image   cellprofiler           /Users/mlozada/Library/Jupyter/metadata/runtime-images/cellprofiler.json         
runtime-image   pandas                 /opt/anaconda3/share/jupyter/metadata/runtime-images/pandas.json                 
runtime-image   pytorch-devel          /opt/anaconda3/share/jupyter/metadata/runtime-images/pytorch-devel.json          
runtime-image   pytorch-runtime        /opt/anaconda3/share/jupyter/metadata/runtime-images/pytorch-runtime.json        
runtime-image   tensorflow_2x_gpu_py3  /opt/anaconda3/share/jupyter/metadata/runtime-images/tensorflow_2x_gpu_py3.json  
runtime-image   tensorflow_2x_py3      /opt/anaconda3/share/jupyter/metadata/runtime-images/tensorflow_2x_py3.json      
runtime-image   tensorflow_gpu_py3     /opt/anaconda3/share/jupyter/metadata/runtime-images/tensorflow_gpu_py3.json     
runtime-image   tensorflow_py3         /opt/anaconda3/share/jupyter/metadata/runtime-images/tensorflow_py3.json`

**Comment by kevin-bates** [comment]
> It is unavailable in the Runtime Image dropdown menu under the properties configuration window for pipeline nodes.

These json files are written in a protected manner - read-write only by owner.  Is your notebook server running as a different user that perhaps can't read `/Users/mlozada/Library/Jupyter/metadata/runtime-images/cellprofiler.json` or the `runtime-images` directory?

If not, you might try restarting your notebook/lab server instance to see if that picks up the file.

**Comment by ptitzler** [comment]
I believe you might be running into https://github.com/elyra-ai/elyra/issues/911. If you restart JupyterLab the new entry should show up in the UI drop down.

**Comment by ptitzler** [comment]
In the unlikely event that this doesn't resolve the issue for you please complete the following steps:

[Disclaimer: we don't recommend updating the `.pipeline` file manually unless absolutely necessary]

- Close the pipeline editor.
-  Open the `.pipeline` file as follows:

![image](https://user-images.githubusercontent.com/13068832/94595234-68d64480-023f-11eb-9f75-280538defaf6.png)

- Locate the `runtime_image` property for the notebook node
![image](https://user-images.githubusercontent.com/13068832/94595599-e9954080-023f-11eb-9559-1b2f9c613aa9.png)

- Replace the current value with the image name you've configured (e.g. `mlozada/testcurl:0.5`)
- Save your changes.
- Open the pipeline using the pipeline editor and try to run it. (Note that if you open the node properties your change will be overridden)

**Comment by mfractal18** [comment]
Thanks, @ptitzler and @kevin-bates. I can now see the Cellprofiler runtime image. However, the image does not seem to work. I wonder if there is something in the [CellProfiler Docker Image](https://hub.docker.com/layers/cellprofiler/cellprofiler/4.0.3/images/sha256-27d0404df555b60a3a1457093321c06d44307ae70725c89842709dde110c720b?context=explore) that prevents it from running in Elyra.

**Comment by ptitzler** [comment]
Would you mind sharing your pipeline file along with any file dependencies it might have, such as notebooks? If you prefer to not share it in public please send me an email at  xxx@us.ibm.com replacing xxx with my github id.

**Comment by ptitzler** [comment]
I did take a quick look at the Docker image you've built.  A bit of background information before I outline the issue you are running into: When the a node is executed during a pipeline run a bunch of commands are run to prepare the running container for execution. Two of these commands are `python` and `pip`.  In your Docker image the version3 python is aliased as `python3`, whereas `python` still links to the 2.7 version.

```
root@396aa6e0998b:/usr/bin# python --version
Python 2.7.12
root@396aa6e0998b:/usr/bin# python3 --version
Python 3.5.2
```

@kevin-bates @akchinSTC Should we consider updating the bootstrapper script to go after `python3` if `python` resolves to a downlevel version?

**Comment by kevin-bates** [comment]
The [references to python are "persisted" prior to the launch](https://github.com/elyra-ai/kfp-notebook/blob/master/kfp_notebook/pipeline/_notebook_op.py#L127-L129) of the image itself, so there's no way to interrogate the image's contents beforehand.

However, I do see that in our [Makefile, when we validate _our_ images](https://github.com/elyra-ai/elyra/blob/master/Makefile#L156-L180), we ensure that both `curl` and `python3` are available as commands.
```
# Contains the set of commands required to be used by elyra
REQUIRED_RUNTIME_IMAGE_COMMANDS?="curl python3"
```

This implies we could (and should) update the aforementioned references to `python3` and still be okay.  That said, we do not officially support Python <= 3.5 (and we should probably add a version check to our image validation).

**Comment by ptitzler** [comment]
Thanks Kevin,

I'll take the TODO to update https://elyra.readthedocs.io/en/latest/recipes/creating-a-custom-runtime-image.html, stating that 3.6 is the new minimum version we are supporting. (I forgot that [Python 3.5 EOL is on 9/30/2020](https://www.python.org/downloads/release/python-3510/#:~:text=Python%203.5%20will%20reach%20its,release%20of%20the%203.5%20series.)).

That said, I'm not ready to give up yet because the interesting challenge is yet to come.

An easy workaround for now is to build the Docker image using the following `Dockerfile`:
```
FROM cellprofiler/cellprofiler:4.0.3
RUN apt-get update && apt-get install -y curl
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3 /usr/bin/python
```

That should result in an "unofficially" compatible image, which should open the door for the next issue that'll prevent this node from running as expected.

**Comment by ptitzler** [comment]
> I'll take the TODO to update ...

See https://github.com/elyra-ai/elyra/pull/945

>  the next issue that'll prevent this node from running as expected

@mfractal18 please take a look at https://elyra.readthedocs.io/en/latest/recipes/creating-a-custom-runtime-image.html#dockerfiles-with-entrypoint-instructions. The scenario applies to your Docker image.

**Comment by mfractal18** [comment]
Thank you @ptitzler and @kevin-bates for your help. I think on our end we can try to re-write the Dockerfile for CellProfiller4 in order to remove some of the `CMD` and `ENTRYPOINT` instructions while keeping all the dependencies necessary to run CellProfiler. Regarding the python version incompatibility, we could also remove the python alias since we will be creating our version of the CellProfiler Docker. What is more concerning is the use of python 3.5. I will check with the CellProfiler developers. I think they originally intended to use python 3.8. Thank you so much for your help. I will report back once we make these changes.

**Comment by lresende** [comment]
@ptitzler @mfractal18 I can get a kfp-notebook release now (a minor one) which could then be used with the current version of Elyra. Does this help on this case?

**Comment by ptitzler** [comment]
> The next version of Elyra will use the python3 alias instead of python and your image will therefore work as is.

Version 1.3 is now available, which contains the fix!

**Comment by lresende** [comment]
Are ok with this issue? Are there any additional things that needs to be addressed?

**Comment by ptitzler** [comment]
@mfractal18 if there's anything else you need please re-open the issue. AFAIK there is nothing on our end that needs to be delivered at this time.
