### ISSUE TITLE
Document how to create a Docker image that can be used as a runtime environment

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#910]
We have currently documented how to add a custom runtime image: https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html. Since there are some constraints that a custom Docker image needs to meet to be usable, we should document the build process and considerations for novice users.

**Comment by ptitzler** [comment]
This issue was in part motivated by https://github.com/elyra-ai/elyra/issues/901.

**Comment by lresende** [comment]
We already have documentation for [docker runtime images](https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html). I believe the specific issue is that Elyra runtime uses this as an environment and would bypass the docker configured startup command and this is what we should document together with possible workarounds to how to start required processes. 

Could we also update the title to describe it more towards the details above?
