### ISSUE TITLE
urllib3 dependency conflicts with python 3.8 in conda-forge

### ISSUE THREAD

**Issue by bolliger32** [elyra-ai/elyra#914]
I also posted this in https://github.com/conda-forge/elyra-feedstock/issues/4 but since there are no other issues there, figured this repo was better monitored. When installing elyra via conda, using the conda-forge channel, the dependency on urllib3=1.24.3 prevents the use of python 3.8 b/c there are no python 3.8-compatible versions of urllib3=1.24.3 on conda-forge (or conda's main channel). Wondering if it's possible to make that a ">=" dependency or if there's something specific about urllib3 version 1.24.3 that is needed for elyra

**Comment by kevin-bates** [comment]
Looks like this was originally pinned in [this commit](https://github.com/elyra-ai/elyra/commit/bcbf59eec35e94812bb46d00ed2f869e318f38c4).  

cc: @lresende
