### ISSUE TITLE
Support for pipelines to be executed on Ray

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#936]
Ray has some advantages over Kubeflow as data passing between workers is highly efficient (shared memory, Apache Arrow over Object Store) and support for a streaming model.

We need to evaluate if it makes sense to use the pipeline editor to directly submit Ray jobs or weather Ray can be part of a multi node/pod stage in a KF Pipeline (like a Spark stage for example) 

The following video gives a very good overview
https://www.youtube.com/watch?v=CCL0ZkLl9ns

**Comment by lresende** [comment]
I believe this is similar to running a Python kernel on an image that has the  necessary artifacts to use PySpark to connect to Spark, just in this case being Ray. This wouldn’t have any specific requirements on Elyra, and from some initial investigations this seems to work today. 

Please let me know if I missed anything, as I didn’t try Ray yet.

**Comment by romeokienzler** [comment]
Let me try it...

**Comment by romeokienzler** [comment]
Ray can be used within any notebook, therefore also using the pipeline editor to push work to KFP. When using a Ray cluster this has to be referenced from within the notebook - therefore no further work within Elyra is necessary

**Comment by lresende** [comment]
Yes, we have also updated the covid-notebooks scenario to use Ray
