### ISSUE TITLE
Cannot define two nodes as an input dependency in pipelines

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#953]
Elyra 1.2.1

As shown [here](https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html) it should be possible to define two input dependencies for a node: (`map` requires `clean-data` and `geographic-data` to have completed before it can be processed)

![image](https://user-images.githubusercontent.com/13068832/94966620-6fb8bd80-04b2-11eb-82d3-80bc549d9350.png)

If I try to create such a constellation I am unable to connect two output nodes with an input node:

![connect](https://user-images.githubusercontent.com/13068832/94967003-1bfaa400-04b3-11eb-8cfc-e0898fd0bce0.gif)

**Comment by ptitzler** [comment]
[pip_freeze.txt.gz](https://github.com/elyra-ai/elyra/files/5320131/pip_freeze.txt.gz)

```
$ jupyter labextension list
JupyterLab v2.2.8
Known labextensions:
   app dir: /Users/patti/anaconda3/envs/elyra_ga/share/jupyter/lab
        @elyra/code-snippet-extension v1.2.1  enabled  OK
        @elyra/metadata-extension v1.2.1  enabled  OK
        @elyra/pipeline-editor-extension v1.2.1  enabled  OK
        @elyra/python-editor-extension v1.2.1  enabled  OK
        @elyra/theme-extension v1.2.1  enabled  OK
        @jupyterlab/git v0.21.1  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

Disabled core extensions:
    @jupyterlab/launcher-extension
```


```
$ jupyter serverextension list
config dir: /Users/patti/.jupyter
    elyra  enabled 
    - Validating...
      elyra 1.2.1 OK
    jupyterlab_s3_browser disabled
    - Validating...
Error loading server extension jupyterlab_s3_browser
      X is jupyterlab_s3_browser importable?
config dir: /Users/patti/anaconda3/envs/elyra_ga/etc/jupyter
    elyra  enabled 
    - Validating...
      elyra 1.2.1 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.8 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.21.1 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.0.0 OK
```

**Comment by lresende** [comment]
This seems to be a regression from #750

**Comment by ptitzler** [comment]
@ibuleje also reported late last week that this wasn't working for him - and then it suddenly did. We are suspecting that this might be an environment/dependency issue. Unfortunately I don't recall if I ever tried to model this in the past and I therefore don't know whether it ever worked in my env.

**Comment by bourdakos1** [comment]
I'm having the issue as well, looks like the max input cardinality was set to 1 instead of -1. It looks like new flows are created with the default max input set to 1: https://github.com/elyra-ai/elyra/blob/master/packages/pipeline-editor/src/palette.json

Could it be that common canvas didn't pay attention to this at one point and now it does?

**Comment by lresende** [comment]
Could you please provide the pipeline file where you are seeing the issue?

**Comment by ptitzler** [comment]
> In Elyra Canvas v 9.1.1 there is now more robust checking of cardinalities of input and output ports when creating links.  Therefore cardinality values for ports should be set appropriately. The maximum value can be set to -1 to allow unlimited number of connections form an output port or to an input port. 

Info from Craig

**Comment by kevin-bates** [comment]
Looks like this is a regression that got reintroduced in this commit: https://github.com/elyra-ai/elyra/commit/746b347a5011050118feda1c5dfe7e965700904c of https://github.com/elyra-ai/elyra/pull/722...

![image](https://user-images.githubusercontent.com/22599560/95481039-6b245700-0941-11eb-8260-728071707d53.png)
