### ISSUE TITLE
Use Elyra UI node label as KFP node name

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#971]
![image](https://user-images.githubusercontent.com/13068832/95794092-f97b3e80-0c9b-11eb-9a7b-c447abe5c2cd.png)

Apparently we currently only use the file name (but not the extension) to generate a node name, which leads to this result in Kubeflow Pipelines for above input:

![image](https://user-images.githubusercontent.com/13068832/95794136-1283ef80-0c9c-11eb-9437-7150f593820c.png)

**Comment by kevin-bates** [comment]
I agree.  I think we should probably make "node-name" a first-class property.  The filename (or whatever the "default name" is tied to for the given node) seems like a great, um, default name.  Allowing a name would enable the reuse of the same notebook on multiple nodes.

**Comment by lresende** [comment]
The file extension is shown in the pipeline editor, at least in my opinion, is a regression that was introduced by #867. Although we could make it more like this suggestion, we are soon going to introduce the ability to add non-file-based components that might get to a similar situation and in that case, we will be back in a similar situation. 

Anyway, for now, let's make it consistent and flow the extension.

**Comment by lresende** [comment]
While investigating this, passing the filename (including the extension to KFP) results in a parsing error:
`ValueError: Only letters, numbers, spaces, "_", and "-"  are allowed in name.`

I will take a deeper look at this and provide more info here.

**Comment by lresende** [comment]
As suggested by @kevin-bates, one option would be to enable editing the label field

**Comment by lresende** [comment]
For editing the label field, we need [#341](https://github.com/elyra-ai/canvas/issues/341)

**Comment by ptitzler** [comment]
Closing as node renaming is now supported from the properties view:

![image](https://user-images.githubusercontent.com/13068832/107082563-374f2600-67a9-11eb-9fd8-a5c90cb926c4.png)

If desired a user can therefore rename nodes to avoid conflicts.

**Comment by kevin-bates** [comment]
Is renaming sufficient?  If I rename a node, to avoid it conflicting with another (notebook) node of the same name, then did I just _rename_ the _notebook_ of the original node?

**Comment by ptitzler** [comment]
You are right. 
 ![image](https://user-images.githubusercontent.com/13068832/107246691-5934ec80-69e5-11eb-83d6-7b32850a318a.png)

The node name (in the kfp UI) is the file name (`untitled.ipynb`) without extension and not the user-assigned label as I mistakenly assumed.
  ![image](https://user-images.githubusercontent.com/13068832/107246445-1c68f580-69e5-11eb-9425-ea23351fbf68.png)

This means we've now lost the association between the "display name" label in the Elyra UI and KFP.

**Comment by ptitzler** [comment]
cc @marthacryan

**Comment by kevin-bates** [comment]
Hmm.  I guess you're describing behavior different from what I was referring to in my previous comment.  I thought that if a downstream node were to be renamed, that operation would essentially rename the underlying notebook.  This would then lead to a "missing notebook" when the upstream node was processed.  Whereas your concern (which is valid) is that the correlation between the front-end node names (that are essentially labels) and KFP's "presentation" (that are filenames) is lost.

Given the numeric suffices on the `untitled` entries, it must be the case that when the same notebook is dragged onto the canvas additional times, we actually create a _copy_ of the notebook.  Is that true?  I guess I wasn't aware that was happening.

**Comment by marthacryan** [comment]
@kevin-bates Changing the label will not change the name of its corresponding file as far as I know. It just changes the label of the node within canvas. I think that the numeric suffices on the `untitled` entries are auto-generated by KFP when there are multiple nodes with the same label, which is happening because all of them are being assigned the label `untitled`. Looks like when we're passing a label to KFP for nodes, we're just using the filename because labels used to be the same as filename - should be a quick fix to change that!

**Comment by ptitzler** [comment]
> I thought that if a downstream node were to be renamed, that operation would essentially rename the underlying notebook.

No. This is what the corresponding section in the `pipeline` file looks like - note the last line

```
     "nodes": [
        {
          "id": "9c551346-1bc9-4cd2-907c-f42b88ac04f0",
          "type": "execution_node",
          "op": "execute-notebook-node",
          "app_data": {
            "filename": "Untitled.ipynb",
            "runtime_image": "quay.io/ptitzler/pandas:1.1.4",
            "env_vars": [],
            "include_subdirectories": false,
            "outputs": [],
            "dependencies": [],
            "invalidNodeError": null,
            "ui_data": {
              "label": "maybe",
```

> Given the numeric suffices on the untitled entries, it must be the case that when the same notebook is dragged onto the canvas additional times, we actually create a copy of the notebook. Is that true?

No. Based on the exported YAML/Python DSL it appears that these identifiers are auto-generated during "compilation":

```
spec:
  entrypoint: lambda
  templates:
  - name: lambda
    dag:
      tasks:
      - {name: untitled, template: untitled}
      - {name: untitled-2, template: untitled-2}
      - name: untitled-3
        template: untitled-3
        dependencies: [untitled, untitled-2]
      - name: untitled-4
        template: untitled-4
        dependencies: [untitled-3]
```

The DSL code we are producing does not contain any references to `...-n` or the UI label.

```
NotebookOp(name='Untitled',
                        notebook='Untitled.ipynb',
```

**Comment by kevin-bates** [comment]
Thanks for the explanations @marthacryan and @ptitzler.  I think I'm caught up now. :smile: 

Have we tried equating the `name` to the `label` - rather than the file's basename?

**Comment by kevin-bates** [comment]
> Have we tried equating the name to the label - rather than the file's basename?

In looking at this when I (redundantly) opened #1440, it's apparent that the parser is not considering the `label` value when setting the [`Operation` `name` property](https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/pipeline.py#L97-L99).

I think this can be wrapped up by just ensuring that `operation.name` is not assumed to be the basename of the file anywhere (in elyra and kfp-notebook).

**Comment by ptitzler** [comment]
> I think this can be wrapped up by just ensuring that `operation.name` is not assumed to be the basename of the file anywhere (in elyra and kfp-notebook).

and in airflow-notebook
