### ISSUE TITLE
Python script is missing `Add file to Pipeline` right-click option

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#990]
Found this while trying to automate some heterogeneous pipeline tests:

When selecting the Notebook file:

![image](https://user-images.githubusercontent.com/382917/96820843-a4e26c80-13db-11eb-8adf-79dabd0451b2.png)

When selecting the Python Script:

![image](https://user-images.githubusercontent.com/382917/96820858-ae6bd480-13db-11eb-821f-7bca5bfb3dac.png)

**Comment by ptitzler** [comment]
Can you clarify what's the expected behavior for the two supported file types? I tried this for notebooks without having a pipeline open, but nothing happened. I kind of expected that a new pipeline would be created ...
