### ISSUE TITLE
Schedular option is not showing after installing 

### ISSUE THREAD

**Issue by ashokpinapathula** [elyra-ai/elyra#999]
Hello,

We have pulled the latest dockerimage and installed the jupyterlab in our docker.

But it is not showing the schedular option in UI.

Could you please help us in finding that

**Comment by kevin-bates** [comment]
Hi @ashokpinapathula, 

You should not have to install jupyterlab into the elyra docker image as it will already be there.

Could you please answer these questions:
1. What image did you pull?  If the tag is 'latest', does it equate to the 1.3 versions?
2. What do you mean by the _scheduler option in the UI_?  Is this the 'Submit Notebook...' button on the Notebook toolbar or something else?  A screenshot or reference would be helpful.
3. If you are modifying the elyra docker image, can you give an idea (or Dockerfile) of the kinds of modifications you are applying?

Thanks.

**Comment by ashokpinapathula** [comment]
We are using elya base image only.

Could you please share the steps that needs to be done for scheduling a file ??

**Comment by kevin-bates** [comment]
Thank you for your response regarding the docker image usage.

> Could you please share the steps that needs to be done for scheduling a file ??

I'm sorry @ashokpinapathula, but I cannot answer that question until you provide more information about what you mean by _scheduling a file_.  In essence, please answer question 2 above (and repeated here):

> 2. What do you mean by the scheduler option in the UI? Is this the 'Submit Notebook...' button on the Notebook toolbar or something else? A screenshot or reference would be helpful.

Where did you learn about an ability to "schedule" files via Elyra?  Depending on the runtime, and once a pipeline has been submitted or exported, the runtime may provide the ability to schedule the pipeline, but that's only after an initial submission or export.  If you can provide such a reference to what you're referring to, we may be able to help answer your question.  Thank you.

**Comment by akchinSTC** [comment]
@ashokpinapathula - Just checking up to see if you have any additional questions or any updates regarding this issue?

**Comment by lresende** [comment]
Please reopen if you are still seeing issues.
